### ISSUE TITLE
Access Project without any VBComponents leaves most Rubberduck menus enabled

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1009]
The resolver toolbar doesn't say Ready, Parsing or Error - It's blank.

The Rubberduck menu and context menus are all enabled, which is inappropriate if there's nothing to explore, inspect, refactor or test.

Steps to reproduce:
 1. Create a new Access Database
 2. Open VBE

**Comment by ThunderFrame** [comment]
This probably holds true for all projects that don't have any VBComponents.

**Comment by retailcoder** [comment]
Interesting. I just assumed any VBA project would have *at least* one `VBComponent`, if only a "Document"-type component.

The `ParserStateCommandBar` being blank makes sense - it's not `Ready` since it didn't parse or resolve anything yet. It's not `Error` either, since no component contains parsing errors, and it can't be `Parsing` since there's nothing to parse. Perhaps it should default to *something* though.. but what?

As for the menus and context menus... it seems unrelated, but in fact it's very closely linked: menus don't evaluate their "IsEnabled" state until parser state changes - that's why we launch an IDE-wide parse at startup. If that doesn't do anything..... it defeats it. Hmm...

**Comment by ThunderFrame** [comment]
The ParserStateCommandBar isn't necessarily blank, it just retains whatever value was there last. In this instance, the project has never parsed, so it is never Ready or Error or Parsing. But, in some instances, where project(s) *with* components have previously parsed (and the CommandBarButton text is Ready), and then another project without any components is loaded, then the parser doesn't run,and the CommandBar text still informs the user that it is ready. We really need to set the CommandBarButton text to *something*, *before* a parser attempt.

**Comment by ThunderFrame** [comment]
The example above is for a project without any references being added, but the same issue occurs anytime RubberDuck doesn't commence the parse (like in current Next, where protected projects stop the parser from running)

**Comment by Hosch250** [comment]
Obsolete.
