### ISSUE TITLE
Parse cached after last VBComponent removed or last Access database closed.

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1011]
If Rubberduck has successfully parsed the project, and the last VBComponent is subsequently removed, or the database is closed, then Rubberduck fails to reparse the project, and Code Explorer shows the project as it was before the last component was removed or the database was closed.

Linking #1009 and #1010

**Comment by ThunderFrame** [comment]
I wonder if this might be related to the crashes on host application exit (which I get in 99% of cases)? That is, as VBprojects and host documents are closed, Rubberduck is left in a state where it can't know about the parse tree, and doesn't exit cleanly?

**Comment by retailcoder** [comment]
The `VBE.Proejcts` collection [exposes events](https://msdn.microsoft.com/en-us/library/aa241502(v=vs.60).aspx) that we should be handling:

 - ItemAdded
 - ItemRemoved
 - ItemRenamed

Hopefully these are available through the Interop assembly. If not, there's no way Rubberduck can know when a project is closed. The crashing is most likely due to an unhandled `COMException` because the `RubberduckParserState` holds references to the `VBProject` and its `VBComponent` objects, which become stale when the project is closed - accessing them at that point invariably throws a `COMException`.

**Comment by Hosch250** [comment]
Closed as obsolete.  These events are being handled and trigger cache updates.
