### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Hosch250** [rubberduck-vba/Rubberduck#1014]
It appears the docked windows do not update when the localization settings are changed.  The Code Explorer, the Todo Explorer, the old Source Control, the Unit Test, and the Code Inspections are the ones that I verified this.  Also, there are a good many values not yet translated that appear blank.

**Comment by autoboosh** [comment]
The problem seems to be that each GUI is instantianted before the config language is loaded. Since the resx-bindings in the WPF GUIs are static they won't update after changing the culture.

Here's a possible home grown solution which loads the correct translations as well as updates at runtime: https://gist.github.com/autoboosh/4129679b72c3f265f7a6.

The solution uses ResourceDictionaries filled via reflection from the resx classes + DynamicResources for actually using the translations.

Doesn't have to be the solution that's actually used but this might bring us closer to one :)

**Comment by Hosch250** [comment]
@autoboosh Feel free to make a PR.

**Comment by autoboosh** [comment]
OK will do.

There's also this project that does basically exactly what we need: http://www.codeproject.com/Articles/35159/WPF-Localization-Using-RESX-Files. But the license is Code Project Open License. Does anyone know if we're allowed to use it in rubberduck? According to https://en.wikipedia.org/wiki/Code_Project_Open_License the license is incompatible with GPL.

**Comment by autoboosh** [comment]
With this pull request all WPF windows are now localized correctly plus can have their language changed at runtime. It uses [WPF Localization Using RESX Files](http://www.codeproject.com/Articles/35159/WPF-Localization-Using-RESX-Files). The library works basically like this:

1. Special MarkupExtension allows directly adding localized strings to the UI using `{Resx ResxName=Rubberduck.UI.RubberduckUI, Key=RefactorMenu_Rename}` syntax
2. In App.cs the `CultureManager.UICulture` is set allowing one to change the language at runtime
3. Each WPF user control has its language set with `Language="{UICulture}"`
4. Since for some reason the assembly resolution process with XAML controls probes the wrong folder, we give it a hint as to where it can find the WPF localization library by adding a small change to Extension.cs
