### ISSUE TITLE
parsing issues of conditional compilations

### ISSUE THREAD

**Issue by u-riaz** [rubberduck-vba/Rubberduck#1056]
Hi,
The following code is a real time scenario, but grammar is failing to parse it throwing error 
"line 2:8 no viable alternative at input '#If VBA7 Then\nPrivate Declare'"

#If VBA7 Then
Private Declare PtrSafe Function ABC Lib "Z" Alias "Y" (ByVal s As String, t As Long) As Long
#Else
Private Declare Function dfg Lib "Y" Alias "h" (ByVal s As String, t As Long) As Long
#End If

From `macroIfThenElseStmt` control goes to `moduleBody` and moduleBody has no rule to handle Declare statements. So, how it would be parsed ?

Thanks

**Comment by Vogel612** [comment]
IIRC Pre-Compiler Directive are not (yet?) supported. At least in the Grammar they are throwing stuff all around.

This is currently in the works (see #1055). There should also be some other related issues, but I can't find them right now...

**Comment by ThunderFrame** [comment]
@Vogel612 I think @retailcoder closed a bunch of the issues that *were* open, about 4 hours ago

**Comment by retailcoder** [comment]
This was addressed and merged into [next] just a few hours ago. See [VBA.g4 lines 359-373[(https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/Grammar/VBA.g4#L359-L373)

**Comment by u-riaz** [comment]
thanks @retailcoder for fixing it.
Here are some issues, RD may find them useful. In the following lexer rules you had added `WS` at ends, which is unnecessary here, (and making errors sometimes e.g. suppose there is no space after `#Else` in actual VBA-code then `MACRO_ELSE : '#' E L S E WS;` would create the unnecessary error)  because we had `WS?` in actual parser rules where these lexer rules had been used. 
```
MACRO_CONST : '#' C O N S T WS;
MACRO_IF : '#' I F WS;
MACRO_ELSEIF : '#' E L S E I F WS;
MACRO_ELSE : '#' E L S E WS;
```
others may work fine, but you should at-least modify `MACRO_ELSE : '#' E L S E WS;`. Because, if i had faced issues, may someone else too :-P

**Comment by u-riaz** [comment]
Hi,
Following is the snippet found in many macro-codes. 
```
#If SMS Then
Public Sub ProcessCommandLine(ByVal strCommand As String, ByRef fSilent As Boolean, ...)
#Else
Public Sub ProcessCommandLine(ByVal strCommand As String, ByRef fSilent As Boolean, ...)
#End If
```
and i think this is a valid syntax as it's getting compiled and run in office files. But, while parsing with this grammar I'm getting error
`
<unknown>:3:0: line 3:0 no viable alternative at input '#If SMS Then\nPublic Sub ProcessCommandLine(ByVal strCommand As String, ByRef fSilent As Boolean, ...)\n#Else'
`

Acc. to me, its due to `subStmt` rule which requires `END_SUB` at end (and no error when fed with `End Sub`).
So, I'm planning to fix it by modifying `subStmt` rule and making `END_SUB` optional. Would that work fine without introducing new problems in VBA context ?
Or, we should introduce new rule(s) like `macroSubStmt` etc.  
Please have a look. Thanks

**Comment by ckuhn203** [comment]
Which version are you running @u-riaz? I believe this has been fixed in the yet-to-be-released 2.0 release. 

cc @retailcoder

**Comment by retailcoder** [comment]
Not quite. We worked around that grammar limitation (`#If` blocks cannot interfere with other parser rules) by actively *interpreting* the conditionals and only giving the "live" code to our parser.

**Comment by u-riaz** [comment]
@ckuhn203 , I'm using latest grammar of last commit [here](https://github.com/antlr/grammars-v4/tree/master/vba).
@retailcoder , ca you please explain a little more? 
You mean, grammar will remain as is and RD handles these issues at programming end (by controlling parse tree etc. )?

Had you released 2.0 version ?

**Comment by retailcoder** [comment]
I mean, we're using *another* grammar that's dedicated to pre-processing, and then (quite a bit of) code was written specifically to implement a little "interpreter" to determine which code was "live" and which code was "dead", to output a modified string that contained only the "live" code, which we then feed to our actual parser (which no longer needs to even know about pre-processor instructions).

Rubberduck 2.0 hasn't been released yet - if you're following us on Twitter or WordPress, you'll be the first to know when we release!

**Comment by u-riaz** [comment]
thanks @retailcoder , I'd got the point. I'll try to fix it somehow.

I'm currently working of parsing issues, and had found some bugs in [grammar](https://github.com/antlr/grammars-v4/blob/master/vba/vba.g4) ,and i think this grammar is the same one as of RD. Sooner I'll let you know of these issues. You might be handling these in some other way or they might fix some bugs of coming version 2.0.

**Comment by retailcoder** [comment]
Indeed, that VBA.g4 grammar was PR'd by myself, off the VBA.g4 file used by Rubberduck. However since then, separate grammars were created for preprocessor statements, and also for module attributes. If you find bugs beyond preprocessor statements and module attributes in VBA.g4, by all means feel free to let us know about them.. but because of the pre-processing we're now doing, keeping the ANTLR repository up-to-date will actually be taking features away from the grammar, and I wouldn't want to do that. Hence, I don't think I'll be updating the ANTLR repository with changes to our VBA.g4 grammar file anymore.

**Comment by u-riaz** [comment]
@retailcoder and others,
How RD handles line continuations ?
In some cases leading white spaces must be skipped as in:
```
fun(1) _
[space(s)/tab(s)] .fun(2) _
[space(s)/tab(s)] .fun(3)
```
In this scenario, leading spaces/tabs must be skipped to make it
`fun(1).fun(2).fun(3)`
otherwise, grammars complains.

Now consider
```
Private Declare Function ABC Lib "shell32.dll" Alias _
"ShellExecuteA" (ByVal a As Long, ByVal b As String, _
ByVal c As String, ByVal d As String, ByVal e As String, ByVal f As Long) As Long
```
in this case, there must be at-least ONE space between `Alias "ShellExecuteA"` to work properly. Means leading white spaces should never be skipped (and what if there are no leading spaces and we've to use newline somehow to parse it correctly). 
There are other scenario too, in some we must skip and not in others. Got stuck in solving this :(

Any helps please..

**Comment by retailcoder** [comment]
Line continuations **must** be skipped, and IIRC they're defined as a whitespace followed by an underscore, followed by an end-of-line. That `Declare` statement effectively breaks the parser because the alias string has no space before it, as far as the parser can see.

Rubberduck will handle this by reporting a parser error, unless we figure out a way to ignore only the underscore and end-of-line, but keep the whitespace into the lexer stream.

**Comment by autoboosh** [comment]
@retailcoder and I just had a quick chat about this and came to the conclusion that two changes are necessary:

1. Allow line continuations between "." method calls (fixes the first example)
2. Preprocess the module code by adding a whitespace after the line continuation's new line. This is more like a workaround since LINE_CONTINUATION tokens are skipped by default. So if there's only a LINE_CONTINUATION token and no "normal" WS token then the parser fails. (fixes the second example)

I'll send a PR.

**Comment by ThunderFrame** [comment]
It seems to me like the *only* continued line that requires the *absence* of white-space between the prior line and the current line, is a continued line that starts with a period. All other continued lines would seem to be valid if only a single white-space was preserved, regardless of the number of line continuations.
Can we define a rule that replaces 1 or more instances of `WS + _ + Environment.NewLine + WS` with an empty string if the next line starts with a period, otherwise a single space? Maybe there's a special treatment for new-line-periods inside comments

Consider this special case of the period problem:

```vb
fun(1) _
[space(s)/tab(s)] .fun(2) _
 _
        _
[space(s)/tab(s)] .fun(3)
'This is a continued comment _
 _
.That starts with a period.
```

**Comment by retailcoder** [comment]
@ThunderFrame  it's a little more subtle than that - the `WS '_'` is part of the `LINE_CONTINUATION` lexer token definition, and that's the part that gets "skipped" at the lexer level; by modifying the input string and giving it `WS '_' WS` everywhere the lexer can match a line continuation, we keep the last `WS` token in the token stream, and the parser will see it - and that fixes the problem.

**Comment by u-riaz** [comment]
How we can write a lexer rule to skip some chars and keep others in a lexer stream. For example, a rule which skips `'_' NEWLINE` from `WS '_' NEWLINE` but don't skip `WS`.

I'd tried following, but it didn't work :( 
` LINE_CONTINUATION : ([ \t]+ (UNDERSCORE '\r'? '\n'-> skip) ); `

Is writing such a rule ever possible ?

**Comment by autoboosh** [comment]
The first problem is fixed. The second one is fixed in general by making whiteSpace a parser rule and not skipping LINE_CONTINUATION tokens anymore.

**Comment by autoboosh** [comment]
Fixed with https://github.com/rubberduck-vba/Rubberduck/pull/1255.
