### ISSUE TITLE
Is it possible to implement inspections/refactoring as scripts?

### ISSUE THREAD

**Issue by sshikov** [rubberduck-vba/Rubberduck#1142]
I mean, Rubberduck scripting extensions, written in VBA itself (but not restricted to), having access to ANTLR parse tree, for example.

Just an idea.

**Comment by ckuhn203** [comment]
Sounds related to #404. 

There's also an issue somewhere about exposing the parser via a COM interface so that we could access the parse tree and symbol table from VBA. 

In short, yes, it's possible, but a pretty large undertaking.

**Comment by retailcoder** [comment]
I don't think we'll expose the ANTLR parse tree itself. But, we can (and eventually, *will*) expose a "reflection API" so that `Declaration` and `IdentifierReference` objects can be browsed/iterated in VBA client code - the API could also expose parser state events to notify clients of a change.

That API is a project all by itself though.

**Comment by sshikov** [comment]
Yea, something like #404. I'm not sure I would like SQL-like syntax for expressions, may be something like XPath, as ANTLR does.

**Comment by ckuhn203** [comment]
Duly noted. That's also an interesting idea!

May I ask what you mean by "as ANTLR does"? I'm unaware of this feature.

**Comment by sshikov** [comment]
I mean  http://www.antlr.org/api/Java/org/antlr/v4/runtime/tree/xpath/XPath.html

**Comment by retailcoder** [comment]
@sshikov nice find, except, no, we're not going to expose the ANTLR parser instance anywhere through COM, or any of the `IParseTree` instances. These are Rubberduck's internals and in no way part of a public API. What we *will* expose to VBA client code, is an iteratable set of objects (perhaps even a tree structure, perhaps even XML-serializable), *representing* the `Declaration` and `IdentifierReference` objects that Rubberduck is working with.

I say "representing", because even `Declaration` and `IdentifierReference` types are Rubberduck's internals, and don't constitute a VBA-friendly API.

**Comment by ckuhn203** [comment]
That's pretty cool @sshikov. I didn't know that existed, thank you for sharing!

**Comment by sshikov** [comment]
If you don't like to expose any parts of parse tree, how would you implement refactorings like Extract variable, just for example? What do you need in this case: having cursor position, find/select some expression around cursor, then try to find the same expression inside current Sub/Function, create Dim + Let/Set before 1st instance, and finally replace all instances of expression by variable reference.

**Comment by ckuhn203** [comment]
We would expose the symbol table, which has resolved all declarations and references instead of exposing the raw AST.

**Comment by retailcoder** [comment]
PR #1238 cracks open Pandora's box
