### ISSUE TITLE
Parser Errors : Optional Enum parameter

### ISSUE THREAD

**Issue by thetopic** [rubberduck-vba/Rubberduck#1160]
### Parser Errors with the code below
```VBA
Public Enum TestEnum
    TestUn = 1
End Enum

Public Sub TestSub(Optional param As TestEnum = TestEnum.TestUn)
    
End Sub
```

### No errors with the code below 
_(Optional param As TestEnum = ~~**TestEnum.**~~TestUn)_
```VBA
Public Enum TestEnum
    TestUn = 1
End Enum

Public Sub TestSub(Optional param As TestEnum = TestUn)
    
End Sub
```

**Comment by Vogel612** [comment]
This problem is probably rooted in the grammar.

The relevant rule about arguments includes a `valueStmt` as initializer for the optional Argument:

    argDefaultValue : EQ WS? valueStmt;

unfortunately the current rule for [valueStmt](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/Grammar/VBA.g4#L442) doesn't include something that would match `TestEnum.TestUn` from what I can see ... (I may be wrong though)

**Comment by retailcoder** [comment]
@Vogel612 that's correct.

**Comment by autoboosh** [comment]
This actually works with the latest version.

**Comment by retailcoder** [comment]
@autoboosh oh nice! is it part of what I just merged?

**Comment by autoboosh** [comment]
No, I think he's just using a 1.x version :).

The only important changes in the recently merged PR were the addition of the EMPTY keyword plus removal of the macro rules.

**Comment by retailcoder** [comment]
Ok cool. Closing then!
