### ISSUE TITLE
HRESULT E_FAIL on launch

### ISSUE THREAD

**Issue by TJ2016** [rubberduck-vba/Rubberduck#1167]
Just installed the latest version and I'm getting a HRESULT E_FAIL popup window when VBA starts. 
Windows 7 64 Enterprise
Access 2013

**Comment by retailcoder** [comment]
32 or 64 bit Office?

Are you local admin? If not, did you follow install instructions for non-admin users ([see here](https://github.com/rubberduck-vba/Rubberduck/wiki/Installing#installing-for-non-admin-users))?

Is the popup from the VBE or from Rubberduck? Can you post a screenshot?

**Comment by TJ2016** [comment]
32 Bit Office
Yes, I'm local admin, ran install as administrator
Tried on another machine got same error
![hresult](https://cloud.githubusercontent.com/assets/17600327/13480876/e7db76e0-e0ae-11e5-9955-9835fee336ca.png)

**Comment by TJ2016** [comment]
Sorry, hit the wrong button

Applied PowerShell commands still getting HRESULT error

**Comment by TJ2016** [comment]
uninstalled and reinstalled as admin, it seems to be working now.

**Comment by TJ2016** [comment]
The steps I used above seem to only have worked on one of the two machines I tried.

The original machine where I first reported the error now randomly gives an error when starting VBA, when it does not give an error, none of the rubber duck functionality works.

**Comment by retailcoder** [comment]
@TJ2016 are there any other VBE addins installed? Not that we know of any interactions, just probing for a lead...

**Comment by TJ2016** [comment]
Nope, no other addins installed

I think I have lead for you though.

On the machine that was working I was getting a requester to install vsta_ide.msi when I launched VBA

It looks like it is needed by Solidworks.

I had been canceling the install, but today I installed it and now I'm getting the HRESULT error on the machine that was working.

**Comment by retailcoder** [comment]
We've had a number of support issues involving a COM exception at startup, but I can assure you that a prompt to run `vsta_ide.msi` is completely unheard of. Pretty much every time, the error was due to Rubberduck not being installed as admin, or not being registered for a non-admin user, or somehow not registering correctly during the installation.

I suspect the latter could be the case here, try running this in an admin-elevated command prompt:

    c:\windows\microsoft.net\framework\v4.0.30319\regasm.exe "(path to install folder)\rubberduck.dll" /codebase /tlb

(details [here](https://github.com/rubberduck-vba/Rubberduck/wiki/Contributing#registering-the-com-types))

There are other recorded instances of the add-in not loading, if useful:

 - #1019 seems to have the same issue
 - #935 documents an annoying WinForms exception sometimes thrown *once* and then never again
 - #320 is about v1.21, but includes screenshots of a [regasm.exe command](https://github.com/rubberduck-vba/Rubberduck/issues/320#issuecomment-82482586) the user ran to re-register the add-in, and it worked

**Comment by TJ2016** [comment]
You suspected correctly, running regasm fixed things

Thank you

**Comment by retailcoder** [comment]
Awesome! You know what? I'm going to add that to the wiki's *Installing* page.
