### ISSUE TITLE
Code Inspector - incorrect proposal UseOfVariantReturningStringFunction

### ISSUE THREAD

**Issue by Pitterling** [rubberduck-vba/Rubberduck#1193]
CodeInspector is proposing replacement of Right$ function by a String Function

```
Option Explicit

Sub Test_UseOfVariantReturningStringFunction()
Dim TestVar As String
Dim lary_Temp() As String

'correct - both Right and Trim are marked
TestVar = Right(Trim(Replace(lary_Temp(UBound(lary_Temp)), """", " ", , , vbTextCompare)), 1)

'correct - only Right is marked
TestVar = Right(Trim$(Replace(lary_Temp(UBound(lary_Temp)), """", " ", , , vbTextCompare)), 1)

'wrong - Right$ is also marked
TestVar = Right$(Trim$(Replace(lary_Temp(UBound(lary_Temp)), """", " ", , , vbTextCompare)), 1)

End Sub
```

**Comment by Pitterling** [comment]
also true for LTrim$, Str$, Chr$

**Comment by retailcoder** [comment]
ugh. this one is *hard*! You have no idea the hoops I had to jump through to get this one to work again off the COM reflection declarations... which makes inspections that look for declarations that aren't user code, impossible to write unit tests for, because they require loading the actual type library to inspect the COM types and their members.

Long story short, the resolver is *supposed* to resolve `Right` to `_B_var_Right` and `Right$` to `_B_str_Right`.

Thanks for reporting this issue, my own in-IDE tests seemed like everything worked properly.

**Comment by retailcoder** [comment]
So I had to explicitly special-case them:

    private readonly IReadOnlyList<string> SpecialCasedTokens = new[]{
        Tokens.Error,
        Tokens.Hex,
        Tokens.Oct,
        Tokens.Str,
        Tokens.CurDir,
        Tokens.Command,
        Tokens.Environ,
        Tokens.Chr,
        Tokens.ChrW,
        Tokens.Format,
        Tokens.LCase,
        Tokens.Left,
        Tokens.LeftB,
        Tokens.LTrim,
        Tokens.Mid,
        Tokens.MidB,
        Tokens.Trim,
        Tokens.Right,
        Tokens.RightB,
        Tokens.RTrim,
        Tokens.UCase
    };

Otherwise, any project-scope declaration that had only 1 possible `Declaration` to resolve to, would "return early", before the `_B_var_` / `_B_str_` "surrogate name" matches were being attempted.

I'm now getting all expected inspection results - and it's unfortunate that I had tested with `Left` and `Left$`.. but `Left` exists multiple times in several places (e.g. along with `Top`) - the same doesn't hold true for `Right` and `Chr` and `LTrim` and the rest of 'em.

Thanks again for your contribution!
