### ISSUE TITLE
Excluded changes can't be undone

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1215]
When a file is modified but the changes are excluded, the [Undo] button doesn't work. It only works when the changes are included and undone from the "included changes" box.

**Comment by Hosch250** [comment]
This strikes me as being strange because they are both wired to the same command.  I think there is a bug, though, where I do not update the UI.  Can you verify that the file does not change?  Also, does the Included Changes button still work on your end?  I seem to have trouble with it on my end now.

**Comment by Hosch250** [comment]
Turns out Undo only worked sporadically from the Included changes command.  I just fixed this.
