### ISSUE TITLE
Reuse grammar fragments

### ISSUE THREAD

**Issue by autoboosh** [rubberduck-vba/Rubberduck#1250]
Quite a few parser issues have been reported yesterday and there's still the open issue of grammar duplication in various parsers (e.g. the AttributeParser and the VBAParser as well as the Preprocessor grammar). That's why I'd like to suggest we first try and refactor the existing grammars so that they can be reused before fixing all the new issues.

We could proceed like this:

1. Split up combined VBA parser into parser and lexer. This will force us to create tokens for everything instead of hardcoding them into the parser
2. Introduce ERROR token so that lexer issues get passed to the parser for error reporting. This is just something I've noticed while dealing with some parser/lexer issues a while ago. Now seems a good time to clean this up.
3. Split up those parts of the parser/lexer into separate files that have to be reused. I'm not quite sure yet which parts and if that's even necessary.

**Comment by autoboosh** [comment]
@retailcoder: I don't quite understand why there's a separate AttributeParser. Couldn't we just use the VBAParser for attribute parsing? Diffing the two grammars it even looks like the AttributeParser contains a few bugfixes that are not in the main grammar yet. Should I add those differences to the main grammar and replace the attribute parser with the main one?

**Comment by retailcoder** [comment]
@autoboosh the reason I split them was to have the simplest possible AST to work with; could be premature optimization though.. I originally intended to only have it feature enough to know the current scope, but it snowballed a bit and I had to include a lot more of the VBA.g4 grammar than I intended to. I'm not against merging them.

**Comment by Vogel612** [comment]
That means we'd have Attributes as Declarations? Or would we introduce an `AttributeListener` for traversing the Parse-Tree?

**Comment by retailcoder** [comment]
@Vogel612 the thing is that the VBE hides the attributes; to get correct line positions for parser tokens we need to parse the code off the VBE - and so attributes must be parsed separately, off an exported text file; I already implemented an attribute listener that works off that AST and collects member attributes, which I then pass to the identifier declarations listener so that it can attach member attributes to member declarations. But the two parses need to be separate, in order to have correct parser token positions, which every `Declaration` and `IdentifierReference` uses to determine its `Selection`.

**Comment by autoboosh** [comment]
Fixed with https://github.com/rubberduck-vba/Rubberduck/pull/1255.
