### ISSUE TITLE
Problem after renaming a unit test

### ISSUE THREAD

**Issue by INOPIAE** [rubberduck-vba/Rubberduck#1252]
I create a unit test with the default name TestMethod1
When I run the test everything is fine.
After renaming the method I get the error method cannot be found.

After closing of the file and reopening it. The test case is not used at all.

**Comment by Hosch250** [comment]
When this issue was created, it is because RD tried to run a "known" module that didn't exist.  You would have needed to refresh the test explorer for it to show up.  Since this issue was created, the same thing will happen until a reparse happens, which will make the explorer update.  There is no good way to prevent this problem because we do not know when a module is renamed, nor which is renamed, from the test explorer.
