### ISSUE TITLE
Add/Remove Project References Dialog

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1276]
The VBE's _add reference_ dialog is painful - we could design a dialog that features a _Search_ box so users can easily locate what they're looking for. We could also keep a list of "recent" references (saved in settings and updated automatically by simply using the dialog) so that users don't even need to search for them at all, and separate COM libraries from saved & opened VBA projects.

**Comment by ThunderFrame** [comment]
Referencing #950

**Comment by ThunderFrame** [comment]
Subtleties of the References Dialog: The References dialog lists *referenced libraries*, then libraries referenced by other open projects (which is one way of discovering libraries that protected projects are referencing), and then registered libraries.

**Comment by rossknudsen** [comment]
@Hosch250 @retailcoder Where do you think the menu command should be located?  Off the root of the RD menu?  Then I can probably give you a preview.

**Comment by ThunderFrame** [comment]
@rossknudsen Did you have something that needed to be PR'ed?

**Comment by rossknudsen** [comment]
Hi @ThunderFrame.  I've got some code which is not ready for PR at this stage.  I have a dependency on a service which can allow the opening of application specific files, so they can be added as reference.  E.g. in Word, I need to be able to open *.docx, *.docm, *.doc, *.dot etc.  Similarly, Excel has a different set of files.

The built in references dialog allows you to reference these files, but it opens them in the background before it creates the reference.

Alternatively, I can create a PR for the references dialog without the ability to do this - i.e. only able to add references to dll/exe/tlb/ocx

**Comment by retailcoder** [comment]
@rossknudsen I still have your old PR in my fork. Haven't had a chance to work on it much for a while, but IIRC I was working on factoring out the dependency on `VBProject` so that project references would only ever get added/removed *after* the dialog is closed (and so nothing would happen if the dialog was cancelled, regardless of what happened while the dialog was open). You might want to pick it up from there, but it's probably over a thousand commits behind at this point.

**Comment by retailcoder** [comment]
Dependencies on `Kavod.ComReflection` also need to be removed.

**Comment by rossknudsen** [comment]
Note, `Kavod.ComReflection` is a provided in a Nuget package.  It provides the enumeration of available COM types.  But you might mean that there is existing Rubberduck code that can replace this - I haven't checked.

From memory I modified the code so no changes are made until the dialog is closed, irrespective of the VBProject dependency.  But you haven't got those changes because I'm pretty sure I haven't pushed them.

**Comment by comintern** [comment]
@rossknudsen - I haven't checked to see what functionality was being used from `Kavod.ComReflection`, but RD's version is in the `Rubberduck.Parsing.ComReflection` namespace.

**Comment by ricardoba13** [comment]
Adding a better Windows Form to add Refrences to the project would be awesome. I t is just because the built in form is just so dump and it does not allow you to know a description of what the dll has or the entire path of the dll you are selecting in order for you to be able to google it and see what you can do with that library.

**Comment by comintern** [comment]
Closed via #4601
