### ISSUE TITLE
CI - return value never assigned/never used - broken with recent changes

### ISSUE THREAD

**Issue by Pitterling** [rubberduck-vba/Rubberduck#1295]
Hi, don't know if I should open an issue at all .. reading through the last changes a lot has happened and might be in transition ...

anyway code fragments like these are reported wrong
```
Public Property Get WorkbookTemp() As Excel.Workbook
 Set WorkbookTemp = m_WorkbookTemp
End Property
```

or

````
Public Property Let DateTimeStartUser(ByVal dTime As Date)
 mTimeStartUser = dTime
 mTimeStartUserSpecified = True
End Property
````

**Comment by retailcoder** [comment]
I noticed as well, thanks for reporting anyway - the issue is that in several places (including the resolver) we're relying on the `VBProject` reference to be usable for equality checks, and ...well, it's not, because COM interop gives us a new object reference everytime we reparse.

We have a work-around though.. I'm currently hunting down all `other.Project == Project` checks and replacing with something more reliable.

**Comment by Hosch250** [comment]
Please check this again now that we changed the apparent bug.

**Comment by Pitterling** [comment]
Its fixed. Thx.
