### ISSUE TITLE
Renaming a project leaves qualified names in class modules as old, but cached/valid names

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1303]
VBE seems to cache a compiled version of the class module code, but restarting Excel will cause compile time errors:

Steps to reproduce:
*Note: I've made the classes Public instanced, but only so that I can return an instance from the method in ThisWorkbook. The instancing isn't critical to this bug occurring*
1. Create a Project and name the project `MyOldProject`
2. Add this VBA / these modules:
```vb
'ThisWorkbook
Option Explicit
Public Function mot() As MyOldProject.MyOtherClass
  Set mot = New MyOldProject.MyOtherClass
End Function

'Class MyClass
'Instancing: Public
Option Explicit
Public Function Other(obj As MyOldProject.MyOtherClass) As MyOldProject.MyOtherClass
  Set Other = New MyOldProject.MyOtherClass
End Function

'Class MyOtherClass
'Instancing: Public
Option Explicit
Public Function Original() As MyOldProject.MyClass
  Set Original = New MyOldProject.MyClass
End Function

'Module1
Sub test()

  Dim o As Object
  Dim v As Variant
  
  Set o = New MyOtherClass
  Set v = o.Original
  
  Set o = ThisWorkbook.mot()
  
  Dim p
  Set p = New MyClass
  Set v = p.Other(o)
  
End Sub
```
3. Run `Module1.Test`
4. Rename the project to `MyNewProject`
5. Run `Module1.Test`
6. Save the project
7. Restart Excel
8. Reopen the project
9. Compile the project

The project compiles and runs for me under Excel 2010 and 2013 (32-bit editions).

Rubberduck should offer to refactor qualified names when a user manually edits a project name.

**Comment by comintern** [comment]
OK, _now _I can replicate this. I wasn't putting the project references on code in the Worksheet modules.  It gets weirder though - because there can **only be 1** top level project identifier.  It will immediately start complaining about a User-defined type not defined on `MyOldProject` as soon as you do pretty much anything that would cause it to attempt to dereference ` MyNewProject `.

I think it should very strongly suggest that it refactor qualified names.

**Comment by Hosch250** [comment]
Yeah, yeah, the beautiful cache bug that cause so many crashes.  I fixed this a while back (or I think I did--feel free to double check).
