### ISSUE TITLE
"Move declaration closer to usage" blows up when only usage is in another module

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1318]
Repro:

 - Expose public field `Foo` in ThisWorkbook
 - Create procedure `DoSomething` in `Sheet1`, make it assign `ThisWorkbook.Foo = 42`
 - Reparse
 - Right-click `Foo` in `DoSomething`; "Move closer to usage" is enabled - click it.
 - :boom: 

---

If the only usage of a public field is in another module, the refactoring should move it to the module where it's used.

**Comment by Hosch250** [comment]
That's a feature.  It only works when moving a field closer to its usage in the current class.

**Comment by retailcoder** [comment]
It's a bug, there's an exception and it blows up - and it should be able to work across different modules.

**Comment by Hosch250** [comment]
I was being sarcastic there...  Pity GitHub doesn't offer a sarcasm font.

**Comment by Hosch250** [comment]
This happened because I designed this with private fields in mind.  When it tried to work off a public field being accessed from a different module, it crashed because I was working in the wrong code pane, and it couldn't find the members in the place it was looking for.  Specifically, it would crash because the string it read didn't have the correct content, so it didn't have the correct index range.
