### ISSUE TITLE
Resolve: implicit variable creation

### ISSUE THREAD

**Issue by autoboosh** [rubberduck-vba/Rubberduck#1387]
Does the resolver automatically create declarations for "implicitly created variables" if Option Explicit is not specified? Should we do that?

**Comment by retailcoder** [comment]
At one point I wanted to implement this, and basically generate declarations on-the-fly for any identifier we encounter but couldn't resolve. The main problem was that I needed declarations for everything in the referenced libraries... and now with COM `ITypeInfo` inspection, we have that.

So... this would work, *if the resolver was completely and perfectly flawless* (e.g. right now a declaration would be created on-the-fly for `Debug` and then its `Print` and `Assert` members).

But let's pretend the resolver *is* flawless for a second.

This opens new (very cool) doors:

 - We could have an inspection for "undeclared variable usage" ("Local variable '{0}' is used but never declared"), and a quick-fix that generates a local variable, or even a class with properties and methods, and a local variable of that type; we could infer the needed return types to the best of our knowledge, and make everything else an explicit `Variant`.
 - "Generate class", "Generate module", "Generate local", "Generate field", and "Generate member" refactorings... which the above inspection/quickfix would actually be calling into.

But, false positives would be incredibly annoying - that's why it hasn't been done yet: because the resolver *isn't* flawless yet.

**Comment by retailcoder** [comment]
This was completed a little while ago. "Undeclared variable" inspection is also implemented.
