### ISSUE TITLE
excel crash trying to refresh code explorer with test window open

### ISSUE THREAD

**Issue by Talorthain** [rubberduck-vba/Rubberduck#1417]
code explorer doesnt show anything. Clicking refresh didnt work
Added a module and a simple couple of lines of code
code inspector worked
todo explorer worked
Added a test module
test window still open, I clicked refresh on code explorer and it crashed excel.

Version 2a

n.b code explorer when first open very slow to start and mouse juddery (I assume it is obtaining information). It eventually returns to normal, but nothing is displayed.

**Comment by retailcoder** [comment]
I actually commented-out the code explorer's ViewModel code for the preview release, and disabled its command menu item; it only comes up with a hotkey, and I disabled that command's hotkey in the default settings for the release (but you could still re-enable it). The reason was because it was (still isn't) not fully implemented, and the way it's implemented is really too prototype-y - I'm creating a separate issue to specify it for @Hosch250 to implement.

The 'refresh' command in all toolwindows is the same as the 'refresh' command in the rubberduck command bar (/status bar), so it would have crashed regardless of whether it was triggered from the code explorer, inspection results, rubberduck command bar, or Ctrl+` hotkey. I have strong reasons to believe this is due to cache invalidation errors in the parser state, which keeps bad pointers to stale COM objects, and then when these objects are accessed they throw a `COMException` at us (sometimes an `AccessViolationException` too), and blow everything up. Once the parser state correctly handles and destroys its COM references, everything should be much more stable.

**Comment by Talorthain** [comment]
Hi, Is this the reason for the crash on exit of excel?

**Comment by retailcoder** [comment]
It could very well be. Crashing on exit has been seen to be caused by a plethora of various different things, all related to things not properly cleaning up, e.g. at one point the `App.Dispose()` method was not being called, and then the crash-on-exit was consistently happening. COM objects sticking around tend to do that, too.

**Comment by Hosch250** [comment]
Closed now that this is fully implemented
