### ISSUE TITLE
Code Inspections not invalidating certain inspection results

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1433]
Language Opportunities seem to be cached, particularly when using the special `$`-suffixed methods, which in this example, aren't resolving from the `Left` name from `_B_var_Left`.

The inspections are correct when first run, but merely changing the line or character position of the offending lines, results in all instances of the inspection being duplicated upon the next refresh.

Adding or removing lines before, and adding or removing characters on the same line before a `_B_var` function will result in the duplication.

Code on first inspection
![inspections1](https://cloud.githubusercontent.com/assets/16574009/15043151/7ff2d14a-130d-11e6-8be7-3bf2b19dbd59.jpg)

Code after inserting a row above the inspection target
![inspections2](https://cloud.githubusercontent.com/assets/16574009/15043163/a3d5bf3c-130d-11e6-833e-3e7d11b063ab.jpg)

**Comment by Vogel612** [comment]
This specific problem is already mentioned in #1405 I assume that's actually the same underlying "issue"

**Comment by autoboosh** [comment]
This is only tangentially related but could we maybe simply create a declaration whose name was Left instead of _B_var_Left in the com collector? Do we have that info somewhere in the type library?

**Comment by ThunderFrame** [comment]
Thanks @Vogel612 for the reference to #1405. I'll post follow-up issue here, as it relates to the example above.
If I choose to `Fix all occurrences in module` for the `Left` inspection result, then *all* of the `_B_Var` prefixed functions in the module are fixed. So, I end up with:

```vb
Sub foo()
  Dim s As String
  s = Left$(s)
  s = Right$(s)
End Sub
```
Even though I only *wanted* the `_B_Var_Left` inspection instances fixed.

**Comment by Vogel612** [comment]
I think that's [status-by-design] The inspection is of the same type. That's why replacing `Left` with `Left$` is considered the "same issue" as replacing `Right` with `Right$`

**Comment by ThunderFrame** [comment]
hmmm, then, IMO, it should be a single inspection result. If there are multiple inspection results, it implies that you can fix *each one* independently, while the current behavior is *fix any one, and fix them all.*

But users might have a reason to only fix *some* of the $ functions, so, IMO the UI should allow them that control.

**Comment by Vogel612** [comment]
@ThunderFrame the current behaviour is not *"fix any one, and fix them all"* it's *fix all, and fix really all*. Each instance of that inspection refers to one call to any of the String functions that don't have a type-hint given as of now.

These can be fixed **one by one**. Then you can select which you want to replace.

I frankly can't think of any situation where you'd want to replace all `Left` calls with `Left$` and **not** do the same for `Right` calls or `Hex` or whatever

**Comment by ThunderFrame** [comment]
@Vogel612 But the current UI is making it look like I'm only going to fix the inspection result that is selected, but the fix action applies to all results in that Language Observations section??

I don't disagree that changing all might be the best approach - it's just that the UI doesn't make it clear that that is the behavior.

I can think of situations where I'd want to fix `Trim` for trimming query input parameters, but then *not* fix `Mid` when it's used on Recordset field values (that might be null). I'm not saying that's good practice.

**Comment by retailcoder** [comment]
This isn't a caching issue. It's a resolver issue.

@ThunderFrame this is by design. "Fix all" works by inspection, and the inspection isn't specific to `Left` or `Right` or `Mid` - the inspection is looking for variant-returning function calls where an equivalent string-returning function exists. That's a list of about 20 built-in functions, handled with one inspection. Making them separate inspections wouldn't make sense - if you "disable this inspection" for "Left should be Left$", then you also expect to disable "Mid should be Mid$". And if "Left should be Left$" is a *suggestion*, then you wouldn't make "Right should be Right$" a *warning*; they're one and the same. Hence, "fix all occurrences" can't be specific to the individual inspection result, it applies to all occurrences *of a given inspection's results*.

**Comment by ThunderFrame** [comment]
OK, so it's my misunderstanding of how the Inspections list is working... I just tried fixing all occurrences of Option Explicit, even though I was on the Sheet1 inspection result, and indeed, Option Explicit was added to the sheet *and* the workbook.

But the UI is *highly* suggestive that it is only going to operate on Sheet1...

![ambig](https://cloud.githubusercontent.com/assets/16574009/15046937/b796d9da-1325-11e6-98b2-aadc9c6bdc36.jpg)

I'm not sure how, but I think we need to make it clearer that the fix will (potentially) apply beyond the currently selected inspection result.

**Comment by Vogel612** [comment]
Fix all occurrences says "**all occurrences**" ... I don't see where this is misunderstandable. If you want to fix the one in `Sheet1` use the Fix button with the option "fix this instance" ... (should be labelled "Add `'option explicit'` to 'Sheet1'") ...

**Comment by retailcoder** [comment]
Actually the bottom panel is supposed to be displaying a generic description of the inspection - the same that's shown in the inspection settings. These *generic descriptions* don't have identifier placeholders; the bold text should say

> **Option Explicit is not specified**

That would address the top-most red square in the bottom panel.

Perhaps the `Selection` of the selected inspection result should be moved into the toolbar, leaving the bottom panel only with *inspection-level* info (vs. *result-level* info)?

As for the 'Sheet1' references in the two red squares in the grid area, they're by design; the grid area is *supposed* to contain result-level, instance-specific information.

**Comment by ThunderFrame** [comment]
@Vogel612 The Fix button that is at the top? Yep, that works, but best not press it too many times, as it applies the fix repetitively. Maybe we can mark the inspections as having been applied, or check before applying the fix, that the fix is still necessary?

**Comment by ThunderFrame** [comment]
@retailcoder yes, I understand the 2 Sheet1's in the grid area are by design. It's the 2 in the bottom panel that are misleading... But the combination of all 4 just reinforces the ambiguity of the 2 at the bottom.

**Comment by retailcoder** [comment]
Agreed. The bottom panel shall be for *inspection-level* info and commands.

**Comment by retailcoder** [comment]
@autoboosh the problem with that is that we'd no longer have the `IdentifierName` telling us whether the function called is the variant or string -returning version, which moves the problem elsewhere. Any ideas?

**Comment by Hosch250** [comment]
This was a bug because the references weren't being cleared before a reparse, resulting in duplicate references.
