### ISSUE TITLE
Problems opening stored repo

### ISSUE THREAD

**Issue by INOPIAE** [rubberduck-vba/Rubberduck#1516]
Using commit 3b65933 with Excel 2010
When trying to open a saved git repro I get this error message:
![image](https://cloud.githubusercontent.com/assets/2772829/15312074/3b68229e-1c01-11e6-8032-b0a1f994a007.png)

Using the ignore button I get this message:
![image](https://cloud.githubusercontent.com/assets/2772829/15312105/903cfc36-1c01-11e6-9294-2c485764511d.png)

**Comment by Vogel612** [comment]
So this blows up because `parent` is null. The error message you get is what happens when you hit the line directly before the one the NRE occurs on.

I assume this has to do with a problematic Settings-File. Would you mind attaching the settings file you have?

**Comment by comintern** [comment]
Parent is null because it can't find the root element.  Oversight on my part - "Configuration" was only the root element of the main user settings.  Can you check your SourceControl.rubberduck file?  I don't have one from before pulling out the old base class, but I suspect the root element might need to be "SourceControlSettings" for that file.
