### ISSUE TITLE
Code Inspections refresh button doesn't *force* a refresh

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1617]
The standard refresh buttons allows you to trigger a refresh, even when the prior refresh is stuck on `Parsing`.

the Code Inspections refresh button will trigger a reparse, but if that parse gets stuck, then subsequent presses don't retrigger a reparse.

**Comment by retailcoder** [comment]
The refresh command is the same command everywhere, be it on the "Rubberduck" command bar, the code explorer, inspection results, or todo explorer (it's only a different command in the source control panel, where the refresh operation involves I/O).

There's no way to *force* a full reparse: refreshing will only ever parse modules that have been modified since the last parse, by design.

@Hosch250 please disable the refresh buttons whenever refreshing wouldn't actually do anything.
