### ISSUE TITLE
Inspection: Object reference possibly not set

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1636]
Consider this code:

```
Cells.Find(...lots of params...).Select
```

`Cells.Find` returns a `Range` object reference that will be `Nothing` if there's no search result; the `.Select` call will blow up with a runtime error if that's the case.

Triggering this inspection for every single object-returning built-in function out there would fire up way too many false positives.

Triggering this inspection for every single object-returning user function out there would also fire up way too many false positives.

Too many false positives makes an inspection useless.

---

Let's make a settings page to allow the user to enlist whatever functions they want to check for - and we could have a default set of functions in that list, that would include `Range.Find`.

For user code, we could have a `'@NeverNothing` annotation that tells Rubberduck to not bother checking call sites of an annotated function. Ideally though, we would instead be able to _actually tell_ whether a function can or cannot possibly return `Nothing`.

**Comment by Vogel612** [comment]
> Ideally though, we would instead be able to actually tell whether a function can or cannot possibly return Nothing.

This seems to be a job for execution path analysis. In general this can be analyzed using formal verification processes like "weakest precondition" or standard semantic analysis.

Especially the "never nothing" case should be easy enough to verify. I don't see the necessity to actually investigate into a user-annotation, because those simply are more unreliable than actually inspecting the code. It's just a comment for the purpose of the code semantics.

Then again the idea of checking for `Nothing` instead of leaving that to humans who can often do this more efficiently than a program might be an overstretch of what Rubberduck can (and should) do...

**Comment by retailcoder** [comment]
@Vogel612 [40,030 results and counting](http://stackoverflow.com/search?q=%5Bvba%5D+not+set)

**Comment by retailcoder** [comment]
linking #2103
