### ISSUE TITLE
Releasing COM objects.

### ISSUE THREAD

**Issue by LNow** [rubberduck-vba/Rubberduck#1704]
Hi, I'm trying to understand how Rubberduck works and can't find a clue how releasing COM object has been resolved.
As far as I remember each and every COM object should be declared and release separately. For releasing object `Marshal.ReleaseComObject()` should be used but it occurs only twice in Rubberduck code.

So, can someone explain me thoroughly how it has been done, please?

**Comment by retailcoder** [comment]
Rubberduck is running in-process with the VBE; maybe we're doing this wrong, but basically we're leaving it to the runtime to determine when to let go and GC things... [which is basically undeterministic](http://stackoverflow.com/a/2260257/1188513). Perhaps this could be why we *sometimes* run into weird issues, like a project that remains in the VBE after its host document was closed...

Thanks for bringing this up.

**Comment by transistor1** [comment]
Forgive me if I'm wrong but I dont think it matters if you are in proc or out of proc.   Every time you access a COM object from VBE, .NET automatically creates a Runtime Callable Wrapper  (RCW) and calls AddRef on the COM object.  This has to be released using Marshal.ReleaseComObject () as @LNow states (actually I have read it's best to use FinalReleaseComObject but I dont have sources at the moment as on a cell). This is most likely one reason why you're getting crashes on close.

That's what is nice about using NetOffice.. it abstracts this away by implementing IDisposable to release the COM for you.  I use it in my product & it's very nice.  I know youve discussed that before & you cant use it... but maybe you could implement a similar strategy?

**Comment by transistor1** [comment]
BTW... Mike Rosenblum (Mr. Excel) is a great source for this.  He has written a ton of stuff on this topic. Heres one http://stackoverflow.com/a/159419/864414

**Comment by LNow** [comment]
@transistor1 in addition if you use COM object in chain like `Application.Workbook.Worksheet.Range` ReleaseComObject will not help you, as RWC can't handle it. It will release only the first one (Application), so you will end up Excel hanging in memory even if you close it.

What I have found is NetOffice creates it's own "object tree" in memory, so at the end of the day you only have to release ONE (aka. main) object, to release every child.

**Comment by transistor1** [comment]
@LNow if you look at the link by Mike Rosenblum above, he suggests calling `GC.Collect()` and `GC.WaitForPendingFinalizers()`, which is supposed to get rid of those intermediate objects that are created by the "two dots" problem you mentioned above (the objects you don't have a direct reference to).  Then you are supposed to explicitly free objects with `Marshal.FinalReleaseComObject()`:

```
// Cleanup
GC.Collect();
GC.WaitForPendingFinalizers();

Marshal.FinalReleaseComObject(xlRng);
Marshal.FinalReleaseComObject(xlSheet);

xlBook.Close(Type.Missing, Type.Missing, Type.Missing);
Marshal.FinalReleaseComObject(xlBook);

xlApp.Quit();
Marshal.FinalReleaseComObject(xlApp);
```

All that said, NetOffice is a way better solution IMHO, as you also stated.

**Comment by retailcoder** [comment]
NetOffice isn't going to cut it, as we found out last year (see #113). Has anyone succeeded in creating a docked toolwindow with the NetOffice PIA's? There's a number of things Office and VBE add-ins are very different about.

**Comment by transistor1** [comment]
@retailcoder 

> Has anyone succeeded in creating a docked toolwindow with the NetOffice PIA's?

[This works for me](https://github.com/transistor1/ComAddinTest).

**Comment by retailcoder** [comment]
@transistor1 did they fix the *force focus* bug? The VBIDE API doesn't always correctly set the focus where we tell it to, and per #617 using NetOffice would break the (quite important) hack we're using to force-focus a given selection.

Also, to be honest I'm not too eager to switch to NetOffice anyway, especially since we don't *only* have Office PIA's referenced - having different abstraction levels for what amounts to the same concern (interacting with the host app and the VBE), doesn't sound like a very sane option.

**Comment by ckuhn203** [comment]
I just want to clarify why we're not using NetOffice.

NetOffice has made a very nice implementation of the different Office APIs, but their VBE Api is not implemented correctly. They broke the *real* interface in ways that are completely incompatible with our project. I can no longer remember the nitty gritty details, but they failed to adhere to some of the COM interfaces when it comes to `ref` arguments to certain methods.

**Comment by LNow** [comment]
Guys my main intention was to point out a problem with releasing COM objects.
Rubberduck is not using NetOffice and we have to deal with this problem without using it. I mentioned NetOffice because we can find there pretty good solution.
Implementation of something similar in Rubberduck will be time consuming - that's for sure. Is it worth? In my opinion definitely.

Having a clean reliable center point, responsible for managing COM objects is something that we should look for.

**Comment by retailcoder** [comment]
@LNow agreed on all points. Although, I'd like it to not delay us from issuing a beta release... the 2.0 Code Explorer is a little revolution all by itself, and has never been released. Not to mention the TON of bugs fixed since the last alpha release - Rubberduck is much more stable that it was just a month ago, thanks to the sustained efforts of many contributors - and we'll strive to keep making it better with every release.

If we were a commercial product, I wouldn't even bother - I'd just say "we're not ready yet" and, at the risk of pulling a *Duke Nukem Forever* (the project that coined the term "vaporware"), delay the next release. But we're talking about a *beta* release, of an *open-source* project. We just want to tell the world "look, this is what we've done, this is where this project is at - yes, it will get even better, give us time, or help us, and contribute!"

**Comment by autoboosh** [comment]
This is a bit off-topic but you're the guy who made the [Access SQL Editor](https://fieldeffect.info/purchase/) @transistor1? I use that addin every day, it makes it possible to use Access without going insane, thanks for making it :)

**Comment by transistor1** [comment]
@autoboosh LOL yes... you're welcome and thank you very much for using it!! I also use it to keep my sanity at work writing SQL in access.  Like you might have guessed, it's an ActiveX object written in C#, which uses NetOffice for interop ;)

**Comment by ThunderFrame** [comment]
@transistor1 I wasn't aware of that tool. Looks great (and a lot like SSMS).

**Comment by transistor1** [comment]
Thanks @ThunderFrame !
