### ISSUE TITLE
Crash after parsing on "inspecting" status

### ISSUE THREAD

**Issue by BobTB** [rubberduck-vba/Rubberduck#1770]
After a simple working and successfully compiled project is successfully parsed, status bar changes to "inspecting..." and the whole MS Access crashes. I am attaching the log. 

[inspectingCrash.txt](https://github.com/rubberduck-vba/Rubberduck/files/308979/inspectingCrash.txt)

![image](https://cloud.githubusercontent.com/assets/15887688/15964509/2b5837f6-2f19-11e6-8390-0759abda046d.png)

**Comment by retailcoder** [comment]
I'm voting for a bug in one or more inspections that's throwing a `COMException` that doesn't get logged and that isn't handled either, crashing the host. We need to add some TRACE or DEBUG logging to the inspector so we know which inspections are running, which have completed and how many results each has returned - the exception handling and logging needs to happen in the inspections thread, otherwise we'll never know exactly which inspection threw the exception, since inspections are running concurrently.

**Comment by Hosch250** [comment]
Do you think you could figure out the minimum code to reproduce this?  We can't see all the code in this project, so we can't even start to figure out what is wrong.  If you make an minimum, verifiable example, I'll take it from there.

**Comment by BobTB** [comment]
Ok, this is a quick thrown together test access db with really almost no code which crashes immediately after  inspecting...  is shown in rubberduck VBA editor.

[Crash.zip](https://github.com/rubberduck-vba/Rubberduck/files/310285/Crash.zip)

**Comment by Hosch250** [comment]
Cool, will get on it soon.

**Comment by Hosch250** [comment]
Perfect--an InvalidOperationException in Single because we weren't correctly distinguishing between declarations in different modules.

**Comment by BobTB** [comment]
great :)
