### ISSUE TITLE
Default Folder for importing/exporting code modules is now the RubberDuck folder

### ISSUE THREAD

**Issue by Zak-Michael-Armstrong** [rubberduck-vba/Rubberduck#1797]
In my particular Case, C:\ProgramData\Rubberduck

I literally have no idea where the old default folder was and now I'm going to have to go google it.

This is not a thing that RD should be altering.

**Comment by autoboosh** [comment]
Also since we parse multiple components in parallel and we use the component name as filename, couldn't it be that one attributeparser reads in the component file of a different component? Perhaps we could use [Path.GetTempFileName](https://msdn.microsoft.com/en-us/library/system.io.path.gettempfilename(v=vs.110).aspx) or use a GUID or something like that?

**Comment by retailcoder** [comment]
@autoboosh yep, best solution would be to let the framework give us a temp filename. Some tweaks will be needed to the SC export interface though, since that code is reusing the SC wrapper for exporting modules.

**Comment by Hosch250** [comment]
As far as I know, I let Windows automatically set that based on your usage.  I don't think I set default locations for import/export.

**Comment by Hosch250** [comment]
This would seem to be a code explorer enhancement, but based on the other comments, I'm not sure what it is.  Is this the folder suggested when importing/exporting components from the CE?

**Comment by retailcoder** [comment]
@Zak-Michael-Armstrong there is no default. Wild guess, the VBE merely brings up the last folder that was accessed by the host's process - and that's the folder where Rubberduck fetches its settings from. Nothing to fix here, nothing harmful either.
