### ISSUE TITLE
Code Explorer - Current node not showing up in list.

### ISSUE THREAD

**Issue by PeterMTaylor** [rubberduck-vba/Rubberduck#1830]
Was looking at one class and opening the Code Explorer and it occured to me that the current viewing node is not showing up in the CE list. Is this the expected behaviour? was expecting to see a node called cDatarow

![capture cdatarow no show](https://cloud.githubusercontent.com/assets/2254567/16078382/f521bef0-3341-11e6-806a-1d5360ad72a4.PNG)

**Comment by retailcoder** [comment]
Parser is in a *Resolver Error* state, we cannot guarantee *anything* is what and where it should be. Still there *should* be a node for every module, even ones that didn't parse at all.

This is a bug.

**Comment by Vogel612** [comment]
ResolverError implies we did get through Parsing and that means we should have the relevant information for CE available, correct? 

Could we just try to refresh the CE, even when the ParserState gets updated to ResolverError?

Basically the only unworkable state is `ParserError` or everything that's not between `Parsed` and `Ready`, right?

**Comment by retailcoder** [comment]
@Vogel612 actually even `ParserError` should show unparsed modules as error nodes. Not sure what's going on here.

**Comment by Hosch250** [comment]
@Vogel612 If we get to Resolver Error while creating the declarations, this is expected behavior.  There wasn't a parser error, so we can't display the warning icon for a single module.  It didn't finish creating the declarations, so there is an incomplete list.  I'm not real sure how to handle this better if this is the case (other than fixing the bug that caused it to throw an exception or whatever here).
