### ISSUE TITLE
Code Inspection suggests Intermediate Fix, a different fix is suggested next inspection (MS Word)

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#1865]
Applies to: RD 2.0.2b, edc2df2

Example. Create new document & add UserForm. Add Query Close from dropdown menu, initially it will look like this:
```
Private Sub UserForm_QueryClose(Cancel As Integer, CloseMode As Integer)

End Sub
```
On the first inspection, Rubberduck will correct the implicit ByRef and an automatic fix will look like this:
```
Private Sub UserForm_QueryClose(ByRef Cancel As Integer, ByRef CloseMode As Integer)

End Sub
```
However, when the code is reinspected, Rubberduck will suggest correction of ByRef to ByVal, resulting in this:
```
Private Sub UserForm_QueryClose(ByVal Cancel As Integer, ByVal CloseMode As Integer)

End Sub
```

I can imagine why it works like this, but it would be nice to go from implicit ByRef directly to explicit ByVal.

**Comment by retailcoder** [comment]
Actually changing `ByRef` to `ByVal` on an event handler would break the code; the inspection needs to ignore event handlers, whether they're for built-in events or not.

The suggestion to explicit `ByRef` is fine; the problem is with changing `ByRef` to `ByVal`, and that suggestion is made because a `ByRef` parameter should be an array, or should be assigned in the body of the procedure; the two results are independent of each other; actually your initial inspection results should have included both results, since "parameter can be passed by value" does not look at whether the parameter is passed `ByRef` implicitly or explicitly.

**Comment by Stevefb** [comment]
Yes you are right about event handlers, I was thinking more about the general case when I wrote that.  Showing both options in the results would be a reasonable approach :+1:

**Comment by Hosch250** [comment]
Actually, now that we have the built-in event handlers, we can fix this.

**Comment by Hosch250** [comment]
Actually, when I see these, usually both inspections are fired up, and when it is made explicitly byref, that one stops showing.  Are you sure only one is firing the first time?

**Comment by Hosch250** [comment]
This is no longer an issue that the `QueryClose` event and a few others not in the dll are hard-coded into RD.
