### ISSUE TITLE
Type-hinted declaration's type is `Variant`

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1928]
A declaration that uses a type hint instead of an explicit type, still has a known type:

    Dim startRow&

Selecting the above declaration displays `startRow (variable: Variant)` in the Rubberduck command bar; this is wrong. It should be the same as this:

    Dim startRow As Long

Which is displayed as `startRow (variable: Long)`.

Fixing this needs to be careful about the `AsTypeName` value of the declaration, since there is code that relies on it being empty for type-hinted declarations. Perhaps we should introduce a `KnownTypeName` property that takes the type hint into account, and use that in the command bar instead of the `AsTypeName`?

**Comment by Vogel612** [comment]
I like that workaround, especially since it allows us to update the KnownTypeName for declarations when they are later assigned values. This would empower the "Variable declared as Variant" inspection to actually declare the used type instead of requiring the user to know.

Note that this could involve doing type-resolution. Since VBA doesn't allow implementation inheritance we're kinda lucky there though.
