### ISSUE TITLE
False Negative: Code Inspection not detecting "Variable not defined"

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#1959]
Following module will not compile using: Debug > Compile 
```vb
Option Explicit

Public Const ABC As Long = 1
Sub FalsePos1()
    Select Case Result     ' <-- variable 'Result' not declared, not reported in Code Inspection
        Case ABC
            ' Do Something
    End Select
End Sub
```
If Option Explicit is commented out, Code Inspection will report "Option Explicit is not specified" but remains silent on the variable "Result" not being declared.

**Comment by Hosch250** [comment]
As far as I know, we don't even have that inspection, do we?

**Comment by Vogel612** [comment]
that's [status-by-design] Rubberduck is intended to work off compilable code with Option Explicit enabled. If the code does not compile correctly, the Parse-Tree can be incorrect and Rubberduck Inspections may result in false positives and false negatives.

**Comment by Stevefb** [comment]
Fair enough, I wonder if it would be possible for RD to force a compile before parsing?

**Comment by retailcoder** [comment]
Technically yes, but it couldn't prevent a reparse if the VBE can't compile the code.

As for the code above, Rubberduck isn't saying anything about the undeclared variable, because Rubberduck works off *declarations* - if it's not declared, it doesn't exist! The logs should contain something about not being able to resolve `result` to anything; however variables aren't the only thing that fail resolving - that inspection was considered at one point, but dropped because it would simply be too many false positives... although it's probably much better now, with the 2.0 resolver.

**Comment by retailcoder** [comment]
This is now implemented, the new `UndeclaredVariableInspection` and `IntroduceLocalVariableQuickFix` classes will ship with next release - stay tuned! :smiley:
