### ISSUE TITLE
Find Symbol dropdown needs better logic

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1973]
The dropdown currently includes all available relevant declarations, and in large projects the performance hit is thoroughly crippling.

Let's limit the number of items to the top 100 matches, auto-complete style; that should keep things smooth.

**Comment by Vogel612** [comment]
I'm not sold on that this is easy to implement ([label:up-for-grabs]). Auto-Complete-Style would require maintaining a Trie of Declarations instead of the current Dictionary (are we still using a dictionary)?

That means touching the code in multiple different (and somewhat outspread) places, as well as either building a DIY Trie or finding some library (I think there's no standard Trie in C#, correct me if I'm wrong).

Aside from that :+1:
