### ISSUE TITLE
rubberduck>Refactor options are disabled.  With no indication as to why.

### ISSUE THREAD

**Issue by TZubiri** [rubberduck-vba/Rubberduck#2058]
Status stuck at Resolving references.
Ctrl Shift R prompts me to change the current module's name.

**Comment by Hosch250** [comment]
CTRL-Shift-R is the Rename command, and can be disabled in the settings.  What did you expect it to do?

**Comment by retailcoder** [comment]
If the parser isn't in a `Ready` state, refactorings (and some other functionalities) can't run, at least not reliably.

Ctrl+Shift+R, as @Hosch250 says, is mapped to the refactor/rename command by default - the fact that the hotkeys work while the command is otherwise disabled is a UI bug that we need to fix: hotkeys simply bypass commands' `CanExecute` and run it regardless, which can be quite a problem when parser state isn't `Ready`.

The non-ready parser state *is* the indication why refactor commands are disabled: "resolving identifier references" means Rubberduck is looking at the parse trees, and everywhere an identifier reference is encountered, it resolves it to a declaration - this is what makes refactor/rename work correctly, because it's the step that associates *identifier references* to *declarations*.

I would expect your logs (logging is enabled?) to contain valuable information about exactly what blew up in the resolver.

**Comment by TZubiri** [comment]
@Hosch250 I expected it to rename the variable I am highlighting or to ask me what variable I want to rename. Rather than rename the module.

@retailcoder where can I find the logs?

**Comment by retailcoder** [comment]
It's prompting for the module because it doesn't see the variable.

You can find the logs via the *settings* dialog; there's a button to open the log folder in Windows Explorer.

**Comment by TZubiri** [comment]
[rubberduck.txt](https://github.com/rubberduck-vba/Rubberduck/files/366250/rubberduck.txt)

**Comment by Hosch250** [comment]
Well, the initial part of this issue is status-by-design.  At the end of the log is a parser error, it shouldn't be saying "Resolving References" anymore.  I'll take a look.

**Comment by Vogel612** [comment]
@Hosch250 how did this one turn out?

**Comment by retailcoder** [comment]
IMO the real underlying issue is the bad exception handling in the resolver... which was significantly improved since then. Closing.
