### ISSUE TITLE
Frozen test explorer when declaring a variable of unknown class

### ISSUE THREAD

**Issue by lkavicky** [rubberduck-vba/Rubberduck#2065]
I have a test module declaring a variable of a missing class (looks like it has been lost in a crash during repository creation, but that's a different topic). When running the tests I get an error message (which I would anticipate), but the explorer hangs and is not reacting (similar to #2056 )

I'm able to reproduce the issue with following steps:
- create empty DB
- add test module, add test function
- add `Private x As NonExistentClass` at the beginning of the module
- run test function

**Comment by retailcoder** [comment]
The one assumption Rubberduck needs to make, is that the VBA can compile and run the code. Failing to resolve `NonExistingClass` to a known declaration will not trigger an error state, and so there is no way Rubberduck can know if your code compiles as it's being parsed. If it parses, it's assumed to compile.

Not sure there's anything we can do for this.

**Comment by retailcoder** [comment]
@Hosch250 can you confirm a parse error in a test module disables running unit tests?

**Comment by Hosch250** [comment]
These are the states I think we can reasonably allow.  At Parsed and ResolvingDeclarations, the unit test explorer doesn't know about the tests; at Parsing and Pending, it doesn't know if the parse will pass, and the error states shouldn't be allowed just as a matter of course (well, ResolveError is iffy--it can be either for ResolvingDeclarations or ResolvingReferences...).

    { ParserState.ResolvedDeclarations, ParserState.ResolvingReferences, ParserState.Ready }

**Comment by retailcoder** [comment]
@Hosch250 agreed. Still, we can't know if the code *compiles*, because we're not *actually* compiling it. So if the user has non-compilable code in a test procedure, the best we'll get is "cannot resolve 'NonExistingClass' in 'TestModule1'." in the logs.

If the resolver was *flawless*, then we could treat any non-resolvable identifier reference as an undeclared variable or type, and prevent running the tests when any test module contains such non-resolvable identifier reference. ...but we can't.

**Comment by Hosch250** [comment]
So, add ResolverError to the mix, and tell them "tuo periculo"?

**Comment by retailcoder** [comment]
Except, a non-resolvable identifier reference doesn't result in a `ResolverError` state. ...and shouldn't.

**Comment by Hosch250** [comment]
Oh, right.  Only exceptions in the resolver lead to that.

**Comment by retailcoder** [comment]
Basically, Rubberduck unit tests *run the test methods*. If the VBE can't compile and run them, Rubberduck will ask the VBE the run the test methods, and when the VBE fails to do so, Rubberduck needs a way to avoid freezing to death.

**Comment by lkavicky** [comment]
I'd be absolutely OK with stopping the VBA using the stop button as @Hosch250 suggested in #2056 but that button is not doing anything in my case.

**Comment by retailcoder** [comment]
The VBE wouldn't run code it can't compile, so there's nothing to stop that's why the stop/reset button didn't do anything. I really hope to find a solution to gracefully handle this, but the VBIDE API is rather limited... no sure it's even possible without writing a compiler ourselves (which is a bit beyond the scope of Rubberduck), so we can tell when the code can/cannot be executed.

Best solution - for now at least - would be to make sure the code compiles before you run any unit tests.

**Comment by lkavicky** [comment]
OK, now I understand. I will try to compile every time before running unit tests.
For the cases when I forget, it would be nice to be able to restart RD from the IDE (#1883).

In any case, I've created some issue descriptions recently, but I feel that I need to add that you are doing really great work with PD!
