### ISSUE TITLE
Button to maximize Source Control window

### ISSUE THREAD

**Issue by eteichm** [rubberduck-vba/Rubberduck#2108]
I suggest that the Source Control window gets a maximize button to make this window fullscreen (to the left of the top right X button).

**Comment by retailcoder** [comment]
Dockable toolwindows all behave identically - I believe you could double-click the title bar to maximize it... otherwise resize manually as you see fit; I'm not willing to turn the SC panel into a dialog though - it just feels too *exactly right* docked to the right like Visual Studio's *Team Explorer*.

**Comment by eteichm** [comment]
I can right-click on the title bar to view the context menu, BUT the Restore, Size, Minimize and Maximize menu items are inactive (grey). I can indeed dock it and resize it manually. This resized size is kept after closing and opening Excel. That's fine !
