### ISSUE TITLE
File extension ".cls" instead of ".doccls" 

### ISSUE THREAD

**Issue by eteichm** [rubberduck-vba/Rubberduck#2109]
To be consistent with the export done by Excel, I suggest to give the class modules ".cls" (or ".sheet.cls") as file extension instead of ".doccls" unless there is a valid reason for the latter. 

FYI: vbaDeveloper excludes .cls files from importing, because of silly excel bug. They need to be imported manually instead.
https://github.com/hilkoc/vbaDeveloper/commit/83f2163278e657be5afa2d41044802589e426f48

**Comment by comintern** [comment]
For future reference, the issue referred to with importing classes in vbaDeveloper is here:  https://github.com/hilkoc/vbaDeveloper/issues/1

I haven't noticed any issues with source control and class modules in RD, but I suspect after glancing through their source that the underlying issue in vbaDeveloper has more to do with importing a class module into a running project (the addin).

**Comment by retailcoder** [comment]
There *is* a valid reason. `Worksheet` and `Workbook`  modules are not class modules; their component type is `vbext_ct_Document`, whereas actual class modules are `vbext_ct_Class`.

When exported, document modules have everything in common with any other class module, save their `VB_PredeclaredId` and `VB_Exposed` attribute values:

	VERSION 1.0 CLASS
	BEGIN
	  MultiUse = -1  'True
	END
	Attribute VB_Name = "Sheet1"
	Attribute VB_GlobalNameSpace = False
	Attribute VB_Creatable = False
	Attribute VB_PredeclaredId = True
	Attribute VB_Exposed = True

The VBE isn't exporting some of the vital information about the module's base type, here a `Worksheet` class - that information is encoded in a GUID that referes to the registered `Worksheet` class, so the VBE knows that `Sheet1` is a `Worksheet` instance. But that information isn't exported, probably by design (I wouldn't call it a VBA/Excel bug).

You can't re-import an exported document module, because document modules are created by the host application, not by the VBE: to add a worksheet to a workbook you need to, well, *add a worksheet to the workbook* - this is host-dependent and entirely separate from the VBE, which isn't specifically tied to Excel (or any other host application) in any way.

If we exported them as `.cls` files, we would have no way of telling class modules from document modules: the `.doccls` extension is how Rubberduck knows to treat document modules as such.
