### ISSUE TITLE
Parser error on Excel specific VBA syntax

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2129]
This VBA assigns a Variant, 1-based 2D array, but _only_ in Excel.

``` vb
Dim array2D As Variant

array2D = [{1,2,3;4,5,6;7,8,9}]
```

**Comment by Hosch250** [comment]
No repro.  Rubberduck parses this just fine:

```
Sub foo()
    Dim array2D As Variant
    array2D = [{1,2,3;4,5,6;7,8,9}]
End Sub
```

**Comment by retailcoder** [comment]
Closing because no repro, but it should be noted that this trips a number of false positive inspection results:

 - Consider renaming variable '[{1,2,3;4,5,6;7,8,9}]'
 - Variable '[{1,2,3;4,5,6;7,8,9}]' is not declared
 - Variable '[{1,2,3;4,5,6;7,8,9}]' is never assigned

Rubberduck interprets the curly brackets as an identifier with a funky name.
