### ISSUE TITLE
False positives for Return value for member is never assigned

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2168]
*Function* and *Property Get* return values passed as ByRef arguments are treated as never assigned.

The return value for function `foo` is passed to both a function *and* a procedure as `ByRef` and is assigned in both cases, but Rubberduck reports:

> VBAProject.Module1 Return value for member 'foo' is never assigned

```vb
Option Explicit

Function foo() As Long
  Dim x As Boolean
  bar foo        'foo = 5
  x = fizz(foo)  'foo = 6
End Function

Sub bar(val As Long)
  val = 5
End Sub

Function fizz(val As Long) As Boolean
  val = 6
  fizz = True
End Function
```

And in a class module, the return value for Property `foo` is passed to a function *and* a procedure *and* a Property Get as `ByRef` and is assigned in all cases, but Rubberduck reports:

> VBAProject.Class1 Return value for member 'foo' is never assigned

```vb
Option Explicit

Property Get foo() As Long
  Dim x As Boolean
  bar foo        'foo = 5
  x = fizz(foo)  'foo = 6
  x = buzz(foo)  'foo = 7
End Property

Sub bar(val As Long)
  val = 5
End Sub

Function fizz(val As Long) As Boolean
  val = 6
  fizz = True
End Function

Property Get buzz(val As Long) As Boolean
  val = 7
  buzz = True
End Property
```

**Comment by retailcoder** [comment]
I'm not sure I want to support this edge case.

    Bar Foo

Makes it impossible to tell the `ByRef` assignment vs a recursive call to `Foo`, and IMO *should* trigger a warning of some sort. `Foo` is never found on the left side of an assignment within the body of `Foo`, and thus isn't a *false positive* but a legit inspection result.

It's a bit more readable in the latter snippet, but then again `foo` is never found left of an `=` token and the member name is used as a local variable, and that's terrible bad practice.

Until there's an inspection that finds RHS uses of the member identifier, I'm tempted to leave this one alone, and if the *variable not assigned* inspection *does* account for `ByRef` assignments, I'm even tempted to mark this one as *by design*.

**Comment by ThunderFrame** [comment]
Are you suggesting the use of `Call`?

```vb
Private Declare Function ArrPtr Lib "msvbvm60" Alias "VarPtr" (Ptr() As Any) As Long

Public Function Peek(ByVal lPtr As Long) As Long
    Call CopyMemory(Peek, ByVal lPtr, 4)
End Function

'--- test for unallocated array
If Peek(ArrPtr(baBuffer)) <> 0 Then
```

**Comment by retailcoder** [comment]
No, I'm suggesting to introduce a local variable instead of using the function's identifier as one.

**Comment by Vogel612** [comment]
@retailcoder soo .. is this a status-declined then?

**Comment by retailcoder** [comment]
@Vogel612 yeah.
