### ISSUE TITLE
Code Inspection: Invalid use of member

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2189]
When working with interfaces and base types, VBA can compile code that will fail at run-time.

Rubberduck should _try_ to identify such problems at inspection-time.

`UserForm1` has the following property

``` vb
Public Property Get FooBar() As String
  FooBar = "FooBar"
End Property
```

``` vb
Sub FizzBuzz()

    Dim bar As UserForm1
    Set bar = UserForm1
    Debug.Print bar.FooBar

    Dim foo As UserForm
    Set foo = UserForm1
    'This compiles but fails at run-time
    Debug.Print foo.FooBar

End Sub
```

**Comment by retailcoder** [comment]
Might be I'm blind, but I don't see the problem with the snippet there. Did you mean to make a `Property Let` accessor call? Please clarify what we're looking for here.

**Comment by retailcoder** [comment]
Oh duh

**Comment by retailcoder** [comment]
Nevermind

**Comment by comintern** [comment]
Now that we have the MemberNotOnInterfaceInspection (that doesn't pick this up), I'd classify this as a bug as opposed to a feature request.

**Comment by bclothier** [comment]
Personally, I'm a bit surprised that the sample syntax for UserForm would cause runtime errors. That is not the same behavior with the Access form.

   Dim MyForm As Access.Form
   Set MyForm = New Form_MyForm
   MyForm.FooBar = "foo" 

The `FooBar` member won't show on intellisense because variable is typed as a `Access.Form`, not `Form_MyForm` but it is still legal, as long the `FooBar` in fact exists.

We have similar situation with `ADODB.Command` where syntax such as `MyCommand.MyStoredProcedure 123` is legal but won't be found on the `ADODB.Command`'s interface. 

So I agree with @comintern that it should be picked up by the MemberNotOnInterface inspection, to warn the users to revise their declaration or to do explicit cast to the specific type. Note that explicit cast wouldn't even apply to the `ADODB.Command` case, however...

**Comment by ThunderFrame** [comment]
Also a bit like the Application.Sum function in Excel.

IIRC, COM marks the interface as `extensible` , and RD picks that attribute up, so we should already know that the member is potentially valid.
