### ISSUE TITLE
Sync local reporistory when project is closed

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/Rubberduck#219]
When the add-in is unloaded, sync the local repository with the state of the actual project.

To get `GitProvider.Status` to reflect the actual project, it has to push the files into the local repository before checking the status. This means unsaved changes may be left in the repository. These changes should be undone if they have not been saved.

Use the [VBComponent.Saved](https://msdn.microsoft.com/en-us/library/office/gg278894.aspx) property to determine what filepaths should be checked out on the `Extension.OnDisconnection` event.

Something along the lines of this.

    var dirty = VBComponents.Where(c => c.Saved == false)
    foreach (var component in dirty)
    {
        git.Undo(System.IO.Path.Combine(repository.LocalLocation, component.Name, component.FileExt());
    }

**Comment by Hosch250** [comment]
We need to handle this in two places.  One, when the project is removed to update it to whatever it had been.  Two, when the add-in is unloaded.  The first could be extremely tricky because holding a reference to the component while handling the sink events causes a lot of problems, but we need component names and code module content.  The other could also be extremely tricky because we may have a limited time to get out before we are kicked, and we need to handle disposal.
