### ISSUE TITLE
blank description in Code Inspection Settings

### ISSUE THREAD

**Issue by connerk** [rubberduck-vba/Rubberduck#2191]
Version 2.0.8.23905 (MSIL)

![image](https://cloud.githubusercontent.com/assets/1771679/17755762/d11ed9ea-6490-11e6-97d0-c53415b30fa5.png)

**Comment by retailcoder** [comment]
Yikes! Well that's embarrassing!

**Comment by Vogel612** [comment]
I have just checked this against next and This didn't show up for me. Additionally the Code Quality Issues Inspections include "Object variable assignment requires 'Set' keyword" on my end, which don't show up here. Then again the order seems kind of messed up, because the other items don't show in that order for me ...

**Comment by retailcoder** [comment]
The missing caption is "Public field breaks encapsulation", and the blank tooltip should be:

> **Public field breaks encapsulation**
> Consider exposing a property instead.

@Vogel612 indeed, the sorting order appears to be different - I believe there is no sorting defined, the order they show up is determined by the order the types are reflected from the compiled assembly by the .net runtime... which is another issue, pointed out in #2193.

This one seems fixed to be now though.
