### ISSUE TITLE
Add option to disable code inspections in Add-ins

### ISSUE THREAD

**Issue by eteichm** [rubberduck-vba/Rubberduck#2210]
I'm developping an Excel Add-in. I code in an xlsm file, then save and use it as a xlam file. 
I'd like to be able to disable code inspections in the add-in. Currently, I have to password protect the code of the add-in to inhibit code inspections in the add-in. 
Could RD have the option to disable code inspections in add-in files even if they're not password protected?
Other solutions welcome!

**Comment by retailcoder** [comment]
Is that because you're facing a ton of "procedure not used" inspection results for the procedures that are meant to be called by client code? If that's the case you can ignore a result in-place with an annotation (select the result and then "ignore once" from the "fix" menu) - doing that adds a comment atop the procedure, like this:

    '@Ignore ProcedureNotUsed
    Public Sub DoSomething()
        '...
    End Sub

Another way is to outright disable the inspection - you can do that from the inspection results toolwindow by selecting any inspection result and clicking the *disable this inspection* link in the bottom panel; this configures the inspection's severity level to `DoNotShow`, which effectively means the inspection won't run (it's not merely *hiding* results, it actually *skips* the inspection altogether).

You can also do that from the inspection settings - setting all inspections' severity level to `DoNotShow` will effectively disable RD inspections, and none will run.

The downside is that you then need to reconfigure each individual inspection to re-enable them.

I think a checkbox (checked by default) to simply "run inspections after a successful parse" or not would have the advantage of not changing the severity levels, while still allowing inspections to run when triggered manually from the inspection results toolwindow.

Thoughts?

**Comment by eteichm** [comment]
Yes, changing the severity levels is not the right way to go. 
A checkbox to simply "run inspections after a successful parse" or not would reduce unnecessary CPU load. 
For code that isn't currently called, I've adopted your proposed solution to add the line "'@Ignore ProcedureNotUsed".  This change generated an HRESULT E_FAIL ERROR. I'll report it in a new issue. 
To avoid the code inspections and reduce unnecessary CPU load, I'll also password protect my own add-ins.

**Comment by retailcoder** [comment]
The `DoNotShow` severity level is actually used as a filter to determine which inspections to run - with all of them set to `DoNotShow`, the inspector will actually iterate exactly zero times, and no inspection would run - which should significantly reduce the CPU load.

I'm worried about that error caused by the `@Ignore`  annotation, I gave you `ProcedureNotUsed` from memory (although a typo should definitely not result in everything blowing up), but *typing it in* manually isn't ideal - does it blow up if you use the code inspections' *ignore once* quick-fix?

**Comment by retailcoder** [comment]
So, next release introduces a new inspection setting:

![there's a new inspection setting in town!](https://cloud.githubusercontent.com/assets/5751684/18229475/b570c166-7248-11e6-93e7-1d33e51518b5.png)
