### ISSUE TITLE
RD executes while VBE is not opened yet

### ISSUE THREAD

**Issue by eteichm** [rubberduck-vba/Rubberduck#2231]
I observed that RD executes while I hadn't opened the VBE yet.  I got a message from RD while I was doing calculations in Excel. I don't remember the message. 
It would be better to only execute Rubberduck when opening the VBE, if possible.

**Comment by retailcoder** [comment]
RD only loads once the VBE attaches its add-ins. If you opened the VBE *once*, and then closed it, RD is still running.

**Comment by retailcoder** [comment]
This can be confirmed by attaching the VS debugger to an EXCEL.EXE process: symbols are only loaded when the VBE is commanded to open, and *only then* does `_Extension.OnConnection` run. The add-in only tears down (well, tries to) when the VBE calls `OnDisconnection` for its add-ins; my understanding is that this only happens when the host application is closing, or when the add-in is manually unloaded.

**Comment by retailcoder** [comment]
Did the calculations involve user-defined functions by any chance?

**Comment by eteichm** [comment]
No, the calculations did not involve user-defined functions. 
Well noted that if I don't want RD to run, I have to close and reopen Excel after opening the VBE.

**Comment by retailcoder** [comment]
Perhaps we could try to determine if the VBE mainwindow is visible... this might be as trivial as checking `VBE.MainWindow.Visible`...

**Comment by retailcoder** [comment]
Yup. Let's add a configuration setting to determine whether to parse anything in the background when the VBE is hidden.
