### ISSUE TITLE
uninstall new version RubberDuck reinstall old version fails

### ISSUE THREAD

**Issue by bajabaq** [rubberduck-vba/Rubberduck#2252]
After upgrading to 2.0.8 (and finding it hangs), I tried to uninstall 2.0.8 and reinstall 1.4.3
After restarting Excel, it cannot find object (1.4.3)

I believe this is because the uninstall does not remove the 2.0.8 registry entries and when it loads it is trying to load the 2.0.8 version (which it can't find) and is failing.

**Comment by retailcoder** [comment]
You uninstalled via the control panel's "add/remove programs", with all VBA hosts closed, and installed with all VBA hosts closed too?

CC: @Zak-Michael-Armstrong

**Comment by bajabaq** [comment]
I uninstalled via the uninstall in the startmenu Rubberduck folder.  Uninstall/reinstall with everything closed.

**Comment by retailcoder** [comment]
Looks like some registration issue. If you're getting a message saying that the Rubberduck add-in can't be loaded, it means the registry key where the VBE is looking for add-ins is present, but then *something* is missing and it's not finding the physical location.

Have you tried following the steps described in [**Troubleshooting: Rubberduck add-in could not be loaded**](https://github.com/rubberduck-vba/Rubberduck/wiki/Installing#troubleshooting-rubberduck-add-in-could-not-be-loaded)?

After doing that, search the registry for key "8D052AD8-BBD2-4C59-8DEC-F697CA1F8A66" (that's the GUID for Rubberduck's `Extension` class) - if you're on a 64-bit system you should find it under `HKEY_CLASSES_ROOT\Wow6432Node\CLSID\{8D052AD8-BBD2-4C59-8DEC-F697CA1F8A66}`. Under that there's an `InprocServer32` key, and under that there's a key for each registered version. If 2.x correctly uninstalled, there should only be a `1.4.3.2343` key there:

![regedit](https://cloud.githubusercontent.com/assets/5751684/18957875/b5375152-862e-11e6-8fb8-61b781af40ce.png)

If that key is present, the add-in *should* load properly. If there's a 2.x key in there, **do not delete it manually** - there are a couple dozen more 2.x keys in the registry, and you don't want to be hunting down these keys manually. The correct way to clean it up would be to re-install 2.0.8 so that the DLL physically exists, and then run `regasm.exe` to *un-register* (using the `/u` switch) the assembly's COM types from an administrative command prompt. The (un-)installer is *supposed* to be doing that automatically though.

**Comment by Vogel612** [comment]
Since this has been stalling for almost a month now, I'm closing it.

**Comment by retailcoder** [comment]
@DiogoRNeves thanks for reporting - would you happen to know what version failed to uninstall?

**Comment by DiogoRNeves** [comment]
thanks for the quick answer!

Yeah, version that failed to uninstall is 2.2.0

**Comment by bclothier** [comment]
There were large changes to the installer between 2.2 and 2.3, so that may be a factor. What you can do is install 2.2, then do uninstall of it. Then install 2.3 separately.

**Comment by DiogoRNeves** [comment]
Tried that, same thing happened. Didn't let me install it...

**Comment by bclothier** [comment]
Fascinating. In that case, my next step would be to wipe registry for all the CLSID & ProgID entries, then try to install the latest.

**Comment by DiogoRNeves** [comment]
So, basically just go through all the registries outputted by the registry search and delete them?

**Comment by retailcoder** [comment]
Are you getting any specific error message(s) when trying to install? Wiping the RD keys manually from the registry is quite a PITA... this should help:

https://github.com/rubberduck-vba/Rubberduck/blob/bbb335ba680ac2b765e9de5094dce4ab70d638d2/Rubberduck.Resources/Registration/RubberduckGuid.cs#L3-L56

**Comment by bclothier** [comment]
Yes, @DiogoRNeves  - if the subkey says `Rubberduck`, you can delete the entire `CLSID` or `TypeLib` node. Note that the code that @retailcoder  linked only covers current GUIDs - to be thorough, we need to cover old GUIDs no longer in use.  You can use Powershell script to help with locating all the registry keys or some registry tools that does a better job of going through the subtrees of the registry.

**Comment by DiogoRNeves** [comment]
IT does... a LOT! Thanks!

**Comment by DiogoRNeves** [comment]
So, deleted all the keys that the ps1 scrupt found and the keys above don't exist. Still the same error:
![image](https://user-images.githubusercontent.com/7635693/51127097-9b969a00-181c-11e9-8ffe-bfb5bac1fc3b.png)

Thoughts?

**Comment by bclothier** [comment]
Shoot, my bad. I need to clarify in my earlier comment that when I said to delete from `CLSID` and `TypeLib`, I should have also included the uninstaller key. 

You need to look inside the subtree:

`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall`

and

`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall`

Locate any key that contains `Rubberduck` somewhere. There should be a key named `UninstallString`. Check that the path is in fact missing. If it's missing, then delete the entire key under `Uninstall` folder --- it typically has a GUID as the name. Here's a sample -- username blanked out as that varies from computer to computer:
![image](https://user-images.githubusercontent.com/2367644/51127770-f5cb3700-17eb-11e9-94fe-0c161488cc28.png)

**Comment by DiogoRNeves** [comment]
That worked like a charm! Thank you! Everything is back up and running!

**Comment by retailcoder** [comment]
@DiogoRNeves awesome! Sorry for the troubles, ....this version *should* update without any issues when you're ready to update to a newer build.
