### ISSUE TITLE
Refactor rename "duplicates" variable name in replacement

### ISSUE THREAD

**Issue by byronwall** [rubberduck-vba/Rubberduck#2276]
I am running the rename to give some variables more descriptive names, but I am having trouble with RD "duplicating" part of the variable name.  It seems to be related to including the previous variable in the new variable name, but I am not sure of that.

This is the before case.  I am looking to rename `ser` to `chtSeries` and `obj` to `chtObj`.  The after case shows that `Series` is duplicated and that `Obj` is duplicated in the `For Each` line.  This leads to code that cannot compile.

```
Sub testSubBefore()

    Dim ser As Series
    For Each ser In ActiveChart.SeriesCollection
        
    Next
    
    Dim obj As ChartObject
    For Each obj In Selection
    
    Next

End Sub

Sub testSubAfter()

    Dim chtSeries As Series
    For Each chtSeriesSeries In ActiveChart.SeriesCollection
        
    Next
    
    Dim chtObj As ChartObject
    For Each chtObjObj In Selection
    
    Next

End Sub
```

These tests are done in a bare module in an empty workbook.  It also happens out in the wild where I am actually trying to do these renames.

**Comment by byronwall** [comment]
If I do an intermediate step where I first rename `ser` to `aaa` and then `aaa` to `chtSeries`, I still get the duplication with it reading `For Each chtSeriesSeries...`

**Comment by retailcoder** [comment]
I'm happy to FINALLY fix this one! This is what did it:

                        var lastSelection = Selection.Empty;
                        foreach (var reference in line.OrderByDescending(l => l.Selection.StartColumn))
                        {
                            if (reference.Selection == lastSelection)
                            {
                                continue;
                            }

And that's because the `For Each` loop adds an implicit "assignment" identifier reference to the declaration of the loop variable, so in `For Each foo` you get 2 identifier references: one for the explicit `foo` (a read) and another for the `For Each foo` (a write/assignment) - the refactoring was simply iterating all identifier references in order; the fix is simply to skip an identifier reference if its selection is in the same spot as the previous one!

**Comment by byronwall** [comment]
I'm sure you knew this, but this does indeed fix the problem.  I've tested the above case along with plenty of other ones.  Thanks for tackling this issue.
