### ISSUE TITLE
Access project causes Resolver Error

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2297]
This free project from EverythingAccess causes a Resolver Error on parse.

http://www.everythingaccess.com/tutorials.asp?ID=Accessing-detailed-file-information-provided-by-the-Operating-System

**Comment by ThunderFrame** [comment]
given the common author, this might be related to #2301

**Comment by Stevefb** [comment]
Hi All,

I'm also getting a Resolver Error but in MS Word (Word 2010 32 bit on 64 bit Win 10, RD Build 2.0.9.18871). Previous versions of RD were able to resolve but this version stalls; my project has not changed much since the previous versions.  

NOTES:
When I close Word (with IDE open, after refreshing RD) I am informed that the file Normal.dotm is in use and I'm prompted to save it.
- this happens irrespective of whether my project is open or if the only thing open is a blank doc
  
When I open Word (no existing document) it RD resolves, if I then open my project and refresh RD stalls.

Hope it helps

**Comment by Vogel612** [comment]
Can't repro this on my Access 2016 from the latest build. @ThunderFrame can you verify?

**Comment by Vogel612** [comment]
Hi @Stevefb 

If you experience problems with Rubberduck you'd be best off opening a separate issue instead of "hijacking" an urelated issue. This issue was specifically related to access. Resolver errors with Word are not really expected under that category.

Also the resolver has seen some work. You might find that your problem is no more present in the freshly released 2.0.11. You may what to check out the new release.

Regards

**Comment by ThunderFrame** [comment]
The resolver error no longer occurs in 2016, but parser won't start in Access XP/2002.
