### ISSUE TITLE
New modules are not send to the git

### ISSUE THREAD

**Issue by Octopus134** [rubberduck-vba/Rubberduck#2300]
I imported some modules from a different database. Clicking on commit & push they are not copied to the repository. I had to close and open the database again. Then they could be sent.

(Access2013-32, Win8.1-64, rubberduck 2.0.8.30557):

**Comment by retailcoder** [comment]
Normally the COM event sinks would pick up a VBComponent being added/removed from the project and automatically refresh the SC panel and put the new module as a new "untracked" file (IIRC) - COM sinks are disabled for now though, so that would need a bit of manual refreshing; the SC panel's *refresh* button performs an export of all modules in the active project and updates the diff status of each one.

Have you tried refreshing the SC panel manually?

**Comment by retailcoder** [comment]
Hmm wait 2.0.8 *does* have the sinks enabled.

**Comment by rubberduck203** [comment]
Please see #3758.
