### ISSUE TITLE
Parser Error

### ISSUE THREAD

**Issue by McWilliamsPete** [rubberduck-vba/Rubberduck#2305]
Statement:
   xxx = String(6. " ")
hangs the parser (see screen shot).

![rd_bad_refresh](https://cloud.githubusercontent.com/assets/22778803/19287670/06ab2fbc-9003-11e6-8319-0ef7284aa9d6.png)

I'd send you the xlsm-file, but it cannot be attached here. Could I mail it to you?
Thanks,
Pete

**Comment by retailcoder** [comment]
Hi Pete,

Wow that "about" box was definitely not designed to look like that! Good thing we've redone it in WPF/XAML in 2.x! (now I'm quite curious to see how the 2.x about box looks on your system!)

The 1.4.3 parser had a number of annoying bugs, most of which are fixed in the 2.x releases - unfortunately 2.x is still rather unstable and can crash at startup (and/or on exit), but if you don't mind crashing on exit you could try 2.0.9 and see if it works for you until a stable 2.0 is released.

One of the things that tripped the 1.4.3 parser, was nested function calls IIRC. Try replacing `Chr(0)` with the `vbNullChar` constant. Also, I *think* the instructions separators *might* be tripping it as well; see if it parses when you put separate instructions on separate lines.

I'd understand if you don't want to install a 2.x preview/pre-release build; feel free to email me your attachment at rubberduckvba (at) gmail (dot com), I'll let you know how 2.x handles it.

**Comment by Vogel612** [comment]
Inactive as well as pertaining to version 1.4, also fixed in the current build. Closing this.
