### ISSUE TITLE
Feature Request: "locate in code explorer"

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2344]
This would sync the CE to the current procedure in the Code Pane.

I know that the RD toolbar shows me the ModuleName.ProcedureName, but sometimes it's handy to be able to visualize it in the CE, as well.

I _can_ go manually find my way to it, but computers are supposed to do the drudgery for us, right?

**Comment by retailcoder** [comment]
Definitely a good feature to have - especially in larger projects, and especially with the modules being depicted in a folder hierarchy. I'm 100% behind this one.

**Comment by daFreeMan** [comment]
In the meantime, would it be easy (easier) to update the RD toolbar to show 

**Folder.Hierarchy: ModuleName.ProcedureName** 

I looked at the tool bar to try to identify where I was, then realized that I didn't know where the specified module was to be found. (Existing project, partially moved to a folder hierarchy)

**Comment by retailcoder** [comment]
Thing is, the toolbar doesn't have much room for it. We need an actual freakin' status bar!

**Comment by daFreeMan** [comment]
To make the code more efficient than attempting to hook ever cursor key movement to keep the CE constantly in sync, enable the currently disabled toolbar button that displays the current **ModuleName.ProcedureName** so that clicking it syncs the CE to the Code Pane.
![rd click here](https://cloud.githubusercontent.com/assets/11889733/21779639/82d3772a-d676-11e6-890d-9cbaddeffc3e.PNG)
_Do not mock my Logitech Trackman writing - I did that with my thumb!_

**Comment by retailcoder** [comment]
That's a great idea - the irony being, it's hooks that track every cursor key movement that keep that "context status bar" in sync ;-)

**Comment by ThunderFrame** [comment]
like this?

![sync](https://cloud.githubusercontent.com/assets/16574009/21783420/576fbf54-d70b-11e6-9c28-ee6fee583afc.png)

**Comment by daFreeMan** [comment]
@ThunderFrame Yes, exactly like that!

@retailcoder I get your points. 
  A) sync may not be the best word for it, Locate is fine by me
  B) If you add the button to the RD tool bar, I'm 100% OK with it. If it's buried under a menu or two or three, even if it's on the right-click, that's way too many clicks to get there. If there's a hot-key for it, that certainly minimizes the pain. (Is Ctrl-L used for anything?)

**Comment by retailcoder** [comment]
I'd use Ctrl+Shift+L to mimick R# hotkeys, but hotkeys can easily be configured in the settings window. But yeah, there's definitely going to be a hotkey for it.

**Comment by ThunderFrame** [comment]
I meant Sync as in make Code Explorer context the *same* as the CodePane/Designer context.

From a UX persepctive, maybe take a cue from VS and put the Sync button in Code Explorer?

As per VS:

![sync2](https://cloud.githubusercontent.com/assets/16574009/21783817/f9a03e74-d70c-11e6-8a06-21af6cb286d5.png)

**Comment by retailcoder** [comment]
Huh, I've never noticed/used that!

**Comment by PeterMTaylor** [comment]
Someone got to learn something somewhere...

**Comment by retailcoder** [comment]
The thing with the *Solution Explorer* is that it navigates with a single click (on selection), so it's actually pretty hard (AFAICT, downright impossible) to select a node in the treeview and then *not* have the corresponding code in the editor, so that "sync" feature essentially boils down to "select the node for the active document".

Fun fact: selecting a member node in the treeview navigates to that member, but selecting a member and then "syncing" doesn't. R#'s *locate in solution explorer* doesn't go to member level either. Perhaps Rubberduck's could?

So, I think the feature is taking shape:

 - `SyncCodeExplorerCommand` would be the command
 - `SyncCodeExplorerCommandMenuItem` would be under the `NavigateParentMenu`
 - I'd personally like to have Alt+Shift+L for its hotkey
 - The *Code Explorer* toolstrip can have a button that runs that command
 - The command needs to be **disabled** when:
  - There is no active codepane
  - The Code Explorer doesn't have a node for the active module

If we have a node for the *module*, but not for the *member* that's selected, then we activate the module node. If we do have a node for the member, then we activate that node.

**Comment by retailcoder** [comment]
Makes me wonder... the Code Explorer *should* be able to have at least module-level nodes for everything in the project *without having to wait for even the initial parse*.

**Comment by rkapka** [comment]
Does it make sense to include a menu item for this command? Running it will have to open the Code Explorer after syncing, otherwise the user won't see any effect. When the CE is open, it makes more sense to fire the command using its button. So essentially the menu item makes sense only when the CE is not open.

Furthermore, when someone discovers the menu item first, they may not look for an alternative in the CE, which is the preferred way of syncing, I think.

**Comment by retailcoder** [comment]
@rkapka agreed, the command needs to bring up the CE if it's not shown. IMO a menu item absolutely makes sense (that's how I discovered the corresponding command in R# :smile: ) - having a hotkey for it wouldn't hurt either (Alt+Shift+L? ...whatever)

**Comment by rkapka** [comment]
Yup, there should be a command. I changed my mind 😁

**Comment by jhiston** [comment]
Can add a UX thought?  The active code pane being 'out-of-sync' with the Code explorer seems to be an issue for me mostly when using VBE's built in "Definition" right-click menu or when debugging - e.g. a break point or unhandled error is hit.  VBA stops at the offending line, but the Code Explorer may still be reflecting the previous state (whatever was in active code pane before the break).  

The #1 place my eyes go to when the break happens to figure out where the heck in the code I know am is...…. the code explorer.  Has been source of much confusion over the years.....

So all that to get to the thought..... once the functionality is in place, it would be pretty nice addition if the 'syncing' code could be automatically triggered by the debugger dumping you into a new active code pane so that the code explorer is also helping to identify where in the code one just found oneself (the whole 'orientation' problem)
