### ISSUE TITLE
Function aliases are resolved as Variant Variables

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2349]
And because they're variables, they don't trigger any UntypedFunctionUsageInspection

Looks like `AddAliasDeclarations` isn't running?

```
Dim foo As String
foo = [_B_var_CurDir] '_B_var_CurDir = Function (Variant)

Dim bar As String
bar = CurDir          'CurDir = Variable (Variant)

```

**Comment by retailcoder** [comment]
It does run.

![image](https://cloud.githubusercontent.com/assets/5751684/20164653/266ce736-a6d4-11e6-8ac8-439401dcec04.png)

`DeclarationFinder.MatchName` finds two matches for it, but none match the given predicate. Investigation is under way.

**Comment by comintern** [comment]
Linking  #2464. This is actually caused by hard-coding the path when the `QualifiedModuleName` is created in the `AliasDeclarations`.  The project name and project path are being hashed to create the ProjectId.  The problem (partially) is that when the aliased declarations are resolved, they have to match this predicate...

`interprojectMatch => interprojectMatch.ProjectId == projectReference.ReferencedProjectId`

If the paths are different _at all_ the built-in declarations fail.

**Comment by retailcoder** [comment]
confirmed as fixed.
