### ISSUE TITLE
Parser error "extraneous input '(' expecting {'%', etc.}"

### ISSUE THREAD

**Issue by NotableAudio** [rubberduck-vba/Rubberduck#2360]
For some reason I am getting an "extraneous input '(' expecting{'%', etc.}" parser error on lines that run fine:

`lngNumberAcross = DLookup("[lngNbrAcross]", "tblOrder", "[idsOrderID] = " & lngJobID)`

and the same error on:

`strJobNumber = DLookup("[chrJobNumber]", "tblOrder", "[idsOrderID] = " & lngJobID)`

I have quite a few other DLookups in my code that aren't causing these errors but otherwise match these samples in syntax. 

I'm not very seasoned in VBA, so I apologize if this is obvious. 

I'd like to refactor these modules but it's presumably blocked by the parser error. Anyone have some guidance about getting this error cleared so I can see them in the code explorer?

**Comment by retailcoder** [comment]
Hi @NotableAudio, thanks for the feedback. Which version are you using? I can't reproduce the issue with the current build.

**Comment by NotableAudio** [comment]
@retailcoder I am running Build 1.4.3.2343

Windows 7 Pro 64-bit and Office 2010 suite.

**Comment by retailcoder** [comment]
Not sure exactly what the problem is, but build 1.4.x is not maintained anymore; we're in the final stages of stabilizing the 2.x build, you can get the latest 2.0.9 pre-release download [**here**](https://github.com/rubberduck-vba/Rubberduck/releases) (please uninstall 1.4.3 first!); I've experienced pretty consistent crashes on exit ("Microsoft Excel has stopped working..."), and *sometimes* random crashes for no *apparent* reason, but still I encourage you to take a look, it's definitely headed in the right direction :smile: 

The parser and resolver have been completely rewritten between 1.4 and 2.0; as of 2.0.9 there is only a very, very limited number of things (off the top of my head, there's only one) that will break the parser (or resolver), whereas the number of known grammar bugs and parser+resolver issues in 1.4.x was quite large.

Feedback on 2.0.x is also welcome, and will likely be integrated into the next "stable" release.

Cheers!

**Comment by NotableAudio** [comment]
@retailcoder I had trouble getting 2.0 to install the first time, which is why I'm on an older build. I'll give it another shot though since I had similar issues with 1.4.x but was likely a PEBCAK. :smile:  Thanks for the help and the awesome add-in!

**Comment by retailcoder** [comment]
@NotableAudio thanks! feel free to star our repository anytime (or save it for celebration day when a 2.x install works)! Please let me know if you run into any trouble installing 2.0.9 and/or getting it to work properly (note - the initial parse must be manually triggered from the "Rubberduck" toolbar's "Refresh" button, which should be docked top-left on the main commandbar in the IDE): at this point in the development of 2.0 we're taking every issue very seriously (I have a plan to fix the crash-on-exit).
