### ISSUE TITLE
Do I need to run code inspections before being able to refactor?

### ISSUE THREAD

**Issue by halcwb** [rubberduck-vba/Rubberduck#2438]
When I normally open up my vba project and I want to refactor, nothing happens. But when I first run code inspection, I can use the refactor methods. I didn't get this from the documentation. Is this behavior intentional?

**Comment by comintern** [comment]
The parser has to run first (and the inspection triggers a parse).  You can trigger the initial parse by hitting the refresh button on the status bar as well.

**Comment by halcwb** [comment]
Ok, thanks.

**Comment by retailcoder** [comment]
Rubberduck doesn't know anything about declarations and their references, until it parses the source code; that's why refactorings are disabled at startup.

Not sure if that was the case in build 2.0.9, but the "refresh" button on the RD commandbar, the "refresh" button on the *Code Explorer*, and the "refresh" button on the *Inspection Results* toolwindows all do the exact same thing: they all trigger a reparse.

Triggering a reparse makes a number of things happen:

 - Referenced type libraries are examinated; libraries unknown to the parser are loaded and their types are iterated - a `Declaration` object is created for each library, module, constant, member, parameter, event, etc. The status bar says "Loading references" at that point.
 - All modules are exported to temporary files; module and member attributes and their values are picked up and stored for the next pass. The temp files are promptly destroyed.
 - The preprocessor pass replaces (in-memory) line numbers and "dead code" in preprocessor branches that aren't "live", with whitespace - this keeps the correct in-CodePane token positioning, while removing duplicate definitions and things we can't parse.
 - The parser processes each module, and generates a *parse tree*. Once we have a parse tree for every module, the status bar says "Parsed".
 - The resolver makes a first pass walking each parse tree, to discover all *declarations*; a `Declaration` object is created for every project, module, member, constant, parameter, event, line label, etc. The status bar says "Resolving declarations" at that point.
 - The resolver makes a second pass walking each parse tree, to identify all identifier usages and resolve them to a known declaration. The status bar says "Resolving references" at that point. There's a number of sub-steps to this, including the *type annotation pass*, where each `Declaration`'s parent and "as type" is resolved to a `Declaration` object whenever possible. When that step completes, we know everything we need to know and the status bar says "Ready".

Once the parser state reaches "ready"*, a number of components get notified, and act accordingly:

 - The code explorer can draw the components
 - The todo explorer knows what to display
 - The menus and commands can determine whether to enable or disable themselves
 - The code inspections can run

<sub>*IIRC the code and todo explorers actually respond to the "parsed" state</sub>

When inspections start to run, the status bar says so; when they complete, it's back to "Ready" and then the inspection results toolwindow populates itself.

All of this happens asynchronously, so you can navigate the code and use the IDE while RD is working.
