### ISSUE TITLE
Rename takes a long time due to complete code base reparse?

### ISSUE THREAD

**Issue by halcwb** [rubberduck-vba/Rubberduck#2456]
Whenever I rename something, it seems like Rubberduck re-parses the complete code tree. Therefore, you have to wait a while before being to rename something else. Does Rubberduck look at the whole code tree or can it differentiate between local changes and only parse that part (knowing the state of the rest)?

**Comment by retailcoder** [comment]
Rubberduck caches the ANTLR `IParseTree` objects, and reuses them whenever a module's `ContentHash` is the same as it was the last time that module was parsed.

Renaming a public member will (well, *should*) affect/modify every calling module, so every modified module will (*should*) be re-parsed.

The reason for this is because we need a refresh on the token positions, which are in the ANTLR parse tree tokens: that's basically how we know that `DoSomething` in `Sub DoSomething` begins on line 42, column 5, and goes up to line 42, column 15. When that procedure is renamed `Sub SomethingElse`, its argument list is shifted 3 characters to the right, and every instruction calling it as well. If we don't re-parse, we can't know that.

The resolver has another problem: when it annotates declarations with `IdentifierReference` instances, it first needs to clear all these lists, and re-walk every parse tree to figure out what's being used where, because again, `IdentifierReference` positioning relies on ANTLR `IParseTree` token positions. A lot of details about how this works were published last year on RD News, see [What do *parsing* and *resolving* mean anyway?](https://rubberduckvba.wordpress.com/2016/02/06/what-do-parsing-and-resolving-mean-anyway/) - there's a section titled "Why re-resolve *everything* every time?" (note, the keyhook-driven live-parse was temporarily dropped). That said I'll happily take a PR that finds a clever way to only update the `IdentifierReference` instances that need to be updated, and leaves the other ones alone...

The parser/resolver in v1.4.3 is slow as hell no matter what though; the 2.x parser uses a completely new ANTLR grammar file, written to literally mirror the VBA specs and leverage ANTLR's "fast mode" whenever possible. We will soon upgrade to ANTLR 4.6 too, which means left-recursive grammar rules (hint: they're all over the VBA grammar) will benefit from tremendous performance increase.

**Comment by retailcoder** [comment]
IIRC the 1.4.3 resolver basically had *O(n<sup>2</sup>)* identifier lookup time, whereas the v2.0 resolver leverages *O(1)* constant-time identifier lookups.

**Comment by halcwb** [comment]
Thanks for the elaborate answer. I am by no means an expert on this topic, the only idea that pops up immediately is that as you have a parse tree and you can monitor changes, couldn't you recalculate the parse tree, instead of going through the source code? Your reference to your blog was interesting reading, thanks.

**Comment by retailcoder** [comment]
I *wish* we could! Roslyn (the C# compiler) seems to be doing something like it - not sure *how* they do it efficiently with immutable red/green AST nodes; one problem is the Abstract Syntax Tree itself: when I wrote the `Declaration` class I knew very little about parsing.. pre-1.2, Rubberduck was working off a (inherently doomed) regex-based parser, that `Declaration` type essentially *is* the closest Rubberduck has to an AST, and it's not enough.. we basically work with prase trees, not syntax trees. The idea is to get ourselves an actual AST after 2.0 is "green-released". Not sure we'll be able to pull Roslyn's magic tricks though.
