### ISSUE TITLE
NRE on RD startup - SetMinimumLogLevel

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2471]
New Year Bug?

![startup](https://cloud.githubusercontent.com/assets/16574009/21580078/4ac22228-d02c-11e6-8cfb-757aa8564eae.png)

Add-in appears to load after the warning.

**Comment by comintern** [comment]
Does anything write to the log when this happens?  The stack trace in the dialog points to a single line of code:

`LogLevelHelper.SetMinimumLogLevel(LogLevel.FromOrdinal(_config.UserSettings.GeneralSettings.MinimumLogLevel));`

I'd be surprised if the settings objects being passed were null at this point, because the logging level is pretty much the last thing that they get used for - I'd expect an NRE much sooner in `App.Startup()` if they weren't being set.

**Comment by ThunderFrame** [comment]
Will have a look tonight. I'm refactoring the Window Settings to use an ObservableCollection of WindowSetting, so that we can persist multiple properties per window. I've worked out how to toggle the dockable property for a ToolWindow, so we can set the Dockability on startup.

I also managed to send a double click to the ToolWindow title-bar, so I'll add members for dock/float.

I *think* I can add messages for sending a drag operation to a ToolWindow. If that works, we should be able to pwn the docking, and dock windows at will.

**Comment by MDoerner** [comment]
@comintern As far as I can see, `UpdateLoggingLevel` is the only place in `App.Startup` where the private instance `_config` of type `Configuration` is used.

**Comment by comintern** [comment]
@MDoerner - It's used to load the culture settings in `LoadConfig()` and it also gets used in `CheckForLegacyIndenterSettings()`, although they're both wrapped in a try-catch.  The call that *should* be failing before-hand is `_hooks.HookHotkeys();` (if the `IGeneralConfigService` is failing). IIR it was bound as a singleton.

**Comment by retailcoder** [comment]
@comintern that one was fixed in a recent PR, right?

**Comment by comintern** [comment]
@retailcoder - Believe so, but I forgot to try and replicate it before fixing it.  :blush:
