### ISSUE TITLE
Interacting with ToolWindows disables their dockability for the remainder of the VBE session

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2472]
Interacting with certain parts of a ToolWindow disables the context-sensitive `Dockable` CommandBarControl. Typically, interacting with column headers is OK, but interacting with empty panels is not. The behavior is different depending upon whether a parse has occurred (possibly because the ToolWindows have different content/structure at that point.

![dock](https://cloud.githubusercontent.com/assets/16574009/21580150/44deecbc-d034-11e6-9e08-6be926d333ba.gif)

I wonder whether this has to do with the WinEventProc code in `Window.cs`. Are we perhaps getting the hWnd of one of the WPF host windows rather than the ToolWindow hWnd? Could it be that the window can't be destroyed too? Maybe this is related to our inability to destroy ToolWindows get a clean exit?

To see whether a ToolWindow is Dockable, you need to add a *copy* of the `Dockable` button to the CommandBars. The easiest way to do that is by Customizing the CommandBars....

![dockable](https://cloud.githubusercontent.com/assets/16574009/21580137/c41f6e9a-d032-11e6-9813-0a1c09cbaf11.gif)

**Comment by comintern** [comment]
Huh.  FWIW, the WinEvents stuff isn't really hooked up to anything yet - the hooks that are dropped by `SetWinEventHook` are passive and translate the unmanaged event into a managed one. The `FindWindowEx` calls are also based on class name then caption name. I suspect that this may be due to the WPF container getting focus.  It looks more like there's an issue in the parent-child relationships in the dockable host.

**Comment by retailcoder** [comment]
Huh... yet the toolwindow docks. You're onto something I think.

**Comment by Vogel612** [comment]
Has any work been done on this? What's the status here?

**Comment by retailcoder** [comment]
Presumably fixed.
