### ISSUE TITLE
Categorize Tests

### ISSUE THREAD

**Issue by Vogel612** [rubberduck-vba/Rubberduck#2499]
Currently a significant number of tests is "uncategorized". This means we don't have a reasonable way of checking which tests are testing "impactfully". Additionally the RubberduckTests project is getting humungous. 

It might be useful to extract tests for specific suprojects into their own testprojects and / or categorize them to provide a clean way of evaluating test runs. Also it helps to not have to run each and every unit-test when developing somewhere, beacause the 1.6k tests are taking quite some time by now. 

Ref #218 too. As of now about 1k tests are not marked with any category. It's also possible to mark tests with multiple categories to allow for something akin to TestSuites

**Comment by MDoerner** [comment]
It would be nice if someone could provide a guideline on how to categorize the tests.
Should the tests only be categorized by what functionality they belong to or should there also be a categorization on what kind of tests they are? With the latter I mean whether they are actual unit tests or rather scenario tests or even integration tests. 

The further categorization came to my mind because I realized that most tests for the inspections are rather slow since they are using the entire parsing and resolving mechanics to produce the declarations and references. Thus, they are rather scenario tests than fast running unit tests that provide the declarations and references directly without parsing. With a categorization by type one could frequently run the actual unit tests, which should take less than one second in total, and less often the longer running scenario tests.
