### ISSUE TITLE
Annotation for Reference dependencies

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2521]
By default, the VBE project keeps all details of early-bound References, and currently, Rubberduck isn't saving that detail to source-control.

Importing a module from another project, or from another repo, might require additional/different references in order for the module(s) to compile.

Rubberduck *could* add/support an annotation that identifies Reference annotations, and then offer to add those References on importing or parsing a project/module for the first time, or adding Reference annotations upon exporting a module. It could also act as a means of identifying References that *are* currently Referenced, but that no longer need to be, because there aren't any Referenced types.

In addition to the GUID of the project, there'd probably need to be an indication of the position of that reference in the References order.
Eg - Requiring a Reference to the Microsoft Scripting Runtime:

```vb
`@References {420B2830-E718-11CF-893D-00A0C9054228} 'Microsoft Scripting Runtime
Option Explicit

```

**Comment by Vogel612** [comment]
I'd say this is kind of breaking the scope of Rubberduck in it's current form. What you're proposing here is a whole Dependency Management system. Things like these are (like source control) subject to huge debates. I'd prefer Rubberduck to possibly expose an interface for external add-ins (or possibly Rubberduck Plugins) to provide this functionality with the help of an external program. (Think nuget, gradle, npm, pip,cabal,  ...) instead of forcing users into one specific way of doing this

**Comment by retailcoder** [comment]
@Vogel612 it *would* allow RD to validate (and restore) project references when synchronizing a project with a remote repository. IMO this would be better off saved in a meta-project file (that has been discussed before, IIRC there's more than just project references we'd want to store in such a "project file") - again that's one thing VBA sucks at, that VB6 makes much simpler (because of the .vbp project file)... although it does it with its own load of new problems.

**Comment by Vogel612** [comment]
That metaproject file seems like a really good place to spin off a separate add-in that does only that ... I'm worried about scope / feature-creep and Rubberduck becoming a huge behemoth too slow to reasonably use ..

**Comment by retailcoder** [comment]
@Vogel612 that would be... taking source control entirely out of the RD standard install?

**Comment by ThunderFrame** [comment]
I know, I felt uneasy adding this. For an entire project, I think a project file would be preferable.

I was thinking more of the specific case of sharing a class module, like @retailcoder's [StringType.cls](https://github.com/retailcoder/VBTools/blob/master/StringType.cls).

You want any user of that module to know that they require:
1. A reference to `Microsoft VBScript Regular Expressions 5.5`
2. A class called `EscapeSequence`

If the annotation existed on *import*, Rubberduck could add/resolve dependencies, and once those dependencies were resolved, the annotation could be removed.

Likewise, the annotation could optionally be added on export, in situations where you intend to provide the exported modules to another host/project, or to another user, *without* needing to provide comprehensive instructions for adding a reference, or having umpteen follow up comments at the foot of an SO question.

**Comment by PeterMTaylor** [comment]
My thoughts on this design consideration is supporting vs mandating a third type of file as .vbp as @retailcoder suggested perhaps called .rdp for rubberduck project is a good step to resolve cross project dependency especially across hosts like excel and access which contains @ThunderFrame's concenrs.
