### ISSUE TITLE
Several (Related?) Issues with Tests

### ISSUE THREAD

**Issue by carlossierra311** [rubberduck-vba/Rubberduck#2563]
I don't really know if this is an error or not, but it seems odd that after the initial parse: 

1. I can't refresh my unit tests in test explorer. 

2. When I double click on any of my tests in the test explorer, the code that gets selected includes part of the next method (the tag and method signature), and excludes the tag of the clicked on method. 
![wrongtextsselected](https://cloud.githubusercontent.com/assets/23511373/22167049/1c11b6ae-df32-11e6-9f3a-e6347bdb23f2.png)

3. I get lots of warnings of the type _Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;Default Context: Failed to resolve Assert..._ in the log (that's probably normal), and one exception at the end of the test battery execution. 
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/720598/RubberduckLog.txt)

4. Three of my tests are failing now, but when I ran them using 1.4.3.0, they run fine and pass. 
![allpassing](https://cloud.githubusercontent.com/assets/23511373/22167074/3561934a-df32-11e6-88a4-d8f0806351f4.png)
![3failingafter](https://cloud.githubusercontent.com/assets/23511373/22167081/395ca5ac-df32-11e6-9283-17b4aa4a2d24.png)

5. I can't seem to find a way to run a single test. 

All this is happening in the pre-pre-release of 2.0.12.0 that you kindly generated for me to try and solve #2557. 

Thanks

**Comment by retailcoder** [comment]
(1) is definitely a problem. the refresh command should be the same on all toolwindows, except the source control, which has its own dedicated implementation.

(2) could be a symptom of (1); the token positions are de-synchronized and lines shifted module content since the last parse.

(3) resolver warnings are normal, assuming you're late-binding Rubberduck.tlb; the exception at the end isn't normal though, that's clearly a bug in `ParameterCanBeByValInspection`:

````
2017-01-20 16:58:25.2583;ERROR-2.0.12.39482;Rubberduck.Inspections.Concrete.Rubberduck.Inspections.Inspector+<FindIssuesAsync>d__18;Rubberduck.Root.InterceptedException: Object reference not set to an instance of an object. ---> Rubberduck.Root.InterceptedException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Common.DeclarationExtensions.FindBuiltInEventHandlers(IEnumerable`1 declarations) in c:\Dev\Rubberduck\RetailCoder.VBE\Common\DeclarationExtensions.cs:line 297
   at Rubberduck.Inspections.ParameterCanBeByValInspection.GetInspectionResults() in c:\Dev\Rubberduck\RetailCoder.VBE\Inspections\ParameterCanBeByValInspection.cs:line 36
   at (Object , Object[] )
   at Ninject.Extensions.Interception.Injection.Dynamic.DynamicMethodInjector.Invoke(Object target, Object[] arguments)
   at Ninject.Extensions.Interception.Invocation.Invocation.CallTargetMethod()
   at Ninject.Extensions.Interception.Invocation.InvocationBase.Proceed()
   at Rubberduck.Root.InterceptorBase.Intercept(IInvocation invocation) in c:\Dev\Rubberduck\RetailCoder.VBE\Root\InterceptorBase.cs:line 14
````

(4) is troubling, needs further investigation.

(5) oh wow - we definitely need a "run selected tests" command!

**Comment by comintern** [comment]
The exception at the end of the log is referring to the line of code [`var host = user != null ? user.Project.VBE.HostApplication() : null ;`](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/Common/DeclarationExtensions.cs#L297), although I'm guessing the root cause is further up in the log file beginning with this warning:

```
2017-01-20 16:58:06.9895;WARN-2.0.12.39482;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;Default Context: Failed to resolve Assert.AreEqual expected:=CDbl(-2), _
                    actual:=CDbl(chainBP), _
                    message:="Buffer's projected chain BP: " + CStr(chainBP). Binding as much as we can.;
```

That points to the same issue as the top screenshot - the "identifiers" that it's trying to resolve are being pulled from the wrong locations in the code module.  The selection that the context is pulling text from (or the context being used for the selection) is wrong.

Is the `ReplenishmentOptimizer` a file that you can upload?

**Comment by carlossierra311** [comment]
@comintern it is a very sensitive file, but I could send it to you through email, provided that you guarantee that no copies of it will be held after the problem is inspected.

**Comment by comintern** [comment]
In that case hold off - I'll see if I can reproduce it from the code in the screenshot.

**Comment by retailcoder** [comment]
@comintern if RD is late-bound, the resolver can't resolve `Assert.AreEqual` calls like that. The message includes the entire "problematic" context, which includes the arguments of the method call.

**Comment by carlossierra311** [comment]
Ok. Let me know if I can be of any help...

**Comment by comintern** [comment]
The binding failures that were logged for `coll` might be of interest.  There was a parser change after the release of 2.0.11 that may have effected how these were treated.  If the code for the `Sub` or `Function` that tripped these warnings isn't too sensitive, it may be of use:

```
Failed to resolve coll(i) > coll(j). Binding as much as we can.;
Failed to resolve coll(j). Binding as much as we can.;
```

**Comment by carlossierra311** [comment]
Sure. Here it goes:

	Public Function SortCollection(ByRef coll As Collection) As Collection
		Dim i As Long
		Dim j As Long
		Dim vTemp As Variant

		For i = 1 To coll.Count - 1
			For j = i + 1 To coll.Count
				If coll(i) > coll(j) Then
					' Store value of greater
					vTemp = coll(j)
					' Remove greater
					coll.Remove (j)
					coll.Add vTemp, Before:=i
				End If
			Next j
		Next i

		Set SortCollection = coll
	End Function

**Comment by carlossierra311** [comment]
Guys, if you want me to test the fix, I'll be happy to.

**Comment by Vogel612** [comment]
This has been quiet for a year (and a green release). I assume this is fixed. If that is incorrect, please do open up a new issue, since this one is at least partly verified to be fixed
