### ISSUE TITLE
 Consider renaming .. questions

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#2616]
Consider renaming class 'CCSACCI1' 
I can understand that for Label1 etc but for Sheet1 it's unimportant (maybe suppress if there is no Sheet1 code) and for other declarations that just happen to end in a digit it's unimportant. eg
 Consider renaming constant 'RGB_GREY25'

**Comment by SystemsModelling** [comment]
Consider renaming parameter 'hwnd' 
No, this is a conventional name.

**Comment by retailcoder** [comment]
Under *Settings > Code Inspections*, you can white-list any identifier (and, starting with 2.0.12, Hungarian prefixes) and the inspection will ignore them. Alternatively, you can set the "Use meaningful names" inspection's severity level to "do not show" and it will not run.

We're not going to special-case or hard-code Excel-specific identifiers, e.g. `Sheet1`.

Numbered identifiers are *generally* a code smell, indicating that you should consider using a more suitable data structure instead of multiple variables, e.g. an array - *that* is what picking up a numeric suffix is trying to catch. I'd suggest white-listing `RGB_GREY25`, or adding an `@Ignore UseMeaningfulNames` annotation on top of each declaration - soon we'll be able to specify an `@Ignore` annotation at module-level to ignore all results of a given inspection in a given module, we're just not there yet ;-)

**Comment by SystemsModelling** [comment]
Consider renaming parameter 'str' 
Maybe better point out conflict with Str()

**Comment by SystemsModelling** [comment]
Thanks retailcoder (Mathieu)

I'll look up about white-listing.

Patrick

**Comment by retailcoder** [comment]
About the conflicting name, I can't fetch the specific issue# atm, but I *think* we have one opened to specifically pick up identifiers that *hide* other identifiers. It's a bit tough though, because it means the resolver needs to keep going up scope levels to see if there's another match higher up - that could seriously impact resolver performance. I hope we find a way to do it efficiently though, it's a very useful thing to point out indeed.

**Comment by ThunderFrame** [comment]
`hWnd` might be worth white-listing by default.
