### ISSUE TITLE
Function/Sub never called Inspection

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/Rubberduck#262]
Probably very similar to the Variable Not Used Inspection #190. If a Function/Sub is never called, it can be removed.

**Comment by retailcoder** [comment]
Yes, I want that! We'll need to refine the usage-finding code though.

**Comment by retailcoder** [comment]
Indeed, VERY similar - from [`VariableNotUsedInspection`](https://github.com/retailcoder/Rubberduck/blob/GrammarIsFun/RetailCoder.VBE/Inspections/VariableNotUsedInspection.cs#L21-L23):

            var declarations = parseResult.Declarations.Items.Where(declaration =>
                (declaration.DeclarationType == DeclarationType.Variable)
                && !declaration.References.Any(reference => !reference.IsAssignment));

Adapting to procedures would look like this:

            var declarations = parseResult.Declarations.Items.Where(declaration =>
                (declaration.DeclarationType == DeclarationType.Function
                 || declaration.DeclarationType == DeclarationType.Procedure)
                && !declaration.References.Any());

Actually... this should also include `PropertyGet`, `PropertyLet` and `PropertySet` - so the inspection would say "*Member* is never called".

**Comment by retailcoder** [comment]
This one needs to be tested against code like this:

    Public Function Foo(ByVal bar As Integer) As Integer
        Foo = bar
    End Function

    Public Sub DoSomething()
        Dim Foo(1 To 10) As Integer
        Foo(1) = 42 ' local-scope array assignment
    End Sub

Function `Foo` is simply not visible to `DoSomething`, because local array `Foo` is shadowing it.

If there's a bug with this, then function [`IsInScope`](https://github.com/retailcoder/Rubberduck/blob/GrammarIsFun/Rubberduck.Parsing/Symbols/IdentifierReferenceListener.cs#L145-L151) needs to be amended.

**Comment by retailcoder** [comment]
The inspection is implemented, but needs some serious brain juice and fine-tuning. Currently disabled and on the verge of being deferred to 1.4 or future release.

**Comment by robodude666** [comment]
What about debug procedures that are manually called by the VBA Programmer, or procedures called by 3rd party tools that open workbooks? Are we assuming that any code that's not called by a button, another procedure, formula, etc, and isn't a Class/Workbook event is "uncalled" ?

**Comment by ckuhn203** [comment]
I'm not sure how it was implemented, but we're very aware that there could be issues around what you're describing. We already talked about the possibility that a `Function` could be called solely by an Access *Macro* (actual macro). Obviously this can look to see what is called within the project. The programmer is ultimately responsible for deciding what to do with the inspection results.

**Comment by retailcoder** [comment]
@robodude666 we're assuming that any public member (be it a `Sub` or a `Function`) in a standard module can be called from outside of VBA, and it's planned to eventually account for projects referencing other projects, so that usages can be found in another project than the project a member, module, or class is declared in.

Class lifecycle handlers (i.e. `Class_Initialize` and `Class_Terminate`) are hard-coded/ignored, and we're picking up all the controls on UserForms so that we can identify (and refactor/rename) these handlers. We're also eventually going to pick up all the `Shapes` in a workbook, so that we can identify handlers and refactor/rename ActiveX and Form controls (and/or any shape with a macro attached), without breaking anything.

**Comment by mgrojo** [comment]
When the use of the subprogram is performed through the `Call` clause, the procedure/function is reported as not used. I have removed these `Call` clauses since it makes apparently no difference. Then should `Call` be marked as obsolete as `Rem` ist?

I'm using 1.4.3.2343 (MSIL). Thanks for your work.

**Comment by ckuhn203** [comment]
@mgrojo that's interesting. Did you receive an "Obsolete Call Statement" warning?

**Comment by retailcoder** [comment]
@ckuhn203 @mgrojo congratulations, you've found a bug ...well, two actually! :+1: 

 - `Call Foobar` should trigger a code inspection result saying 'Use of obsolete Call statement'.
 - `Call Foobar` should be caught as a usage of the `Foobar` identifier... and it's not. Which means if you rename `Foobar` to `Foobaz`, the refactoring will break the code if `Call` is used.

**Comment by mgrojo** [comment]
@retailcoder that makes my day! Thanks.

**Comment by ckuhn203** [comment]
@retailcoder do you want to log those separately, or do you consider them to be part of this issue?

**Comment by retailcoder** [comment]
@ckuhn203 I'll have to investigate. ObsoleteCallInspection worked fine in 1.22, and the inspection itself wasn't modified AFAIK, but there's a [known flaw that should also be addressed](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/Inspections/ObsoleteCallStatementInspection.cs#L24), even at the cost of performance:

            //note: this misses calls to procedures/functions without a Declaration object.
            // alternative is to walk the tree and listen for "CallStmt".

Looking at the code...

            var calls = (from declaration in parseResult.Declarations.Items
                from reference in declaration.References
                where (reference.Declaration.DeclarationType == DeclarationType.Function
                       || reference.Declaration.DeclarationType == DeclarationType.Procedure)
                      && reference.HasExplicitCallStatement()
                select reference).ToList();

This is definitely a resolver issue - I would guess *something* in the resolver code isn't setting the `HasExplicitCallStatement` anymore; I haven't looked at that code in a while, but it must be it.

That said, walking the parse tree and listening for `CallStmt` grammar rules will remove the hard requirement to have `HasExplicitCallStatement` in the interface of `IdentifierReference`, and will pick up `Call SomeFunctionThatHasNoDeclarationInTheParseTree`, which a resolver-based inspection can obviously not pick up.

**Comment by retailcoder** [comment]
That should have been closed a while ago already
