### ISSUE TITLE
Can you detect variables changed byref?

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#2623]
This could be hard to code, but if you could suppress this one:

 Variable 'asCatQID' is used but not assigned 
It is passed to another proc which changes it byref

**Comment by MDoerner** [comment]
This is basically the same issue as #2365.

There, we came to the conclusion that it should be left to the user to make an ignore annotation for the specific inspection.

The reason is that, in general, it is impossible to tell at compile time whether a procedure to which you pass a ByRef argument actually ever assigns to the argument. The specific problem is that VBA knows interface inheritance. So, at compile time, you have no idea what implementation of a public procedure on a class you are calling.

Since it does not happen that often that variables are only assigned by passing them to a procedure as ByRef arguments and, furthermore, you  should know what you are doing if you do it, we rather err on the side of safety and present an inspection result. As already stated above, you can always make an annotation to ignore variables in the inspection.

**Comment by comintern** [comment]
Add the code-path-analysis tag on the off change that we decide to re-evaluate this in a future where RD can determine if a `ByRef` variable is assigned outside of the declaring function.

**Comment by retailcoder** [comment]
@comintern After 2.1, `Declaration` and `IdentifierReference` instances will be annotated with inspection results, so we'll have a better shot at reporting long-running expensive checks in the background without paralyzing the *inspection results* toolwindow.
