### ISSUE TITLE
(Not an Issue) Ideas from MzTools and TM VBA-Inspector

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#2625]
MZTools
[Class Field] Class fields cannot be declared with the Dim keyword
[Method Constant] Method constants must be all upper case
[Method Variable] Method variables cannot be a single letter
[Module] Modules cannot have more than 1000 lines of code
[Parameters] The number of parameters of a method cannot be greater than 10
The method / parameter / variable etc '...' is not used

Userform things
The text '...' of this control has no access key			
This control has an access key 'R' that is already used in the control 'lSector'
This control has the TabIndex property with value 0 instead of 1

Thomas Moeller's VBA Inspector
![image](https://cloud.githubusercontent.com/assets/13900438/22602451/200db60e-ea3b-11e6-9a82-ff49669d85b0.png)

![image](https://cloud.githubusercontent.com/assets/13900438/22602458/274686da-ea3b-11e6-94e2-c3b0d99601ca.png)

(I don't have a picture of the third tab)

**Comment by retailcoder** [comment]
MZ-Tools has a rather different scope (albeit with some overlap) than Rubberduck; I'm not sure I want RD to get into inspecting whether form control captions, for instance.

- [Class Field] Class fields cannot be declared with the Dim keyword
 That one is covered already, by [ModuleScopeDimKeywordInspection](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/Inspections/ModuleScopeDimKeywordInspection.cs).

- [Method Constant] Method constants must be all upper case
 IMO that's an arbitrary naming convention; we *could* implement a feature that verifies casing and allows customizing the rules though.

- [Method Variable] Method variables cannot be a single letter
 Covered by [UseMeaningfulNamesInspection](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/Inspections/UseMeaningfulNameInspection.cs).

- [Module] Modules cannot have more than 1000 lines of code
 Seems a rather arbitrary threshold; I see what it's trying to encourage, but if users don't understand *why* then it's just an incentive to split up large uncohesive modules into smaller uncohesive modules (I've seen that! ..although the limit was VB6's own compiler limit of 65K LoC per module).

- [Parameters] The number of parameters of a method cannot be greater than 10
 Another arbitrary threshold; again I see what it's trying to encourage, but the limit is twice what I'd put it at. Needs to be configurable.

- The method / parameter / variable etc '...' is not used
 Covered by `ConstantNotUsedInspection`, `VariableNotUsedInspection`, `ParameterNotUsedInspection`, `ProcedureNotUsedInspection`, and enhanced with `FunctionReturnValueNotUsedInspection`.

The VBA inspector has a number of interesting inspections that we have either planned or already implemented.. feels like the UI is implemented in a way that makes it look like it has more inspections than it actually has... or we're the ones combining things. Anyway:

 - Empty procedures, not implemented.
 - Scope not declared - see "ImplicitPublicMember"
 - Function declared without data type - see "ImplicitVariantReturnType"
 - Parameter not used - done
 - Parameter has no data type - done, see "VariableTypeNotDeclared"
 - Error-handling is missing - that's encouraging cargo-cult code, not all procedures need an error handler.
 - Constant/Variable not used - done, done
 - Constant/Variable has no data type - done and done
 - Implicit data type character is used - done, see "ObsoleteTypeHint" inspection
 - Parameter uses implicit data type character - same as above
 - Data access object declared without a library - huh? that sounds rather overly specific. does it assume the add-in is running in Access? does it aim to identify member hiding occurrences? planned.
 - Parameter is not declared with explicit ByRef/ByVal - done, see "ImplicitByRefParameter" inspection

 - Option Explicit will not be inserted automatically - that's nice, but redundant if you're already warning about option explicit being missing.
 - Option Explicit is missing - done (since v1.0 IIRC)
 - Empty modules - okay, perhaps.
 - API-Function not used - this would be redundant if "Procedure not used" would pick it up. Consider it planned.
 - Enumeration not used - consider it planned.
 - Type not used - ditto.
 - Constant/Variable not used - already implemented
 - Event is not "fired" - planned.
 - Variable is declared "Dim ...As New.." - not sure what this is about. If it's about the `Dim` keyword used instead of `Private`, then it's covered. If it's about the `As New`, we're actually warning about *procedure-scoped* locals that do this. Thinking again, might be a good idea to warn about auto-assigned object *fields* too, for the exact same reasons.
 - Parameter is declared "As Any" - IMO if someone uses that, they know what they're doing.
 - A `DefType` statement is used - has been planned for a while... but we can't just *warn* about it - `DefType` statements actually thwart our resolver, which is doubly annoying.
 - Scope of field isn't explicit - whatever that means, it's covered already. well, we warn about `Dim` being implicitly `Private`, if that's what it means.
 - Constant/Variable has no data type - done and done
 - Implicit data type character is used - done
 - Keyword 'Global' is used - done

**Comment by comintern** [comment]
"API-Function not used" will be in my next PR.  It's literally 2 lines of code that adds `DeclarationType.LibraryFunction` and `DeclarationType.LibraryProcedure` to the procedure types in `ProcedureNotUsedInspection`. This can also handle `DeclarationType.Event` for "Event is not 'fired'" in the same way (it might be better from a performance standpoint in the combined inspection).

"Data access object declared without a library" attempts to warn about an ancient issue in Access 2000 and Access 2002.  Microsoft decided to make ADO the default instead of DAO, which broke code.  They switched back to DAO on Access 2003.  I'd be shocked if RD even ran in Access 2002.  If it did, an `ObsoleteAccessVersionInspection` or a `HolyCrapImRunningOnAccess2000Inspection` would be more on target.

"Option Explicit will not be inserted automatically" is an inspection on the user's IDE setup, not on the code. Code inspections shouldn't be checking this. I personally have it turned off.

`As Any` should not be an inspection.  It's only allowed for library procedures, and there are situations where you *have to* use it. I'd consider it out of scope for RD to be inspecting the calling conventions of random libraries.

Just as a side note on the "missing error handler", some code that was run through VBA Inspector was actually the rationale for #2026 - the author added do-nothing `On Error GoTo 0` statements to every single procedure that VBA Inspector was flagging with that inspection to silence them.

**Comment by retailcoder** [comment]
`HolyCrapImRunningOnAccess2000Inspection` - status: planned? :rofl:

**Comment by ckuhn203** [comment]
lol. 
On a slightly more serious note, we explicitly decided only to support Office 2007+ IIRC. Do I?

**Comment by retailcoder** [comment]
@ckuhn203 yep. hence "holy crap I'm running in Office 2000" - I don't *think* it would run... but I don't have a VM to test it with.

**Comment by ThunderFrame** [comment]
Rubberduck runs just fine in Access XP/2002.

IIRC, All versions of Access since 2000 expose DAO/ADODB returning members `CurrentDB`/`CurrentProject` and `CodeDB`/`CodeProject`, among others. It's just the default reference that varies.
