### ISSUE TITLE
Passed ByVal and assigned a value

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#2635]
This can be intentional.

	Parameter 'wb' is passed ByVal and assigned a value	
	Function GetWorksheetByName(sName As String, Optional wb As Workbook) As Worksheet  ' ignore errors, return nothing if not found
     On Error Resume Next
     If wb Is Nothing Then
        Set wb = ActiveWorkbook
   End If
...

 
 	Parameter 'PictureAppearance' is passed ByVal and assigned a value	TPI.PPTCopyPaste

Function RetryCopyAndPasteShape(ByRef oObject As Object, ByVal PasteDataType As Long, Optional ByVal PictureAppearance As XlPictureAppearance = xlScreen) As Object
...code...
If lErr <> 0 And PictureAppearance = xlPrinter And lRetries < 2 Then
PictureAppearance = xlScreen
fall back to screen appearance if printer fails (eg no printer installed)

**Comment by comintern** [comment]
The top one...

```
Function GetWorksheetByName(sName As String, Optional wb As Workbook) As Worksheet
    On Error Resume Next
    If wb Is Nothing Then
        Set wb = ActiveWorkbook
    End If
```
...is the partially the same issue as #2601. Otherwise it's the same as the one below (and by design).

The second sample...
```
Function RetryCopyAndPasteShape(ByRef oObject As Object, ByVal PasteDataType As Long, _
    Optional ByVal PictureAppearance As XlPictureAppearance = xlScreen) As Object
    '...code...
    If lErr <> 0 And PictureAppearance = xlPrinter And lRetries < 2 Then
        PictureAppearance = xlScreen
```
...returns the "Parameter 'PictureAppearance' is passed ByVal and assigned a value" result by design.  The purpose of the inspection is to discourage the use of a parameter as if it was a local variable. Consider the counter example where the `ByVal` is missing:
```
Function RetryCopyAndPasteShape(ByRef oObject As Object, ByVal PasteDataType As Long, _
    Optional PictureAppearance As XlPictureAppearance = xlScreen) As Object
    '...code...
    If lErr <> 0 And PictureAppearance = xlPrinter And lRetries < 2 Then
        PictureAppearance = xlScreen
    End If
```
In this case, VBA defaults the `PictureAppearance` to `ByRef` (which triggers an "implicitly passed by reference" inspection). What the "passed ByVal and assigned a value" does is let you know that it isn't clear from the assignment `PictureAppearance = xlScreen` whether the change in `RetryCopyAndPasteShape` is _supposed to_ be visible to the caller - the `ByVal` declaration and assignment signal unclear intent.  Making a local copy makes it explicit that the value is only intended to be used within the scope of `RetryCopyAndPasteShape`:

```
Function RetryCopyAndPasteShape(ByRef oObject As Object, ByVal PasteDataType As Long, _
    Optional PictureAppearance As XlPictureAppearance = xlScreen) As Object
    
    Dim appearance As XlPictureAppearance
    appearance = PictureAppearance
    '...code...
    If lErr <> 0 And appearance = xlPrinter And lRetries < 2 Then
        appearance = xlScreen
    End If
```

Like any of the other inspections, this can be disabled in the settings or ignored if you don't subscribe to that particular style philosophy.
