### ISSUE TITLE
Source Control: Type of git servers

### ISSUE THREAD

**Issue by JoLuGit** [rubberduck-vba/Rubberduck#2663]
Is it possible to use a ssh-based git server an put into the remote path field something like
ssh://myuser@mygitserver/repository

**Comment by ckuhn203** [comment]
It *should* be possible, but not something I've personally attempted. Are you getting some kind of failure when you try it?

**Comment by JoLuGit** [comment]
It says:
Failure to clone remote repository.
Unsupported URL protocol

**Comment by Vogel612** [comment]
I suspect that's because the url needs to be of the following kind:

     ssh:myuser@mygitserver/repository

**Comment by ckuhn203** [comment]
It's possible that the library we use doesn't support it. I'll look into that. Brb.

**Comment by ckuhn203** [comment]
https://github.com/libgit2/libgit2sharp/issues/255#issuecomment-278391234

**Comment by ckuhn203** [comment]
Ahhh. We do not, and likely will not be able to support this feature in the near future. The underlying library doesn't support it and I don't really want to bind to a fork of it. 

> you can use libgit2sharp fork with SSH support based on @Therzok work, available in NuGet under 'LibGit2Sharp-SSH' name.

https://github.com/libgit2/libgit2sharp/pull/1072#issuecomment-262408247

**Comment by Vogel612** [comment]
so it seems we're awaiting libgit2sharp finding a way to fix the brokenness of Windows 👏 🙈 

FWIW this means Rubberduck will possibly not be able to support this (unless we switch the internal git provider) unless there's considerable effort expended. This is pretty unfortunate, since one of the really important benefits of git over other version control is in the transport layer security you can get from ssh 😭

**Comment by ckuhn203** [comment]
This is really unfortunate, but I don't expect libgit2sharp to ever support it. I counted a half dozen issues related to this, all with just as much activity around them. Edward Thomson chimed in saying that the way to fix it is to build our own version of libgit2sharp bound to a version of the ssh lib that works on windows. I'd rather not go that route, because I don't want us to end up supporting a custom version of both libgit2 and an ssh lib.

**Comment by retailcoder** [comment]
Thanks for the research @ckuhn203. Closing this issue for now.
