### ISSUE TITLE
RD needs a way of getting the topmost MDI Child Window

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2671]
I need to discover the active/top-most MDI child, even if the MDI Window doesn't have focus. For example, I have 4 codepanes open but not maximized, and one of them is necessarily active/top-most, but the active window is the (docked) Immediate Window, VBIDE doesn't offer a way of identifying the active MDI child.

Complicating matters, the dockable windows can be made non-dockable, and they become MDI children, so I guess what I really need is a way of getting the top-most MDI-child, and optionally requesting the top-most CodePane/Designer window, rather than the top-most window.

Use Case: I need to know, for a form, whether the Designer is active, or the CodePane is active. I can't find any other way to determine that, other than the z-order of the MDI children.

**Comment by retailcoder** [comment]
We could track the last active interesting `IWindow` - i.e. a code pane or designer window, and expose it in the `IVBE` wrapper?

**Comment by comintern** [comment]
I think I tried that at one point.  The problem I was running into was that the VBE was recycling the windows for the code panes, so they kept getting re-wrapped. I'm guessing the easiest way to get this would be through the Window menu:

![untitled](https://cloud.githubusercontent.com/assets/8944005/22831635/b3e357be-ef70-11e6-953e-97f1c5489b19.png)

For MDI hosts, these will typically always be in the current Z-order.  This may be the most disruptive way to do this because it doesn't require subclassing or dropping new hooks.

**Comment by ThunderFrame** [comment]
@retailcoder Well Windows has some concept of active or top-most child, as it is styling the title bar differently.

![mdichild](https://cloud.githubusercontent.com/assets/16574009/22845108/275547f6-f035-11e6-9d5f-6435e521ab7b.png)

@comintern The menu might be the best approach.

**Comment by ThunderFrame** [comment]
Well, I thought that reading the control captions twice was enough to get a refreshed value, but it seems that the windows menu doesn't get updated all of the time, I *think* the VBE is lazy about refreshing the window when an MDI child closes, so it's easy to get bad data by reading the menu without showing the menu first.

I think I've found a workaround that gets me the detail I need without needing to know the topmost window.
