### ISSUE TITLE
Target .net 4.0

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#2675]
We've had a request for a build targeting .net 4.0, so that RD can run in an environment whee 4.5 cannot be installed. Since both 4.0 and the current 4.5 end up running off the same 4.0 CLR, I'm pretty sure it can work, even if/when we start using C# 6.0 features... as long as we're not depending on .net framework things that aren't available in 4.0.

So let's try issuing 2.0.12 with a 4.0 target.

**Comment by MDoerner** [comment]
If we want to do this, we will need to add a reference to the package that contains the `async` support for 4.0.

**Comment by Hosch250** [comment]
Only thing that needs to happen is changing the compile mode to .NET 4.0.  Using C# 6, or even C# 7, shouldn't affect this.

**Comment by retailcoder** [comment]
Honestly I'm starting to *really* **want** to be able to use null-coalescing operators and string interpolation.

**Comment by ckuhn203** [comment]
.Net 4.5 introduced the async/await and Parallel paradigms, which we utilize pretty heavily if I recall correctly. 

https://msdn.microsoft.com/en-us/library/ms171868(v=vs.110).aspx#core

I now seem to remember making a conscious decision to take advantage of 4.5 precisely for this reason (and because it still allowed us to support the Win7 OS).

**Comment by ckuhn203** [comment]
In short, I believe it would take a large effort to rewrite any async or parallel code to work with .Net 4.0. It's not as simple as targeting 4.0 with a newer compiler/language version. We're actually relying on features introduced in 4.5

**Comment by MDoerner** [comment]
To  have `async` in 4.0, one has to load the package Microsoft.Bcl.Async. However I am not sure whether the syntax is fully identical. 
The Task Parallel Library is actually 4.0.

**Comment by ckuhn203** [comment]
I certainly won't stand in the way if the community thinks it's worthwhile and possible. Just providing historic context. :+1:

**Comment by retailcoder** [comment]
Turns out the person that requested it ended up already be running .net 4.5, which makes demand for 4.0 support drop to 0... I'd rather *up*grade than *down*grade the tech, so I'm going to close this issue for now - let's see if more requests for 4.0 support come in the future; for now it's just not worth it.

**Comment by robodude666** [comment]
+1

I was interested in .NET 4.0 support 2 years ago #277 and still am.

**Comment by Vogel612** [comment]
@robodude666 IMO this is a very rare edge case. Sure there's possibly quite a number of companies that still are on XP / .NET <= 4.0, but they *sooner or later* will upgrade to .NET 4.5.

The codebase relies incredibly much on `async` and the TPL, as such "backporting" to .NET 4.0 is an effort that benefits too little users for the cost it has. Especially since "manually" multithreading code is **really** hard, and the chance of bugs is high. If you can find people willing to do this with you: The code is open-source, you can make a fork and backport it yourself :smile:

**Comment by robodude666** [comment]
@Vogel612 I understand a backport will likely not happen; was merely pointing out there still _are_ users interested in it. If I had to pick, I'd rather get #2923 :stuck_out_tongue:
