### ISSUE TITLE
Unit Test>Test Explorer>Add>Test Method

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#2763]
Adds the method wherever the cursor is active. This may have it add it to an existing method creating
```
Public Sub SomeTest()
    dim someVar as string
    someVar = "someValue"

Public Sub AnotherTest()

End Sub

End Sub
```

**Comment by retailcoder** [comment]
Really?!! Wow, how did we miss that!

**Comment by comintern** [comment]
Pretty sure this was related to the UI thread lag I just fixed by moving to asych events.  This needs to be retested after my next PR.

**Comment by retailcoder** [comment]
I don't think we can repro this. The `AddTestMethodCommand` implementation adds the code at the end of the module:

````csharp
module.InsertLines(module.CountOfLines, body);
````

It works off the active codepane, but the `CanExecute` implementation only returns `true` when the `SelectedVBComponent` is a test module. Because the `Execute` implementation works off the `ActiveCodePane` and not the `SelectedVBComponent`, I've changed `CanExecute` to work off the `ActiveCodePane` as well, but this *shouldn't* affect it anyway.
