### ISSUE TITLE
Refactor>Move Closer To Usage removes member calls

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#2774]
Code before:
```
Sub TestRDMoveCloserToBefore()

    Dim someRange As Range
    
    Dim someOtherRange As Range
    

    Dim someRange As Range
    Set someRange = Selection
    
    Set someOtherRange = ActiveWorkbook.Sheets(2).Range("A1")
    
    Set someRange = someRange.Resize(someRange.Count)
    
End Sub
```

Code after: `.Resize` is gone as is `.Count`
```
Sub TestRDMoveCloserToAfter()

    'Moved someRange
    Dim someOtherRange As Range
    

    Dim someRange As Range

    Dim someRange As Range
    Set someRange = Selection
    
    Set someOtherRange = ActiveWorkbook.Sheets(2).Range("A1")
    
    Set someRange = someRange(someRange)
    
End Sub
```

**Comment by retailcoder** [comment]
:fearful:

**Comment by comintern** [comment]
`someRange` is declared twice in the top example.  Is it possible that the refactor is running _twice_ without updating the selection cache?  Note that even though the "Before" code doesn't compile due to "Duplicate declaration in current scope", the RD parser has absolutely no issue with it. That means that every usage of `someRange` has too many references pointed at it:

![untitled](https://cloud.githubusercontent.com/assets/8944005/23521835/40bc7a78-ff46-11e6-8e82-cadcff87d20c.png)

**Comment by retailcoder** [comment]
@comintern shouldn't that throw a resolver error?

**Comment by comintern** [comment]
I stand corrected.  The top declaration has zero references:

![screenshot from 2017-03-02 12 49 45](https://cloud.githubusercontent.com/assets/8944005/23521927/be3c43de-ff46-11e6-8ee5-3710466141b9.png)

**Comment by IvenBach** [comment]
Looks like the extra `Dim someRange as Range` was from me not `Undo`ing enough from a first move. I can't get it to reproduce the error now. When I do run it without the extra `Dim` it works fine.
