### ISSUE TITLE
Closing Workbook and Code Module Without Saving Triggers Excel Recovery

### ISSUE THREAD

**Issue by pmtutko** [rubberduck-vba/Rubberduck#2782]
Using Excel 2013. Rubberduck v2.0.11.2453 (MSIL)

1. Open a blank workbook, then open the VBA Editor.
2. Insert a code module and create a no-op Sub.  (The error doesn't occur with an empty module)
    mine was: Sub Test()
                          Debug.Print "test"
                      End Sub
 
3. Close Excel by clicking the "X" on the upper right of the Excel main window.
4. Choose "Don't Save" when prompted to save the workbook.

Each and every time I close an unsaved workbook with a VBA module, Excel closes then immediately displays the recovery window showing "Excel is attempting to recover your information" then reopens with a blank workbook.

**Comment by retailcoder** [comment]
@comintern that's likely fixed at this point, no?

**Comment by comintern** [comment]
Thanks for taking the time to file an issue.  This is a known problem with the order in which the VBE tears down tool windows when Rubberduck is unloaded, and we're actively working on getting it fixed.  Unfortunately, since we are running inside the process of the host application and the VBE "owns" the tool windows, this is an extremely complex problem.  Complicating matters is the fact that these errors are thrown from the unmanaged side of the COM interop boundary, so we can't catch them in managed code.

I thought there was an open issue for this already, but I can't seem to locate it.

**Comment by comintern** [comment]
Linking #2524 - that one is specific to the status bar tear down, but the underlying issue is similar.

**Comment by Falthazar** [comment]
I'm getting the same issue as well. Any thing I need to do to help with troubleshooting?

**Comment by MDoerner** [comment]
This should have gotten a lot better within the last prereleases. For more information, see issue #3614 dedicated to the problems on shutdown.

**Comment by comintern** [comment]
This appears to have been resolved.
