### ISSUE TITLE
Closing Module-Window during Parse blows up

### ISSUE THREAD

**Issue by Vogel612** [rubberduck-vba/Rubberduck#2786]
Reported by Peter M Taylor in chat [here and following messages](https://chat.stackexchange.com/transcript/message/35823024#35823024)

The repro steps are simple enough.

1. Click the refresh button in the Rubberduck status bar.
2. **During the parsing** click the small x to close the opened document in the VBE

![image description of repro steps](https://i.stack.imgur.com/zWJrQ.png)

**Comment by PeterMTaylor** [comment]
Appending additional information from my debugger et al.
![capture rd development 2 0 12 target window comexception disassembly](https://cloud.githubusercontent.com/assets/2254567/23578444/468cb30a-012b-11e7-879f-63df13323ffd.PNG)
![capture rd development 2 0 12 target window comexception callstack](https://cloud.githubusercontent.com/assets/2254567/23578446/468d65f2-012b-11e7-9eca-2ec4aa8b9cc6.PNG)
![capture rd development 2 0 12 target window comexception output screen](https://cloud.githubusercontent.com/assets/2254567/23578445/468d10de-012b-11e7-93a1-73b45b15b3fb.PNG)
![capture rd development 2 0 12 target window comexception](https://cloud.githubusercontent.com/assets/2254567/23578447/46903480-012b-11e7-9005-14515be28e16.PNG)

**Comment by comintern** [comment]
Fix forthcoming. This is almost certainly being caused by a slightly over-zealous approach to attaching subclasses to `VbaWindow` hWnds when they're created. Since the VBE's object model doesn't have a direct method to associate an IWindow with an ICodePane, that's being done from within the event handler. The failure is due to that code path attempting to wrap one of the other _native_ window types in the wrong `SafeComWrapper`.
