### ISSUE TITLE
Referencing of RubberDuck.tlb causes indefinite Loading References

### ISSUE THREAD

**Issue by Xipooo** [rubberduck-vba/Rubberduck#2789]
Just starting out with RubberDuck and I'd like to use is for TDD practices.  Unfortunately when I turn on Early Binding which causes the RubberDuck.tlb file to be referenced, the refresh button is stuck on "Loading references" indefinitely and my Test Explorer window can not find any of my tests when I try to refresh it.  The buttons to run my tests are also disabled.

I want to have late binding when I distribute, but I want early binding while I'm developing so I can get the good intellisense.

Steps I've taken so far to try and resolve this:

- Tried registering the tlb file manually
- Tried moving the tlb file to the System32 directory
- Tried installing RubberDuck to a different folder with less file permission restrictions than the ProgramData folder
- Tried removing and re-adding the reference

Current ecosystem:
- Windows 10
- Access 2013 (File Version 15.0.4893.1000) x64
- Intel i7-6700
- 16 GB Memory
- RubberDuck version 2.0.11.2453

Update: I was able to get past the "Loading References" by un-referencing the tlb, hitting refresh, then re-add the reference.  I can also run the test refresh to find new tests by having the tlb un-referenced, then re-referencing it again when I want to do intellisense.  But this is very annoying to have to un-ref then re-ref every time I want to run a new test.  Especially if I'm going to do TDD.

**Comment by ThunderFrame** [comment]
Thanks @Xipooo , I saw you mention this in your latest video. I recall it being mentioned as an issue among the devs, and I think a fix is in place with the imminent 2.0.12 release. I'm running the latest source, and I can't repro your issue. The next release is <s>hours</s> days away

**Comment by ThunderFrame** [comment]
Linking #2557 
Looks like @comintern was working on fixing early-bound `Rubberduck.tlb`, but I can't find a commit, but as I say, early-bound seems to work for me with the latest source.

**Comment by comintern** [comment]
The permanent fix for this got back burnered a couple weeks ago due to more critical priorities.

&lt;speculation&gt;The underlying issue seems to be the use of `LoadTypeLibEx` on `Rubberduck.tlb`.  RD is being loaded directly into the host's process, but the VBE isn't (doesn't have to) bind anything other than the extension interface.  This would mean that RD's GUID is already "loaded" in the context of the executing process, which wouldn't be a normal condition for `LoadTypeLibEx` to have to deal with when presented with a request to load the tlb.&lt;/speculation&gt;

The fix is to just build the API Declarations with managed reflection instead of loading a tlb that we generated (it seems a bit backward when put like that anyway).  Note that this _could_ be hard coded, but that would make it extremely tedious to extend the API's functionality later.  The reflection code is a bit involved, so it didn't make the cut for 2.0.12 - look for it in 2.0.13.

**Comment by Xipooo** [comment]
Yeah, I loaded up the current builld instead of the release build and the problem went away.  When 2.0.12 does get release this issue will be resolved.  You can probably close this issue.

**Comment by comintern** [comment]
I'll leave it open pending a permanent fix - keeps it on my todo list.  :wink:

**Comment by comintern** [comment]
This issue should be resolved with custom tlb registration.
