### ISSUE TITLE
False positive on `NonReturningFunction` inspection

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2803]
RD 2.0.12, Excel2010, Win7

![image](https://cloud.githubusercontent.com/assets/11889733/23615222/add356c6-0253-11e7-8072-889a4045e3ec.png)

```VBA
Private pIndustries As Collection               'Stores all the industries to be reported on

Public Property Get Industries() As Collection
    Set Industries = pIndustries
End Property
```

**Comment by comintern** [comment]
In this bit of code from `NonReturningFunctionInspection`:
```
    var unassigned = from function in functions
                     let isUdt = IsReturningUserDefinedType(function)
                     let inScopeRefs = function.References.Where(r => r.ParentScoping.Equals(function))
                     where (!isUdt && (!inScopeRefs.Any(r => r.IsAssignment)))
                        || (isUdt && !IsUserDefinedTypeAssigned(function))
                     select function;
```

`r.IsAssignment` is false for `Set Industries = pIndustries` because it's part of a `SetStmtContext` instead of a `LetStmtContext`. The `FunctionReturnValueAssignmentLocator` doesn't have a `SetStmtContext` listener. Should be a pretty easy fix.
