### ISSUE TITLE
Code inspections

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#2865]
"Fix all occurrences in project" takes too long. It's quicker to do find & replace.
After what should be a simple Fix, the circle of dots continues to rotate for a long time.

Variable uses Hungarian Notation - "Disable this inspection" does not disable it, and it is not in the Settings under Maintainability & Readability.

**Comment by comintern** [comment]
"Fix all occurrences in project" should be improved tremendously by changing the current code re-writing to token stream re-writers.

We definitely need to get the inspection settings fixed for the Hungarian Notation inspection though.

**Comment by retailcoder** [comment]
I have that one covered - my fork isn't ready to PR yet, but I'm moving the inspections into the `Rubberduck.Parsing` library as a first step towards getting inspections under the full control of the `ParseCoordinator` (and share cancellation tokens with the parser). But the most significant part is the rewriter API which is well under way also - when I merge my changes Rubberduck will be able to perform all code changes *at once*, and rewrite entire modules in one single operation (with a caveat: since "dead code" from `#If` precompiler conditionals isn't in the token stream, the "dead code" will need special handling or will otherwise be wiped out).

Missing inspection settings *should* be a trivial fix.

**Comment by MDoerner** [comment]
Regarding the long run time, the fix itself is not what takes so long. Currently, we reparse after refactoring modules (as part of the quickfix) to get the new identifier position and then run all inspections again. What is really taking long is running the inspections, possibly several times. 
This process will be streamlined once the changes @retailcoder mentioned above are done.

**Comment by Vogel612** [comment]
@retailcoder fixed since when?
