### ISSUE TITLE
Object assigned without set QuickFix, false positive

### ISSUE THREAD

**Issue by CHR-IS-B** [rubberduck-vba/Rubberduck#2874]
RD correctly identified the object variable mergeAreaTmp as being assigned without the 'Set' keyword in the procedure below, however this procedure compiles and runs without error and works as intended.  The procedure unmerges all cells in the active workbook.

```
Public Sub UnMergeAll(Optional ByVal optionDataInAllCells As Boolean = False)
    Dim cellTmp As Range
    Dim mergeAreaTmp As Range
    Dim varCell As Variant

    For Each cellTmp In activesheet.usedRange
        If cellTmp.MergeCells Then
            Set mergeAreaTmp = cellTmp.MergeArea
            varCell = mergeAreaTmp.Cells(1, 1)
            mergeAreaTmp.MergeCells = False
            
            ' If option is chosen, add back the merged cell contents
            '  to every unmerged cell
            If optionDataInAllCells = True Then mergeAreaTmp = varCell
        End If
    Next
    
End Sub
```

**Comment by comintern** [comment]
Thanks for taking the time to report this - the underlying problem is a known issue.  We're currently not taking the use of the default member of object variable into account for that inspection (see #2602).  Note that this should probably be triggering a different inspection, something along the lines of "Implicit use of default member Value".

**Comment by CHR-IS-B** [comment]
Thanks for the reply!
