### ISSUE TITLE
RD's enums should follow COM naming conventions.

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#2885]
In COM, it's traditional to prefix your enumerations in order to avoid namespace collisions - i.e. `VbMsgBoxResult` or `XlSortOrder`.  RD's COM visible enumerations should probably be following that convention with things like `RdAccessibility` and `RdDeclarationType`.  Accessibility is already a pretty good example of a potentially colliding namespace.

The downside to doing this is that we've already shipped the interfaces, so renaming these would be a potentially breaking change.  Because of that, I'm tagging this discussion.

Thoughts?

**Comment by Vogel612** [comment]
Sounds like a tech-debt that needs to be paid to me. The question is: how much code are we breaking with this??

**Comment by retailcoder** [comment]
@Vogel612 doesn't matter. The COM API is advertised (if at all) as an experimental feature, subject to breaking changes.

**Comment by bclothier** [comment]
Just a thought - one way to avoid breaking the old changes is to do what Microsoft did when they renamed their constants -- dump them in a module named `OldConstants`, then define new constants with same value. I know this exists in Access' object model, at least. That way, you can then deprecate 2 versions later and thus remove it. Probably not applicable in this situation since it's already unstable but that would be one way to control such breaking changes in future, coupled with the inspection for experimental feature use which could be then quick-fixed in this case by replacing the old Enum constant with the new constant.

**Comment by bclothier** [comment]
Closing this issue since it's kind of already mentioned in the proposal #6 of the issue #2903.
