### ISSUE TITLE
Aggregated Inspections need a navigation/visibility option

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2900]
I'm parsing a project that takes 40 minutes for the inspections to complete. Some inspection results are aggregated (up to 1000 aggregations), and double-clicking the inspection only selects the first inspection selection.

Unfortunately, some of the inspections are false positives due to parser problems, so I have to manually coerce the first result to not trigger the inspection and then reparse, and wait 40 minutes for the inspections to complete, just so I can verify the next inspection in the aggregate.

Rubberduck should have the ability to toggle the aggregation view, and/or navigate the individual results in an aggregated inspection (eg. Move Prior, Move Next).

**Comment by retailcoder** [comment]
The original aggregated results knew about all the individual results. The problem is that this didn't contribute to reduce overhead at all.. So we removed individual results from aggregates - an aggregate result doesn't know about any "child" results.

What's a good way to do this?

**Comment by Vogel612** [comment]
why did the encapsulation of individual results not help us? If we can reintroduce these results (which shouldn't actually be a problem, since we do keep them all in memory at one point anyways) then fixing this is significantly easier...

I'm guessing the eager initialization of QuickFix instances for all our child results made keeping the individual results not provide sufficient memory-saving... could we work around that? Would it be feasible to have a single QuickFix for each Inspection that gets passed the InspectionResult when we want to fix it? This should alleviate the problems we have there ...

If we want to allow navigation (or visibility changes) of the aggregated results, we need to find a way to reduce the memory footprint of keeping them, and the above seems like a viable idea to me. This would of course mean that InspectionResults need to be passed to a QuickFix instead of containing one, but ... that's only a minor semantic change. Opinions?

**Comment by comintern** [comment]
@Vogel612 - I'm thinking that the quick-fixes _helped_, but not nearly enough.  I still lean in the direction of trying to fix this at the UI level - the `InspectionResultsControl` is still rendering the entire grid so that it can size the scroll-bar.  Whatever direction displaying aggregates goes, at some point we need to figure out how to address that.

**Comment by Hosch250** [comment]
Is there a way to tell it to only load the first N items?  If we do that, then we can load more when the user hits the last loaded item, or we can have a "load more" button.

**Comment by PeterMTaylor** [comment]
Just thinking here, is what @Hosch250 is saying in comparison to SQL Select distinct (count(inspection)>1) from InitialRun.Parser ? And optionally load more if required?

**Comment by MDoerner** [comment]
I agree that it would be nice to be able to load only the first N inspection results and then to have a button to load more results. Something like this is actually a quite common feature in mobile applications and should be intuitive to the user. Moreover, limiting the number of loaded results should avoid having memory problems again.

**Comment by ThunderFrame** [comment]
What about a treeview approach? Expanding an aggregated node returns the individual inspections?

**Comment by SystemsModelling** [comment]
Yes, I'd like to collapse repeated reports of the same thing but not have to turn it off and re-inspect.
