### ISSUE TITLE
IInspection/IInspectionTarget

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#2913]
So `IInspection` is now under the `Rubberduck.Parsing.Inspections` namespace. Step one, completed.

Great!

We want to turn this:

    IEnumerable<IInspectionResult> GetInspectionResults()

To this:

    void AnnotateInspectionTargets()

How do we go about doing this *without breaking everything*?

**Comment by Vogel612** [comment]
We don't ... We just break it in a controlled way.

For one we still need to find a way to actually enumerate the InspectionResults to display them in the UI, which means there still **will** be a method somewhere that has the signature `IEnumerable<InspectionResult> GetInspectionResults()`

That method will have to wait for the full annotation of the parse-tree to complete though. As such we may need to know about how far the annotation process has progressed when we want to retrieve inspection results.  
Long story short: We already have the `ParseCoordinator`. What we need now is for someone to coordinate how we annotate things to encapsulate the process of generating and retrieving inspection results to cleanly change from `GetInspectionResults()` actually **creates** the results (via `Inspector`) to `GetInspectionResults()` walks the parse-tree to fetch annotated results.

This then is the breaking change we need to perform to allow smoothly transitioning. This two-step process allows clean migration of the unit tests (which are supposed to be all-green) before doing the huge change to "production" code.

**Comment by MDoerner** [comment]
Another option would be to not make this change at all and instead let the `Inspector` annotate the trees with all results in one walk over the tree.

We will anyway have to change the `IInspector` interface and move it to `Rubberduck.Parsing.Inspections` if we want to trigger the inspections from the `ParseCoodinator`. (I think we should constructor inject the `IInspector` into the `ParseCoordinator` and continue to handle the details of running the inspections in the `Inspector`.)

**Comment by Hosch250** [comment]
I have a thought about cleaning up the mess with injecting quick fix dependencies into the inspections.  This is a total mess; we need to make the quick fixes call the inspection result, not vice-versa (the current way). So, suppose we told each quick fix what inspection result types it could fix and gave it a `Fix` method that took a result, like so:
```
public interface IInspectionQuickFix
{
    List<IInspectionResult> CanFix { get; }
    void Fix(IInspectionResult target);
}
```
Now, we can inject all the quick fixes into the Inspections viewer:
```
public class InspectionViewModel
{
    InspectionViewModel(List<IInspectionQuickFix> quickFixes);
}
```
Finally, we can regroup the list of quick fixes somehow by the results they can fix, and these quick fixes can be displayed in the Quick Fix dropdown. Rather than the selected quick fix being responsible for knowing what can fix it, the viewmodel behind the display knows. When the user chooses a quick fix, the vm passes that parameter to a command, the command casts it to an `IInspectionQuickFix`, and calls `fix.Fix(SelectedInspectionResult)`.

Now, the quick fixes are in charge, and we actually save memory by having only one instance of them, instead of one instance in every result that uses them. Ninject is responsible for creating and injecting the quick fixes, so they can have whatever crazy dependencies they want without affecting the inspection--it is terrible that the inspection has to change whenever we add a dependency to a quick fix. Now, we could support users writing add-ons for RD with new quick fixes for a given inspection because the inspection result does not know anything about its quick fixes.

**Comment by MDoerner** [comment]
I like what @Hosch250 proposes above. However, I would take it one step further and inject an `IQuickFixHandler` into the view model and inject all the quickfixes into its implementation. I think the view model itself should not know the details of how applying the quickfixes works. It should just translate the input and pass it on to somebody else who knows.

**Comment by Hosch250** [comment]
@MDoerner That makes sense.

**Comment by Hosch250** [comment]
The quick fix stage of this is done.

**Comment by Hosch250** [comment]
Next stage: Extend the parse tree nodes (perhaps `ParserRuleContext` or `RuleContext`?) to include an `IList<IInspectionResult>` and add the inspections to that.

**Comment by retailcoder** [comment]
@Hosch250 the base classes aren't `partial`. only the *generated* ones, inherited from `ParserRuleContext`.
