### ISSUE TITLE
RefactorRename does not modify Interface references

### ISSUE THREAD

**Issue by BZngr** [rubberduck-vba/Rubberduck#2930]
ClassModule IClass1:
```
Public Sub DoSomething()
End Sub

```
Class module Class1:
```
Implements IClass1

Private Sub IClass1_DoSomething()
End Sub
```

Class module Class2:

```
Private Sub RefTheInterface()
    Dim c1 As Class1
    Set c1 = New IClass1
    c1.DoSomething
End Sub

Private Sub RefTheInterface2()
    Dim c1 As Class1
    Dim c2 As IClass1
    Set c1 = New Class1
    Set c2 = c1
    c2.DoSomething
End Sub
```

Run Refactor->Rename-> choose a valid new name.

IClass1 and Class1 reflect the new name.  "Both references to "DoSomething" in Class2 remain unchanged.

**Comment by retailcoder** [comment]
Just to be clear, what's being renamed is `DoSomething`?

**Comment by rubberduck203** [comment]
* on Class1

?

**Comment by BZngr** [comment]
Yes - I selected DoSomething on IClass1, Class1, and on references within Class2.  Same outcome.

**Comment by MDoerner** [comment]
@BZngr I guess it is a typo in your first method that you omitted the `I` in `Dim c1 As IClass1`, right?

Given that, I can fully reproduce this when renaming any public sub on an interface. As remarked above, it does not matter whether the method is called via an interface. Whenever the interface of a class gets implemented, no references are updated by `RefactorRename`, period. Only the implementing methods get adjusted.

Since we currently do not clean up sub and super classes when we reparse, this even persists after removing all implementing classes, until the implemented class gets modified the next time.

I guess that there is some special handling for the implementing methods that runs instead the usual handling, instead than additionally.

**Comment by retailcoder** [comment]
> Since we currently do not clean up sub and super classes when we reparse

We should be doing that for all user code.

**Comment by BZngr** [comment]
Not necessarily a typo...at least this is how I've used VBA interfaces in the past.  The first line establishes what class is implementing the interface in preparation for the Set statement.  If I had added the "I" in the first statement, calls to DoSomething() are forwarded to the interface defintion (empty proc bodies).

**Comment by BZngr** [comment]
FWIW - RenameRefactoring was free of unit tests for renaming controls (though it has code for for doing that).  I added a RenameControl unit test and it failed in a similar manner as this issue (renamed declaration, left references as they were).  I'm currently working on refactoring RenameRefactoring and am fixing these issues as I find them.
