### ISSUE TITLE
Rubbeduck>Navigate>Code Explorer Default Folder for Worksheets

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#2980]
How hard would it be to place Worksheets within their own "Microsoft Excel Objects" without putting that annotation at the top of every code behind? Is this something that would merit its own section under Settings?

**Comment by retailcoder** [comment]
That would be "Document class modules" in a host-agnostic way.

The problem is that it then encourages creating folders by *module type*, e.g. "Class modules", "User Forms", "Standard Modules", like the project explorer does - which would be a fairly useless usage of the `@Folder` annotations.

The name of the default folder could be configurable though... but making it "Document class modules", or anything really, would still be misleading in that anything without a folder annotation would end up under that folder, including an unannotated class module.

The simplest solution is to leave the default folder as it is, and let the user decide where they want their stuff... which is what we're currently doing.

To get document modules under a default "Microsoft Excel Objects"  folder, we'd have to make the folder logic host-aware, and then add an annotation to all document modules before the initial parse - and that's a challenge in itself, for we can't use rewriters and parse trees *before* we parsed anything.

The very idea of folders is to be able to regroup modules by *functionality* rather than by *type*, so you can have related things regrouped together, as you would in a Visual Studio project's namespaces.

If you have multiple module types in a folder and want to easily locate worksheets, you can always *sort* them by type.

**Comment by IvenBach** [comment]
Getting used to Non-VBA way of thinking will take some time.

**Comment by retailcoder** [comment]
FWIW it's the *VBE* way - VBA itself has no bearing on how modules are to be organized.
