### ISSUE TITLE
MSForms control members trigger 'Member does not exist on interface' inspection

### ISSUE THREAD

**Issue by A9G-Data-Droid** [rubberduck-vba/Rubberduck#2982]
I am getting the following errors:

> Member 'Clear' is not declared on the interface for type 'ListBox'.
> Member 'SetFocus' is not declared on the interface for type 'TextBox'.

These are clearly valid members because I can see them in the VBA code completion, they compile, and they function. You can clear a listbox and you can set the current focus to a textbox. There might be a greater issue with evaluating members of form objects but I couldn't find an open issue for it.

My code exists locally in the form and I am calling the object with no qualifications:
```
serialNumber.SetFocus
partNumber.Clear
```

**Comment by retailcoder** [comment]
Which version are you running? MSForms controls have a ...rather peculiar interface setup. IIRC there were PR's merged (relatively) recently to address this particular issue.

FWIW the object browser doesn't see `TextBox.SetFocus` either:

![image](https://cloud.githubusercontent.com/assets/5751684/25192095/f11a29c2-24ff-11e7-9e25-2addfeacdaf9.png)

The method is a member of `MSForms.Control`, which *should* be picked up as an interface implemented by `TextBox` - but there's something weird about how MSForms does its thing.

Please confirm your build version. @ThunderFrame do you get a repro with the current build?

**Comment by retailcoder** [comment]
Somewhat related: #2922

**Comment by A9G-Data-Droid** [comment]
@retailcoder I'm using RUBBERDUCK Version 2.0.13.32288
Excel VBA: Retail 7.1.1056
Forms3: 15.0.4737.100

I see what you are saying about TextBox.SetFocus but I do see .Clear under ListBox...
![listbox clear](https://cloud.githubusercontent.com/assets/26984068/25199433/b82f525e-24ff-11e7-87ae-b1d749082045.PNG)

**Comment by retailcoder** [comment]
Kudos to @ThunderFrame for identifying the actual issue here:

![image](https://user-images.githubusercontent.com/5751684/29905014-f3b64524-8dd9-11e7-8c9e-9d784fa9ef8b.png)

`MSForms` controls are shadowing `EXCEL` controls, and since the host application's type library takes precedence, the type annotation pass of the resolver was resolving e.g. `TextBox` to the `Excel.TextBox` type.

The fix involves annotating `MSForms` controls with the correct `AsTypeDeclaration` upon creation, and then preventing the type annotation pass from overwriting that.
