### ISSUE TITLE
Removing a module causes unrecoverable Parse Error.

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#3062]
Steps to reproduce.

1. New Workbook
2. Open VBE, allow auto-parse
3. Add module (either Standard or Class)
4. Allow the auto parse to complete
5. Remove the module without saving, using the PE context menu
6. Next parse results in Parse Error. The VBE isn't frozen, but the workbook must be closed and reopened for RD to recover.

**Comment by ThunderFrame** [comment]
Same symptom when removing a worksheet in the (Excel) host - which, presumably, is related to the removal of the underlying document-type module.

**Comment by retailcoder** [comment]
Must be related to the problem I'm having with re-importing a module after modifying attributes, and with how source control seems to break the parser: we're holding on to stale COM objects (`VBComponent`) too long. Is the Code Explorer ViewModel in your stack trace?

**Comment by MDoerner** [comment]
I cannot reproduce this with the with the current build, i.e. the build including my PR from yesterday. That PR removed a bug that the parser state was set to `ResolvedDeclarations` at the start of a reparse instead of `Pending`. Accordingly, the code explorer got refreshed, which is probably the origin of the problems.

**Comment by ThunderFrame** [comment]
hmm, I had pulled, but seems I may not have built successfully. Can't reproduce now. Treating as resolved/closed
