### ISSUE TITLE
CodeExplorer: only shows an empty window

### ISSUE THREAD

**Issue by FrankHentzschel** [rubberduck-vba/Rubberduck#3078]
The CodeExplorer, a very nice tool, since about 30 minutes only shows an empty window. 
I don't know the reason why.

I restarted Excel, I also destroyed the remaining Excel-Task with in the TaskManager. 
I deinstalled an reinstalled rubberduck, I restarted windows, but at the moment it dows not work!

At the moment also the TestExplorer does not do anything. There are existing tests and it worked before.

Does anyone have ideas about that problem?

Thanks in advance 

Frank

**Comment by MDoerner** [comment]
When clicking the refresh button in the command bar, do you get any kind of error?

**Comment by FrankHentzschel** [comment]
It did not change. BUt as far as I know, the problem occured then early binding for unit tests was activated.

**Comment by retailcoder** [comment]
That's RD loading its own type library and COM-reflecting the exposed members. That's a known issue, not sure why it works on some systems but not on others; remove the reference to Rubberduck.tlb and your project should parse again - you'll need to switch your existing tests to late-binding for them to he runnable then, and set the binding mode to "late-bound" in test settings so that RD doesn't add itself back as a project reference when tests execute.
