### ISSUE TITLE
Rubberduck crashes host when selecting very long procedure name

### ISSUE THREAD

**Issue by MDoerner** [rubberduck-vba/Rubberduck#3082]
To reproduce:

1. Add a new module.
2. Add a method whose name has a length of 255.
3. Refresh RD.
4. Select the method declaration.

![screenshot_20170620_012603](https://user-images.githubusercontent.com/22868956/27310063-f87c2084-5557-11e7-8b6a-842efb7e88b9.jpg)

It seems the caption is too long to legally be set to the `CommandBar`.

**Comment by BZngr** [comment]
I did some experimenting with this issue(...slow night...).  Hopefully what follows is new information:  

When a procedure is selected, the `Target.Caption` property is assigned a string value that is comprised of the procedure name prepended with the selection coordinates and the procedure's parent scope.  

The assigned value looks something like:  
"L39C20 | MyXlsFile.MyModuleName.MyReallyLongSubroutine...<lotsmorecharacters>...Name(procedure)"

So, the `Target.Caption` property does, in fact, accept 255 characters - But, 256 or more causes an exception.  In the case of a procedure, the 255 character limit appears to **_include_** the characters of the prepended information.  So, if you have a 255 (or nearly 255) character procedure name, it will always cause an exception because of the added selection and scope characters.

I'm not sure what to do with this information, but I'm hoping it provides a useful clue for those who understand the internals of RD better than I do.

**Comment by MDoerner** [comment]
I think we should truncate the procedure name as much as needed to make the whole string fit the 255 character limit.

Moreover, we might also want to drop the file name in case we hit the 255 character limit si ce file names can be very long. 

The result would look like `ModuleName.MyVeryLongProcedureN... (Procedure)`.

**Comment by BZngr** [comment]
To allow a 255 character procedure name allowed by VBA, everything including `ModuleName.` and `(procedure)` would need to be stripped.

**Comment by PeterMTaylor** [comment]
Just to check an assumption I thought when reading this. Is it dangerous to consider offering chopping/trimming/reducing to met the total length with ellipses as in "..." on the end?

**Comment by ThunderFrame** [comment]
I experienced the same issue when selecting an external identifier that was (the maximum) 255 characters.

e.g.

`x = [SomeReallyLongExternalIdentifier....ThatIs255CharactersLong]`

**Comment by MDoerner** [comment]
That is what I meant with _truncate the name_. We should drop the file name and then truncate the procedure name to make the whole string fit the limit. 

It will be truncated in the display anyway, unless you undock the command bar and stretch it over several screens.

**Comment by ThunderFrame** [comment]
@MDoerner Agreed - We can make best efforts to retain as much meaning as possible (eg. truncate the name, retain the type), but ultimately there should be a guard clause on the `CommandBarControl Caption` setter that limits the text to 255 characters. I wonder if the `TooltipText` is limited to the same 255 characters?

**Comment by retailcoder** [comment]
Ugh. What we need is a darn status bar in that IDE...
