### ISSUE TITLE
Flag Integer variables for update to Long

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#3084]
Unless they are used where mandated they should be a Long data type.

**Comment by retailcoder** [comment]
The `Integer` data type dates back from the golden days of 16-bit Windows. Since then, CPU's have been optimized to work with 32-bit integers - which is a `Long` in VBA. Moreover, in many languages `Integer` refers to a 32-bit integer, so its use could easily be accidental.

Let's have an inspection that finds all variables and members declared `As Integer`, and suggests to declare them `As Long` instead (`Declare` statements should be ignored).

Result text could be:

> {0} '{1}' is declared 'As Integer'

Where `{0}` is the declaration type (variable, function, property, etc.) and `{1}` is the identifier.

Meta:

> **Use of 16-bit integer type**
>
> The maximum value of a 16-bit signed integer is 32,767 - using a 32-bit (Long) integer data type where possible can help prevent 'Overflow' run-time errors, and is better handled by modern CPU's.

I think I'd go with "Hint" or "Suggestion" for the default severity level.

**Comment by Vogel612** [comment]
I'm not quite sure why this is declared 02? IIUC this only can recognize variables declared with the correct type and parameters. In either case it's an `IParseTreeInspection` that checks the `AsTypeDeclaration` for the `Integer` token, right??

**Comment by MDoerner** [comment]
As an alternative approach, one could implement an oridinary inspection that iterates over `AllUserDeclarations` filtering on `AsTypeName == "Integer"`. The quickfix could rewrite the corresponding `AsTypeContext`.

**Comment by rkapka** [comment]
I just wanted to say I'm working on this at the moment, so that we don't duplicate work :-)

**Comment by rkapka** [comment]
While working on the inspection, I found out that `AsTypeName` returns `Variant` for parameters/variables with typed identifiers (e.g. `Dim j%`). Fixing this to display the actual type would greatly help me implement this inspection and probably other inspections in the future.
I can look into this myself if someone points me in the right direction.

**Comment by Vogel612** [comment]
@rkapka IIUC the `AsTypeName` refers to the explicitly declared type in the `As [...]` clause. 

As such this behaviour is assuredly intentional. I do wonder whether VBA actually **uses** type-hints to find types, or the type is still only declared (and handled) as Variant, which would make the behaviour you desire actually incorrect...

**Comment by MDoerner** [comment]
@Vogel612 According to the [VBA specification](https://msdn.microsoft.com/en-us/library/dd361851.aspx), the _declared type_ of a variable declared in a _typed variable declaration_, i.e. using a _typed name_, i.e. an identifier with a type-hint, is always the type corresponding to the type-hint. Moreover, a _typed variable declaration_ does not allow an _as clause_. 

Only variables defined in an _untyped variable declarations_ (or not at all) can have the _declaration type_ `Variant` and then only if they are explicitly defined to in an _as clause_ or if the variable is implicitly typed and there is no matching _implicit definition directive_ (I seriously hope nobody uses those.) or one defining it to be of type `Variant`, which would be completely pointless.

**Comment by retailcoder** [comment]
Or dang, that's right - we're *still* not accounting for that `Def[Type]` crap.
