### ISSUE TITLE
Auto-Save removes focus from active editor

### ISSUE THREAD

**Issue by polaroidkidd** [rubberduck-vba/Rubberduck#3118]
1. Thank god you guys made this. It's truly a blessing

2. I've come to find that having the auto-save function enabled will move the focus away from the active editor. I'll be coding away when suddenly the cursor is gone from the editor window. I've only had this happen while the auto-save function is enabled.

**Comment by MDoerner** [comment]
Thank you for reporting this and thanks for the praise. 

This has already been reported in #2988. Because the way saving is achieved is not possible without loosing focus, there will be no auto-save anymore in the next release. For the time being, you should be able to deactivate it in the settings.

**Comment by shadowofsilicon** [comment]
What if the auto-save functionality was tied in with another aspect of the program?  I'm thinking maybe on the click of the Parsing/Ready button?  Auto-save wouldn't necessarily happen on a consistent basis, but it should be relatively frequent.
