### ISSUE TITLE
Code Explorer duplicates module names

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3121]
Code Explorer seems to be treating module nodes as having a signature:

![image](https://user-images.githubusercontent.com/5751684/28173863-c45f9b1e-67bd-11e7-9883-3c4d16120c72.png)

Gotta fix that.

**Comment by MDoerner** [comment]
I pinpointed since when this is broken:

The doubling started and the show signatures button ceased to work with commit 67e45787ae33a6d97fb16195db51347cd46218d4 (PR #3005), in which @Hosch250 removed the dependency on `System.Windows.Interactivity `.

**Comment by Hosch250** [comment]
Ah crap. That isn't supported anymore, and it was a bit of a pain to get it out of there. I hope there is a way to fix this without bringing that back.

**Comment by retailcoder** [comment]
*cough* or redoing the UserControl in WinForms ;-)

**Comment by MDoerner** [comment]
@Hosch250 What exactly do you mean with not supported? Is it just an issue with VS2017? 

I just reverted that specific commit and now everything seems to work properly again. This includes a number of additional issues: 

- Toggeling _Display signatures_ actually changes something, 
- _Find all References_ is not always deactivated in the context menu.
- _Find all Implementations_ is not always deactivated in the context menu.
- _Navigate_ is not always deactivated in the context menu.
- _Expand node and all child nodes_ and _Collapse node and all child nodes_ in the context menu works again as advertised. 

So, I would suggest to revert this commit for now. (It actually does not contain extensive changes.) That way we can release the next version of RD without a broken CodeExploerer. 

Then, after the release, we can have a look into how to remove the dependency on `System.Windows.Interactivity` without breaking most of the CodeExplorer. (The work in the commit will not be lost since we can revert the revert of the commit.)

**Comment by Hosch250** [comment]
It isn't supported anymore, and you can't get it with 2017+. Go ahead and revert it for now, but this will have to be the first thing I re-revert when I come back because I don't have 2015, and I can't get it anymore.

**Comment by Hosch250** [comment]
Basically, they don't package that library with VS 2017, so you can't build RD.

**Comment by retailcoder** [comment]
@Hosch250 I sent you a DropBox link to the VS2015 Community Edition installer, so you don't have to re-revert it. What do we need that dependency for anyway?

**Comment by Hosch250** [comment]
We use it to allow the VM to set whether a folder is selected.

**Comment by retailcoder** [comment]
ref. #3264
