### ISSUE TITLE
`Missing annotation` quick fix generates broken code

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#3166]
Access2010, Win7, RD 2.1.2003

![rd annotation inspection](https://user-images.githubusercontent.com/11889733/28675088-c86f55f8-72b4-11e7-8c90-a71ba82e6fed.PNG)

Starting code:

```Option Compare Database
Option Explicit
'@folder Utilities.Logger

Private Type TDebugLogger
    Name As String
    MinLevel As LogLevel
End Type
Private this As TDebugLogger

Implements ILogger

Public Function Create(ByVal loggerName As String, ByVal loggerMinLevel As LogLevel) As ILogger

    Dim result As New DebugLogger
    result.Name = loggerName
    result.MinLevel = loggerMinLevel
    Set Create = result

End Function
```

Clicking either `Fix` option yields this code:

```
Option Compare Database
Option Explicit
'@folder Utilities.Logger

Private Type TDebugLogger
    Name As String
    MinLevel As LogLevel
End Type
Private this As TDebugLogger

Implements ILogger

Public Function Create('@PredeclaredId
ByVal loggerName As String, ByVal loggerMinLevel As LogLevel) As ILogger

    Dim result As New DebugLogger
    result.Name = loggerName
    result.MinLevel = loggerMinLevel
    Set Create = result

End Function
```

**Comment by retailcoder** [comment]
Ugh. Looks lile the token positions are from the *attributes pass* parse tree... I don't think the unit tests can cover that... *back to drawing board* 😞

**Comment by MDoerner** [comment]
I think what the quickfix should dois the following:

If the attribute is a module attribute, it should put it at the atrt of the module, i.e. it search the parse tree from the code pane version of the module and act in the following way. 


1. If there is a folder annotation, find it and insert after the folder annotation.
2. If there are option statements, find the last one and insert after it.
3. Insert at the start of the module.

If it is a member annotation, the quickfix should search the parse tree of the code panel version for a context of the matching type with a matching identifier. Then it should insert the annotation above the corresponding declaration.

**Comment by Stevefb** [comment]
Similarly... another example of broken code:
![capture](https://user-images.githubusercontent.com/9349975/28992011-14405302-79d5-11e7-81cd-26fcfe5375b4.PNG)

Also 2 out of ~30 userforms suddenly attracted this 'opportunity'. The inspection does not go away after fixing, further the only changes to the code base that occurred prior to this Code inspection result appearing for me were:

1. change all `Dim x As y` **to** `Dim x As Word.y` _or_  `Dim x As VBA.y` _or_  `Dim x As MSForms.y` etc. 
2. decompiled the project using Orlando's tools (http://cpap.com.br/orlando/VBADecompilerMore.asp)

**Comment by retailcoder** [comment]
@Stevefb the inspection doesn't "go away", because the quickfix fails to do its job and add the annotation in the intended location. IOW the bug is with the quickfix, not the inspection. That's a tough one to write unit tests for, because the input code needs to include module attributes (from the *attributes pass*), but the quickfix needs to operate on the *code pane pass*, ...which doesn't include attributes - and the mock parser unit tests use don't hit the file system with temp files (for obvious reasons), instead it just parses whatever code we give it.

The quickfix needs to work off the *code pane pass* parse trees; looks like it's currently working off the *attributes pass* parse trees, hence the offset token positions. I think that one will have to be played by ear.

**Comment by retailcoder** [comment]
ref. 996a8b8e6fb81d09855b3467388c1d95de853c66

**Comment by retailcoder** [comment]
won't fix, feature dropped.
