### ISSUE TITLE
Code Explorer does not populate an empty Project

### ISSUE THREAD

**Issue by ghost** [rubberduck-vba/Rubberduck#3243]
The Code Explorer window does not populate the `CodeExplorerViewModel` with a `CodeExplorerProjectViewModel` if the referenced `VBProject` does not contain any `VBComponent`s.

Steps to reproduce:
1. Launch a clean instance of PowerPoint, then Rubberduck.
2. Do not parse the project.
3. Remove any empty modules.
4. Run a Parse.
5. Code Explorer will show no items in it's menu tree.
6. Add a empty module, reparse.
7. Code Explorer will show a Project -> Folder -> Module tree.
8. Remove the module, reparse.
9. Code Explorer will show a single Project item and the Folder and Module will be removed.

Expected Behavior:
1. Launch a clean instance of PowerPoint, then Rubberduck.
2. Do not parse the project
3. Remove any empty modules.
4. Parse
5. Code Explorer will show a single Project item without anything else.

**Comment by shadowofsilicon** [comment]
It looks like maybe the DeclarationFinder isn't recording empty projects or isn't returning empty projects when `CodeExplorerViewModel` gets the collection of `UserDeclarations`...?

**Comment by retailcoder** [comment]
I think it's more of a bad assumption in the VM code; declarations are regrouped by project and module... Possibly we're not even looking at actual project declarations.

**Comment by shadowofsilicon** [comment]
`RubberduckParserState.RefreshProjects` adds empty projects to it's collection.

The VM gets `AllUserDeclarations` from the `DeclarationFinder` the project isn't in there (it's empty, as it should have at least the project in it.)  Same results if I change it to `AllDeclarations`
`CodeExplorerViewModel.cs` line 260

**Comment by MDoerner** [comment]
The problem here is how the declaration resolver and the `ParseCoordinator` work. The projects present in the VBE play no direct role in what gets processed. If there is no component, the `ParseCoordinator` neither parses nor resolves anything. 

`ProjectDeclaration`s are only created as a byproduct of generating module declarations in the declaration resolver. Whenever it cannot find the declaration for a project of a module it creates the corresponding module declaration. 

So, fixing this issue would entail rewiring the parsing process  regarding the treatment of projects.

**Comment by ThunderFrame** [comment]
An empty project still has references, but they aren't resolved, because nothing uses them?

**Comment by shadowofsilicon** [comment]
At what level does the parsing process begin?  Does it iterate though all the components?

Doesn't seem like it would be too much effort to iterate though all the projects and create declarations for them first.  Does that sound like a viable strategy?
