### ISSUE TITLE
Code Explorer caches case insensitive component names

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#3334]
If I accidentally name a module `myUTilities`, then parse, then rename the module (in the properties window) to `myUtilities`, and reparse, the Code Explorer doesn't refresh the capitalization of the new name.

**Comment by bclothier** [comment]
Just to comment that the case-preserving behavior gets weird when you have names in different cases. For example, we get `.Value` with various libraries but in MSXML, it's `.value`. However, since MSXML comes in late, it all gets changed to `.Value` because, you know, ha-ha loser! 

Then there's the case where you have a control on a form named `FOO` and create a variable named `Dim Foo As String`, it'll change everything to `Foo`.... temporarily. Next time you load the module, it's back to `FOO`. Argh!

This behavior is not limited to just objects but also applies to module names, so I think it's worthwhile to ensure it is in fact changed, or you'll end up seeing conflicts between CE and what VBA editor thinks it is.

None of this is going to break the code but holy hell, does it get my eye twitching!

**Comment by retailcoder** [comment]
Ugh. Gotta love a case-insensitive language...

**Comment by MDoerner** [comment]
OK, this is stupid.

First, the behaviour persists between restarts of Excel. More precisely, if you insert a new module and change the case afterwards then restart Excel, the CE will still show the original name with the original case.

Second, it is not us who is the problem. The name the component interop object is returning does not change when you change the case of the component name in the VBE. To VBA it is exactly the same object. This seems to be similar to the stupid problem in Access that you cannot change the the cae of the name of a field in a table. You have to rename it to something els in between. Otherwise, it just gets autocorrected back.

**Comment by MDoerner** [comment]
Another piece of evidence that only the project explorer really knows about the rename:

If you did what I wrote und er second and then insert a new variable As your class, the VBE will autocorrect it to the original case. 

The way I see it now, it is more the project explorer which is wrong in showing the module name in the new case than us showing the original one which is enforced by the VBE inside the code panes.

**Comment by MDoerner** [comment]
I just found out that even IntalliSense provides the name in the original case.

**Comment by MDoerner** [comment]
Can we close this as status-by-design?  

We are following exactly the behaviour of the VBE's VBA engine, in contrast to the project explorer that is lying to the user. 

Alternatively, we would have to implement a double rename, i.e. rename to new module name with last character changed, then to new module name with the correct last character. Otherwise, the VBE's engine does not take up the new name and, hence, the new name is presented to us.

**Comment by bclothier** [comment]
Closing this as by-design.
