### ISSUE TITLE
Rubberduck for Excel on Mac

### ISSUE THREAD

**Issue by ashkaps** [rubberduck-vba/Rubberduck#3361]
Is it possible that I can use Rubberduck for excel on my Mac?
Can someone please guide me through the steps if available?
Thanks!

**Comment by retailcoder** [comment]
I don't have a Mac to test it, but I'll venture to say that *even if Mac-VBA supported IDE add-ins* (does it?), it couldn't work even if we wanted it to, because:

 - It's written in C#, compiled in .NET (not .NET Core), and *requires* the full-fledged framework. Rubberduck on a Mac is likely failing at the "run the installer" step, even assuming a Mac knows what to do with a `.msi` file.
 - COM components are registered in the Windows Registry. No such thing on a Mac AFAIK.
 - Win32 p/invoke: Rubberduck patches a lot of holes in the VBIDE API using Win32 functions that are located in system libraries that wouldn't exist on a Mac (e.g. `Kernel32.dll` and `User32.dll`).
 - File system differences: Rubberduck reads and writes files from the file system.
 - Altogether different IDE: not sure there's even an `IDTExtensibility2` entry point available to hook up add-ins. And if there is, I'm not sure the VBIDE API is even *available* on a Mac. Even if there's a VBIDE API that works on a Mac, I'm pretty sure the `CommandBar` API wouldn't; we have no way to add our custom menus anywhere if we can't get a handle on the IDE's main commandbar/menubar.

There are probably a ton of other reasons why it simply can't work, but these alone should make a solid case against it.

**Comment by ashkaps** [comment]
Okay. That makes it clear. So any idea if you can help me, are there other tools like rubberduck that i can use on Mac?

**Comment by retailcoder** [comment]
I don't think any VBE add-in comes anywhere close to offer half of Rubberduck's functionality, but if even the closest thing (MZ-Tools) doesn't run on a Mac, IMO that pretty much seals it: VBE extensibility on a Mac is a hopeless venture.

**Comment by retailcoder** [comment]
FYI I asked on the [*Bringing back visual basic IDE to Office for Mac*](https://answers.microsoft.com/en-us/msoffice/forum/all/bringing-back-visual-basic-ide-to-office-for-mac/d634d60b-3fd8-4389-a13e-2abdeb24b454?rtAction=1504815523810) discussion thread on answers.microsoft.com, to see if there was any way to extend the Mac VBE.

**Comment by ThunderFrame** [comment]
VBA in Excel for Mac 2016, already has a severely hampered VBA editor - see [Bring back a fully functional VBE (Visual Basic Editor for VBA)](https://excel.uservoice.com/forums/304933-excel-for-mac/suggestions/9098431-bring-back-a-fully-functional-vbe-visual-basic-ed).

But even before that, Office for mac never had the ability to use COM add-ins, nor to use nearly as many ActiveX controls as Windows, not the ability to call as many DLLs. The only way to have something "like" Rubberduck on a Mac, would be to write the entire thing in VBA.

Currently, the best VBA experience on a Mac involves a virtual PC and a Windows instance.

**Comment by retailcoder** [comment]
@ThunderFrame IDK, maybe there could be an extensibility point accessible with some clever Objective-C code. I doubt it, but there's nothing like asking :smiley:
