### ISSUE TITLE
Mid statement is incorrectly identified as a Function in VBA library (in the Strings module)

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#3377]
While having the same appearance with regard to their names and parameters, the `Mid` statement is part of the `VBA` language, while the `Mid` function is (after aliasing) a function in the `VBA` type library.

RD should be able to add a `SubroutineDeclaration` for `Mid`, and then make the distinction between a statement call and a function call, and therefore correctly resolve usages of `Mid` as a Statement or Function respectively.

**Comment by MDoerner** [comment]
I do not see the issue here. 
I used the following code to test the reolution of the Mid statement and the Mid function.
```vba
Public Sub MidTest()
    Dim str As String
    str = "some string"
    
    Dim target As String
    target = Mid(str, 6)
    Debug.Print target
    target = Mid(str, 6, 3)
    Debug.Print target
    
    Dim toReplaceWith As String
    toReplaceWith = "1234"
    Mid(str, 6, 3) = toReplaceWith
    Debug.Print str
    Mid(str, 6) = toReplaceWith
    Debug.Print str
End Sub
```

The first two resolve to the `Mid` function and the last two do not resolve to anything, as expected for keywords in a statement.

So, the resolution is correct now. The other part of the request, adding a subroutine declarations for the statement) is covered in the linked issue.
