### ISSUE TITLE
Consider replacing listeners with visitors where appropriate

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#3383]
Up to now, whenever a parse tree traversal was needed, the code will use a listener rather than a visitor.

This has few points to consider:

1) currently, a walker is not cancellable but a visitor can be made to be cancellable
2) most of time, we use listeners to return a result which requires us to build a listener and then add state to it. Visitors on the other hand already will return a result by default and thus need to not contain any state which leads to...
3) a visitor template would make it easy to build more idiomatic expression of what we are doing normally when analyzing the parse tree. For example:

a) pre-traversal validations
b) traverse and collect all contexts relevant to an inspection/quickfix/whatever
c) post-traversal validations & processing

The final results can be then sent to the Rewriter in more uniform pattern which hopefully makes it easier to refactor and develop the components where tree traversals are involved.

Thoughts? Crazy idea? :)

**Comment by Vogel612** [comment]
I don't quite see what point you're trying to make here... 

1. It's not like the walker can't be made cancellable with little effort. The ANTLR team have been so nice to declare the `Walk` method on ParseTreeWalker as `virtual`, which makes it easy to overwrite.

2. That's not **quite** correct. You can't expect a visitor to return an aggregated result (like some listeners do) without introducing state in the visitor. What's more: visitors are inherently stateful and context aware. 

3. Listeners already provide a cohesive interface for **exactly that**. They all derive from an auto-generated abstract class which has methods for each available context in the grammar. There's an `OnEnter` and an `OnLeave` for each context, which knocks out pre- and post-traversal.  
Additionally there's `VisitErrorNode` and `VisitTerminalNode`.

Last but not least using Listeners has a tremendous advantage over visitors:

We can combine **all listeners at once** into a `CombinedParseTreeListener` (see `Rubberduck.Parsing.VBA.CombinedParseTreeListener`) because these Listeners follow a unified interface and are **passive** instead of *active** like a visitor.
This allows us to minimize the number of walks across the parse tree. 

We can not do that with visitors, because they are **active** components. They walk the tree themselves, which cannot be put in a unified interface (or a unified parse tree walk)

**Comment by bclothier** [comment]
Thanks, @Vogel612  for those points. That helps me understand the architecture a bit more now.

1. That's true, and that was what one of ANTLR member suggested to @retailcoder  before. However, it means copying the base implementation and then adding the cancellation logic. Something I wasn't too thrilled because if they change the method, we have to update it again. I do not think this is easily done by calling `base.Walk()`; it must be re-implemented.

2. Maybe that's not the best wording I could have used. What I did not like about listeners was that from what I saw, people would add new fields or stuff to the listeners to collect the state. A visitor, OTOH, can take the "shape" of the state, then we focus on updating it as we visit the node. 

3. I'm not sure this carries any weight --- listeners themselves derive from a similar base and already has all the methods similar to listener (albeit instead of `OnEnter`/`OnLeave`, it's `VisitXXX` but they are still there to be derived. 

That said -- the last point is probably the most powerful one, though. We definitely don't want to have unnecessary walks during the parse. That might be enough to end the discussion right there.

Just one more question - does it matter whether for the purposes of reacting to a user's selection, that we use a listener also or would we be better off with a visitor in that context?

**Comment by retailcoder** [comment]
I don't see anything wrong with using listeners for inspections (single, full traversal of every module), and visitors for refactorings (custom/partial traversal of specific modules, usually a single one) and the quick-fixes that might need it - or whatever is the best tool for the purpose.

`ParseTreeInspection` walks *don't* need to be cancelled; inspections need to look at everything, everywhere. Actually I'm pretty sure *one* inspection throwing a wrench in the walker's walk wouldn't mean anything good for the other inspections.

Refactorings are a different beast entirely: they have very specific needs, a listener / full traversal is usually overkill, since they need to work with a subset of the parse trees.
