### ISSUE TITLE
Unhandled Exception on Parse

### ISSUE THREAD

**Issue by CHR-IS-B** [rubberduck-vba/Rubberduck#3384]
I had an unhandled exception occur when parsing a project.  Here's the details:

**What led to the unhandled exception:**
1.  Rubberduck alerted me to the  parse error above.
2.  I deleted all text in moduled `mFreezePanesNoSplit` and reparsed.  Still got the same parse error.
3.  I renamed the module from `mFreezePanesNoSplit` to `mFreezePanesNoSplitTER` and reparsed.  Still got the same parse error.
4.  I deleted the module `mFreezePanesNoSplitTER`.  On reparsing, got the unhandled exception below.
5.  The exception is thrown again when reparsing or when closing Excel files.  I assume RD automatically reparses when an open file is closed.

**After closing and re-opening Excel, I could NOT reproduce this error.**

**Rubberduck Version:**	
2.1.0.2232

**Parse error details:**
	Member: mFreezePanesNoSplitTER
	Type: Module
	Location: L2C1
	Context: extraneous input 'rivate' expecting {<EOF>, ":", ATTRIBUTE, BEGIN, CONST, DECLARE...... **[Yes, it was 'rivate' not 'Private'.]**

**Details of the unhandled exception:**

	Unhandled exception has occurred in a component in your application. If you click Continue, the application will ignore this error and attempt to continue.

	System Error &H80070006 (-2147024890).   The handle is invalid. .
	&Details
	&Continue
	See the end of this message for details on invoking 
	just-in-time (JIT) debugging instead of this dialog box.

	************** Exception Text **************
	System.Runtime.InteropServices.COMException (0x80070006): System Error &H80070006 (-2147024890).   The handle is invalid. 
	   at Microsoft.Vbe.Interop._VBComponent.get_Name()
	   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBComponent.get_Name() in C:\projects\rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBComponent.cs:line 25
	   at Rubberduck.UI.Command.ShowParserErrorsCommand.<>c__DisplayClass9_1.<FindModuleDeclaration>b__1(Declaration item) in C:\projects\rubberduck\RetailCoder.VBE\UI\Command\ShowParserErrorsCommand.cs:line 118
	   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
	   at Rubberduck.UI.Command.ShowParserErrorsCommand.FindModuleDeclaration(IVBComponent component) in C:\projects\rubberduck\RetailCoder.VBE\UI\Command\ShowParserErrorsCommand.cs:line 117
	   at Rubberduck.UI.Command.ShowParserErrorsCommand.<CreateViewModel>b__8_0(Tuple`2 error) in C:\projects\rubberduck\RetailCoder.VBE\UI\Command\ShowParserErrorsCommand.cs:line 99
	   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
	   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
	   at Rubberduck.UI.Command.ShowParserErrorsCommand.CreateViewModel() in C:\projects\rubberduck\RetailCoder.VBE\UI\Command\ShowParserErrorsCommand.cs:line 103
	   at Rubberduck.UI.Command.ShowParserErrorsCommand.UpdateTab() in C:\projects\rubberduck\RetailCoder.VBE\UI\Command\ShowParserErrorsCommand.cs:line 56
	   at Rubberduck.UI.Command.MenuItems.UiDispatcher.<>c__DisplayClass5_0.<InvokeAsync>b__0(Object x) in C:\projects\rubberduck\RetailCoder.VBE\UI\Command\MenuItems\UiDispatcher.cs:line 29

<sub>edit @Vogel612: removed loaded assemblies from debug information</sub>

**Code in module** `mFreezePanesNoSplit` **identified by the parse error:**

```
Option Explicit

Public Sub FreezePanesNoSplit(ByVal freezeOn As Boolean, ByVal ws As Worksheet, Optional ByVal rowNum As Long, Optional ByVal columnNum As Long)
    '=======================================================================
    '  NAME:         FREEZE PANES  (Procedure)
    '
    '  DESCRIPTION:  Freezes panes in the specified worksheet and at the
    '                 specified cell.
    '
    '  AUTHOR:       Chris Brackett
    '  CREATED:      2017-08-22
    '=======================================================================
    
    Dim errorDescription As String
    
    ' Validate Passed Parameters
    If rowNum < 0 Or columnNum < 0 Then
        errorDescription = "Row and column parameters must greater than or equal to zero."
    ElseIf rowNum = 0 And columnNum = 0 Then errorDescription = "Both row and column parameters are zero.  At least one must be a positive number."
    ElseIf rowNum >= 512 Then errorDescription = "Row paramater of " & Format(rowNum, "#,###") & " must be less than the 512."
    ElseIf columnNum >= 512 Then errorDescription = "Column paramater of " & Format(columnNum, "#,###") & " must be less than 512."
    ElseIf rowNum = 0 And columnNum = 0 Then errorDescription = "Both the column and row paramaters are set to zero.  At least one must be greater than zero."
    End If
    

    ' Validate Parameters
    If errorDescription <> vbNullString Then
        ' Parameters failed validation.  Throw ERROR and exit.
        Err.Raise vbObjectError + 15401, , "FreezePanes Procedure: " & errorDescription ' Throw custom error.
        Exit Sub
        ' #################### END ####################
    End If
    
    
    ' Parameters Validated
    ws.Activate                                  ' Activate the window to be worked on.
    
    If freezeOn = True Then
        ' Freezeparamater set to TRUE.  Freeze panes.
        With ActiveWindow
            .FreezePanes = False
            .Split = False
        End With
        With ActiveWindow
            If columnNum > 0 Then .SplitColumn = columnNum
            If rowNum > 0 Then .SplitRow = rowNum
            .FreezePanes = True
        End With
    Else
        ' Freezeparamater set to FALSE.  Unfreeze panes.
        With ActiveWindow
            ActiveWindow.FreezePanes = False
            ActiveWindow.Split = False
        End With
    End If
End Sub
```

**Comment by retailcoder** [comment]
> I renamed the module from mFreezePanesNoSplit to mFreezePanesNoSplitTER and reparsed.

I think this is what took Rubberduck by surprise - you couldn't have renamed the module through Rubberduck:

![image](https://user-images.githubusercontent.com/5751684/30674103-b8089b04-9e45-11e7-9690-610e4780f0ef.png)

When we're in an error state, we discard the parse tree and abort everything: without *every module's* parse tree, i.e. with only a partial understanding of the code, Rubberduck would at best pop a bunch of inspection false positives, at worst completely wreck the code by running a refactor/rename operation and editing the tokens at the wrong code pane positions. So we disable everything (hopefully) that can modify the code, and don't bother running the inspections (we disable the quickfixes, but really we should invalidate/disable the whole content of that toolwindow).

By renaming a module directly through the *Properties* toolwindow, Rubberduck detects the renamed component and tries to reparse, but the error is still there, so we remain in an error state. The state of the UI at that point is ..interesting:

![image](https://user-images.githubusercontent.com/5751684/30674441-1a913518-9e48-11e7-98a3-1708ca6c46e0.png)

Should you double-click on the "search result" item, you navigate somewhere between 1 and 9 lines under where you'd expect to end up: that's because the parse exception originated in the *attributes pass*, where Rubberduck exports the module and processes the text file with its module and member attributes - the parse tree contains tokens that the code pane isn't showing, that's why things are off (we need to "fix" that).

When you then delete the module, you get a persistent `COMException` in `VBComponentClass.get_Name()` from the `ShowParserErrorsCommand`, that keeps coming back no matter how you attempt to reparse - Rubberduck is essentially bricked at that point, it's stuck in a parser error state, with most commands disabled and an unhandled `COMException`.

Assuming `Option Explicit`, renaming a module without involving Rubberduck leads to this:

!["Compile error: variable not defined"](https://user-images.githubusercontent.com/5751684/30674809-978c31a6-9e4a-11e7-9dc7-c6cb6dd3c46d.png)

...which is interesting: we should have an error-level inspection for undeclared variables in modules that have `Option Explicit` specified.

When renaming a module via the IDE's UI, Rubberduck should prompt whether to apply a *rename* refactoring, to propagate the change throughout the code.

![image](https://user-images.githubusercontent.com/5751684/30674942-7e241cc8-9e4b-11e7-8c1d-4d50ecb01b34.png)

Of course this could only work in a `Ready` state though. For now, Rubberduck assumes it's working against legal, compilable code. We still need to gracefully handle that exception (prevent it, actually: looks like a "ghost" of the removed module with the wrong name is lingering around).

Once we have a better grip on what happens in the code panes, we'll be able to unleash Antlr and put an end to the bail-out error-handling strategy, and do [much] better. In the meantime users need to mind parser errors: they're typically *compile errors* too, so fixing them as soon as possible, before anything else, is a good idea 😉

**Comment by retailcoder** [comment]
I can't reproduce the parser error with the code you supplied. It's possible Rubberduck didn't shut down correctly, and you have one or more EXCEL.EXE processes sleeping in *Task Manager* - these *can*, and *do* interfere with Rubberduck.

**Comment by MDoerner** [comment]
As @retailcoder already mentioned, the reported location is off because it is the location in the exported file, which always has some attributes and stuff at the start, and we are not offsetting the reported location to fit the code pane position. SO, since the location of the parser error is L2C1, the error actually happened above what you can see in the code pane. However, I do not really know what happened there without seeing the exported file.

The reason for the COM exception, is that the `ShowParserErrorsCommand` uses and caches the `VBComponent` with the error which is no longer there. It really should not do that. We have to make it use QMNs, which buffer all information needed.

**Comment by retailcoder** [comment]
Linking #3385

**Comment by MDoerner** [comment]
Following the procedure outlined, I cannot reproduce the error with the current version. Moreover, the proposed changes to the `ShowParserErrorsCommand` have been incorporated. 

If this error comes up again, please reopen this issue.
