### ISSUE TITLE
Rename Refactoring leads to non recoverable parse error

### ISSUE THREAD

**Issue by SteveLaycock** [rubberduck-vba/Rubberduck#3431]
I've been using Rubber Duck to do a significant amount of renaming.  I'm finding that after a short number of renames the reparsing of the code comes up with a reparse error.  This error cannot be cleared by manually reparsing.

The code is clean as VBA recompiles it without any compilation errors

After restarting word, Rubberduck completesthe first code analysis without any issues. 

This problem has been evident for all versions uploaded over the past few weeks.

**Comment by MDoerner** [comment]
Thanks for reporting this.

By any chance, did your renaming include a module or any other component?

We have a known issue that the parser error dialog caches the component with an error, which turns out to be a problem if the component does not exist anymore. Then we end up with an unexpected exception that stops the parsing process. 

Unfortunately, we have not gotten around to fix this,  yet.

**Comment by SteveLaycock** [comment]
The renaming involves function names and variables/constants at function and module level.  I'm not renaming modules or classes.

**Comment by SteveLaycock** [comment]
Just testing 2.1.1.450 and code now parses again.

But the impressive thing is how quick this is compared to previously.

**Comment by Vogel612** [comment]
Tentatively fixed
