### ISSUE TITLE
Not needed test: type member 'wYear' is declared as Integer

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#3495]
Hint: User-Defined type member 'wYear' is declared as Integer - (XLTest163a.xlsm) XLTest.FindFileInfos, line 72

That is intentional:
Private Type SYSTEMTIME
   wYear As Integer
   etc

**Comment by Vogel612** [comment]
Not sure what this issue intends to achieve... If that's intentional, you should either ignore the Inspection for this declaration or change it's severity to `DoNotShow` in the settings to never be warned about inefficient declarations again :)

**Comment by retailcoder** [comment]
16-bit integers are warranted in some Win32 API dll imports, otherwise a 32-bit integer should typically be used in place of a 16-bit integer, in a vast majority of situations, especially when Excel object model is involved, notably for anything that means to represent a row number. Modern CPUs are optimized for 32-bit integer processing.

Also:

> Traditionally, VBA programmers have used integers to hold small numbers, because they required less memory. In recent versions, however, VBA converts all integer values to type Long, even if they're declared as type Integer. So there's no longer a performance advantage to using Integer variables; in fact, Long variables may be slightly faster because VBA does not have to convert them.

https://msdn.microsoft.com/en-us/library/office/aa164506(v=office.10).aspx

This inspection is working as intended.

**Comment by SystemsModelling** [comment]
Yes, I see it is intended in the vast majority of situations. Where I know that I really need that data structure,  I should add an ignore comment.
