### ISSUE TITLE
ShadowedDeclarationInspection does not see all shadowing directions

### ISSUE THREAD

**Issue by MDoerner** [rubberduck-vba/Rubberduck#3508]
Currently, the `ShadowedDeclarationInspection` does not recognize all situations where which declaration shadows which other declaration depends on where you try to reference them.

As an example, it recognizes that a public sub in a standard module with the same name as the enclosing project shadows the project inside this module. However, it does not recognize that the project shadows the procedure everywhere else.

I have not yet looked at all other constallations where such two-way shadowing is possible, so there might be more cases where inspections results are missing.

**Comment by rkapka** [comment]
@MDoerner Please take a look at my comment from September 6 in #3252. Since no one objected to what I wrote, I assumed it's OK to leave it like this.

I have to admit that it makes sense for a project to shadow a procedure. When accessing a procedure from another module, it is not possible to invoke it because the project shadowes the procedure (within one module, procedure takes preference). However, when the project is a referenced project, an inspection stating that the referenced project shadows the procedure doesn't make much sense to me, because the user cannot rename the referenced project, and I think that's the goal of the inspection - 'A hides B, so rename A'. I believe there are more nuances like this.

**Comment by MDoerner** [comment]
@rkapka I have not read those comments in the PR before. Thanks for pointing me to them

Please note that my example above does not refer to a referenced project but the project containing the procedure with the same name. 
I have tested that this compiles fine indeed. Outside the module, trying to reference the procedure unqualified leads to a rather uninstructive compile time error.

**Comment by rkapka** [comment]
I gave this some thought and I don't think I agree that the inspection does not work correctly when looking at its basic assumption. The most important thing to keep in mind is that currently the inspection does not look at declaration references - it only checks the declaration definitions. Because of this, if we have a project and a procedure with the same name, there can be only one direction of shadowing between the two. I assumed that a project is more "important" than a procedure, so the latter is shadowing the former. To fix the problem, the inspection would need to be much smarter than it currently is.

**Comment by MDoerner** [comment]
I think we have a different understanding of what _shadowing_ means. To me a declaration `A` _shadows_ a declaration `B` whenerver there is a context in which an identifier would resolve to declaration `A` but would resolve to `B` if `A` did not exist. So, _shadowing_ can go both ways if there are different contexts where the resolution rules are reversed.

I agree that using this definition, the problem of determining whether a a declaration shodows another is hard, since VBA has rather complicated resolution rules. It does not help that VBA infers context at a lot of places, like the module a public procedure is contained in.

**Comment by rkapka** [comment]
I agree that your definition is more reasonable. However, just as you say, implementing this definition will need a lot of work. I propose to close this issue and open a new one that describes the problem. We can also change the name of the current inspection.
