### ISSUE TITLE
Refactor menu missing item

### ISSUE THREAD

**Issue by BluejacketScott** [rubberduck-vba/Rubberduck#3509]
It's missing the Extract Method item but the keyboard shortcut still works.  It would be exceedingly better if a dialog would open asking for the method name and access modifiers though.  Thanks!

**Comment by retailcoder** [comment]
*Extract Method* is currently undergoing a full rewrite. I promise it will bring up a UI that lets you:

 - Name the extracted method
 - Pick a possible return value
 - Preview the extracted method
 - Cancel the method extraction, or confirm and proceed

**Comment by bclothier** [comment]
Note that the current (and broken) implementation does not show an UI at all. You can see the list of current issues [here](https://github.com/rubberduck-vba/Rubberduck/projects/2); they all are showing as ToDo ATM due to the fact that we're completely rewriting, so it's hoped that all will get addressed collectively.

**Comment by retailcoder** [comment]
Let's remove the menu item and not hook up its hotkeys in non-debug builds.

**Comment by bclothier** [comment]
@Vogel612 assign to me and add to epic.

**Comment by daFreeMan** [comment]
Strikes me that this should be closed since the `Extract Method` is, well, defunct and not likely to see a resurrection any time soon.
