### ISSUE TITLE
Load failure is too silent

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#3563]
The current behavior when Rubberduck fails to load is that the RD menus and windows simply don't appear. The error are logged just peachy. Nonetheless, this makes for a confusing user experience because they've already seen the splash form and thus naturally assume/expect RD to be loaded. 

I'd suggest that when RD does fail to load, the user should be at least alerted to the fact, and perhaps helpfully linked to the log so that the user is aware that something went wrong and can take action.

**Comment by retailcoder** [comment]
That is *not* by design. Failure to initialize is intended to go through this path:

            catch (Exception exception)
            {
                _logger.Fatal(exception);
                System.Windows.Forms.MessageBox.Show(exception.ToString(), RubberduckUI.RubberduckLoadFailure,
                    MessageBoxButtons.OK, MessageBoxIcon.Error);
            }

[This line](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/Extension.cs#L224) seems suspicious:

            catch (Exception e)
            {
                _logger.Log(LogLevel.Fatal, e, "Startup sequence threw an unexpected exception.");
                //throw; // <<~ uncomment to crash the process
            }

That commented-out rethrow is actually *preventing* the exception from bubbling up to the intended `catch` scope which shows the message box.

**Comment by MDoerner** [comment]
Just to mention it, because of the first exception handler in the post above, the comment in the commented out code is a complete lie: uncommentiong does **not** crash the process. This has already been rather confusing and annoying when porting to CW. (I really wanted to see where it crashes in the debugger.)
