### ISSUE TITLE
"Procedure not used" is a problem for native interface implementations

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#357]
Almost identical to the `VariableNotUsedInspection` is a `ProcedureNotUsedInspection` which is useful for finding dead code. However there are native handlers in VBA code that aren't meant to be called by user code, like worksheet events `Worksheet_Activate` and `Class_Activate` and `Class_Terminate` class members.

Ignoring methods that have an underscore in their name would be dumb... but what other way is there? Hard-coding every event in the Office object model doesn't seem to be a good solution either.

Brainstorm time!

**Comment by ckuhn203** [comment]
Interesting question. As I see it, we have two closely related problems here. One is easier to solve than the other. So, the easier to solve problem first.

# Field Variables With Events

Any time a variable is declared `With Events`, we can use its name to find the routines that handle its events by looking for `"identifier" & "_"` in a subroutine's signature and assume they are used.

    Private WithEvents foo As UserForm
     
    Private Sub foo_OnLoad()
          ' assume this used
    End Sub

*SideNote:* Since we'll need to find these event routines anyway, let's add an inspection that reports back any event routines that are `Public` or `Friend` scoped.

If you wanted to get *really* fancy (and perhaps over complicated), you could look at [the event declarations](https://msdn.microsoft.com/en-us/library/ee200325.aspx) of custom defined classes to ensure that the event does indeed exist.

# Life Cycle Handler Declarations

Life Cycle Handlers should be easy enough to filter out. [There's only two of them](https://msdn.microsoft.com/en-us/library/ee199474.aspx).

1. `Class_Initialize`
2. `Class_Terminate`

Heck, we could almost add them directly to the grammar itself if we wanted to. In fact, they're part of the ABNF grammar I just linked to.

# Object Model Events

This one is ***tough***. I'm not sure what a good approach would be here. Mostly because of the tight dependency on the Host Application. There's also the sheer number of events in each Host App's object module. In some ways they're very similar to the Life Cycle Handlers, but I know of no comprehensive list (that isn't scattered across hundreds of different docs) and we would need to check the host app's type to say what is and isn't an event procedure for any given module.

I think this discussion will revolve around this particular issue.

**Comment by retailcoder** [comment]
Excellent points.

`WithEvents` needs to be addressed in a way similar to #347 - by locating the `WithEvents` declaration and either assuming any method starting with `ThatIdentifier_` is an implementation of that event provider interface, *or* by locating the declaration of the `WithEvents` *type* and finding its public members - from there we can infer the actual method names, but then there's an issue if the class is declared in another project that's protected - and that's likely to happen.

I think the safest (and easiest) way would be to grab the `Something` in `Private WithEvents Something As MyEventProvider`, and make the assumption that any member named `Something_*` is a member of `MyEventProvider`.

I have no real issue with hard-coding `Class_Initialize` and `Class_Terminate`, especially if they're part of the official language grammar.

---

So the only real problem that remains is object model events. Perhaps a hybrid between hard-coding the host object model and assuming what the members are?

The object model events can only be handled in `Document` type objects - in Excel that's a `Workbook` or a `Worksheet`: how about we pretend there's an implicit `Private WithEvents Workbook As Workbook` in any `Workbook` document, and apply the assumptions above (i.e. any `Workbook_*` method is a member of that implicit `Workbook` event provider)?

The same logic could apply to `UserForm` type objects - if we pretend there's an implicit `Private WithEvents UserForm As UserForm` in every `UserForm` module, we can then assume that any `UserForm_*` method is a member of that implicit `UserForm` event provider.

How's that?

**Comment by retailcoder** [comment]
The new problem now, would be *how do we "pretend" there's an implicit `WithEvents` field in these modules*...

**Comment by ckuhn203** [comment]
Well... here are some things to look for in Access that are like `Workbook_*` and `Worksheet_*`

 * `Form_*`
 * `Report_*`

But only if it was that easy... Consider this button click handler for a button named `cmdInstaller`.
  
    Private Sub cmdInstaller_Click()
        
What the heck would we do with that?

**Comment by retailcoder** [comment]
do we have programmatic access to a form's `Controls` collection from the VBE API? .........ugh.

**Comment by retailcoder** [comment]
Yes we do. Through the `Controls` collection of the `Designer` property of the `VBComponent`. Awesome.

**Comment by retailcoder** [comment]
Well, there's another problem. There's no easy way of knowing the *name of the type* of a `Document` component - telling a `Workbook` from a `Worksheet` is much harder than it appears to be... but then in our case we also need to tell a `Workbook` (Excel) from a `Document` (Word) and a `Report` (Access), a `Presentation` (PowerPoint) or a `Session` (Outlook)... and who knows what else.

I think we're going to have to assume that no one in their right minds would ever create a method starting with `Workbook_*` in a worksheet or report code module, so we can "reserve" a number of known document component method prefixes and call it a day (e.g. `Workbook_`, `Worksheet_`, `Document_`, `Report_`, `Form_`, ...any others?).

**Comment by ckuhn203** [comment]
Access is actually pretty easy. All form component names are in the form of `Form_[formName]`. Likewise with reports. If have to confirm it, but I'm pretty sure trying to rename them outside of that default format actually breaks Access.

**Comment by ckuhn203** [comment]
@retailcoder  you closed this, but what was the result? Status-declined? Just don't want to get confused 6 months down the road..

**Comment by retailcoder** [comment]
You're right, it shouldn't be closed yet.

**Comment by Hosch250** [comment]
What's up with this?  Does the COM collector make this obsolete?

**Comment by retailcoder** [comment]
@Hosch250 completely
