### ISSUE TITLE
Quickfix unavailable for inspection Implicit Reference to ActiveSheet

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#3570]
Quickfix unavailable:

![quick](https://user-images.githubusercontent.com/16574009/33235322-23fb2eb2-d28a-11e7-8602-6143e2553a04.png)

**Comment by retailcoder** [comment]
`ImplicitContainingSheetInspection` offers a "Qualify with `Me.`" quick-fix, but the inspection flagging implicit refs to `ActiveSheet` has no quick-fix available other than ignore once/in module; this appears to be by design, since making `ActiveSheet` calls explicit aren't actually making the code any better.. just more verbose.
