### ISSUE TITLE
Unit tests raise error on Excel 2013 with Japanese language

### ISSUE THREAD

**Issue by kamokj** [rubberduck-vba/Rubberduck#3607]
I installed Rubberduck 2.1.1 on Windows 10 64bit, and run unit tests on Excel 2013 with Japanese language.

After adding test module and test method, I ran All Tests from Test Explorer, but encountered following error.
![image](https://user-images.githubusercontent.com/34459265/33913840-d3b15c6c-dfde-11e7-972f-19958c18b3ee.png)
The message says a file "C:\Users\kamo\Documents\Book1.xlsm - [TestModule1 (コード)].xlsx" was not found. ("C:\Users\kamo\Documents\Book1.xlsm" is a file which contains the test module.)
After restarting PC, I encountered the same error.

Following is the method I used.
```
'@TestMethod
Public Sub TestMethod1() 'TODO Rename test
    On Error GoTo TestFail
    
    Assert.IsTrue 1 = 1

TestExit:
    Exit Sub
TestFail:
    Assert.Fail "Test raised an error: #" & Err.Number & " - " & Err.Description
End Sub
```

I'm not sure that the problem is language, but I suppose it is one of possibilities.

**Comment by Vogel612** [comment]
Wow that's cool. I think the Japanese localization we had was dropped half a year ago, because it wasn't maintained... Maybe there's some stuff still around that messes with us here....

Do you perchance have your computer set to Japanese regional settings? Otherwise that wouldn't make a lot of sense...

**Comment by retailcoder** [comment]
Looks like the test engine went to the fallback method that uses the mainwindow caption to figure out the name of the module - IIRC the logs would have the exception details here. Got logging enabled?

**Comment by kamokj** [comment]
@Vogel612 Yes, a default setting of my PC is Japan region. But, I changed only display language of Windows to English. (time zone and country setting is Japan region)

**Comment by kamokj** [comment]
@retailcoder I got the log after I set the log level to Trace.
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/1555157/RubberduckLog.txt)

**Comment by MDoerner** [comment]
This should have been fixed since we switched abandoned using `Application.Run` to run code.

I tested with Japanese characters on a system with English language settings. 

If this still persists with Japanese language settings please reopen this issue. (My Japanese is not good enough yet to change to Japanese language settings on my system.)
