### ISSUE TITLE
Variable is used but not assigned inspection fires multiple times with `With` block

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#3636]
This code triggers the inspection 4 times, with all 4 inspections referring to the `wb`  in `With wb` location;

```vb
Sub test()
    Dim wb As Workbook
    With wb             'Variable wb is used but not assigned
      Debug.Print .Name
      Debug.Print .Name
      Debug.Print .Name
    End With
End Sub
```

I'd argue that the inpsection should only fire once, for the above code block, as the member calls are actually against the temorary variable created by the With block, rather than against the `wb` variable.

Also, in my build, the quickfix for all occurrences in module throws an error.

**Comment by comintern** [comment]
Duplicates are an easy fix (PR inbound).  The BTW "quickfix for all occurrences in module throws an error" appears to be due to the selection logic in the `GetQualifiedMemberName` ([here](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.CodeAnalysis/Inspections/Results/IdentifierReferenceInspectionResult.cs#L25)).

This asserts on the "in procedure" quick-fix also. The problem seems to simply be that there are multiple matching enclosures.
