### ISSUE TITLE
Fortify on Demand vulnerability scan

### ISSUE THREAD

**Issue by SadPraetor** [rubberduck-vba/Rubberduck#3754]
I'm trying to get permission to get this COM addin approved in company where I work. They require vulnerability scan by "Fortify on Demand". This scan requires to fill information about Technology Stack and Language level
I filled .NET and 4.5
The scan is rejected with reason: "Missing PDB/DLL files, Notes: .Net payloads must contain dlls and pdb files". I'm uploading .zip file "Rubberduck-Rubberduck-v2.1.2.2827"
Any advice how to approach this?

thank you

![rubberduckfortifyondemand](https://user-images.githubusercontent.com/28290207/35868348-85d454aa-0b5c-11e8-8991-7a6e6d336fc7.PNG)

**Comment by Vogel612** [comment]
It's a tad difficult to know what they exactly want. The zip file does contain the **sources**, and not a dll / pdb. 

Does this service allow putting `C#` as the technology/stack? If yes, you'll probably want to use that and set the language level to 7.2 then.

**Comment by retailcoder** [comment]
Would uploading the .msi installer help? If not, how are you supposed to supply them with a DLL that's in an installer package, without running that installer to extract the DLL in the first place?

**Comment by SadPraetor** [comment]
C# is not within possible options

So this is written in C#? (not an expert here, be patient please, thank you)

![2018-02-06 16_45_44-release details _ fortify on demand - internet explorer](https://user-images.githubusercontent.com/28290207/35869801-4c83d9f6-0b60-11e8-9007-00fad14dbd0c.png)

**Comment by bclothier** [comment]
C# is a subset of .NET, so the `.NET` is what you'd select in this case.

Given that you can't upload .exe file, I'd be inclined to download the source files (here) and try to see if it'll take the zip file (or at least the extracted folder). We're not familiar with Fortify (my experience is limited only to the VPN client) so we're also guessing here.

**Comment by retailcoder** [comment]
Go with .NET ...weird that it's listing VB6 and ASP but not C# - Yup, Rubberduck is written & compiled with C# 7.2. Looks like it *does* want the source files, to make its own build? The language it's written in wouldn't matter at all otherwise.

You can get the latest "green-released" installer [here](https://github.com/rubberduck-vba/Rubberduck/releases/latest). (sorry not .msi, - it's a setup.exe file, generated from [this InnoSetup build script](https://github.com/rubberduck-vba/Rubberduck/blob/next/Installer%20Build%20Script.iss). Every later release is a more or less stable "pre-release" automated build; whenever a pull request is merged, the updated build is automatically made available as such (without release notes).

TBH I'm failing to see what "vulnerabilities" this tool could possibly find. From their website:

> With nearly 80 percent of applications at risk, you need an ongoing security testing program that includes both **static code analysis** and regularly scheduled dynamic scans, and one that does not interfere with software innovation. Fortify on Demand leverages the most advanced dynamic and static testing technologies through a global infrastructure that’s augmented by an experienced team of researchers, testers and software engineers who are available to assist you 24 hours a day.

I hope you're not paying a fortune for this "service"... looks like security through buzzwords and management-appeasing techno-babble.

If it's any good then it's going to find:

 - A conditionally executed HTTP GET request to http://rubberduckvba.com/Build/Version/Stable in the `VersionCheck` class, which we invoke at startup to notify if/when a newer version is available. No, it's not HTTPS, and no, I'm not paying an SSL certificate for this. The HTTP request can easily be disabled from the settings dialog.
 - A ton of Win32 API calls, low-level hooks on mouse and keyboard, which we use to determine where the caret is in the editor (the VBIDE API doesn't tell us) and whether we need to check if menu commands should be enabled or disabled, depending on context.

I honestly have no idea what else if might consider "suspicious". Please keep us posted with the tool's findings, I'm quite curious! :smile:  we're a VBIDE add-in, not some PHP website riddled with SQL injection vulnerabilities... I honestly don't see the point of that scan.

FWIW we use Roslyn and ReSharper's static code analysis, and there are currently a handful of known compiler warnings due to some dead code in the "Extract Method" refactoring feature, and... that's all.

**Comment by SadPraetor** [comment]
In direct communication, and their side is asking whether this is pure C#

**Comment by retailcoder** [comment]
Well there's XAML markup for our UI's... and the original legacy VB6 Smart Indenter source code is in the repository (and probably in the .zip source files too - but the legacy VB6 code wouldn't be compiled into any of the .dll's)... the VBA grammars are Antlr4.6 format and Antlr "compiles" them to a C# lexer & parser that can understand VBA syntax.

Other than that... it's close to 250K lines of C#, yes.

**Comment by retailcoder** [comment]
>  .Net payloads must contain dlls and pdb files

Looks like you need to supply the compiled binaries... which you can't, unless you build the source code yourself, or extract them from the installer. Not sure PDB files would be included in a release build.

**Comment by SadPraetor** [comment]
Well, they referenced me to guide how to prepare .NET files for tests. Basically do it yourself approach
Can I get this done by using .zip source file?

And a ton of thanks for such fast replies. Really appreciate it. All of this is big enterprise policy where no one wants to bear responsibility for anything, so they cover their asses

![2018-02-06 17_53_48-preparing net application files](https://user-images.githubusercontent.com/28290207/35872330-d7f02d18-0b66-11e8-89db-8e87f5612db5.png)

**Comment by retailcoder** [comment]
lol, building a debug build of Rubberduck requires a Visual Studio instance running with administrative privileges, for proper & correct COM registration...

**Comment by bclothier** [comment]
@SadPraetor 

FWIW, I uploaded the compiled source files which includes PDB and compiled DLL as well the original source codes. Hopefully that helps. 

[Temporary download link](https://www.dropbox.com/s/lcfxmkw5p4tuxrl/Rubberduck.zip?dl=0)

**Comment by Inarion** [comment]
I have no intention of derailing the topic, but I felt I had to leave this here:

> No, it's not HTTPS, and no, I'm not paying an SSL certificate for this.

You don't need to. [Let's encrypt](https://letsencrypt.org/) let's you do it for free. (And rather easily as well, as I experienced it.)

**Comment by Vogel612** [comment]
@Inarion seems like a good issue to open over on RubberduckWeb

**Comment by bclothier** [comment]
Closing the issue since question has been answered.
