### ISSUE TITLE
Class module false positive on naming scope when using Refactor>Rename

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#3767]
```
Private foo As Range

Public Sub Initialize(ByVal duk As Range)
    Set foo = duk
End Sub

Public Property Get Bar() As Range
    Set Bar = foo
End Property
```

Renaming `duk`--> `bar` will cause the following message, and the resulting code below.
![untitled](https://user-images.githubusercontent.com/26076874/36285458-7a53ec16-1260-11e8-8d67-c77b760d053c.png)
```
Private foo As Range

Public Sub Initialize(ByVal Bar As Range)
    Set foo = Bar
End Sub

Public Property Get Bar() As Range
    Set Bar = foo
End Property
```
Testing below I didn't catch any unexpected behavior.
```
Sub TEST()
    Dim foo As Class1
    Set foo = New Class1
    foo.Initialize Sheet1.Range("A1")
    foo.Bar.Value2 = "Temp"
End Sub
```

**Comment by bclothier** [comment]
AISI, there *is* a naming clash, but only inside the `Initialize` procedure -- you've effectively hidden the class's property `Bar` from the `Initialize` code --- try to reference the property `Bar` without qualifying, and you'll fail. You'd have to use `Me.Bar` but that's only workable as long as the `Bar` property is public. But with a private property, you'd be truly SOL. From the calling code's POV, there is no "clash" which is why your testing didn't come up with problems.

**Comment by IvenBach** [comment]
Just tried making the `Bar` property `Private` and I see what you're saying. Learning a little each day.
