### ISSUE TITLE
Encapsulate Field refactoring

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#379]
When parsing a Class Module, identify all Private properties that don't have Public Get/Let  functions. Offer to generate them one-at-a-time, or bulk generate them all.  For example:

    Private pMyString As String
    Private pMyLong As Long

Would produce:

    Public Property Get MyString() As String
      MyString = pMyString
    End Property
    Public Property Let MyString (ByRef x As String)
      pMyString = x
    End Property

    Public Property Get MyLong() As Long
      MyLong = pMyLong
    End Property
    Public Property Let MyLong (ByRef x As Long)
      pMyLong = x
    End Property

The `ByRef` could be changed to `ByVal`, or it could be user-configurable.

**Comment by ckuhn203** [comment]
Properties should be passed `ByVal`, otherwise :+1:

**Comment by retailcoder** [comment]
This looks like an *encapsulate field* refactoring. The use case would be something like:

 - Right-click a field declaration in a class module
 - Select *Refactor/Encapsulate Field*
 - Rubberduck pops a dialog letting you confirm the name and type of setter (let/set), and whether the value parameter should be passed by value or by reference.
    - Primitive types would be passed `ByVal` by default; `Property Set` would be disabled.
    - Known object types (i.e. if there's a class module in the project for the field's type) would be passed `ByVal` by default, but `ByRef` would be enabled; `Property Let` would be disabled.
    - `Variant` fields would be `ByVal` by default, with both `Property Let` and `Property Set` enabled - both could be validly selected, too - default would be just `Property Let`.
 - Value parameter name (in the setter's signature) would be `value` by default.
 - Default property name would be determined by the backing field's name, following a configurable naming convention. User could always enter a different name.

The idea is that the Rubberduck dialog would be smart enough so that most of the time, the user simply needs to click Ok (or hit Enter) to create the members.

Short of a configurable naming convention, the name box could be left blank, so user would only need to supply a name.

**Comment by Hosch250** [comment]
Reference PR: https://github.com/rubberduck-vba/Rubberduck/commit/3c02d713d99bbc193f3ed9907e367536fc2c6825
