### ISSUE TITLE
Unit testing issues

### ISSUE THREAD

**Issue by WaynePhillipsEA** [rubberduck-vba/Rubberduck#3809]
In unit test modules, when the VBE 'Compile On Demand' option is OFF (and probably when ON in some cases), and there is a compile time error that makes ModuleInitialize uncallable, it will throw an error in the TypeLib API ExecuteCode which is being thrown right back to the RunAllTestsCommand.   No visual feedback is given as to the problem, and the remaining test results are not updated.

I believe this code in the UnitTesting.TestEngine needs exception handling to catch and update the test results:

     Run(module.Key.FindModuleInitializeMethods(_state));

Additionally, it appears that the 'Compile Before Parse' option isn't effective for the automatic parse that is triggered from running tests.

**Comment by bclothier** [comment]
Hmm. the problem may be a bit deeper than that. Because as part of running, it will implicitly call `_state.OnParseRequested(this);`, which is an asynchronous method. I'm not sure that actually make sense to run unit tests in a middle of a parse and think it should block (or simply not ask for it).

The check for the compilation should be left up to the parser, not the test engine, I think.
