### ISSUE TITLE
Installer only adds 32-bit registry entries for Rubberduck.Extension

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#3816]
It seems the installer only adds registry entries under the 32-bit key:
> `HKEY_CURRENT_USER\Software\Microsoft\VBA\VBE\6.0\Addins`

But **not** under the 64-bit key:
> `HKEY_CURRENT_USER\Software\Microsoft\VBA\VBE\6.0\Addins64`

That's going to cause issues for 64-bit users.

It's also worth noting that while you can't install 32-bit **and** 64-bit Office, side-by-side, you **can** install 32-bit Office and a non-Office 64-bit VBA host, so you could end up in a situation where Rubberduck works in the 32-bit host and doesn't work in the 64-bit host.

**Comment by ThunderFrame** [comment]
hmm, it seems if you install Rubberduck on a system with 64-bit Office installed, then the 64-bit keys get written, and the 32-bit keys aren't. And, if you install Rubberduck on a system with 32-bit Office installed, then the 32-bit keys get written, and the 64-bit keys aren't.

I'm unsure what happens if you install Rubberduck on a system that doesn't have Office installed, but does have a VBA host.

**Comment by A9G-Data-Droid** [comment]
I would like the default behavior to install for both bitness all the time. This is because I love the rubberduck so much I want to use it in every VBE all the time! I found it works great for my -undisclosed application- which happens to be 64-bit.

Here is what I had to do to get it to work:
`New-Item -Path 'HKCU:\Software\Microsoft\VBA\VBE\6.0\AddIns64\Rubberduck.Extension' -Force
New-ItemProperty -Path 'HKCU:\Software\Microsoft\VBA\VBE\6.0\AddIns64\Rubberduck.Extension' -Name Description -PropertyType String -Value 'Rubberduck'
New-ItemProperty -Path 'HKCU:\Software\Microsoft\VBA\VBE\6.0\AddIns64\Rubberduck.Extension' -Name FriendlyName -PropertyType String -Value 'Rubberduck'
New-ItemProperty -Path 'HKCU:\Software\Microsoft\VBA\VBE\6.0\AddIns64\Rubberduck.Extension' -Name LoadBehavior -PropertyType DWord -Value 3
c:\windows\microsoft.net\framework64\v4.0.30319\regasm.exe "C:\ProgramData\Rubberduck\rubberduck.dll" /codebase /tlb`

**Comment by retailcoder** [comment]
@A9G-Data-Droid feel free to take a peek at #3836 :smiley:  the latest (as of now) build for that PR successfully built an installer, which you can get [here](https://ci.appveyor.com/project/retailcoder/rubberduck/build/2.1.2.2978/artifacts) (that's what AppVeyor automatically attaches to the "pre-release" tags when a pull request is merged).

**Comment by bclothier** [comment]
I should probably update the PR to indicate that it will close this issue once merged, because as @retailcoder  alludes, the new installer will no longer be 32/64 but rather attempt to install to both 32/64 bits without regarding the Office bitness.
