### ISSUE TITLE
Refactor | Move Closer to Usage removes object property references

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#3828]
Starting with this code:

```
  Dim CI As ClinicItem
... a bunch of lines of other code
      Set CI = New ClinicItem
      CI.Name = SurveyListRS!MidName
      CI.IndustryCode = SurveyListRS!IndustryCode
```

With a clean parse, `Refactor | Move Closer To Usage` gives me this:

```
... a bunch of lines of other code
      Dim CI As ClinicItem
Set CI = New ClinicItem
      CI = SurveyListRS!MidName
      CI = SurveyListRS!IndustryCode
```
with the missing properties, that won't compile terribly well and is likely of limited use. ;) 

Note also, the failure to follow indentation settings. `Indent | Current Procedure` will fix that up nicely, so my guess is that's it's just not calling the indenter.

Also of note - it parsed the incorrect code cleanly, because I had several `Dim` statements that I wanted to move closer to their uses and had to manually parse between each `Refactor`.

Also just realized that this code:

```
  Dim clinicList As New Collection
... a LOT of other lines of code
      clinicList.Add CI, Key:=CI.Name
```
Yields this after a `Move Closer To Usage`:
```
... a LOT of other lines of code
      Dim clinicList As New Collection
      clinicList CI, Key:=CI.Name
```
Note the missing `.Add`

**Comment by Vogel612** [comment]
labelling [critical] because this results in code breakage. 

Also: I'm pretty sure that the incorrect indentation behaviour is a result from how we handle whitespace in the parser... Basically the indentation on a statement belongs to the `endOfStatement` context of the **previous** statement. 
As of now rewriters do not take that into account. I've been toying with the idea of changing that behaviour, but these changes may result in rather large changes in how rewriters need to account for whitespace... It's all a bit of a mess...

**Comment by daFreeMan** [comment]
Frankly the indentation is a minor annoyance in comparison to broken code.

Thanks for jumping on the labeling! :)
