### ISSUE TITLE
Proof of Concept for supporting per-user install of Rubberduck

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#3832]
COM registration can be a major PITA when one wants to install Rubberduck. Currently one must run regasm.exe which always requires admin privilege because it always writes to the HKLM.

What is not apparent is that it is simply a bunch of registry entries. Instead of relying on a tool to register, we can just write to the registry directly ourselves to achieve the same effect. The challenge is in effectively enumerating all registry entries that we must write, especially as we may add or alter any public interfaces / classes or even new assemblies. 

The proposal is to create a new project.... tentatively called `Rubberduck.Deployment` to help us with extracting the information at the build time, so that we can then build the registry script, which can be then executed by the installer, hopefully with parameters where needed. 

For extraction part, we can use wix's `heat.exe`. Here is a sample output when the `heat.exe` is run on both `Rubberduck.dll` and `Rubberduck.tlb` (originally XML files, renamed to txt for upload):
[Rubberduck.dll.xml.txt](https://github.com/rubberduck-vba/Rubberduck/files/1799460/Rubberduck.dll.xml.txt)
[Rubberduck.tlb.xml.txt](https://github.com/rubberduck-vba/Rubberduck/files/1799461/Rubberduck.tlb.xml.txt)

The challenge is to transform the above output into a format that we can use. The assumption is that we don't want to change the installer from Inno Setup to WiX just to have the registry entries, and even if we did use WiX, we still have to perform transformation because in the script, the default hives are still HKLM. 

To help test this idea, I extracted out the registry values from the registry hive directly and edited them directly (originally .reg files, but has .txt appended for uploading):

[Original Rubberduck Registries Entries.reg.txt](https://github.com/rubberduck-vba/Rubberduck/files/1799468/Original.Rubberduck.Registries.Entries.reg.txt)
[Delete Rubberduck Registry Entries.reg.txt](https://github.com/rubberduck-vba/Rubberduck/files/1799469/Delete.Rubberduck.Registry.Entries.reg.txt)
[HKCU Rubberduck Registry Entries.reg.txt](https://github.com/rubberduck-vba/Rubberduck/files/1799470/HKCU.Rubberduck.Registry.Entries.reg.txt)
[Delete HKCU Rubberduck Registry Entries.reg.txt](https://github.com/rubberduck-vba/Rubberduck/files/1799471/Delete.HKCU.Rubberduck.Registry.Entries.reg.txt)

This can be tested by using this VBA code:

```
Set x = CreateObject("Rubberduck.AssertClass")
Set x = New Rubberduck.AssertClass
```

When the registry entries are missing, one is still able to browse and select the `Rubberduck.tlb` in the Tools -> References, and the metadata can be read in the object browser. However, the `CreateObject` or `New` will fail. 

Installing the same keys to the HKCU will work and both early/late versions of creating an object will then succeed. 

So we know that using HKCU is viable, provided that we write to all the `Interface`, `CLSID`, `Classes`, `Record` and `TypeLib`, all which are required to enable a successful creation of object. 

`Regasm.exe` has the `/regfile` option which unfortunately is incomplete and won't produce the same output as WiX's `heat.exe`. Fortunately, the `heat.exe` can be bundled as a part of nuget package (Wix-ToolSet), and therefore enable building in AppVeyor, with syntax similar to this:

```
"$(SolutionDir)\packages\WiX.Toolset.3.9.1208.0\tools\wix\heat.exe" file "$(SolutionDir)\RetailCoder.VBE\bin\$(ConfigurationName)\Rubberduck.dll" -out "$(TargetDir)\Rubberduck.dll.xml"
"$(SolutionDir)\packages\WiX.Toolset.3.9.1208.0\tools\wix\heat.exe" file "$(SolutionDir)\RetailCoder.VBE\bin\$(ConfigurationName)\Rubberduck.tlb" -out "$(TargetDir)\Rubberduck.tlb.xml"
```

To get the registry entries in a format we can use, we likely will need to follow up with a PowerShell script so that AppVeyor can then execute it to perform the transformation of the XML files into a suitable format (`.reg` file?) that InnoSetup can then use. Because the path may be changed at install time, the format should be parameterized to support those scenarios. 

Note that this does not include the registry entries required for VBA Add-In registration, which is already in HKCU. The final solution may or may not have to include that.

Comments or questions welcome.

**Comment by bclothier** [comment]
Ref #3006

**Comment by christophocles** [comment]
Glad to hear this is still a consideration. A non-admin installer would really help people like me who want to use this add-in on an office computer with no admin rights and too much red tape and approvals necessary to get a new, limited-audience, beta program added to our software distribution environment. Even if it was added, I would be stuck on an old version for years because IT would never go through the effort of updating it. This is exactly what happened with MZTools8. I would be stuck with the version that was originally installed 2 years ago unless I update it myself, which is only possible because of per-user installation.

I tried to get rubberduck non-admin install to work a couple years ago and was unsuccessful. But I saw the advances this project has made in the past 2 years and I decided to make another attempt tonight, and it works! The dockable windows and the unit test classes work without errors. I confirm that COM-registration in HKCU is feasible.

I did it by capturing all the registry entries from the installer using freeware program NirSoft RegistryChangesView, which helpfully generates a .reg file automatically. I then simply run a copy/replace of HKLM for HKCU, zip up the folder C:\ProgramData\RubberDuck along with the .reg file, and copy it all to my office PC and load the .reg.  I'll have to do this every time a new version comes out, but at least now I can start using rubberduck and I have control over when it gets updated. It will be nice when the installer handles this automatically.

**Comment by bclothier** [comment]
@christophocles  thanks for offering additional confirmation. It's cool to hear that you used the same tool for manually extracted the entries generated by `regasm.exe` as part of the installer, which was what I also did in my original entry.

I just want to make sure, when you tested that, did you take care to uninstall everything and manually delete the leftover registry keys? Otherwise, the test may be flawed because the old keys may be still used and for some entries, there may be multiple entries per version. 

A simpler test would be to load it on a PC that never ever had Rubberduck installed before so when you do have the chance, please follow up whether it worked on a virgin PC as well.

Thanks for sharing!

**Comment by christophocles** [comment]
My office PC never had a proper installation and it works there.  The docked code explorer is working and I can instantiate objects of type Rubberduck.AssertClass.

I am actually getting some errors that I was not getting on my personal PC, but I believe these are probably unrelated to installation method. The errors seem to come up when I try to interact with a locked VBA project, of which I have several on my office PC, and none on my personal PC. The errors say "Run-time error -2147467262 (80004002) "Unable to cast object of type 'VBClassicExtensibility.VBProjectClass' to type 'Microsoft.Vbe.Interop.VBProject'".  If I unlock all the projects then the errors stop occurring, but then the newly-unlocked projects still don't show up in the Code Explorer.  However, I searched for this error message in the issues library and couldn't find it. Since I couldn't be sure it's unrelated I mention it here.

**Comment by bclothier** [comment]
@christophocles Sweet! Thanks for confirming it worked on a virgin PC. That's the best confirmation that the idea is in fact viable.

Regarding the error, it is known that we have some restrictions WRT dealing with locked projects. But normally, we'd just skip over the locked project. Am I to understand that it works on your personal PC even though the projects are locked? The fact that simply unlocking them cause it to not show up in the CE seems backward to me. Is it possible for you to attach a full log with the errors? That may help us determine whether this is relating to the installation or something else.

**Comment by christophocles** [comment]
The exceptions pop up when I first open the VBA editor, and when I select the name of a locked project in the VBE project list, and when I quit Excel.

[RubberDuckLog vbe exception.txt](https://github.com/rubberduck-vba/Rubberduck/files/1800617/RubberDuckLog.vbe.exception.txt)

I did not run the parser for this log.  If I unlock all the projects, the errors stop occurring.  If I run the parser before unlocking all the projects, then the locked projects will not appear in the rubberduck code explorer even if I unlock them later.  I have to close and re-open Excel to do that.

**Comment by bclothier** [comment]
Looking at the log quickly, I think it has less to do with the method of installation and more with the add-in that you are apparently using. I am assuming it's an add-in because the error suggests to me it's written in VB6, or something like that. I'm wondering if you have the same add-in on your personal PC? If not that may be why. Maybe try and disable all add-ins and see whether it runs normally without the unlocking/locking business. THEN, enable the add-in. It should work fine since we already have an active VB project. THEN, restart Excel and verify you get the same error. That may help rule out definitely it's not to do with the model of installation.

**Comment by christophocles** [comment]
If I disable all add-ins, it runs normally. I do not have the same add-ins on my personal PC and I was not able to reproduce the error there, even with some locked projects present. I concur it's probably related to these specific add-ins.

The parser appears to run normally with all projects unlocked. However, when I log the execution of the parser it throws some additional exceptions, but I don't want to post that error log here because it shows all the module and symbol names.

**Comment by bclothier** [comment]
Thank so much for taking the extra time to verify the culprit. That does sounds like this isn't about the method of installation, after all. I'm pretty sure that this is possibly a first report (at least for me) where a certain add-in interferes with Rubberduck's working.

I'd really like it if you could open a new issue, and provide more information about add-in (assuming it's not a private in-house add-in), so that we can figure how to avoid that particular trip up since it shouldn't have to matter whether that got loaded first or not. 

For the other exceptions - I appreciate your concern but I need to ask whether those are actually displayed to you as a messagebox or something similar? It is my understanding that parsing may encounter errors but those are expected and are usually handled as part of the parsing. If you got to the "Ready" state, then there is no problem (even though the log may say there were errors but you should consider them handled). What you should be worried is whether the parser stop with an `Unexpected error`, which means there is an error we did not handle and we need to fix that. That would be its own issue as well. 

Again, thank you very much for all the help you've given. This is a tremendous boon! :)

**Comment by christophocles** [comment]
There were no additional messagebox errors. The parser exceptions were apparently handled because I didn't know about them until I looked at the debug log.

I will open a new issue on the VBE exceptions tomorrow when I'm at my desk, with as much info as I'm able to provide.
