### ISSUE TITLE
Smarten up the templates for unit testing

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#3879]
We support both early and late bound testing but what I don't like is that they derive from two different templates and make it hard to flip between the states. (You gonna help me enable my intellisense addiction, mmkay?)

My suggested template is provided below:

What it brings:

1) To change between early/late binding, we change *exactly* only one line -- The `#Const LateBind = ...` and add references accordingly.

2) Only one default template to maintain instead of 2. The setting used for binding when adding a test module would be then used to determine what default value of the `#LateBind` should be. WE always use `CreateObject` regardless of the mode, so we do not need to write `Set Assert = New Rubberduck.AssertClass`. 

3) This can be tied into a project-level compilation constant in case we need to support project-wide switch, rather than per-module. This is achieved with `#Const LateBind = LateBind` (assuming the `LateBind` is defined in the project's conditional compilation arguments). This approach also makes it easy for us to conditionally enable only early binding on a particular test module, rather than for all test modules. 

```
Option Compare Database
Option Explicit
Option Private Module

'@TestModule
'@Folder("Tests")

#Const LateBind = 0

#If LateBind Then
Private Assert As Object
Private Fakes As Object
#Else
Private Assert As Rubberduck.AssertClass
Private Fakes As Rubberduck.FakesProvider
#End If

'@ModuleInitialize
Public Sub ModuleInitialize()
    'this method runs once per module.
    Set Assert = CreateObject("Rubberduck.AssertClass")
    Set Fakes = CreateObject("Rubberduck.FakesProvider")
End Sub

'@ModuleCleanup
Public Sub ModuleCleanup()
    'this method runs once per module.
    Set Assert = Nothing
    Set Fakes = Nothing
End Sub

'@TestInitialize
Public Sub TestInitialize()
    'this method runs before every test in the module.
End Sub

'@TestCleanup
Public Sub TestCleanup()
    'this method runs after every test in the module.
End Sub
```

**Comment by Vogel612** [comment]
note that the check for early-binding modules may need to smarten up. it **should** work, but it's better to keep that in mind

**Comment by comintern** [comment]
I'm going to disagree on this one - we shouldn't use `CreateObject` for an early bound reference for no other reason than IMO it promotes poor coding practices.  I also don't really like the idea of always using a conditional compile block, mainly because the vast majority of the VBA code that I write isn't going to be distributed. So, I like my "Early binding" setting just the way it is.

I also don't like the idea of going through every single test module to change the compilation constant, and would personally find that pretty obnoxious in my own projects.

Finally, in order to localize the unit test code generation (see #4220) and move it to `Rubberduck.UnitTesting` (where it belongs) per the liberal sprinkling of `TODO` and `FIXME` comments, it's going to need to be refactored anyway.

However, much of the code generation can be made static and can be cleaned up considerably in order to make maintenance easier. So, I'm going to swing in the complete opposite direction here and add a _third_ option for "Dual binding" to the settings that would add the conditional compilation directive. If users want custom test modules, they will also eventually be able to create their own once the user template implementation is complete.

**Comment by comintern** [comment]
`CreateObject` involves a registry lookup to convert the ProgID to a CLSID at runtime, whereas `New` performs that operation at compile time.  If you're early bound, there is never a reason to use `CreateObject` IMO, and it should really be added as something like `CreateObjectUsedOnEarlyBoundTypeInspection`.

The definition of a "good template" is something that is largely subject to user preference though. The only reason I'd suggest conditionally compiling the instantiation is that it would avoid a situation where generated code would trigger that type of inspection. Also TBH, unless they know damned well what they're doing, end users probably shouldn't be touching the code in `Sub ModuleInitialize()` _anyway_ - including potentially via quick-fixes.

Conditionally compiling the instantiation doesn't really add that much more code to the template - it would look more like this (`Option Compare Database` would only be added for Access hosts):

```
Option Explicit
Option Private Module

'@TestModule
'@Folder("Tests")

#Const LateBind = 0

#If LateBind Then
Private Assert As Object
Private Fakes As Object
#Else
Private Assert As Rubberduck.AssertClass
Private Fakes As Rubberduck.FakesProvider
#End If

'@ModuleInitialize
Public Sub ModuleInitialize()
    'this method runs once per module.
#If LateBind Then
    Set Assert = CreateObject("Rubberduck.AssertClass")
    Set Fakes = CreateObject("Rubberduck.FakesProvider")
#Else
    Set Assert = New Rubberduck.AssertClass
    Set Fakes = New Rubberduck.FakesProvider
#End If
End Sub

'@ModuleCleanup
Public Sub ModuleCleanup()
    'this method runs once per module.
    Set Assert = Nothing
    Set Fakes = Nothing
End Sub

'@TestInitialize
Public Sub TestInitialize()
    'this method runs before every test in the module.
End Sub

'@TestCleanup
Public Sub TestCleanup()
    'this method runs after every test in the module.
End Sub
```
