### ISSUE TITLE
Empty Access Form Event in VBA is deleted upon parsing

### ISSUE THREAD

**Issue by FuSoftware** [rubberduck-vba/Rubberduck#3882]
Hello, I don't know if this is a feature or an issue, but since it does something I didn't not expect it to do, I'll report it as possible issue.

RD deletes any empty Form Event (Actually, any empty event from any form control). Just in case it's an issue, here are the steps to reproduce it :

Steps : 
- Create a new ACCDB file
- Create a new Form
- Right Click -> Create Event
- Keep the event's body empty
- Start RD's parsing
- The created even should diappear

**Comment by bclothier** [comment]
Thanks for the report, @FuSoftware  --- this is actually not RD"s but Access' and has always behaved like that for a number of versions, if not forever. You can still observe the same behavior when you have Rubberduck unloaded and just try to compile the code. 

You might be now observing it because in recent versions of Rubberduck on the account of the new feature we introduced, `Compile Before Parse` (see PR #3783). By default, it will compile code prior to parsing as to avoid falling into parser errors. But since it runs the compile, it of course has the same effect that was present; removing empty event handlers.

To avoid this, you can just add a `'` empty comment to the body and it won't go away.

**Comment by FuSoftware** [comment]
Okay, thanks for the info, didn't realize it was from Access and not RD, should have tested the Compile stuff before.
