### ISSUE TITLE
Indenter removes and doesn't replace bookmarks and breaks

### ISSUE THREAD

**Issue by mkrause01** [rubberduck-vba/Rubberduck#3941]
The indenter removes and doesn't replace any bookmarks and/or breaks.  It also removes blank lines (white space) after procedures and functions.  Reducing empty lines to one line from more than one line would be acceptable.

**Comment by retailcoder** [comment]
There's an indenter setting that controls vertical whitespace between members; if that checkbox is ticked then this behavior is by design:

![image](https://user-images.githubusercontent.com/5751684/38929605-df5cd80c-42da-11e8-90e2-722b4ecc05a3.png)

As for losing bookmarks and breaks, that would be true of any code-modifying feature - we are rewriting the entire module in a single operation so we don't fill up the undo stack with every single modification. I'd love to reinstate bookmarks and breaks, however these are nowhere in the VBIDE API so we would have to find them in undocumented places through reverse engineering, and then hope to find a way to not only read them, but also write them - if it's possible at all, we'll get to it eventually. But please don't hold your breath!
