### ISSUE TITLE
Code Explorer should allow VB6-specific ComponentTypes to be added

### ISSUE THREAD

**Issue by mansellan** [rubberduck-vba/Rubberduck#3997]
When running in VB6, currently only the ComponentTypes available to VBA are addable from Code Explorer:

![image](https://user-images.githubusercontent.com/25420409/39716306-e81dfc9e-5227-11e8-8a4f-6dd1ddabbedb.png)

UserForm is not applicable to VB6, and selecting it leads to a COMException. We should remove that, and extend to allow the VB6 types to be added:

![image](https://user-images.githubusercontent.com/25420409/39716375-17f84d02-5228-11e8-8ba3-eee082c7b915.png)

Note, only some of these are first-class ComponentTypes. Others such as DataReport are subtypes of ActiveXDesigner, and the list of those is likely extensible. Suggest these are not considered initially, as it's not clear how they can be accomodated (and they are much less critical).

One other consideration is that the types available to be added in PE is based on the VBP project type, we should replicate this behaviour.

**Comment by bclothier** [comment]
I want to point out that this is a good example where we need to coordinate between the `Rubberduck.Core` project and the `Rubberduck.VBEEditor.XXX` because we need to achieve host-specific behavior. Of course, we don't want any direct interactions; they should be all restricted via the abstract implementation within the `Rubberduck.VBEEditor` project. For that reason, it's likely that it will be necessary to pass a `Action` or a `Func` with some data structure so that the behavior of the menu can be completely controlled by the corresponding `Rubberduck.VBEEditor.XXX` projects.

**Comment by retailcoder** [comment]
@bclothier looks like a good opportunity to leverage the [RequiredHostAttribute](https://github.com/rubberduck-vba/Rubberduck/blob/d09a533780c0ce6a2fd550d4c0e4f1c8ab2896d4/Rubberduck.Parsing/Inspections/RequiredHostAttribute.cs) (and move that class somewhere less inspection-centric.

**Comment by mansellan** [comment]
I was debating whether or not to add this to vb6 go-live, as there's easy workarounds available. But on balance, we should at least guard for the ComException on UserForm (and preferably hide that menu item).
