### ISSUE TITLE
Annotation 'ModuleInitialize' is illegal in this context

### ISSUE THREAD

**Issue by carlossierra311** [rubberduck-vba/Rubberduck#4003]
I am getting the Rubberduck Opportunity described in the title of the issue. I've tried several things to solve it, but haven't been able so far. Things I've noticed/tried: 

1. It's only present for the second to fifth test modules. The first one doesn't have this "opportunity".
2. Fixing it (adding the '@Ignore IllegalAnnotation) doesn't make it go away either, as can be seen on the screenshot. 
3. Removing the tag breaks the execution of the test cases in the test module. 

![moduleinitialize](https://user-images.githubusercontent.com/23511373/39933592-0eebbd78-5509-11e8-9338-e37cb0372d3f.png)

Version 2.2.6672.28001
OS: Microsoft Windows NT 10.0.16299.0, x64
Host Product: Microsoft Office 2016 x86
Host Version: 16.0.9226.2114
Host Executable: EXCEL.EXE

ps. I searched for a similar case, but didn't find anything to explain/solve this.

**Comment by retailcoder** [comment]
If you replace the `'@Ignore IllegalAnnotation` line with a NEWLINE (i.e. leaving a blank line between the declarations section and the `Sub` statement, does the inspection result go away?

**Comment by carlossierra311** [comment]
Although it isn't very clear in the screenshot, there is a line between the declarations section and the sub statement already. Anyway, I just removed the `'@Ignore IllegalAnnotation` with a blank line, but this didn't make the result go away. I added more white space before the sub statement, but that didn't fix it either.

**Comment by Vogel612** [comment]
The root cause for this is the fact that the parse-tree listener does not recognize the end of the ModuleDeclarations section correctly and considers the first annotation on a member to belong to the module declarations.

That is because annotations are considered "EndOfLine" statements by the parser. This leads to the unfortunate side-effect that (unless you declare a module attribute), we do not correctly interpret the Annotation as inside a moduleBody, but before it, which results in this false-positive.

A solution is unfortunately nontrivial. A workaround would be to introduce a procedure or sub before the first annotation that does... nothing... That is rather *ugly* though 😭

**Comment by Vogel612** [comment]
Actually we already have code taking care of that false-positive. Unfortunately that code is not correctly prepared. We're not correctly resetting the Contexts of ParseTreeListeners between every module

**Comment by Vogel612** [comment]
Another time I am rather grateful for the extensive test-suite we have... I did some nonsense and the tests called me out on it. The actual solution was to reset the flag that takes care of this when entering a module, not by resetting the contexts between modules (which drops inspection results).

A fix is coming up (awaiting passing unit-tests and a review)

**Comment by carlossierra311** [comment]
Thanks Guys. Please let me know when the fix is out so that I can help testing it.
