### ISSUE TITLE
Test explorer Icons and Labels incorrect

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#4011]
![unit test labels](https://user-images.githubusercontent.com/26076874/40091872-15d8105a-586f-11e8-9d0f-6ec3bfbfe2f2.png)
![unit tests icons missing](https://user-images.githubusercontent.com/26076874/40091875-17d9ef7c-586f-11e8-9a30-e9ee3405d7db.png)

Version 2.2.6709.33354
OS: Microsoft Windows NT 10.0.17134.0, x64
Host Product: Microsoft Office 2016 x86
Host Version: 16.0.9226.2126
Host Executable: EXCEL.EXE

**Comment by retailcoder** [comment]
The [XAML is still referring to `RubberduckUI`](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Core/UI/UnitTesting/TestExplorerControl.xaml#L487) - the fix is to pull the resources from `Rubberduck.Resources.UnitTesting.TestExplorer` instead. This is entirely my oversight.

The CommandBar menus need more attention though:

    public override string Key => "TestMenu_RunAllTests";

The `ParentMenuItemBase` class is [pulling the resource keys from `RubberduckUI`](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Core/UI/Command/MenuItems/ParentMenus/ParentMenuItemBase.cs#L32):

    public Func<string> Caption { get { return () => Key == null ? null : RubberduckUI.ResourceManager.GetString(Key, Settings.Settings.Culture); } }

So we need a .resx file in `Rubberduck.Resources` that will contain the resource keys for all CommandBar menu items (including context menus).
