### ISSUE TITLE
IgnoreModule annotation doesn't stop all Inspection Results

### ISSUE THREAD

**Issue by Greedquest** [rubberduck-vba/Rubberduck#4013]
I hear annotations are on their way out (although I'm yet to stumble across anything concrete to confirm this), so this may be a bug to ignore. Either way, the `'@IgnoreModule` annotation is not working as I would have expected. Although the majority of inspection results are ignored, `Option Explicit` is not (see image, where I have `'@IgnoreModule` in Module 2)

![image](https://user-images.githubusercontent.com/25348920/40120583-75b92696-5917-11e8-961e-793f980f8602.png)

I often leave out `Option Explicit` in modules where I'm developing tests (I also don't want inspection to look there), so if these two things were both possible at the same time it would be best. Thanks, let me know if you need any more info about the issue.

**Comment by retailcoder** [comment]
There was an idea at one point, to use member-level annotations such as `@Description`, `@DefaultMember`, and `@Enumerator`, and module-level annotations such as `@PredeclaredId` and `@Exposed`, and to use these as an easy interface to the corresponding member & module attributes.

The problem with that is that because the rewriters work off the code pane token streams (so that token positions line up exactly with what we see in the editor), attributes get wiped out on rewrite anyway (this is still a problem), a decision was taken to remove the attributes-related annotations and their corresponding functionality, so as to avoid building a feature on top of broken behavior.

Other annotations which have nothing to do with module/member attributes, are here to stay!

Glossing over the details, `@Ignore` annotations need to be honored by each individual inspection. `OptionExplicitInspection` is literally the first inspection that was implemented, as such predates ignore annotations by quite a bit - it's fairly possible a number of older inspections weren't updated to account for the new functionality.

Is it only `OptionExplicitInspection`?
