### ISSUE TITLE
AutoComplete interference with IntelliSense auto complete

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4087]
Build .3384

I've enabled {Tab} for RD AC. 

Within a `With` block, I was adding a new line. Concatenating a `String` variable to the end of a text string I started with this:
![rd ac intellisense 1](https://user-images.githubusercontent.com/11889733/41433829-05d6e75e-6fe8-11e8-8600-cb5a39fa8df9.PNG)

I hit `{Tab}` and ended up with this:
![rd ac intellisense 2](https://user-images.githubusercontent.com/11889733/41433857-146664ac-6fe8-11e8-809d-83c5024baa5d.PNG)

This is somewhat inconsistent (ain't those the best?) - the first couple of times, I got no completion. However, setting up to get the first screen grab, I hit `Tab` and it worked just fine. It was then, though, that I realized that the extra `Wend`s (I had 2 from testing it twice to be sure of what I was seeing) had been inserted (I had 2 at that point). I cleaned up the code back to my starting condition, and was able to reliable reproduce it to get the 2nd screen grab.

This could, potentially, be related to the fact that the code is currently executing, but "well... don't do that" isn't a reasonable fix - a lot of people do do that.

Hitting `Enter` seems to be a pretty reliable way to get IntelliSense to AC without triggering the RD AC issue. ("Pretty" reliable, because I haven't tested it more than 2 or 3 times...)

**Comment by retailcoder** [comment]
Hold on hold on hold on... you managed to get a `Wend` autocompleted off a `With` block???

**Comment by daFreeMan** [comment]
Yeah, that took a minute to sink in... see #4088

**Comment by retailcoder** [comment]
There's not really a way to tell, right now, whether an IntelliSense popup is being shown (and thus whether to yield any TAB hit to that popup). Presumably there's a WM message somewhere to pick up & handle for that. As for AC not firing, I suspect #4080.

**Comment by Vogel612** [comment]
labelling critical because of the resulting code breakage

**Comment by retailcoder** [comment]
@Vogel612 intellisense does get in the way, but not as much as it seems from this issue: the real problem here is that AC picked up a `While` keyword in a string literal on the current line, so hitting TAB triggered AC and added the corresponding `Wend` - IMO triggering AC on string literals (and end-of-line comments) is the critical showstopper issue here; blocking AC when intellisense is shown would only have coincidentally prevented this.

Not saying AC interfering with intellisense isn't a problem, but in this specific case intellisense is just a distraction.

    With foo.B{TAB}

Would have the TAB keypress eaten by AC, resulting in:

    With foo.B
        |
    End With

Which is bad, but not critically broken IMO.
