### ISSUE TITLE
Autocomplete & Quick Info

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#4110]
When AC is enabled, the yellow texttip that normally shows as soon as you start the argument list for a method no longer appear. To get it, one must type space to get it back only to lose it again when another AC is triggered (e.g. for quoting a string).

As an example:

```
DoIt|
```

typing `(` brings us:

```
Dolt(|)
```

without the intellisense. Typing a space, we get it:

```
DoIt( |)
```

But as soon as we type `"`, we get it AC'd but lost the intellisense again:

```
DoIt("|")
```

Consequently, it's annoying to have to keep spacing just to get it back. Can we ensure this gets triggered after a AC?

**Comment by retailcoder** [comment]
I've been giving this some thought - currently when AC sets `e.Handled = true`, we swallow the keypress.

I think we could easily tweak the `wParam` to make it look like Ctrl+Space or Ctrl+i was pressed. But sending a space wouldn't be right.

**Comment by bclothier** [comment]
No, `Ctrl+Space` would bring up the list of available member, which isn't the same as the yellow text tip that comes up. However, `Ctrl+i` would be indeed appropriate. For now, it's more important to retain the vanilla behavior, so we should do that at least OOB.

**Comment by bclothier** [comment]
OBTW, just checked - the official name for that yellow tip is `Quick Info`.

**Comment by retailcoder** [comment]
Now the big question is.. what would be the `wParam` value for Ctrl+i? :smile:

**Comment by retailcoder** [comment]
This is currently implemented in [ShowIntelliSenseCommand.cs](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Core/AutoComplete/ShowIntelliSenseCommand.cs) which invokes command ID 2531 (probably needs adjustment for VB6 support, cc @mansellan), however I ended up commenting it out because whenever that command is invoked and there's no "quick info" available, the VBE makes a very annoying "ding!" (beep?).

Ideas welcome - closing/declining this issue for now.
