### ISSUE TITLE
RD considers variants an object in Code Inspection

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#4162]
RD is considering the use of the split function to return an object. This code in my personal macro workbook comes up as a code inspection.
```
Private Sub Foo(ByVal buzz As Range)
    Dim cell As Range
    For Each cell In buzz
        Dim bar As Variant
        bar = Split(cell.Value2, "|") 'Object variable 'bar' is assigned without the 'Set' keyword.
        Debug.Print bar(1)
    Next
End Sub
```
Yet when I copy this code to a new workbook I'm not getting any inspection result.
![rd inspection not found in new book](https://user-images.githubusercontent.com/26076874/42391592-c31030e6-8104-11e8-993a-7db84193cdbf.png)

**Comment by comintern** [comment]
This appears to have nothing to do with the inspection - looks like it was defaulting the return type to Object because the VBA type library didn't load correctly. This works fine after the changes in #4181. Status bar shows Split returning a Variant, and the inspection is not triggered with the sample code above.
