### ISSUE TITLE
Is a RD API on the cards?

### ISSUE THREAD

**Issue by Greedquest** [rubberduck-vba/Rubberduck#4226]
I've made a little project for exporting code modules/projects as single self extracting files. It occured to me that it would be nice if I could access Rubberduck's knowledge of `'@Folder()` annotations to export only files within a certain folder. Or more generally, there are a number of bits of RD that I could use in various projects.

Are there any plans to expose some of Rubberduck in an API? I heard somewhere about thoughts of a unit testing api for use in CI, but I'm on about a Rubberduck object that I can access from VBA directly.

**Comment by bclothier** [comment]
Since PR #3975, it is already available but relatively untested. Note that it's a separate library, so you must reference the dll "RubberduckAPI.XXX.tlb", where the "XXX" corresponds to the bitness you are using. IIRC, you need to use a pre-release as it hasn't been included in the last green release(?).

There are a number of limitations; the main one being that the parser class is indepdent of the actual parser used by the RD main plugin, meaning you can't see same state but you can run that parser and then iterare over the declarations / references. The rewriter API is also not exposed, so you don't have a way of using its rewriter to support rewriting VBA but you still can use VBIDE API in conjunction with results you get from the parser. 

PRs that enhance the API are of course welcome.

**Comment by Vogel612** [comment]
Do note that the API we currently expose is considered highly experimental and may change arbitrarily between any two releases
