### ISSUE TITLE
RD unloads before user answers "Save before exiting" dialog

### ISSUE THREAD

**Issue by Inarion** [rubberduck-vba/Rubberduck#4255]
Not sure whether this is *status-by-design* or similar, but here it goes:

MCVE:
 1. Open new instance of excel
 2. Modify fresh workbook in any way (to force the unsaved changes dialog to appear when exiting)
 3. Open VBE (to have RD loaded)
 4. Command Excel to close - Excel will pop up a dialog asking you whether to save or discard the changes done to the workbook. At this point, RD is already gone from your VBE.
 5. Select `Cancel` in the dialog.
 6. You now have a VBE without RD. An Excel restart it necessary to get the duck back.

Again, not sure if that is how it has to be to guarantee a smooth RD shutdown. But I found it curious enough to report it here.

Version 2.2.0.3576
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2010 x86
Host Version: 14.0.7208.5000
Host Executable: EXCEL.EXE

**Comment by retailcoder** [comment]
That's by design indeed - per the VBA SDK specifications, a VBA host needs to fire certain events in a specific order to allow add-ins to unload; the way we have it wired up right now is exactly how MZ-Tools has it (Carlos helped us with it). It's annoying indeed, but there's literally nothing we can do about it. I'd report that as a bug to Microsoft, but it's literally *specified* to behave that way, and "fixing" it would wreck VBE add-ins.

Note that at step 6 RD is still holding on to a number of object references; reloading RD at that point should not be done.
