### ISSUE TITLE
SmartIndenter enhancement - strip/trim all spaces from blank lines

### ISSUE THREAD

**Issue by TroyB9** [rubberduck-vba/Rubberduck#4363]
This option would make it immensely easier to insert and delete blank lines while editing code if the SmartIndenter had an option to trim all spaces from blank lines when invoked.

**Comment by comintern** [comment]
That would be a fairly trivial change - right now the indenter is just basically just ignoring "empty" lines (those containing nothing but whitespace). 

The main question would be whether to even bother making this a settable option.  Are there any instances where we wouldn't want to replace a line full of spaces with a simple newline?

**Comment by comintern** [comment]
Linking [chat](https://chat.stackexchange.com/transcript/message/46722184#46722184).

**Comment by TroyB9** [comment]
I like your comment:

> Makes sense to me - adding an option for that would probably make me lean toward a **"how to handle empty lines" setting**. 

```
( ) leave as is (current setting)
(*) remove all spaces
( ) pad to the current indent level 
```

My personal preference is the 'remove all spaces'.  :)

**Comment by CHR-IS-B** [comment]
To me it makes sense for the indenter to remove the whitespace lines without an extra option to turn on and off.  I can't think of any reason to want to preserve it.  If this is made an optional setting then having it on by default seems like the way to go.

**Comment by retailcoder** [comment]
For *your* preferences, perhaps. As far as I'm concerned, blank lines that
don't honor the indent level they're at, drive me nuts. I systematically
add that indent whenever I paste code from CR or SO into the VBE. If
current indent is 3 levels, I see no reason to suddenly have a blank line
(which is pretty often just completely arbitrarily left blank) at 0 indent
just because it's blank - if it's already indented then if I type a comment
(or an instruction) on that empty line then *it's already indented*.

To each their own - I fully support this being configurable, ...and I'm
strongly inclined to make "indent blank lines" the default.

>

**Comment by rubberduck203** [comment]
I just showed up to argue with Retailcoder. 

Git shows indentation on blank lines as white space error. It makes the diff noisy. 

Of course, VBA commits in Git tend to have a ton of noise anyway, so... yeah. I just felt like being contrary. 

Having an option is definitely the way to go.

**Comment by CHR-IS-B** [comment]
@retailcoder I can understand that.

**Comment by TroyB9** [comment]
Wow, just installed the latest release and this new 'remove' setting is awesome.  So much easier to clean up code with predictable cursor movement.  Thank you for implementing this!!
