### ISSUE TITLE
Crash when adding double quote after pipe

### ISSUE THREAD

**Issue by CHR-IS-B** [rubberduck-vba/Rubberduck#4373]
I consistently get a crash when I type a double quote at the end of a line of code, immediately after a pipe symbol.  It happens in both Excel and Outlook (haven't tried other apps).

I can trigger a crash by typing this into a new module:

`|"`

It also crashes when I type those two characters or if I add a double quote after a pipe character on an already existing line of code.

There is NO issue if:

- The double quote is not typed at the end of a line.
- The double quote is pasted instead of typed.

Could this be an issue with RD's autocompletion?

One more thing (this may be irrelevant to this issue) – I noticed that while autocomplete normally replaces `"` with `""` and moves the cursor between the two double quotes, if a line of code ends with a space and I type a double quote immediately before that space, the space is removed and autocomplete only adds a single double quote.

Version 2.2.0.3762
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Outlook x86
Host Version: 16.0.4717.1000
Host Executable: OUTLOOK.EXE

**Comment by retailcoder** [comment]
The VBIDE API does not allow us to edit a line of code in-place: we have to *replace* it, and doing that causes the line to be validated/parsed by the VBE, which is what is causing the most violent headaches around autocompletion: I have to try and *predict* what the code will look like in the VBE after the original code is "autocompleted", in order to be able to correctly determine where to place the caret... and while in *most cases* it's relatively easy, the edge cases are... *insanely* infuriating - so much that I'm considering ditching the feature altogether... which would be a shame, because *when it works*, AC in the VBE is absolutely awesome (IMO).

The crashing reminds me of one such edge case, where typing `msgbox(` would bring everything down in flames. Not sure what the pipe character has to do with it, but generally speaking, AC tends to behave strangely when non-compilable code (or code that mismatches what the VBE would "prettify" it as) is being typed.

**Comment by MDoerner** [comment]
I think the problem here might be that AC uses the `CodeString` class to work with the code and the caret position. This treats the pipe character in a special way, which it really should not for real code.

**Comment by retailcoder** [comment]
I'm adding a `CodeString.PseudoCaret` public static `char`, and making its value `￤` - the VBE can't render that character, so there's no chance of it interfering with anything - that should permanently fix this problem.

**Comment by MDoerner** [comment]
The actual problem here is that the `CodeString` constructor taking an explicit selection removes the pseudo caret character at the selection and that the new position is computed as one to the right nonetheless. This means that we try to set the the position to the right of the code. This causes an exception we do not handle for some reason.

**Comment by retailcoder** [comment]
@MDoerner linked commit moves that logic to `TestCodeString` - leaving that concern completely out of the "production" code path.
