### ISSUE TITLE
Move Closer to Usage Does Nothing Without Notification

### ISSUE THREAD

**Issue by ChrisBrackett** [rubberduck-vba/Rubberduck#4376]
When using the refactor tool "Move Closer to Usage" on a declaration for a variable that is not actually used, RD doesn't move the variable (as it should).  There is no notification so from the user's perspective, no action was performed.

RD should notify the user why it did nothing (i.e. can't move variable closer to usage because it's not used).

**Comment by Vogel612** [comment]
Arguably we shouldn't even provide the **option** to move closer to usage on such variables. The described intended behaviour is fine, though.

**Comment by CHR-IS-B** [comment]
@Vogel612, by not providing the option I assume you mean the menu item would be grayed out.  I agree completely.  I ran into the issue using the default keyboard shortcut so that wouldn't have helped me.

What about playing a sound?  This is how VBE deals with a user who, for example, tries to view "Quick Info" on code that doesn't have any "Quick Info".  It plays the "Windows Ding" sound.
