### ISSUE TITLE
Cannot get to Settings in version 2.2.0

### ISSUE THREAD

**Issue by SanAndTang** [rubberduck-vba/Rubberduck#4445]
On the Rubberduck menu, the Settings submenu does not open the settings window.

**Comment by k-j-kleist** [comment]
The same here, since I updated one (or two?) days ago:
```
Version 2.2.0.4008
OS: Microsoft Windows NT 10.0.17134.0, x64
Host Product: Microsoft Office 2016 x86
Host Version: 16.0.9126.2295
Host Executable: EXCEL.EXE
```

**Comment by MDoerner** [comment]
Thanks for reporting this.

I can reproduce the issue and I am currently investigating which changes caused it.

**Comment by MDoerner** [comment]
This issue has been introduced with PR #4217.

**Comment by MDoerner** [comment]
The origin of the problem is between the two merge commits cd379a103241515b5a1b7eea0cbaba5267e84187 and 3b94644619d9b2496815de3c3b4ea8ff2efb04a1, both syncing with `next`, probably one of the two. I cannot fully pinpoint the origin because the commits from the first sync till before the second one do not load at all. At the point of the first sync `next` was broken and did not load at all, since the merge of PR #4272.

**Comment by retailcoder** [comment]
Should be good now
