### ISSUE TITLE
DeclarationFinder returns UDT variable references as Variant variable declarations

### ISSUE THREAD

**Issue by BZngr** [rubberduck-vba/Rubberduck#4448]
Given a C# Unit Test scenario with the following VBA code:

```
Option Explicit

Private Type MyType
   fld1 As String 
   fld2 As Long 
End Type 

Private mType As MyType

Public Sub Foo(arg1 As Long)
    myType.fld2 = arg1
End Sub

Public Sub Goo(arg1 As String)
    myType.fld1 = arg1
End Sub
```

And a call to `DeclarationFinder.Members` after parsing:
`var declarations = State.DeclarationFinder.Members(<moduleDeclaration>);`

In the `declarations` collection, `mType` references in `Foo` and `Goo` subroutines are returned as a `Variant` variable declarations rather than as `myType` variable references.

Running the 'real' `DeclarationFinder` against this scenario correctly returns the references (and no Variant variables).

(As a side note, `DeclarationFinder.Members` returns all module declarations rather than just members.)

**Comment by MDoerner** [comment]
This issue is also present with RD running in the VBE.

You can observe it by pasting the above code ant selecting `myType` in one of the two procedures. The status bar will show `Variant` as type.

**Comment by MDoerner** [comment]
I think this is not an issue but a typo. 

After looking at the code provided again, I had to realize that the variable `myType` in the procedures is an undeclared variable, and thus `Variant`. This code actually does not compile because of `Option Explicit`. (Note that the variable in the procedures is `myType`, not `mType`, which the VBE makes more explicit by pretty-printing it to `MyType`.)

After changing the variables in the procedures to `mType`, RD in the VBE correctly identifies them as `MyType` variables. Moreover, the following unit test passes:
```csharp
[Test]
[Category("Inspections")]
public void AsTypeNameOfReferencesToUDTTypeMemberAreUDT()
{
    const string inputCode =
        @"Option Explicit

Private Type MyType
    fld1 As String 
    fld2 As Long 
End Type 

Private mType As MyType

Public Sub Foo(arg1 As Long)
    mType.fld2 = arg1
End Sub

Public Sub Goo(arg1 As String)
    mType.fld1 = arg1
End Sub";
    var vbe = MockVbeBuilder.BuildFromSingleStandardModule(inputCode, out _);
    using (var state = MockParser.CreateAndParse(vbe.Object))
    {
        var references = state.DeclarationFinder.AllIdentifierReferences()
            .Where(reference => reference.IdentifierName == "mType");
        var referencedDeclarations = references.Select(reference => reference.Declaration);
        var distinctTypeNames = referencedDeclarations.Select(declaration => declaration.AsTypeName).Distinct();
        var typeName = distinctTypeNames.Single();

        var expectedName = "MyType";

        Assert.AreEqual(expectedName, typeName);
    }
}
``` 

Accordingly, I cannot reproduce the issue with the corrected code. Am I missing anything?

Btw, in the `DeclarationFinder`, `Members` does not have the meaning of module accessible members, but rather of everything with the matching QMN. This includes all variables and the module declaration itself. (It might be a slight misnomer.)

**Comment by BZngr** [comment]
@MDoerner  you are correct - this is a typo, not an issue...Grrrrr.  Looked at this for so long...and didn't spot it....amazing. :(

**Comment by MDoerner** [comment]
No problem. It is rather hard to spot.
