### ISSUE TITLE
More SCP silliness - adding an extra "("

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4468]
RD .4058

Starting with:

    DateSerial(Year|)

Type a `(`, end up with:

    DateSerial(Year((|))

Or, for the most _M_ CVE:

    (|)

Typing a `(` yields:

    (((|))

It also "works" with `{` and `(`:

    {|}

yields

    {((|)}

_However_...

    (|)

Adding a `{` yields the expected:

    ({|})

**Comment by daFreeMan** [comment]
As an additional note, starting with the borked:

    (((|))

hitting <kbd>Backspace</kbd> yields

    ((|)

which ain't right neither...

**Comment by retailcoder** [comment]
I noticed as well, thanks for making an issue for it. Was introduced with the previous prettifier fix. Unfortunately that's the part that can't really be unit-tested, making it vulnerable to such regression issues.

**Comment by retailcoder** [comment]
RE Bakspace: the behavior is correct and as designed. `(((|))` -> `((|)` removes the innermost pair, no problem there. Backspacing works fine.

**Comment by MDoerner** [comment]
[This](https://github.com/rubberduck-vba/Rubberduck/blob/0aaf7c1d7aa08a671de9b708958e1099cc2d954e/Rubberduck.Core/AutoComplete/Service/SelfClosingPairHandler.cs#L69) seems to be the root cause of the issue.

The SCP completion has been applied via `Prettify` but the character typed does not get swallowed because of the bailout.
