### ISSUE TITLE
Some fakes do not play well together

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#4476]
Discovered while developing PR #4475 and verified that it's a pre-existing issue.

Provided the following code, it can be observed that while we can fake the `Date` and `Now` individually without problem, any tests that tries to fake them both will blow up. This is due to the fact that `Date` (aka `rtcGetDateVar`) indirectly calls `Now` (aka `rtcGetPresentDate`) which ends up calling the faked `Now` delegate that's already hooked and then 💣 !

```
'@TestMethod
Public Sub TestMethod1() 'TODO Rename test
    On Error GoTo TestFail
    
    'Arrange:
    Fakes.Date.PassThrough = True
    
    'Act:
    Debug.Print Date ' OK
    
    'Assert:
    Fakes.Date.Verify.AtLeastOnce

TestExit:
    Exit Sub
TestFail:
    Assert.Fail "Test raised an error: #" & Err.Number & " - " & Err.Description
End Sub

'@TestMethod
Public Sub TestMethod2() 'TODO Rename test
    On Error GoTo TestFail
    
    'Arrange:
    Fakes.Now.PassThrough = True
    
    'Act:
    Debug.Print Now ' OK
    
    'Assert:
    Fakes.Now.Verify.AtLeastOnce

TestExit:
    Exit Sub
TestFail:
    Assert.Fail "Test raised an error: #" & Err.Number & " - " & Err.Description
End Sub

'@TestMethod
Public Sub TestMethod3() 'TODO Rename test
    On Error GoTo TestFail
    
    'Arrange:
    Fakes.Now.PassThrough = True
    Fakes.Date.PassThrough = True
    
    'Act:
    Debug.Print Now
    Debug.Print Date '<== KA-BOOOM
    
    'Assert:
    Fakes.Now.Verify.AtLeastOnce
    Fakes.Date.Verify.AtLeastOnce
    
TestExit:
    Exit Sub
TestFail:
    Assert.Fail "Test raised an error: #" & Err.Number & " - " & Err.Description
End Sub
```

**Comment by comintern** [comment]
My best guess without have dug around in it is that there's probably some confusion over who is responsible for the memory of the `Variant` that is getting passed around, the wrong dll tries to free it (vbe7, RD, and easyhook are all touching it), and... access violation.

My money is on RD, but the forwarded calls need to be sorted out regardless of the resulting Appslosion  because this will also give incorrect testing results due to multiple hooks tracking the same invocation.
