### ISSUE TITLE
Code Explorer search bar is invisible

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#4478]
ref. #4477 

The CE search bar is subconsciously picked up as empty space, which makes it invisible for some users.

Let's add a <s>big flashing purple arrow</s> subtle gray watermark "search" text in the search bar - IMO that'll give it just the little nudge it needs to become more easily discoverable, without being obnoxious once you know it's there.

**Comment by Inarion** [comment]
Heh, I'm totally aboard the "subconsciously identified white space" train. I guess my projects haven't been large enough to be needing the search function.

This appears to me like a very fine example of a good first issue. Maybe this should be the moment where I install VS...?

**Comment by Inarion** [comment]
Can someone please assign me to this issue? I want see how far I can get with it. :)

I've done some research on the weekend and it seems to me that a functionality like *watermark*, aka *cue banner* is not natively supported by [`textbox` controls](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.textbox?redirectedfrom=MSDN&view=netframework-4.7.2). (I initially assumed that all it would take to resolve this issue was to set a property - it now seems it's a bit more involved than that.)

[This SO question](https://stackoverflow.com/questions/833943/watermark-hint-text-placeholder-textbox) has about one million answers showing different implementations of a watermark functionality. We could take a solution from there; some of them are XAML-only - though at this point it's not clear to me how to implement it in a way that makes the functionality reusable.  
Or we elect to make use of an existing [collection of adorners](https://github.com/GuOrg/Gu.Wpf.Adorners) - not sure what the stance is regarding additional libraries.

**Comment by rubberduck203** [comment]
Cool. Go for it!

**Comment by Inarion** [comment]
@comintern I just saw in that demo for the new CE that you implemented a watermark there. Which probably means, nothing more needs to be done here?  
I'll remove my assignment in any case, as it's unlikely I'll get anything done in the foreseeable future.

**Comment by comintern** [comment]
@Inarion Gah! Sorry about that, I completely missed this issue when I was trolling for CE related tags.

**Comment by comintern** [comment]
Not big or flashing purple, but closed by #4661
