### ISSUE TITLE
"Find all references" missed a couple

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4479]
Win10, Excel2016 (desktop), RD build .4070

After using `Refactor | Rename` to rename a class member, I used `Find all references` to return to where I was making some changes. The locations where I was working did _not_ show up in the list of search results.

![2018-10-31 14_42_44-microsoft visual basic for applications - satisfaction summary master v3 26 - de](https://user-images.githubusercontent.com/11889733/47811322-dc9e0880-dd1b-11e8-859c-a68ba507c8d5.png)

As you can see, there is no scroll bar in the dialog, so it's not off the bottom of the display. There are 3 references in this particular `Sub` that do _not_ appear in the result set.

_Note: Ignore the redundancy in the code - it's undergoing revision at the moment, some of that is cruft that's about to be cut out._

**Comment by retailcoder** [comment]
Question impacting the severity of this issue: did the refactor/rename actually miss any references?

**Comment by comintern** [comment]
What's the full signature of `GatherSatSurveyData`?  Is `CI` declared as an interface or a concrete implementation?  IIR that needs some work.

**Comment by daFreeMan** [comment]
The Rename _did_ seem to get all references - the code now compiles clean.

The full signature:

    Private Sub GatherSatSurveyData(ByVal projSettings As ProjectSettings, ByVal Clinics As ProcessClinic, ByRef CI As ClinicItem, ByRef dbConfig As DBConfiguration)

Saved the file, closed & reopened Excel - still having the same issue.

**Comment by retailcoder** [comment]
This is by design. MCVE:

```vb
Sub test()
    foo = 10
    Debug.Print foo
    foo = 27
End Sub

Property Get foo() As Long
    foo = 42
End Property

Property Let foo(ByVal rhs As Long)
    Debug.Print rhs
End Property
```

If you put the caret on the `foo` of `foo = 10` in the `test` scope, you'll see "2 references" in the RD toolbar, with the info label saying "projectname.modulename.foo (property let accessor)" - selecting the `Property Let` accessor gets you the `Property Let` references. *Find all references* then lists `foo = 10` and `foo = 27`.

If you put the caret on the `foo` of `foo = 42` in the `foo` scope, you'll see "2 references" in the RD toolbar, with the info label now saying "(property get accessor)". *Find all references* then lists the `foo = 42` return value of the `Property Get` member itself, as well as the `Debug.Print foo` instruction, which effectively involves the getter.

Refactor/rename ensures the accessors of a property are renamed consistently, but this behavior of *Find all references* isn't wrong per se - that said the behavior being by-design doesn't mean things don't need to be improved: the tab name in the *Search Results* toolwindow should probably say:

> All references: 'foo' (Get)

Or

> All references: 'foo' (Let)

As it stands, we can have too tabs that say

> All references: 'foo'

Each with different, valid, up-to-date content.

**Comment by comintern** [comment]
Visual Studio is a bit spastic on this one. If I use find all references on a getter, it gives this:

![screenshot from 2018-11-13 22-59-39](https://user-images.githubusercontent.com/8944005/48461197-1b11d980-e798-11e8-85e1-2bf84466805b.png)

Note that it puts "get_CompileOnDemand" in the window caption, but shows results for both the get and set.

**Comment by retailcoder** [comment]
![image](https://user-images.githubusercontent.com/5751684/48462031-74800580-e7a4-11e8-8ba6-b21283dbb06c.png)
