### ISSUE TITLE
Code inspection "Variable is used but not assigned" issue

### ISSUE THREAD

**Issue by inDeev** [rubberduck-vba/Rubberduck#4485]
Hi, can you look on attached image, please?
Code inspector is alerting me about some Variant variables, that them are not assigned, but as you can see, they are.

![code-inspector-bug](https://user-images.githubusercontent.com/8944005/47918261-0c632280-de7a-11e8-8185-bf07e701710f.jpg)

[https://image.ibb.co/cy6Xxf/Code-Inspector-bug2.jpg](url)

**Comment by comintern** [comment]
Thanks for taking the time to report this. This is a known issue, and it is caused because we're currently not handling `ReDim` statements correctly (see the Jun 20 comment on #4107).

Also see #3765 (there may be others).

If this is causing too much "noise" in your inspection results, I'd suggest giving it a quick scan for ones that are not false positives, then disabling the inspection in settings before you inspect the project.

**Comment by retailcoder** [comment]
@comintern there's a problem with `ReDim` being used for declaring arrays (#4353), but that's only a problem when the array isn't already declared with a `Dim` statement. Seems this is caused by something else, given there *are* `Dim` statements for every array here.

The resolver is (correctly) skipping the `foo(i) = bar` assignments, because they're not assigning `foo` itself - but the inspection isn't seeing that the arrays are arrays (because they're declared `As Variant` and not as an explicit array).

This code fires the false positive:

```vb
Sub test()
    Dim foo As Variant
    ReDim foo(1 To 10)
    foo(1) = 42
End Sub
```

But this doesn't:

```vb
Sub test()
    Dim foo() As Variant
    ReDim foo(1 To 10)
    foo(1) = 42
End Sub
```

I'll make a separate issue for the `AssignmentNotUsed` inspection having the same problem here (it's wrongly firing a result about `foo` assignment not being used - but it's not `foo` that's being assigned), but I don't think getting `ReDim` statements to create an array local variable declaration will fix this: the inspection itself (both of them) needs to somehow understand that this `Variant` is an array, and thus should be ignored.

**Comment by retailcoder** [comment]
linking #4486
