### ISSUE TITLE
How do I get notified of new Rubberduck builds?

### ISSUE THREAD

**Issue by MikeAndLisa** [rubberduck-vba/Rubberduck#4514]
Can we please have latest version emails.

Regards
Mike Green

**Comment by Vogel612** [comment]
You can subscribe to the repository on Github as an intermediate workaround. I don't think subscribing to a list for pre-releases is a viable idea, the feed volume seems unreasonably large.

Additionally whenever you start rubberduck, it checks for a newer release if you have enabled the "check for updates" feature.

**Comment by retailcoder** [comment]
For pre-releases, you can get that directly from GitHub, by [watching](https://github.com/rubberduck-vba/Rubberduck/watchers) the repository - if you filter for notifications from @rubberduck-vba-releasebot then you'll get an email notification for every pre-release build, as soon as it's available (that is, whenever a pull request is merged); note that pull requests are sometimes merged in batches, so it's not impossible that a pre-release build becomes available, only to be superseded 20 minutes later by the next build. Watching the repo for everything _can_ get noisy though (*looks at own inbox... yep*), so an inbox rule to filter for releasebot notifications can really help cut the noise.

Since v2.0.12 (IIRC), Rubberduck sends an asynchronous HTTP request (you may opt-out through settings) to http://rubberduckvba.com/build/version/stable and compares the returned version number with the version that's currently running - a mismatch triggers a prompt saying that a newer version is available; okaying that prompt takes you to the [latest release](https://github.com/rubberduck-vba/Rubberduck/releases/latest) page. The later 2.2.x pre-release builds ensure the asynchronous request isn't left lingering if the host process is shut down before a response is returned. This is currently working off an actual web deployment of the RD build, but will probably eventually end up working off the GitHub API.

You may also follow the [RD News](https://rubberduckvba.wordpress.com/) blog, where an official stable release is definitely going to be announced. There's a widget on the sidebar that counts down the days to the next release, once we've committed to a date (v2.3.0 isn't committed yet). Blog posts are automatically published on the [@rubberduckvba Twitter feed](https://twitter.com/rubberduckvba) and the [Rubberduck on Facebook](https://www.facebook.com/rubberduckvba/) page.

**Comment by MikeAndLisa** [comment]
Thank you soooo much Mathieu!!!

Much appreciated.

Mike


________________________________________

**Comment by daFreeMan** [comment]
"once we've committed to a date (v2.3.0 isn't committed yet)"

_pokes the duck_

**Comment by retailcoder** [comment]
@daFreeMan fair enough; I think Nov.25 makes a good target and leaves us some time to update the translations and bugfix & polish a bit.

**Comment by MikeAndLisa** [comment]
thank you Clemens!

Mike

________________________________________

**Comment by MikeAndLisa** [comment]
YES!!!!

Thank you!!

________________________________________
