### ISSUE TITLE
.resx needs a clean-up

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#4541]
There are a number of resource strings that were copied from the old `RubberduckUI.resx` file and into smaller, more specialized & manageable, namespaced resource files - but remained in their original location, resulting in duplicate keys.

There are also a number of duplicate resource strings *under different keys*, that should probably be consolidated.

Basically, string resources need a clean-up.

**Comment by bclothier** [comment]
[Ref](https://github.com/rubberduck-vba/Rubberduck/pull/4769#discussion_r257172372)

In addition to the issues highlighted in the OP, we should consider cleaning up the key names. Because they came from a single huge resx originally, they had a prefix in the key name which now look very redundant now that we have a specialized .resx file. Those should be stripped out to make the already long names somewhat shorter.

**Comment by IvenBach** [comment]
I'm willing to wade through this one. Initially perusing RubberduckUI.resx and ToDoExplorerUI.resx I see duplicates. I know my lizard brained `Ctrl+F` search is sub-optimal. What's the best/preferred/easiest way to do this?
