### ISSUE TITLE
`Return value for member 'Test' is never assigned` false positive

### ISSUE THREAD

**Issue by wqweto** [rubberduck-vba/Rubberduck#4545]
. . . when function retval is assigned through a ByRef output param.
```
Public Function Test() As Long
    pvSetValue Test
End Function

Private Sub pvSetValue(RetVal As Long)
    RetVal = 42
End Sub
```

**Comment by retailcoder** [comment]
`ByRef` assignment has always been the bane of that inspection.. I'll try to sneak a tweak in #4529

**Comment by retailcoder** [comment]
Making significant progress on this - just making a note that the logic will need to be reused for the "variable not assigned" inspection.

Also note, I'm only going 1 level down: if `pvSetValue` passes `RetVal` to some other procedure `ByRef` and *that procedure* is making the assignment, `Test` will still be flagged by this inspection: this is a performance compromise, since tracking whether a parameter is assigned given an argument, is rather expensive.

**Comment by retailcoder** [comment]
@MDoerner pointed out a very valid complication: when the callee (e.g. `pvSetValue` here) is a member of a class module; Rubberduck can't take the member at face value and can't reasonably be sure that the member it's resolving to is the member that will execute at run-time, because the containing class could be implemented by an unknown number of other classes. So the inspection will bail out if the callee isn't in a standard/procedural module.
