### ISSUE TITLE
New inspection: "Wall of Dim"

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4563]
A good hint-level inspection:

```VBA
Private Sub Foo()
  Dim Bar as Long
  Dim Baz as String
  Dim Sum as dinner

 'some code here

  Bar = 1000000
```

Flag `Bar`, `Baz` and `Sum` with a "Wall of Dims" or "Consider moving closer to first usage" inspection result. 

Quick Fixes:
1) Existing "Move Closer to Usage" refactor 
1) Ignore Once

**Comment by FuSoftware** [comment]
Will it require a fixed "wall height" ? Because it's heavily subjective. For the sake of it :
```
Dim i as Long
Dim Bar as Long
Dim Baz as String
Dim Sum as dinner

Sum = 0
Baz = 1
Bar = 1000000

For i=Sum To Bar Step Baz
'...
```
This kind of stuff is bad code, okay, but then again all declarations are used almost immediately, 

Also :
```
Dim Sum as dinner
Sum = 0

Dim Baz as String
Baz = 1

Dim Bar as Long
Bar = 1000000

Dim i as Long
'...
```
Even if the variable are initialized right under the declaration, it still is a "wall of declaration". So I doubt it can be properly put i place since it's so subjective

**Comment by retailcoder** [comment]
@FuSoftware is right, this inspection is opinionated, despite its good intentions. Users that don't like walls of declarations can already refactor / move closer to usage.
