### ISSUE TITLE
Experimental COM/reflection API is no longer exposed

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#4603]
The experimental COM/reflection API has been unavailable since the COM cleanup, apparently:

![Object Browser showing members in the Rubberduck type library](https://user-images.githubusercontent.com/5751684/49452626-89eabd00-f7af-11e8-92eb-0019acc125aa.png)

Now is probably a good time to review the design then.

**Comment by bclothier** [comment]
Actually the COM API has been moved to their library:

![image](https://user-images.githubusercontent.com/2367644/49453008-e053fd80-f7a7-11e8-9fd8-e65e9d2a7672.png)

aka `Rubberduck.API.dll`/`.tlb`.

**Comment by retailcoder** [comment]
I had to manually browse to the tlb location in the install folder... is something off with the registration?

**Comment by bclothier** [comment]
The issue is with VBE, not with how we register our libraries. VBE has had exhibited strange behavior in how it choose to display libraries in a list and this has been observed even with Microsoft's own libraries such as shell32.dll.

For that reason, I'm inclined to close this as <kbd>status-bydesign</kbd> with the suggestion that the workaround is to use the upcoming reference explorer.

**Comment by retailcoder** [comment]
Agreed! I get this feeling many will even forget what the VBE's *Project References* dialog even looks like in a few weeks... I'd suggest we default the RD libraries to the *pinned* tab.
