### ISSUE TITLE
RD Crashes while resizing code explorer window

### ISSUE THREAD

**Issue by Stonovsky** [rubberduck-vba/Rubberduck#4607]
As it is written in the topic - RD crashes (together with MS Access) when I resize RD code explorer window or close VBE code explorer window when both (RD and VBE code explorers) are displayed. It seems that RD crashes while RD code explorer is resized or moved. Thank you for any advice how to solve this problem.

**Comment by daFreeMan** [comment]
The first step would be to provide an RD log. Go to `Rubberduck | Settings`, make sure logging is set to `Trace` level, then trigger the crash. Go back to `Settings` then click the "Log folder" button to go to the directory where the logs are stored and upload `Rubberducklog.txt`.

**Comment by bclothier** [comment]
I just tried this on Access 2010 and nothing happened. It might be a specific sequence of steps. Please provide that as well.

**Comment by retailcoder** [comment]
reminiscent of #2936

**Comment by Stonovsky** [comment]
Dear All thank you for answers. After I post this issue I couldn't open Access VBE at all - it immediately crashed all the time (but Excel VBE worked but slowly). So I uninstalled RD, erased all folders connected with RD, scan and remove registry issues using CCleaner, reset the computer, install RD and now it works like a charm. Ufff... I do love RD and could not imagine writing VBA code without it :)

**Comment by retailcoder** [comment]
@Stonovsky thanks! Docking in the VBE is.... "special", and repro steps for this particular issue can be inconsistent and/or rather hard to pin down. IIRC a work-around for the linked issue is to avoid dragging toolwindows when they are docked, i.e. undock them first, *then* dock them elsewhere. Not sure how to go about *resizing* a docked toolwindow though, but it's very possibly related.

**Comment by bclothier** [comment]
The fact it was consistently crashing after that crash makes me think it got persisted to the VBE's registry setting. See, VBE stores all the windows' positioning & docking within a registry key `Dock`, which is a binary format. If it's that you managed to find a certain positioning that would cause the crash and that got saved, then it would consistently crash everytime you open the VBE, since it'll read from the registry key. Two ways to avoid that would be to disable RD temporarily or to delete the `Dock` key (which will lose all the positoning and you must re-set them all -- not just RD's toolwindows but *all* toolwindows.

For reference, the `Dock` key is stored in this path:
`HKEY_CURRENT_USER\Software\Microsoft\VBA\*\Common`
where `*` may be either `6.0` or more likely, `7.0`.

**Comment by bclothier** [comment]
I'd like to check if this issue still persist even in the latest pre-release. Does it?

**Comment by bclothier** [comment]
Closing this as stale. If anyone observe this, one is welcome to reopen it.
