### ISSUE TITLE
Return value not used false positive given object variable

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#4625]
This function:

```vb
Public Function GridCoordToRange(ByVal gridId As Byte, ByVal position As IGridCoord) As Range
    With PlayerGrid(gridId)
        Set GridCoordToRange = .Cells(position.Y, position.X)
    End With
End Function
```

Is used here:

```vb
Private Sub IGridViewCommands_OnSelectPosition(ByVal gridId As Byte, ByVal position As IGridCoord)
    If sheetUI Is Application.ActiveSheet Then
        sheetUI.GridCoordToRange(gridId, position).Select
    End If
End Sub
```

The `.Select` is a member call against the returned `Range` object, yet the inspection still deems the return value "not used". This is a false positive.

**Comment by bclothier** [comment]
The issue is with this part:

https://github.com/rubberduck-vba/Rubberduck/blob/b4f45bf0f076519375fc3a0467d1974c919477af/Rubberduck.CodeAnalysis/Inspections/Concrete/FunctionReturnValueNotUsedInspection.cs#L107-L120

The argument list comes up `null` which cause the procedure to return `true`, which I think is incorrect. 

It's not exactly clear to me why we're doing this, though - it *looks* like this was meant to handle the case where the return value is used as an argument to some other call expression, but in this case, we're probably getting the `Select()` argument list, not the `GetRange(x)` argument list.

**Comment by bclothier** [comment]
Actually, fortunately, we had 2 other unit tests that covers a related scenario which helped narrow down the correct changes:

`FunctionReturnValueNotUsed_ReturnsResult_InterfaceMember` and `GivenInterfaceImplementationMember_ReturnsNoResult`

Unfortunately, I'm not 100% happy with the changes which currently passes all the tests including the new unit test reproducing this issue. This is the change:

```
            var indexExpr = usage.Context.GetAncestor<VBAParser.IndexExprContext>();
            if (indexExpr != null)
            {
                var memberAccessStmt = usage.Context.GetAncestor<VBAParser.MemberAccessExprContext>();
                if (memberAccessStmt != null &&
                    callStmt.SourceInterval.ProperlyContains(memberAccessStmt.SourceInterval) &&
                    memberAccessStmt.SourceInterval.ProperlyContains(indexExpr.SourceInterval))
                {
                    return false;
                }
            }
```

Which feels a bit *too* specific. With the interface tests, it would fail if I tested only the `MemberAccessExpr`; it did not have `IndexExpr` expression, so I had to add that to the check to ensure that interface unit tests will still get results while the chained member access will not. 

Can that be done better?
