### ISSUE TITLE
@Description annotation

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#4626]
Annotations can no longer be used at both module and member level (right?): modules that have a `@Description` annotation are now tripping the "Illegal Annotation" inspection, which is fine - but there's no `@ModuleDescription` annotation, and the corresponding `VB_Description` attributes don't get synchronized.

Do we kill it? Or cure it? How?

**Comment by MDoerner** [comment]
We could simply add the `ModuleAnnotation` flag to the `@Descrption` annotation. Than, it will also work for modules.

**Comment by bclothier** [comment]
On the one hand, we already have the procedure separator to tell us which procedure we are in. Thus a `@Description` in a `(Declarations)` should be obviously a module level description. We can pass this off as a user-training issue; they need to actually use the separators to guide them to how they should place the annotations.

The above assumes that it is not possible to have that applied to any other elements in the declarations... right? If that assumption is incorrect then the only sensible option is to have an explicit `@ModuleDescription` to avoid it from getting applied to any elements within the declarations section or the first member by mistake.

**Comment by retailcoder** [comment]
The more I think about it, the more a `@ModuleDescription` annotation makes sense and simplifies telling it apart from valid and legitimate annotations that would describe public fields, for example.

So, let's leave it the way it is and treat `@Description` as illegal for a module-level docstring, and let's introduce a `@ModuleDescription` annotation when we're ready to make the corresponding `VB_Description` attribute synchronize for module-level (along with `@PredeclaredId`).

**Comment by MDoerner** [comment]
Let me clarify a few things. We no longer consider the anything from the VBE API to determine the scope of an annotation. All annotations above a member are scoped to the member until the is a line without a member annotation. Moreover, because not applying module annotations present in these sections was perceived as unintuitive, we apply all module annotations above the first member to the module.

Furthermore, the description for module variables has to be different because the attribute is different. (`VarDesc`)

Introducing a new `@ModuleDescription` would certainly be the easiest fix.
