### ISSUE TITLE
Invalidate test results on an individual basis rather than all results when running tests

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#4705]
Originally from https://github.com/rubberduck-vba/Rubberduck/issues/4698#issue-397357974

> In the latest release (2.3.1.4308) a refresh will reset the status of all of my tests regardless of whether or not they have been affected. I remember this not being an issue with the previous version I used, although I can't remember which version that was. In general it makes writing tests and adding new tests a real chore as you have to either find the test you are working on in the menu and run that, or run every test for every change you make to either your code or your tests.
> 
> Ideally I want how it used to work as I remember that working "as expected".
> 
> **To reproduce**
> 
>     1. Make an empty sheet with a test module with one empty test.
> 
>     2. Run the test
> 
>     3. Click refresh
> 
> 
> _Edit (added the version/host info)_
> 
> Version 2.3.1.4308
> OS: Microsoft Windows NT 10.0.17134.0, x64
> Host Product: Microsoft Office x86
> Host Version: 16.0.11029.20108
> Host Executable: EXCEL.EXE

The idea is that the test explorer should be more smart about invalidating only results for tests that actually got ran. The way it is, it will reset all tests' status, which is different from how most unit testing framework behaves. That would make RD's framework more consistent with say, NUnit or MSTests.

**Comment by bclothier** [comment]
Neither Nunit nor MS Test provide that functionality, do they?

Normally, Nunit resets the results after a build. In our case, after a reparse is good enough reason to reset. I am hard pressed to think of a scenario where I should need one except one... Automatic resets via reparse are not reliable enough. But that isn't what we are facing, are we?

**Comment by comintern** [comment]
My working code currently checks to see if an existing test has exactly the same code after the reparse and resets the status if it doesn't.  So basically, the only way that the test result can change is if it is re-run or the test code itself is modified.  That means the test explorer will always show the result from the last time the test was run using the current parse. IIR this matches the behavior of NUnit - I've only seen them reset there if the test itself changes - making code changes or recompiling things that are under test doesn't change the result in the Test Window.  

AFAICT, the behavior that I currently have basically matches that.  I was trying to think of use cases where you would want to override that though - I added code when I was debugging to force all tests back to a "not run" result so I didn't have to keep closing and reopening Excel while I was live testing it. If there's a use case for it, I can hook a toolbar button up and leave it in.  Otherwise, I'll remove it.

**Comment by bclothier** [comment]
That probably can stay as a debugging tool, just like that serialize button.

One uncertainty I have is how NUnit behaves when you change the code of the SUT. Does it also reset the status in that case? I want to say yes but indirectly; it would trigger a rebuild of assembly which would then reset the covering tests, but I am not at VS to confirm that my memory isn't making it up.

**Comment by comintern** [comment]
If it does change the SUT for covered code, it's either an optional setting somewhere or mine is borked.
