### ISSUE TITLE
"Open Designer" does not work for document modules

### ISSUE THREAD

**Issue by Gener4tor** [rubberduck-vba/Rubberduck#4708]
When I select a Form in the CodeExplorer and click on "Open Designer" nothing happens.

The same Nothing happens when I choose "Open Designer" in the Context menu...

In the VBE-build-in-Explorer the function "Show Object" works...

**Comment by Vogel612** [comment]
What Version are You on? Because this issue has been previously raised and fixed at #4605

**Comment by Gener4tor** [comment]
This is my version:

Version 2.3.0.4221
OS: Microsoft Windows NT 10.0.16299.0, x64
Host Product: Microsoft Office 2016 x86
Host Version: 16.0.4711.1000
Host Executable: MSACCESS.EXE

**Comment by Vogel612** [comment]
This is the same version as reported in the linked issue. Please update rubberduck to the [current latest green release (v2.3.1.4308)](https://github.com/rubberduck-vba/Rubberduck/releases/tag/v2.3.1) and check whether the issue persists.

**Comment by Vogel612** [comment]
Access Forms are possibly a special beast... They are possibly not recognized as components with a Designer.

**Comment by bclothier** [comment]
A more complete solution could be in this form:

1) Add a `bool CanOpenDocuments()` and `bool OpenDocument(QualifiedModuleName module)` methods to the [`IHostApplication` interface](https://github.com/rubberduck-vba/Rubberduck/blob/c13d151132c32d175fe763d65264f176bee39d40/Rubberduck.VBEEditor/SafeComWrappers/VB/Abstract/IHostApplication.cs)
2) Implement virtual methods in [`HostApplicationBase` abstract class](https://github.com/rubberduck-vba/Rubberduck/blob/c13d151132c32d175fe763d65264f176bee39d40/Rubberduck.VBEEditor/SafeComWrappers/Abstract/HostApplicationBase.cs), defaulting `CanOpenDocuments` to always `false` with `OpenDocument` being a no-op.
3) Implement the Access-specific methods for opening document in design view in [`AccessApp` class](https://github.com/rubberduck-vba/Rubberduck/blob/c13d151132c32d175fe763d65264f176bee39d40/Rubberduck.VBEditor.VBA/SafeComWrappers/Application/AccessApp.cs), taking care to dispose the `DoCmd` object and containing appropriate checks. 
4) Update the code explorer so that if it gets `CanOpenDocument` = `false`, to disable the `Open Designer` menu item when it's a document module. Otherwise, it will enable the menu and defer the implementation to the host application. The code explorer also should have `View Object` listed separately in the context menu at all the time (since it serves a slightly different function).
