### ISSUE TITLE
DeclarationType is not correct for documents

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#4724]
That was discovering while fixing #4708 -- for documents, they are given `DeclarationType.ClassModule`. That is because of the document falling into the `default` case:

https://github.com/rubberduck-vba/Rubberduck/blob/dda930087260194b2e3935fac1171143b6f5cdf4/Rubberduck.Parsing/VBA/DeclarationResolving/DeclarationResolveRunnerBase.cs#L186-L213

The fix is trivial; we can just add a `isDocument = false` to the `ClassModuleDeclaration` and set the declaration type accordingly. The fix does not break any unit tests which is a red flag that there is insufficient coverage so we may end up breaking more things than fixing. We will need to do a careful review of the code to determine the risk and pay this technical debt. There are likely callers out there that are unnecessarily checking both declaration types and component types because of that.

**Comment by MDoerner** [comment]
I reclassified this because, first, it really requires to know how to handle the change in a lot of places in RD and, second, because this is not a bug but a know and at one point probably intentional quirk of the setup of the type enums in RD. (It also applies to user forms.) 

That no test broke is not surprising since we generally do not add tests regarding document modules to test fixtures not explicitly sealing with host specific features.
