### ISSUE TITLE
ThunderCode Inspection

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#4778]
@ThunderFrame is sorely missed, and we want to include *at least* one Easter Egg to honor his many contributions to the project. One idea is to make an inspection that trips on *ThunderCode* - the trademark edge-cases we all went "wuuut" when he revealed them.

Ideas include:

- Non-breaking spaces in identifier names
- Keywords as `Enum` and/or `Type` members
- `Rem` comments, but with the `Rem` token followed immediately by a special character (there's a whole list somewhere)
- Line continuations in unexpected places, like between `End` and `Sub`.
- Fiendishly brain-melting ambiguous naming, like #973

Any others?

Also, needs a description - suggestion:

> **ThunderCode!**  
> Andrew "ThunderFrame" Jackson would be proud! You're seeing this inspection result because there's no way that's real code and you're just pushing the limits of Rubberduck's parsing and resolving capabilities, right? ...RIGHT? In memoriam, 1972-2018

False positives are not allowed to happen here. Thoughts?

**Comment by PeterMTaylor** [comment]
Did Thunderframe found out you can find out the type of variable in the immediate window?

**Comment by MDoerner** [comment]
The `Rem` comment thing will most likely not work. When the special character is also a type hint, the VBE swallows it. Thus, we have no chance to recognize the comment.
If we would not faceplant on it, I would add spaces and instruction separators in enum names to the list. (The crazy thing where you use a foreign name identifier for the enum name and the VBE prettyfies away  the brackets.)

**Comment by comintern** [comment]
How about line numbers in hex?

**Comment by daFreeMan** [comment]
Since <s>most</s> exceptionally few coders (especially VBA coders) aren't dastardly enough to trip a ThunderCode inspection, maybe add an egg that's sure to trip. 

On the anniversary of his birth or death (if these are known), or first or last PR to the RD codebase, pop an alternate ThunderDuck logo with a note about his contributions. Alternatively/in addition, the "About" box could display the alternate logo on that day, as well. This would (hopefully) alleviate bug reports, since people would (hopefully) go to the "About" box to get the version info and see the reasoning behind the alternate logo.

**Comment by bclothier** [comment]
Unfortunately, we cannot implement the inspections for the following cases:

1) unusual characters in an enum name
2) use of hex in line numbers (at least for negative numbers)

Those 2 result in a parser error, so no inspections can be had.

3) Ambiguous naming

While doable, I'm worried that the performance will be horrid since in order to determine if the name is ambiguous, I'd have to compare n^n identifiers (more or less) which is O(MG).
