### ISSUE TITLE
Odd characters in Code Explorer

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4811]
**Rubberduck version information**
Version 2.4.0.4533
OS: Microsoft Windows NT 10.0.15063.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.4795.1000
Host Executable: EXCEL.EXE

**Description**
When an Excel file name is too long to be completely displayed in the Code Explorer, I'm seeing odd non-English characters in my English Excel installation

**To Reproduce**
1. Give an Excel file a long name
2. Open the Code Explorer in a pane that's not wide enough to display the whole name
3. Profit! (or not)
4. oh... See error

**Expected behavior**
One would expect an ellipse `...` when a long name is truncated.

**Screenshots**
![2019-02-18 07_40_57-microsoft visual basic for applications - satisfaction summary master v3 31 - de](https://user-images.githubusercontent.com/11889733/52951931-1c334380-3351-11e9-85ed-5cfffd1dab8c.png)

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2875627/RubberduckLog.txt)

**Additional context**
Noted this a build or two ago, but never had a chance to report it.

**Comment by MDoerner** [comment]
This seems to be an unfortunate effect of a bug in the `Window.Caption` property in the `VBIDE` library. 

We currently use the caption of the VBE window to get the document name. For documents with a sufficiently long name, this caption gets rather long. This is where the `VBIDE` bug comes into play. Apparently, the backing field for the `Caption` property of the window has a rather small maximum size. (Note that this is separate from the actual code displaying the window.) In case a string is too long, it seems to only copy up to some number of characters smaller or equal to the maximum size of the backing field. Unfortunately, this seems to be interpreted as a null-terminated string. Since the original string goes on, there is no null character to terminate it. So, you get to see all memory until the next 16-bit value that is zero.

**Comment by daFreeMan** [comment]
Would it be reasonable to work around the bug by looking for the two characters that seem to be consistently displayed and replacing them with an ellipse if they appear?

I mean, RD fixes a lot of the VBE's other sins...

**Comment by MDoerner** [comment]
I think we can work around this issue by first trying to get the name from the filename and only getting it from the caption if the document is not saved. In that case, the name should usually not be too long.

**Comment by daFreeMan** [comment]
An alternate potential solution would be to determine if the width of the displayed string would extend off the edge of the CE and self-truncate with an elipsis `...`.
