### ISSUE TITLE
Grammar license

### ISSUE THREAD

**Issue by shlnz** [rubberduck-vba/Rubberduck#4836]
Hi,

I was wondering if it's possible to change the grammar license.
As @retailcoder already described [here](https://github.com/decalage2/ViperMonkey/issues/19#issuecomment-274238282), the grammar is more a completely new implementation than a further improvement from the [grammar repository](https://github.com/antlr/grammars-v4/blob/master/vba/vba.g4). 
The GPL license forces other projects to be published under the GPL license, which is often not possible for commercial software ([link](https://opensource.stackexchange.com/questions/1926/is-the-code-generated-from-a-gplv3-ebnf-grammar-a-derivative-work)).

**Comment by Vogel612** [comment]
If we were to change the license, since we nominally do depend on the GPLv3 basis of the Grammar, we'd be opening ourselves up to a copyright infringement lawsuit.

Whether or not the grammar is a completely new implementation is at least somewhat debatable and I'd personally not want to take the risk of fighting these peculiars out in a court of law...

To change the license of the grammar you'd need to reach out to **at least** the following people and get their written agreement:

 - Ulrich Wolffgang <u.wol@wwu.de> (original author)
 - Andrin Meier (@ autoboosh) who did extensive work on it during their involvement in RD
 - Max Doerner (@ MDoerner) who also did extensive work on the grammar
 - Mathieu Guindon @retailcoder and me
 - Andrew Mansell (@ mansellan)
 - Scott Denison (@ ScottDenison) who did some great work on the host language predicates and fixed a bug around module configuration members

From my side, this gets a clear no. It's too dangerous that I missed someone in the quick research here. If you want to take that risk, you have my express consent to consider my contributions to the grammar licensed under MIT/Apache2.0 :)

**Comment by Vogel612** [comment]
I've just been told by Max that apparently @ Hosch250 also contributed to the grammar, which just further illustrates my point about the specific issue that's IMO prohibitive here.

**Comment by Hosch250** [comment]
Same. I prefer MIT/Apache 2.0 to (L)GPL, so I have no issue with relicensing my contributions. However, I agree with @Vogel612 that this is a legal risk we probably do not want to take.

**Comment by comintern** [comment]
I think this is a non-issue. The "traditional" way of dealing with this is to separate the GPL and non-GPL components, and then publish the source code of components that fall under GPL.  It does ***not*** prevent commercial use unless you are conflating the idea of "proprietary" with "commercial". The license is about the accessibility of the source code and the source code of derived works. It is not about the ability to sell it. Anyone *could* sell Rubberduck itself if they wanted to, they would just need to release the source code.

**Comment by Vogel612** [comment]
So there has been a discussion in the publicly visible chatroom frequented by the core development team [staring around here](https://chat.stackexchange.com/transcript/message/49266564#49266564). The gist is: We're not going to relicense the grammar for multiple reasons:

 - Commercial use is not prohibited by the GPL license
 - The risk posed by a relicensing is not something that we want
 - Rubberduck itself will remain GPL licensed software (if only for the Smart Indenter source code)
 - A relicensing does not give us as development team **any** benefit whatsoever. We stand to gain nothing from this.
 - We very much value the attribution clause, thanks :)

With that I'd consider this request declined and the issue closed. Thank you for asking.
