### ISSUE TITLE
On Error Goto -1 causes a "That's not real code" (Thundercode) error

### ISSUE THREAD

**Issue by MegaDudeNZ** [rubberduck-vba/Rubberduck#4886]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

Version 2.4.1.4627
OS: Microsoft Windows NT 10.0.17134.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.11328.20222
Host Executable: EXCEL.EXE

**Description**
On Error Goto -1 is a legitimate statement to clear a previous On Error statement 
See https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/on-error-statement

The parser sees the -1 and thinks it's a negative line number, then lists it as a code quality issue saying "Andrew "Thunderframe" Jackson would be proud!  There's no way that's real code"

PS Awesome work guys - Rubberduck is fantastic!

**Comment by retailcoder** [comment]
Here's the documentation for the `On Error` statement *in VBA*: https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/on-error-statement

Note that `GoTo -1` isn't one of the documented options, and experimentation leads me to believe that in VBA `On Error GoTo -1` is indeed legal, but behaves exactly like `On Error Resume Next` outside of an error-handling subroutine, **and has nefarious, undocumented side-effects inside an error-handling subroutine**:

```vb
Public Sub DoNotRunThis()
    On Error GoTo Oops
    Debug.Print 1 / 0
    Exit Sub
Oops:
    On Error GoTo -1
    Debug.Print 1 / 0 'INFINITE LOOP!
End Sub
```

This inspection is completely by design and working as intended :smiley: 

We highly recommend replacing it with `Resume Next` outside of error-handling subroutines, and restructuring any error-handling strategy that depends on the behavior of `GoTo -1`.

**Comment by MegaDudeNZ** [comment]
Thanks for the quick reply, and the suggestion – much appreciated!


________________________________

**Comment by MegaDudeNZ** [comment]
Hi Mathieu,

Thanks for the quick reply, and the suggestion – I’ll rewrite it accordingly.  Much appreciated!

Nev



________________________________
