### ISSUE TITLE
Getting started with version control help

### ISSUE THREAD

**Issue by shahrodkh** [rubberduck-vba/Rubberduck#4976]
Hello Rubberducks!
I am very excited about this project as I've just been put in charge of an overgrown and undocumented spaghetti monster Access program. I initially came across it because I am sorely in need of a version control system, and I read that Rubberduck will integrate git. I am most used to git but I'm open to whatever will help me track changes.

I have been looking through the issues in the repo for someone else who's been unable to get started using the git features in Rubberduck, and many answers reference a wiki article which doesn't actually seem to exist any more.. https://github.com/rubberduck-vba/Rubberduck/issues/3531#issuecomment-341527484

So can someone help me get started with this feature if it still exists? Or could I get help using version control at all with Access programs? To be honest I am comfortable with git CLI but I don't even know how to compare versions of files other than copy and pasting into winmerge from  the VBE. Please help! Thank you!

**Comment by bclothier** [comment]
Hi! A very good question. Because this is Access, you might want to consider looking at two commercial tools that helps with version control; [OASIS-SVN](https://dev2dev.de/index.php?lang=en) or [Ivercy](https://www.ivercy.com/). The reason I mention those is because they already have leveraged Access-specific capabilities for supporting version control and can handle document modules which is not even handled by VBIDE API alone. 

Rubberduck does help with exporting and importing VBA objects but it cannot handle imports of Access forms / reports (that's the document modules) and the exports would only have code but not the layout data. 

I personally use OASIS for version control and Rubberduck for everything else. I hope that helps.

**Comment by shahrodkh** [comment]
@bclothier thanks so much for your prompt reply. I have downloaded a trial version of OASIS-SVN but I am totally lost on how to start using it. Is there any chance you'd be able to give a little more guidance on what to do.. all the documentation appears to be in german

**Comment by bclothier** [comment]
I normally use Google Translate on those page which suffice to get an overview. That said, one aspect that usually stumbles up people is that with a VBA project the process is now two-step; you have to export your VBA project into the filesystem so that git can do something about it. Likewise, if you want to merge changes from git, you must pull the changes or switch branches or something like that, *then* import the files back into the VBA project. 

For OASIS SVN specifically, you do need to configure the file for version control, usually by using the `Settings` and setting the project directory for the file. Once that has been set up, you can start exporting/importing.

If you look on the OASIS SVN ribbon, you will see the buttons for Import / Export. That should be the first thing you want to get familiar with. 

I may write a bit more about the process when time permits.

**Comment by bclothier** [comment]
Closing this issue. FWIW for those who want to know more about [using OASIS-SVN, there's now an article](https://accessexperts.com/blog/2019/07/02/using-oasis-svn-and-git-for-access-source-code-control/). Free feel to open a new issue for new feedback and thanks for using Rubberduck!
