### ISSUE TITLE
Invalid test setup for Find All Implementations command

### ISSUE THREAD

**Issue by bclothier** [rubberduck-vba/Rubberduck#5040]
In the PR #4833 we uncovered a possible bad test setup which will be ignored when the PR is merged:

https://github.com/rubberduck-vba/Rubberduck/blob/3be18f996a5af0155fc9df8345b8286457ae1baf/RubberduckTests/Commands/FindAllImplementationsTests.cs#L180-L202

The reason the test is passing in the `next` is because it does not currently invoke the `CanExecute` method within the `Execute` method and the test calls the `Execute` directly without calling the `CanExecute`. In this case, we call the `_finder.CanFind`:

https://github.com/rubberduck-vba/Rubberduck/blob/98b9f4a764e13a46337e71b3cc924530accdaf1f/Rubberduck.Core/UI/CodeExplorer/Commands/CodeExplorerFindAllImplementationsCommand.cs#L40-L46

which evaluates those conditions:

https://github.com/rubberduck-vba/Rubberduck/blob/98b9f4a764e13a46337e71b3cc924530accdaf1f/Rubberduck.Core/UI/Controls/FindAllImplementationsService.cs#L39-L44

Currently those return false, even after adding the `'@Interface` annotation. Thus, the messagebox will never be shown because `CanExecute` puts an early end to the show. The resolver might need to be updated to handle the correct identification?

**Comment by MDoerner** [comment]
My opinion on the now failing test is that the test is right and the implementation of `CanFind` is wrong. The implementation of `IsUserInterface` already determines whether there are implementations, which should not be part of the `CanExecute` method. (In general, all classes can potentially have implementations in VBA.) The `CanExecute` check should only determine whether there can potentially be an implementation.

Accordingly, `CanFind` should not test for `IsUserInterface` for classes. Moreover, for the module body element, it should check for public access ability instead of `IsInterfaceMember`, which also already checks whether there is an implementation.
