### ISSUE TITLE
ObsoleteCallStatment inspection needs an overhaul

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#5057]
The inspection is inefficient, and hits the `CodeModule` when it doesn't need to - only to avoid reporting a false positive in an edge-case situation that actually does warrant the presence of the `Call` keyword (ref. #1877):

https://github.com/rubberduck-vba/Rubberduck/blob/f5e9c2afa3894b3b0d8594dfd1f64cd74c5af817/Rubberduck.CodeAnalysis/Inspections/Concrete/ObsoleteCallStatementInspection.cs#L59-L82

This logic should be able to be handled in the listener during the parse tree traversal, without pulling the line of code from the module.

**Comment by Vogel612** [comment]
this should check the corresponding `endOfStatement` for being a `COLON` instead of working off line positions

**Comment by retailcoder** [comment]
@Vogel612 in the listener - not the inspection itself, right?

**Comment by MDoerner** [comment]
As I already mentioned in chat, I think the edge case still does not warrent the explicit call statement. Instead the quickfix should smarten up and replace the statement separator with a newline.

However, I realise now that this might be a bit more complicated because further statement separators have to be taken into account as well.

```vba
Private sub bar
End sub

Private sub foo
    Call bar: bar: bar: bar: bar: bar
End sub
```
Replacing just the first statement separator will make the second invocation a line label.

Still, I think the `Call` in not warrented here. This should better not have statement separators at all.

**Comment by BZngr** [comment]
The overhaul has been done.
