### ISSUE TITLE
Stop Rubberduck from Automatically Recalculating

### ISSUE THREAD

**Issue by BriargateExcel** [rubberduck-vba/Rubberduck#5127]
I just started using 2.4.1.4627

Rubberduck is recalculating frequently - every time I add a new module, when I change the name of a module, ...

How do I turn this off?

**Comment by Vogel612** [comment]
Are you referring to automatic reparsing or automatic code inspections on reparse? The reparsing itself is pretty quick and it's also necessary to allow Rubberduck to perform it's core functionality.

Nearly everything that RD does relies on knowing the **current** state of the code in your VBE, and that necessarily involves parsing...  
Over years of work, parsing now works pretty quickly and does almost no excess work.

You may also be referring to Code Inspections refreshing. If that's the case, you should find an option in the Settings under "Code Inspections" that says "Run inspections automatically on successful parse".  
If you don't  regularly use inspections, you can toggle that off to make Rubberduck and the VBE more responsive.

**Comment by retailcoder** [comment]
When a module is added to a project, all we know is that the project isn't in the same state it was when we last analyzed it: we don't know if it's an empty module or a 5K LoC toolbox module that was imported; maybe there's existing code referring to it and what was previously unresolved can now be understood. Same with a renamed module: if Rubberduck doesn't see the code exactly as it is in the editor, then asking it to modify the code (refactorings, quickfixes, etc.) could have disastrous consequences: it's best we go out of our way to keep everything in sync, so that every command is readily usable and doesn't attempt to modify code that isn't where it thinks it is.

The vast majority of the processing occurs on background threads, leaving you free to navigate the IDE. The code explorer becomes usable as soon as we've acquired all declarations (modules, members, variables, etc.), so you can still navigate the project while we process the parse trees. If you don't intend to use a RD feature yet, then you can even keep modifying the code as it's processed (may cause parser errors), and then you can manually refresh after making changes, keeping in mind that the parser state is stale until the project is parsed again.

A note about renaming a module with the Properties toolwindow: if that module's identifier is used anywhere in the code, consider using Refactor/Rename instead; that will automatically adjust all references.

**Comment by MDoerner** [comment]
One thing of note is that the last stable version contains a bug that makes one stage of the parsing process a lot slower than it needs to be.

Unfortunately, we never released a stable hotfix release for that issue. The fix is in the prereleases for several months now.
