### ISSUE TITLE
Code Inspection: Check Case of object name matches case of object name in Attribute

### ISSUE THREAD

**Issue by SteveLaycock** [rubberduck-vba/Rubberduck#5141]
**What**
To detect the change of case when Myclass is renamed to MyClass

**Why**

1.  The Attribute VB_Name is not updated to reflect the name change
2. The class name provided by intellisense is that of the VB_Name attribute.

**Example**

1. Create a class called 'Myclass'

2. Run the code below.  The output will be "Myclass"

    ```
    Sub TestClassNameCaseSensitivity()
 
    Dim my_class_obj                    As Myclass 

        Set my_class_obj = New Myclass
    
        Debug.Print TypeName(my_class_obj)
    End Sub
    ```

3. Now rename Myclass as MyClass in the properties window.  Run the code above

4. The output will be "Myclass" and not MyClass"

**QuickFixes**
The quick fix should be that Rubberduck updates the VB_Name attribute to match that shown in the Properties window.

**Comment by bclothier** [comment]
We have to also consider the scenario where the name's cases won't match because of other identifiers. 

As an example, if there's a control on a form somewhere named `mYcLASS`, then even though we can temporarily change the name, it won't actually hold and revert to `mYcLASS`, which may confuse users into thinking there's something wrong with the inspection. 

Thus, we probably need a separate inspection to check for collisions in the names among different types. I know that there has been people who has gotten quite annoyed when VBIDE change the lettercases because of that.

**Comment by MDoerner** [comment]
I just tested this and I have to disagree that the name provided in IntelliSense is the name from the `VB_Name` attribute. It is whatever the currently valid name is in the p-code. This is determined by the last identifier that has the same name (case-insensitive).

To test this, add a class `Class5` to a project and some module with the following code.
```vba
Public Sub TestTestTestTest()
    Dim cls As class5
    Set cls = New class5
    Debug.Print TypeName(cls)
End Sub
```

Running it yields `Class5` and IntelliSense shows `Class5`, e.g. when starting to type `Public Function Foo As Cla`. Exporting the class, the `VB_Name` attribute has the value `Class5`.

Now, add a line `Dim class5 As Variant` to get the following code.
```vba
Public Sub TestTestTestTest()
    Dim cls As class5
    Dim class5 As Variant
    Set cls = New class5
    Debug.Print TypeName(cls)
End Sub
``` 

Running this still yields `Class5` and on export the `VB_Name` attribute still is `Class5`. However, IntelliSense will show `class5`.

Changing the `Name` property in the Properties window to something that matches the old name in a case-insensitive way, neither changes whet IntelliSense shows, nor the `VB_Name` attribute.

Actually, whenever you type `Class5` or `ClaSs5` as the type name now, it will autocorrect to `class5` because that is the value in the p-code. The only way to change that is to declare something new with the desired capitalization. (This can easily be achieves be renaming `Class5` to something else and then back to `Class5`.) 

Btw, if you do not only change the case in the properties window, the change is transferred to the `VB_Name` attribute.

**Comment by SteveLaycock** [comment]
That may be correct.  I can only comment that removing the class (with save class), fixing the name in the VB_Name attribute, and reimporting gives the correct case and automatically updates the names in code.

The observation you make that renaming to a different name and then back to the name you want is useful as it avoids removing and reimporting the class, but it would be interesting to understand why this doesn't work when just changing the case of one or more letters.

The advice that renaming to something else and then back to the name you want seems like a good idea as it saves r

**Comment by MDoerner** [comment]
Maybe a little background on how the VBE works will help here. After finishing to enter a statement, whatever you see in the code panes of the VBE is not really what you typed but what the VBE thiks you have typed. More precisely, the VBE compiles your input into p-code (something akin to bytecode for Java or IL for .Net) and, for historical reasons, throws away your input. To be able to show you something you can work with in the code panes, it reverse engineers the source code from the p-code. (This is also the reason why ISO dates like `#2019-12-31#` automatically get translated into the American `#12/31/2019#`.)

Internally, the VBE seems to associate one name with fixed lettercase to each case-insensitive name in the p-code. Then it reverse engineers each symbol with the case-insensitive name in the p-code using this name. It updates it whenever a new declaration is made with the same case-insensitive name. Changing only the lettercase does not count as a new declaration because the case-insensitive name in the p-code does not change. However, changing to another name, cahenges the symbol in the p-code and thus counts as a new declaration, as well as changing it back.

That the Properties window allows to make changes to the lettercase is rather a bug than an actual feature, since it has no effect at all, again because the case-insensitive name does not change, on which VBA depends.

**Comment by retailcoder** [comment]
What @MDoerner said about names applies to every identifier in VBA: there's literally a (case-insensitive *names list* in memory, and any entry can be overwritten at any time by declaring a variable with an existing name but using a different case - that's why doing that will change the case of everything with that name that appears in the VBE, even if it's a "built-in" identifier from a referenced or standard library.

Changing the case of an existing identifier does not overwrite any entry in the names list, so there's not much Rubberduck can do for this: we can't make VBA case-sensitive.

**Comment by SteveLaycock** [comment]
Dodgy typing is something that seems to be normal for me.  I frequently capitalise the second the letter following a Capital.  Its just the way my fingers work.  The manual quick fix reported by @MDoerner is sufficient for me so I suppose this request can be closed.
