### ISSUE TITLE
Move dev chat out of SE?

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#5163]
Stack Exchange is undergoing a series of controversial changes, and recent events have brought to light a rather worrying attitude in the higher-up stratosphere of StackLand.

Long story short - and this is very much heart-breaking, but we should start thinking about leaving the craddle of CR/SE chat, and make ourselves a new "war room" dev chat.

Suggesting [Gitter](https://gitlab.com/gitlab-org/gitter/webapp), primarily because of ease of integration with GitHub webhooks, but open to other suggestions... including keeping everything on SE chat.

**Comment by bclothier** [comment]
FWIW, I would say it's premature primarily because politics of SE don't directly impact our use of SE chat (yet, at least). The main barrier is that large transcript history and chat search that SE provides and I'm not sure we can easily migrate it. When the chat transcript comes up in a google search for some hard problem to solve, you know there's lot of gems. 

Given that the politics of SE doesn't directly impact us, I think we can stay until it does in fact hurt us. Hopefully it won't come to that.
