### ISSUE TITLE
Simplify & centralize inspection @Ignore and @IgnoreModule handling

### ISSUE THREAD

**Issue by Vogel612** [rubberduck-vba/Rubberduck#5184]
There is an undue amount of issues open here, where the `@Ignore` and `@IgnoreModule` annotations do not work correctly. While they are comparatively easy to fix, it would be much better if we didn't get these issues in the first place because such checking is automatically done for every inspection.

This necessitates centralizing the ignore handling into the InspectionBase class.
Notably the Inspections dealing with references that can be ignored at their declarations need custom support for lookups, though.  
Therefore the checking must be extensible by the concrete inspection.

This follows up on #2668, #4013, #4965, #4812 and probably a handful of others.

**Comment by retailcoder** [comment]
IIRC the main reason this wasn't centralized is because not all inspections *can* be ignored. ...and since that was established, AFAICT out of all inspections we made, there is only one that cannot be annotated (default project name)... which in hindsight wasn't a good reason at all. Let's fix this!
