### ISSUE TITLE
ValueRequired needs a "Add 'Set' keyword" QuickFix

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#5267]
**Justification**
The `ValueRequired` inspection is completely correct, but nonetheless confusing for beginners that don't understand all the mechanics involved in a *value* assignment, and don't necessarily know that a `Set` keyword is all that's needed to make the assignment a *reference* assignment.

If the most common reason for this inspection to come up is [confusion over value vs reference assignment](https://stackoverflow.com/q/58733770/1188513), then the most common fix for this inspection result, would be to add the missing `Set` keyword - but nothing in the inspection info says anything about that, and the only quickfix available is "ignore once".

The fact that this inspection pops up *in place of* `ObjectVariableNotSet` in many circumstances, together with the fact that adding the missing `Set` keyword indeed fixes it, the conclusion is that the quickfix should be offered for this inspection.

**Description**
Let's offer the quickfix, and let users decide whether the problem is a missing `Set` keyword or not. Not offering the quickfix makes the solution not as obvious as it should be.

**Implementation**
Simply add `ValueRequiredInspection` to the list of supported inspections for the quickfix:

https://github.com/rubberduck-vba/Rubberduck/blob/5c7c292ca632479d5277265ba8c03592e20a4d56/Rubberduck.CodeAnalysis/QuickFixes/UseSetKeywordForObjectAssignmentQuickFix.cs#L12-L14

**Comment by MDoerner** [comment]
I do not see why we should add that quickfix for this inspection. In all but one case where this inspection triggers, adding `Set` does not even make sense, since there is no assignment.

Moreover, there should never be a result for this inspection for a LHS of an assignment. Instead, there will be a result for `ObjectVariableNotSet`.
If the RHS of an assignment cannot be Let assigned, there will be a result for this inspection, but also one for `ObjectVariableNotSet`.

**Comment by retailcoder** [comment]
I agree that if `ObjectVariableNotSet` fires, this issue is moot. But with the code in the linked SO question, it doesn't, and the result is a very confusing situation where we're dealing with an extremely common beginner-level mistake, and presenting an extremely technical description of the problem, without offering the extremely simple solution.

**Comment by MDoerner** [comment]
Then this is more an issue about the other inspection not firing, which I will have to investigate once I am home.

Just adding the quichfix would be very bad, though as it will throw exceptions when used on a result in any other situation.

**Comment by MDoerner** [comment]
Now, I had a look at the linkes post on SO. For this expression, it is not possible for us to determine whather adding `Set` is even legal. The reason is the same as why there is no result for `ObjectVariableNotSetInspection`: the left hand side is a late bound member call. We simply have no idea whether the member is a `Let` property, a `Set` property, a value field or an object field.

Since we cannot be sure here whether adding `Set` is legal, we should not provide that option, IMHO.

**Comment by retailcoder** [comment]
Thanks for investigating, you are absolutely correct. Closing.
