### ISSUE TITLE
Code Inspection Error: Test methods give the  Procedure Not Used inspection

### ISSUE THREAD

**Issue by SteveLaycock** [rubberduck-vba/Rubberduck#5281]
**Rubberduck version information**

Version 2.4.1.5196
OS: Microsoft Windows NT 10.0.18362.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.12130.20272
Host Executable: WINWORD.EXE

**Description**
This has been happening for a while with Test Modules and I've been dealing with it using an '@IgnoreModule annotation.  However if I remove the '@IgnoreModule annotation from a Test Module then all the tests within that module give rise to a  'procedure not used inspection' .  This includes the boilerplate methods installed when you insert a rubberduck TestModule.

**Comment by MDoerner** [comment]
I guess, we should simply exclode all methods from the results that have one of the test annotations.

**Comment by jonathan-rizk** [comment]
How do I reproduce this? I created a test module with a test method that does `Assert.IsTrue(1)` to see if I could see the issue myself, but I the test ran without any 'procedure not used inspection' issues.

**Comment by MDoerner** [comment]
You will want to add the following test(s) to the ones already present in `ProcedureNotUsedInspectionTests`:
```csharp
        [TestCase("@TestMethod(\"TestCategory\"")]
        [TestCase("@ModuleInitialize")]
        [TestCase("@ModuleCleanup")]
        [TestCase("@TestInitialize")]
        [TestCase("@TestCleanup")]
        [Category("Inspections")]
        public void ProcedureNotUsed_NoResultForTestRelatedMethods(string annotationText)
        {
            string inputCode =
                $@"
'{annotationText}
Private Sub TestRelatedMethod()
End Sub";

            Assert.AreEqual(0, InspectionResultsForModules(("TestClass", inputCode, ComponentType.StandardModule)).Count());
        }
```

**Comment by jonathan-rizk** [comment]
Would it make sense to make make a child annotation called something like "TestAnnotation" -> make those test cases the new annotation type -> exclude anything that's a "TestAnnotation" from the results?

I don't know exactly how all of the pieces work together at this point, so that's my initial thought of how to implement excluding those annotations from the results.

**Comment by MDoerner** [comment]
What you could do is toame the annotation classes for tests inherit a marker interface `ITestAnnotation` and exclude all results with such an annotation from the results of the inspection. 

You cannot make the test relevant annotations inherit from some new annotation class, since they are already on a different hierarchy.
