### ISSUE TITLE
Using the refactoring dialog Close button executes the refactoring

### ISSUE THREAD

**Issue by BZngr** [rubberduck-vba/Rubberduck#5287]
Version 2.4.1.16231
OS: Microsoft Windows NT 10.0.18362.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.12130.20272
Host Executable: EXCEL.EXE

**Description**
If the user uses the Close button rather than the Cancel button to dismiss a refactoring dialog, the refactoring executes rather then cancelling.

**To Reproduce**
1. Attempt to Rename or Encapsulate a field.
2. Click on the Close button
3. The code pane is updated with refactored code.

**Expected behavior**
Dialog should be dismissed and the code remains unchanged.

I've observed this with Rename and EncapsulateField refactoring.  I'm suspecting this is a general issue that likely applies to all refactoring dialogs.

**Comment by MDoerner** [comment]
The problem here arises because we never set the dialog result if the dialog is closed not using the button. This causes the observed behaviour since the first element of the results enum is `Execute`. This can be fixed by either making `Cancel` the first element or adding a third value `Undetermined` as the first value.
