### ISSUE TITLE
Scroll wheel doesn't work in code inspections or the test panel

### ISSUE THREAD

**Issue by Irubataru** [rubberduck-vba/Rubberduck#5302]
**Rubberduck version information**
```
Version 2.4.1.5200
OS: Microsoft Windows NT 10.0.18362.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.12130.20344
Host Executable: EXCEL.EXE
```

**Description**
The scroll wheel doesn't work in neither the code inspections window nor the test explorer window, but it works in the code explorer window. One has to drag the scroll bar by clicking it in order to scroll.

**To Reproduce**
1. Open the Code Inspection window with enough inspections to get a scrollbar.
2. Try to scroll with the mouse wheel.

**Expected behaviour**
The window should scroll.

**Comment by MDoerner** [comment]
I think the problem here is the recently introduced scroll viewer around the entire control. I guess that scroll viewer handles the scroll event and marks it as handles such that the data grid scroll viewer never gets to see the event.

I really thing the overall scroll viewer should not be activated for vertical scrolling.

**Comment by Irubataru** [comment]
Also, after the introduction of the scroll viewer around the control there is no scroll viewer for the data grid any more. Basically #5265.
