### ISSUE TITLE
Statically accessible sheet can be referred to by its code name

### ISSUE THREAD

**Issue by mv-82** [rubberduck-vba/Rubberduck#5307]
**Description**
In this page 
https://rubberduckvba.com/Inspections/Details/SheetAccessedUsingString
the documentation say that only ThisWorkbook.Worksheets and ThisWorkbook.Sheets calls are verified but seems that inspection check also Workbooks.Worksheets.

**To Reproduce**
This code raise the warning in the object of this topic.
```
    Dim shtProd As Worksheet
    Set shtProd = Workbooks("Listino.xlsm").Worksheets("Optional")
```

**Rubberduck version information**
Version 2.4.1.4627
OS: Microsoft Windows NT 10.0.18363.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.12130.20390
Host Executable: EXCEL.EXE

**Comment by retailcoder** [comment]
That would be `Workbook.Worksheet`; the member call is made against the object returned by `Workbooks.Item(name)` (the `Item` member call is implicit), and that's a `Workbook`.

That's currently a problem indeed, because the `Workbook` nature of `ThisWorkbook` isn't understood by Rubberduck. Thanks for the report!

**Comment by retailcoder** [comment]
That's fixed now.
