### ISSUE TITLE
Parameter named 'Object' incorrectly triggers ParameterNotUsedInspection

### ISSUE THREAD

**Issue by martin-east** [rubberduck-vba/Rubberduck#5336]
Version 2.5.0.5244
OS: Microsoft Windows NT 10.0.18363.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.12410.20000
Host Executable: EXCEL.EXE

**Description**
A function/property parameter named 'Object' triggers ParameterNotUsedInspection, even though the parameter is used. Changing the name from 'Object' to anything else, e.g. 'ObjectX', does not trigger the inspection

**To Reproduce**
' this (incorrectly) triggers ParameterNotUsedInspection:

Public Function Foo(Object As Object) As Object
    Set Foo = Object
End Function

' this (correctly) does not trigger ParameterNotUsedInspection:

Public Function Foo(Objectx As Object) As Object
    Set Foo = Objectx
End Function

+++

Note that a local variable called 'Object' will also incorrectly trigger a VariableNotUsedInspection

**Comment by retailcoder** [comment]
Thanks for the report!

**Comment by MDoerner** [comment]
This is an edge case for the parser. The RHS of a both the `letStmt` and the `setStmt` is just an expression. In expressions, we match `lExpression`s last, in particular after literals, which include the type literals. This is necessary because the `identifier` rule would match most of them otherwise. Unfortunately, this means that if you choose the name o a built-in type as yout variable name, e.g. `Object`, it will be parsed as a type literal instead of an identifer. Thus, the resolver does not correctly identify it.

I guess best bet for fixing this is to add handling of type literals as potential identifiers in the resolver. However, I am not too sure how much effort this will be.

**Comment by martin-east** [comment]
Hi, 

 

My two cents worth: 

 

Ideally, Rubberduck would handle variables with a built-in type name exactly as if they had a name which was not a built-in type: where the VBA compiler allows it, so should Rubberduck. That being said, a new inspection warning of use of built-in type names for a variable would be helpful, as most programmers (though not me) prefer to avoid using built-in type names for variables

 

I can understand that this would not be top priority, but it would be an improvement nonetheless

 

Best

Martin

**Comment by retailcoder** [comment]
> *where the VBA compiler allows it, so should Rubberduck*

Definitely! This exact phrase has been our guiding light since the beginning: Rubberduck must be able to correctly process any code that's legal, otherwise we're leaving holes and gaps in Rubberduck's understanding of the code, and that generally translates into inspection false positives (or refactoring glitches).

But VBA's compiler was hand-crafted, not generated from a formal grammar: over the years we've fixed the vast majority of the bugs we could find in the grammar, and what remains is a number of edge cases that can't easily be patched - this is one of them.

I agree that it would be a welcome improvement, and getting the resolver to understand what's grammatically a type name token as an identifier is not impossible - just a lot of tedious, error-prone work!

> *most programmers (though not me) prefer to avoid using built-in type names for variables*

It's not a personal preference thing though: type names make terrible variable names that convey absolutely zero meaning - it's kind of like having Hungarian Notation prefixes, but for the whole identifier name. Consider using more meaningful identifier names, "object" (or "integer", "date", or "string", etc.) is almost assuredly a poor generic name and a missed opportunity. "source" and "target" tell the reader how the objects are used, whereas "object1" and "object2" say nothing we don't already know from the data type alone.

As for having an inspection to flag such names, I think it would make sense to have the `UseMeaningfulName` inspection do it.

**Comment by martin-east** [comment]
Hi Mathieu, 

Thanks for giving me this background information. I guessed this would be non-trivial, as VBA’s grammar is hugely (and in my view unnecessarily) complex. 

Re type names as variable names, in general I agree with you. I use them only for two situations:

•	Arguments to a procedure or function that provide system functions, such as HexAdress(Object as Object)
•	Return values for conversion methods to that type

Actually, it’s almost academic, as the compiler doesn’t allow basic types (String, Integer, Long etc.) as variable names or class names, so I resort to misspellings like Stryng and Intiger. In fact the only basic type I can think of that the compiler does allow is Object (see VBA Language Spec, p37). So maybe you could fix the problem with a specific check for “Object” rather than a general solution.

I assume you are aware that UDT members can have names that are VBA reserved words? So you can happily declare

Public Type Weird
  String As String
  Call As String
  Gosub As String
  With As String
  As As String
  For As String
  End as String
End Type 

Also, external libraries can also have methods or functions that are VBA reserved words: Excel’s Range.End is a good example. I find it annoying that it’s not possible to do the same with one’s own classes within VBA, but that's life, I guess.

And finally, I agree with your stance on Hungarian notation. 

Best regards
Martin
