### ISSUE TITLE
FunctionReturnValueNotUsed incorrectly triggered

### ISSUE THREAD

**Issue by martin-east** [rubberduck-vba/Rubberduck#5337]
Version 2.5.0.5244
OS: Microsoft Windows NT 10.0.18363.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.12410.20000
Host Executable: EXCEL.EXE

**Description**
Some functions I have generate an incorrect FunctionReturnValueNotUsedInspection. It's very mysterious, because it only affects some functions. If I copy the functions and give them a different name, they do not trigger the error. If I change them to Property Get, the error is also not triggered. If I rename the functions, the error is sometimes triggered, sometimes not

**To Reproduce**
I'm not sure how to reproduce this without giving you my entire source code, but maybe the code extracts below will help you find the issue: 
```vba
'this class function incorrectly triggers FunctionReturnValueNotUsed

Public Function AsLine(Optional ByVal Format As ListFormat = Nothing, Optional ByVal Void As Stryng = Nothing) As Stryng
    Set AsLine = AsLines(Format, Void).AsString
End Function

'if I add the following class function (exactly the same except for the name), FunctionReturnValueNotUsed is not triggered for it:

Public Function AsLinex(Optional ByVal Format As ListFormat = Nothing, Optional ByVal Void As Stryng = Nothing) As Stryng
    Set AsLinex = AsLines(Format, Void).AsString
End Function

'if I rename AsLine to (say) AsLinex instead of making a copy of it, FunctionReturnValueNotUsed is not triggered, **provided** AsLinex is not called within the project. However, if AsLinex is called somewhere in the project, then FunctionReturnValueNotUsed **is** triggered.

'if I change AsLine to a property, FunctionReturnValueNotUsed is not triggered (this is my workaround)
Public Property Get AsLine(Optional ByVal Format As ListFormat = Nothing, Optional ByVal Void As Stryng = Nothing) As Stryng
    Set AsLine = AsLines(Format, Void).AsString
End Property
```

**Comment by MDoerner** [comment]
What does the place look the inspection result refers to? (You should be able to navigate there double-clicking the result.)

The thing is that the inspection does not inspect the function itself but its usage. It should trigger whenever you use the function like a procedure and discard the return value. E.g. somehting like the following should trigger a result:
```vba
Private Sub DiscardIt()
    AllLines
End Sub
```
However, the following should be OK, provide `Strying` has a sub `Foo` in the second case.
```vba
Private Sub AssignMe()
    Dim val As Stryng
    Set val = AsLine()
End Sub

Private AccessMe()
    AsLine().Foo
End Sub
```

So, it would be very helpful to us, if you could tell us which usage the result refers to.

**Comment by martin-east** [comment]
Hi Max, 

 

The Double click on the inspection result takes me to the declaration of the function, not the use. 

 



 

And as I wrote before, the function isn’t called from anywhere in the project, whether as a sub or as a function

 

Does this help?

 

Best

Martin

**Comment by MDoerner** [comment]
That the inspection returns a `DeclarationInspectionResult`, which is why a double-click navigates to the function instead of the usage, is a bug in and of itself. It should really return an `IdentifierReferenceInspectionResult` or the usage. That said, from the implementation, I cannot see how any function can produce a result if it is not referenced at all, either through usage or by being implemented by another class. The second possibility is also a bug.

I have found the following two test setups producing false positives:
```csharp
            const string classCode = @"
Public Function Test() As Bar
End Function

Public Sub FooBar()
End Sub
";
            const string callSiteCode = @"
Public Sub Baz()
    Dim testObj As Bar
    Set testObj = new Bar
    testObj.Test.FooBar
End Sub
";
```
where `Bar` is the name of the class;
```csharp
            const string interfaceCode = @"
Public Function Test() As Integer
End Function
";
            const string implementationCode = 
                @"Implements IFoo
Public Function IFoo_Test() As Integer
    IFoo_Test = 42
End Function
";
```
where the interface class is called `IFoo`.

This inspection really looks at the wrong condition, namely that there are references not o a list of specified types. It only does not give too many false positives for non-interface functions, because there all without references that are no assignment targets are excluded.

All things considered, this inspection needs to be rewritten completely.

BTW, there is no result for Property Get members, because not using the return value of a Property Get causes a compile error.

**Comment by MDoerner** [comment]
Is this still an issue with the latest prerelease?

The inspections should now be split into a part for discarding a return value at a specific place and one inspecting that the return value is not use although the function is used somewhere.

My test setups pass now at least.

**Comment by MDoerner** [comment]
Since there has not been any reply that this still is an issue, I close it.
