### ISSUE TITLE
Get Annotation @Description "read this" working

### ISSUE THREAD

**Issue by el-campesino** [rubberduck-vba/Rubberduck#5449]
Hi, 
I wonder how to get the @Description-annotations (and the others too) running. Folder-organisation works fine, but I can't get descriptions (neither @Description nor @ModuleDescription) working. They don't appear at the bottom of the project-explorer and they don't appear in the Rubberduck-toolbar. I tried both the lastest stable Rubberuck and the current pre-release-version. What am I doing wrong? 
Thank you!
Georg

This is the version info created by Rubberduck: 
Version 2.5.0.5394
OS: Microsoft Windows NT 6.2.9200.0, x64
Host Product: Microsoft Office 2010 x86
Host Version: 14.0.7245.5000
Host Executable: EXCEL.EXE

![no desc](https://user-images.githubusercontent.com/62850251/77856518-0badf780-71f8-11ea-9529-0e07579ae0b9.jpg)

**Comment by retailcoder** [comment]
Thanks for asking! After adding the annotations in a module, make Rubberduck parse the changes, and run code inspections (by default they run automatically after parsing finishes).

In the Code Inspections toolwindow, search for "annotation" or "description" - it should filter down the inspection results to a series of "Rubberduck Opportunities" results mentioning a mismatch betwen the annotation and the corresponding attribute:

![filtered inspection results](https://user-images.githubusercontent.com/5751684/77857418-43527a80-71cb-11ea-9e24-55f9713c1abf.png)

Alternatively group the results by inspection, and look for results under the **Missing Attribute** inspection:

![results by inspection](https://user-images.githubusercontent.com/5751684/77857452-81e83500-71cb-11ea-92d0-881ffd92b8c6.png)

Right-click the result, or click the "Fix" dropdown to reveal available quick-fixes:

![quickfixes](https://user-images.githubusercontent.com/5751684/77857479-ab08c580-71cb-11ea-9668-f42c1ffdbf56.png)

Selecting "Add missing attribute" will automatically export the module, add all the missing hidden attributes, and re-import the module back into the project.

This had to be implemented like this, because parsing alone doesn't alter the modules - and adding a hidden `VB_Description` attribute does exactly that. Note that the "missing attribute" inspection looks specifically for annotation comments that don't have a corresponding attribute; another inspection looks for annotation comments that have a corresponding attribute but where the value of the attribute mismatches that of the annotation - all these inspection results _should_ be under the "Rubberduck Opportunities" category.

**Comment by MDoerner** [comment]
The `@Description` and `@ModuleDescription` are related to the attribute `VB_Descrption` attribute. Adding the annotation will not automatically add the attribute. This works a bit differently. 

Have a look at your inspection results. There will be results stating that an attribute is missing for the annotation. Right-click that result and add the quick fix _Add Attribute_. That will add the actual attribute. Afterwards, the description should show up in the properties.

**Comment by el-campesino** [comment]
Bonsoir à tous, 
Thank you, that solved the problem, I would not have figured that out on my own. I recently started rubberducking. I did have seen the inspection-window, but there too many errors (I know, I can configure this).  
Keep up the good work!
Georg
