### ISSUE TITLE
Move Closer to Usage

### ISSUE THREAD

**Issue by alberto-gilman** [rubberduck-vba/Rubberduck#5459]
**Justification**
The 'Move Closer to Usage' creates a **Dim** sentence for declaring the variable

**Description**
When you ar moving a module level variable to a method in the module, a **Static** statement should be created, instead of a **Dim** sentence
**Additional context**

**Comment by retailcoder** [comment]
I like this, but I think the best would be to ...offer both `Dim` and `Static`, with `Static` being the default since that's indeed not affecting semantics, and let the user decide :smiley: 

I feel like there should be a counterpart "move `Static` local to module level" flipside refactoring for this, too.

**Comment by BZngr** [comment]
Closed by #5941
