### ISSUE TITLE
Dual Inspections triggered for "On Error GoTo -1".

### ISSUE THREAD

**Issue by mccordscvs** [rubberduck-vba/Rubberduck#5544]
### Rubberduck version information
- Version 2.5.0.5508
- OS: Microsoft Windows NT 10.0.18362.0, x64
- Host Product: Microsoft Office 2016 x64
- Host Version: 16.0.5005.1000
- Host Executable: EXCEL.EXE

### Description
The  "On Error Goto -1" statement is triggering 2 inspections: "Negative Line Number Encountered", "On Error GoTo  -1 Encountered". These Inspections are also at severality level Warning. GoTo -1 is the only way, that I know, to reset the Error Handler the err.Clear statement does not reset the error handler it just clears the error which is not the same thing. 

**Expected behavior**
The negative line number inspection should not be triggered. I believe that the severality level of "On Error GoTo -1" should be changed to Info or the inspection is not totally revmoved. 

**Screenshots**
![RDScreenShot](https://user-images.githubusercontent.com/29987068/88114136-d77c8f00-cb78-11ea-95cb-260a83073b42.jpg)

**Comment by MDoerner** [comment]
Thanks for reporting this. Indeed, there should not be a result for the negative line label.

However, I do not agree with reducing the severity level for `On Error Goto -1`. First of all, this feature is undocumented for VBA. Moreover, it actually has undefined behaviour when used while error handling is not active.

The way you are supposed to exit error handling in VBA is to use `Resume`, `Resume Next` or `Resume <label>` in order to jump back into the ordinary execution flow.

**Comment by retailcoder** [comment]
`On Error GoTo 0` is more commonly used for that purpose, and is documented. `On Error GoTo -1` is being legitimately flagged here (although, it shouldn't trigger the "negative line number" inspection).
Severity levels default to *warning* for most inspections; use *inspection settings* to configure them as you please - note that *DoNotShow* level effectively disables an inspection (i.e. it won't run at all).
