### ISSUE TITLE
Make Annotation Syntax Configurable

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#5570]
**Justification**
Our grammar makes annotation legally parameterized with or without parentheses, and `@Folder` annotations for folders that are legal `PascalCase` identifiers are legal with or without the `"` double quotes. Currently the "annotate" command generates the non-parenthesized syntax (it also changes parenthesized syntax to non-parenthesized), without any way for the user to change the generated code before it's generated.

**Description**
Let's add a `PreferredAnnotationSyntax` configuration setting (and default it to non-parenthesized, to maintain the current default behavior) in a new `AnnotationSettings` settings tab.

The possible values could be:
 - `QuotedNoParens` / `'@Annotation "argument"` - current default, surrounds the arguments with `"` double quotes, without parentheses (always safe).
 - `QuotedParens` / `'@Annotation("argument")` - surrounds the arguments with `"` double quotes, with parentheses (always safe).
 - `NoQuoteNoParens` / `'@Annotation argument` - avoids surrounding arguments with `"` double quotes *if possible*, without parentheses. Quotes can still be added if the argument (as parsed) contains spaces.
 - `NoQuoteParens` / `'@Annotation(argument)` - avoids surrounding arguments with `"` double quotes *if possible*, with parentheses. Quotes can still be added if the argument (as parsed) contains spaces.

The *annotate* command will need to be amended to listen for configuration changes and update its annotation-generation mechanics accordingly; the user preference may need to be overridden if they prefer no quotes but the argument contains spaces (I know that breaks the `@Folder` annotation, haven't checked others).

Another `KeepExistingAnnotationSyntax` setting (checkbox/Boolean) would override all of these, in cases where the annotation already exists. Turned on, that would make the command keep whatever syntax is currently being used when rewriting existing annotations. Turned off (should be the default, to maintain current default behavior), it would make the command use the preferred syntax when rewriting existing annotations.

**Comment by daFreeMan** [comment]
I'm generally all for user options, but I'm actually tending to agree with @bclothier  on this one. I just looked at the 2 modules I've got open in my Excel project at the moment and I've got `("x")` and `"y"` formats in the two. Because I didn't know which one is "correct" and the duck just accepts both, I'm not sure which is preferred to use in my next module.

TBH, though, it seems like the `Tabs v Spaces` argument: Go with whatever your local coding standard is and live with it because in the long run, it really doesn't matter. Set the standard in the Duck's options and move on (so long as there's an option for the Duck to "fix" anything that doesn't match the selected option).
