### ISSUE TITLE
Add 'AS IfaceName after a with

### ISSUE THREAD

**Issue by angedell** [rubberduck-vba/Rubberduck#5593]
**Justification**
I am enjoying using the brilliant concise with end with.
I like it keep the object self contained!

` 
    Dim conn As ADODB.Connection
    Set conn = CurrentProject.Connection
    
    Dim createNewTableInDB As Boolean
    createNewTableInDB = True
    
    
    With conn.OpenSchema(adSchemaTables, Array(Empty, Empty, Empty, "Table")) 
        Do While Not .EOF
            If CStr(.Fields("TABLE_NAME").Value) = strTableName Then
                createNewTableInDB = False
            End If
            .MoveNext
        Loop
    End With
`

**Description**
I realized it gets difficult to understand what interface I will be able to access inside the WIth block, therefore it would be nice to have a feature that would add `'@uses AS ADODB.Recordset` next to the opening with.

` 

    Dim conn As ADODB.Connection
    Set conn = CurrentProject.Connection
    
    Dim createNewTableInDB As Boolean
    createNewTableInDB = True
    
    
    With conn.OpenSchema(adSchemaTables, Array(Empty, Empty, Empty, "Table"))  '@uses as ADODB.recordset
        Do While Not .EOF
            If CStr(.Fields("TABLE_NAME").Value) = strTableName Then
                createNewTableInDB = False
            End If
            .MoveNext
        Loop
    End With
`

**Comment by retailcoder** [comment]
Wouldn't you be getting the return type of `OpenSchema` just by placing the caret inside it? (in the RD commandbar or, with vanilla-VBE, get a tooltip with ctrl+i)

This type of comment is of the "what" kind, which is the kind of noisy comment you typically want to get rid of: comments about the data type of things are among the first comments to become obsolete lies after a minor refactoring.

I can see the annotation providing valuable type metadata in the case of late-bound code: Rubberduck could conceivably leverage the metadata to bind the `With` block variable's type, and that would make inspections pick up typos and erroneous late-bound member calls made inside that `With` block... but we're not looking at a late-bound use case here.

Valuable comments are a hard thing to automate, because the comments that are valuable are those that explain *why* things are happening: it's usually best to let the code itself explain *what* is going on.

**Comment by angedell** [comment]
Thank you for your reply, and for the learning ;-)
