### ISSUE TITLE
Move field closer to usage

### ISSUE THREAD

**Issue by Hosch250** [rubberduck-vba/Rubberduck#564]
Essentially the opposite of https://github.com/rubberduck-vba/Rubberduck/issues/386

**Comment by retailcoder** [comment]
I like this one. Indeed, it's essentially the opposite of *promote local* - when a module-scope variable is only used in one scope (/procedure), its declaration should be tightened to the smallest possible scope.

I'm adding the code inspections label here, because this is something I would want an inspection to pick up - the refactoring would be the quick-fix. Or rather, the quick-fix for that inspection needs to call that refactoring.

**Comment by Hosch250** [comment]
Implementation notes:

1) Do nothing if there are no references.
2) Do nothing if it is referenced from more than one method.

**Comment by retailcoder** [comment]
#884 won't have an inspection, what "referenced too far from declaration" is possibly too subjective.

But, a field that's used in only a single procedure scope, is objectively declared at a scope that's wider than it needs to be. Let's implement that one.

**Comment by retailcoder** [comment]
commit e34fe49d64033ca3165bdeb4836bebc5d29a9316 closes this
