### ISSUE TITLE
Enhanced Module Import for source code management

### ISSUE THREAD

**Issue by Dob4115** [rubberduck-vba/Rubberduck#5654]
Well, I was about to write up an enhancement request, but then realized Rubberduck probably can already do what I need. So I have a hopefully quick support question instead:

Can anyone point me to documentation for the Sync Project and Add->Existing Files menu items? I checked the wiki, but couldnt find anything explaining the differences and intent behind them.

(I guess I would add a question about why these are not with Export in the main Rubberduck menu... that's where I looked first for the feature!)

**Comment by retailcoder** [comment]
Thanks for the feedback! Rubberduck has... very little documentation indeed. Wiki is open!

I'll be writing about it on the project's blog, but shortly put:

The **Add** commands create/add one or more component to the active project. The **Existing files...** command is basically the VBE's "Import File..." command, except now you get to import multiple files at once.

**Sync Project** commands were written with *source control* in mind, where a project's code is synchronized with on-disk actual exported code files.

 - **Update Components** will replace existing component(s) with the same name, otherwise it simply imports the selected file(s).
 - **Replace Contents** is destructive (it will prompt for confirmation), it removes all removable components and then imports all the selected files.

Together with the *Export Active Project* command (which prompts for a folder to export the code files into, and overwrites existing files), these features make it much more seamless to use any version control system (VCS) you like (e.g. git), or simply to import/overwrite code modules from the file system.

**Comment by Dob4115** [comment]
Yes, I enjoy documenting and am costantly trying to get people to document systems and ideas at work. And yet, I just constantly realize how bad I am at documenting!

Thank you for your explanations, they are exactly what I needed. The features are as well... they were there before I even knew I wanted them!

**Comment by retailcoder** [comment]
For posterity, [this article](https://rubberduckvba.wordpress.com/2020/12/11/sync-project-with-files/) was written to document the *sync project* commands.

**Comment by daFreeMan** [comment]
If you _enjoy_ documenting, @Dob4115 , I do believe the Wiki is open for anyone to edit... 😉
