### ISSUE TITLE
ComPointer doesn't respect addref parameter

### ISSUE THREAD

**Issue by Greedquest** [rubberduck-vba/Rubberduck#5657]
Just having a peek at the code and in this function: https://github.com/rubberduck-vba/Rubberduck/blob/2d29c231796b9dbb784755ceecf0c7aaa753d0d2/Rubberduck.VBEEditor/ComManagement/TypeLibs/Unmanaged/ComPointer.cs#L73-L79 why don't you use addref? It is called with true in some places e.g. 
https://github.com/rubberduck-vba/Rubberduck/blob/2d29c231796b9dbb784755ceecf0c7aaa753d0d2/Rubberduck.VBEEditor/ComManagement/TypeLibs/TypeInfoWrapper.cs#L248

Just trying to get my head around the code and was confused by this bit

**Comment by Vogel612** [comment]
There is a codepath in ComCastViaAggregation that will call AddRef, but only if `queryForType` is false. As I understood the code (without having any clue how COM properly works), it seems that we're adding a filter to some COM references and sometimes unifying multiple COM objects into a single "RCW Wrapper" (at least that's what the naming suggests to me).

The best person to ask would probably be @bclothier (who is in the blame for the code you were confused by).

**Comment by bclothier** [comment]
The key point to remember is that there are both managed and unmanaged access to the pointer. With unmanaged access, we are responsible for calling IUnknown::AddRef. But in managed access, the framework may implicitly do it for us. 

Marshal.QueryInterface:
> Calling an object with this method causes the reference count to increment on the interface pointer before the pointer is returned. Always use Marshal.Release to decrement the reference count once you have finished with the pointer.

Source: https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.queryinterface?view=net-5.0

Marshal.GetObjectForIUnknoqn:
> This method wraps IUnknown in a managed object. This has the effect of incrementing the reference count of the COM component. The reference count will be decremented when the runtime performs garbage collection on the managed object that represents the COM object.

Source: https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getobjectforiunknown?view=net-5.0

For that reason we need to be careful and not call AddRef in those cases or we would end up with dangling objects, or worse, prematurely deallocate the object before we were done with it.

**Comment by Greedquest** [comment]
@bclothier Thanks for the quick reply:)  Yeah that's very clear, I see why you might want to choose when to add a ref and when not to, I was more confused about the fact that the parameter doesn't appear to be used even though sometimes it's true and sometimes it's false e.g:

https://github.com/rubberduck-vba/Rubberduck/blob/2d29c231796b9dbb784755ceecf0c7aaa753d0d2/Rubberduck.VBEEditor/ComManagement/TypeLibs/TypeInfoWrapper.cs#L248

https://github.com/rubberduck-vba/Rubberduck/blob/2d29c231796b9dbb784755ceecf0c7aaa753d0d2/Rubberduck.VBEEditor/ComManagement/TypeLibs/TypeInfoWrapper.cs#L271

So it's like the addRef argument of `ComPointer<TComInterface> GetObjectViaAggregation(IntPtr pUnk, bool addRef, bool queryType)`  is being ignored? I don't speak much c# so may be missing something, soz!

@Vogel612  as bclothier points out, it looks that while AddRef is called explicitly on the unmanaged object for queryInterface = False, it's called implicitly by `Marshal.QueryInterface` when it's True so the underlying COM object ends up having the same ref count regardless IIUC.

**Comment by bclothier** [comment]
Greedquest, I am not sure why you think AddRed is being ignored, so I will try my best.

The line 248 has `addRef: true` because we have a managed object passed in:
https://github.com/rubberduck-vba/Rubberduck/blob/2d29c231796b9dbb784755ceecf0c7aaa753d0d2/Rubberduck.VBEEditor/ComManagement/TypeLibs/TypeInfoWrapper.cs#L241

OTOH, the line 271 has `addRef: false` because we only have an `IntPtr`:

https://github.com/rubberduck-vba/Rubberduck/blob/2d29c231796b9dbb784755ceecf0c7aaa753d0d2/Rubberduck.VBEEditor/ComManagement/TypeLibs/TypeInfoWrapper.cs#L261

The actual call to the `AddRef` would happen in the `ComPointer` class within the private ctor which is implicitly called via other paths:
https://github.com/rubberduck-vba/Rubberduck/blob/2d29c231796b9dbb784755ceecf0c7aaa753d0d2/Rubberduck.VBEEditor/ComManagement/TypeLibs/Unmanaged/ComPointer.cs#L97-L111

However, when we are aggregating objects, it’s a different rule as described here:
https://github.com/rubberduck-vba/Rubberduck/blob/f606675a9ee8e06474d2b41efcd175882440b812/Rubberduck.VBEEditor/ComManagement/TypeLibs/Unmanaged/ComHelper.cs#L34-L54

[This documentation](https://docs.microsoft.com/en-us/windows/win32/com/aggregation) describes how aggregation ought to work. But we are in a managed world, so we don’t get to directly control the implementation of the `IUnknown` interface. Thus we must ensure that aggregation doesn’t result in a dangling pointer due to having both the pointer to. the inner object and the outer object. We are supposed to release the inner object because the outer object will hold a reference to the inner object.

Also, it may help to note this function which is a part of the aggregation path:
https://github.com/rubberduck-vba/Rubberduck/blob/4797188e7600cc57825c360af19e04246aa8f5ee/Rubberduck.VBEEditor/ComManagement/TypeLibs/Unmanaged/ComHelper.cs#L140-L151

This allows us to “hide” buggy COM interfaces and expose only our safe COM interfaces.

Hope that answers your questions?

**Comment by Greedquest** [comment]
Let me explain my confusion; the function fragment I talked about in my first post:
https://github.com/rubberduck-vba/Rubberduck/blob/2d29c231796b9dbb784755ceecf0c7aaa753d0d2/Rubberduck.VBEEditor/ComManagement/TypeLibs/Unmanaged/ComPointer.cs#L73-L79

looks to me like a factory method for making new ComPointer objects. *The 2nd parameter to the factory function, `addRef`, doesn't appear to be used anywhere in the function body above*

---
 Now I may be missing something obvious and it is being used implicitly because of some weird inheritance stuff in C# that I don't get, but I think on line 78 you call the actual ctor which doesn't seem to use it:

https://github.com/rubberduck-vba/Rubberduck/blob/2d29c231796b9dbb784755ceecf0c7aaa753d0d2/Rubberduck.VBEEditor/ComManagement/TypeLibs/Unmanaged/ComPointer.cs#L119-L125

... it doesn't need to do any addref since `TComInterface comInterface` is a managed object at this point, but it's just weird the factory function has that parameter if all the addref is handled intelligently by the `RestrictComInterfaceByAggregation` constructor.

**Comment by Greedquest** [comment]
Yeah @bclothier, you say:

> The actual call to the `AddRef` would happen in the ComPointer class within the private ctor which is implicitly called via other paths

but both those ` internal TypeInfoWrapper(...)` functions call `InitFromRawPointer` which in turn calls `GetObjectViaAggregation` which _does not_ use the default ctor you reference, but an overloaded one with different parameters that doesn't accept an addref parameter, so `AddRef` is never additionally called* based on `bool addref`.

... I think - Or maybe I'm misunderstanding your explanation (I would not be surprised as you obviously know the code much better than my cursory glance!) Thanks for your time so far btw

*<sub>not to be confused with the fact that queryForType being false triggers Marshal.AddRef, this is a different point</sub>

**Comment by bclothier** [comment]
Correct. I looked at the aggregation code path & history and I can't remember why it is passing around `addRef` parameter. As noted earlier, aggregation works a bit differently from simply casting and thus the referencing counting are handled separately between the 2 cases (the private ctor and the aggregation "ctor").

Anyway, you're correct there. That function shouldn't have to take a `addRef` parameter. Maybe in one iteration, it did but it was determined to cause dangling pointer and then removed but without removing the now-unneeded parameter.
