### ISSUE TITLE
Power point unhandled exception

### ISSUE THREAD

**Issue by actioncentertest** [rubberduck-vba/Rubberduck#5676]
The weird exception dint allow to save document and keep popping up when I select a slide.   The error was "Pre-Production unhandled exception 'aou39'

**Comment by MDoerner** [comment]
Could you please verify whether this persists after deactivating loading Rubberduck on startup in the addin menu of the VBE?

If it does not persist, could you please provide us with the log after activating it again and encountering the error again?
Otherwise, we will have little chance to be of help.
