### ISSUE TITLE
How to use Rubberduck along with Git

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [rubberduck-vba/Rubberduck#5680]
Hello! How to use Rubberduck along with Git? Is there any CLI? I want to restrict any commits with ugly code.

**Comment by MDoerner** [comment]
Currently, there is no direct git integration. What Rubberduck provides is a method to export an entire project into a folder, reachable e.g. via the context menu of the code explorer, and several methods to import/sync files. There is a plain import command allowing to import multiple files. In addition there are the two sync commands, again reachable via the CE. The update command will import or overwrite from the selected files, i.e. already existing modules/classes will be replaced, but other modules will be left as-is. The replace command, on the other hand, will delete all modules/classes from the project and load the selected files instead. The exception are document modules since these can neither be created nor deleted from the VBE. Here, we only update the code.

**Comment by Greedquest** [comment]
Matt made a good blog post about this https://rubberduckvba.wordpress.com/2020/12/11/sync-project-with-files/

**Comment by gicif** [comment]
Hi all !
I apologize for this old boring question...
I have a couple UserForms in a VBA project.
Whenever I "export project", these UserForms are always seen as modified in version control (git), even if they really aren't.
There seems to be something volatile in these components or, better, in the binary file of these components (frx), since the code text file (frm) is unchanged. How could this behavior be managed? (is it possible to manage it?)

**Comment by retailcoder** [comment]
@gicif there's a bug in the VBIDE API with importing/exporting UserForm modules; it inserts a new empty line at the top every time - in principle Rubberduck's export commands "fix" this by removing that extra line, so if the diff isn't showing it then it's something else.

The .frx would be modified whenever anything changes in the designer, and IIRC there's just no telling how the VBIDE API is going to export that file: it's not impossible that it's indeed different every time if controls and their properties serialize in a somehow non-deterministic way.

If the .frx diff is pure noise, consider undoing changes in .frx files before committing.

**Comment by gicif** [comment]
> it's not impossible that it's indeed different every time if controls and their properties serialize in a somehow non-deterministic way.
>

This is indeed the case. I open the project, export it, close the project without saving anything. I reopen the project and re-export it. I compare the two frx (with a hex viewer) and they are different. I repeat everything and they are always different, even from the first time (other hex values).

>If the .frx diff is pure noise, consider undoing changes in .frx files before committing.
>
Thanks Matt, for the tip, I'll try it!

**Comment by EmilyGraceSeville7cf** [comment]
Are there any updates to this issue? 🌝

**Comment by Vogel612** [comment]
Considering how Rubberduck is currently being rearchitected to use LSP for Rubberduck 3, I would consider exposing any sort of CLI functionality for RD out of scope for RD2.

This notably includes the use-case described here.

Generally speaking Rubberduck will have a harder time correctly resolving references without access to a running VBE instance, which makes supporting non-VBE-bound usecases a LOT harder for inspections. Everything else is a different story.

**Comment by retailcoder** [comment]
I want this to happen the way we intended it in 2015 - that is, pretty much like in Visual Studio where you get a "Git Changes" UI in a tooltab, but without repeating the mistakes of 2015.

_A posteriori_, the main mistake was to integrate it as part of the main code base; it became a resource/dev hog that slowed down progress on everything else.

I want an extensibility model in the RD3 editor, so that it can load plugins that define their own tooltabs. Then, the very first plugin that comes to mind is exactly this, a "Git Changes" tooltab. Other extensions could be for a package manager (like Nuget or NPM but for VBA!), or anything else that is itself a project in its own right, maintained separately (possibly by the same people making RD).

Until such a plug-in exists, command-line git is the way. I'll try to get a _Windows Terminal_ instance hosted in a RD3 toolwindow, but I doubt RD3 features will be back-ported to 2.x, so it could be a little while still.
