### ISSUE TITLE
Code Inpsections>Ignore in module does not execute

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#5686]
**Rubberduck version information**
Version 2.5.1.0
OS: Microsoft Windows NT 10.0.18362.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.4978.1000
Host Executable: EXCEL.EXE

**Description**
Right clicking on an inspection result to choose Ignore in module then any option within has no annotation added and no action performed.

**To Reproduce**
1. Add a standard module.
2. Create new Sub procedure with several unqualified Range/Cells calls resulting in `ImplicitActiveSheetReference` results.
3. Parse and via IDE menu Rubberduck>Code Inspections to display the Code Inspections window. 
4. Group by inspection. Locate ImplicitActiveSheetReference group and ignore in module.

**Expected behavior**
Correct annotations is added depending on option selected.

**Comment by MDoerner** [comment]
The issue here is actually a bit worse. The problem is that the annotation currently gets added in the module of the inspection result's target. For most inspections, this is actually the same module the result is contained in. However, for identifier references, this can be an entirely different module. 

In this specific case, the inspection result is contained in the `EXCEL._Global` module, which does not have a code behind. Because of this, the quickfix silently fails with a caught NRE.

I will fix this oversight, which probably is my own.
