### ISSUE TITLE
Dimmed variant without index redimmed with index triggers incorrect warning and error

### ISSUE THREAD

**Issue by Rhodri-Howell** [rubberduck-vba/Rubberduck#5700]
Version 2.5.1.5557
OS: Microsoft Windows NT 10.0.19042.0, x64
Host Product: Microsoft Office 2016 x86
Host Version: 16.0.5134.1000
Host Executable: EXCEL.EXE

**Description**
A variant dimmed without an index and then redimmed with an index triggers variable is not assigned, when it has been assigned (with the index)

**To Reproduce**

    Public Function fn_Foo() As Variant
    Dim v_Foo As Variant  'Triggers Variable 'v_Foo' is not assigned; (NB Dim v_Foo(0) as Variant wouldn't)
    ReDim v_Foo(0)
    v_Foo(0) = "Test"
    ReDim Preserve v_Foo(1)
    v_Foo(1) = "Test 2"
    fn_Foo = v_Foo ' Triggers Varible 'v_Foo' is used but not assigned    
    End Function

**Expected behavior**
Don't report existing warning/error
Suggest Dimming with an index

**Comment by retailcoder** [comment]
The problem is that the local `Variant` has no metadata telling Rubberduck that it's an array, so it analyzes its use as it would a local `Variant` variable.

> Suggest Dimming with an index

I like that suggestion very much! I'd word it something like "Declare '{target_name}' as a dynamically-sized array", and have it quick-fix the declaration to `Dim v_Foo() As Variant`.

**Comment by retailcoder** [comment]
Actually fixing this involves implementing some runtime semantics around `Variant`, and that's... well, complicated.

As a rule of thumb, declaring anything `As Variant` or `As Object` is telling Rubberduck "that's late-bound and none of your business": whenever a more specific type can be used, a more specific type *should* be used, because late binding negatively affects static code analysis.

On one hand, I want to say "sure Rubberduck can infer the desired behavior from usage" - on the other hand, this absolutely feels like a huge can of worms with tons of bug-inducing implications. @MDoerner thoughts?

I'd like to get back to the problem statement:

> A variant dimmed without an index and then redimmed with an index

This is a problem in itself, because:

 - The no-index `Variant` declaration is redundant, because `ReDim` re-allocates it immediately.
 - Removing the redundant `Variant` declaration removes the two contested inspection results.
 - Dynamically-sized variant arrays should be declared like `Dim Name() As Variant`, with the `()` being all Rubberduck needs to understand `Name` as being an array. Without it, there is simply no compile-time metadata justifying treating it as an array.
 - Changing the redundant declaration to `Dim v_Foo() As Variant` also removes the two contested inspection results.

I'm thinking it's probably best for both Rubberduck and your own code, to leave the inspections alone and either:
- Remove the redundant `Variant` declaration, or
- Change the `Variant` declaration to a dynamically-sized array declaration
