### ISSUE TITLE
Latest release (v2.5.2.5906) has been flagged as malicious.

### ISSUE THREAD

**Issue by DavidS-BDO** [rubberduck-vba/Rubberduck#5762]
Microsoft Defender SmartScreen blocked the download flagging the file as 'could harm your device'. 

Additionally, a few other authorities flag it as well: https://www.virustotal.com/gui/file/b16b65e5120fad2095e97f5fe1cfac73d7668c102c0a182ce544868c0c75a0a3/details.

**Comment by retailcoder** [comment]
Thanks for the heads up!

This is a recurring and frankly extremely annoying behavior from AV software, that IMO is massively hurting OSS as a whole. If I recall correctly the last Rubberduck build I bothered to get white-listed was v1.4.3, back in 2015. The white-listing process ("just send us an email sent from a corporate email account") disgusted me so much, I consider anti-virus companies and their bloated software little more than a giant scam.

As you know this is open-source software, you can review the source code yourself if you like, and build it on your own machine if you don't trust AppVeyor CI's free tier to not introduce malicious components, but no, we're not going to hunt down every anti-virus provider out there to ask them to kindly whitelist our installer every time we build one. Just not going to happen. It's the same tiring story every single time, every release.

Antivirus software simply flags as "malicious" anything they haven't seen enough of before. >600 downloads in 48 hours isn't enough for them, apparently.

There's nothing we can do, other than have every single pre-release build white-listed every time with every AV provider out there, and I have other things to do with my life so that's not going to happen. For the record I personally download and install every single build onto my company-provided work laptop, and get the same Avast and Windows Defender prompts as everyone else. Sometimes I "report this application as safe" but it always seems to do exactly nothing whatsoever.

If you are downloading Rubberduck from https://rubberduckvba.com or the GitHub releases page on this repository, then you are downloading the tool we built. If you are downloading Rubberduck from some 3rd-party distributor, ...then you must trust that distributor to be distributing the exact same build as ours - and we do provide the hashes for that purpose.

**Comment by daFreeMan** [comment]
If the AV is actually preventing installation with no option to bypass, you may want to wait a couple of days and try again.

On occasion, I've had the installer flagged by our corporate AVs (yes, at one time, IT had 3 (three!) different AV apps installed on our machines). Either I've stuck with an older pre-release build until a new one was released (often within days), or I simply tried again the next day and it installed without complaint.

**Comment by retailcoder** [comment]
Note that it's 4 providers **out of 68**, and the fact that we're using an InnoSetup installer script **alone** accounts for over 48% of the "threat" rating. Consider the alternative: we could burn $1,250 for an InstallShield license just so antivirus providers stop telling people we're dangerous, and then we'd be distributing the _exact same software_ and none of these providers would be flagging it.

See how it's a scam?

**Comment by DavidS-BDO** [comment]
Perfect. That all makes sense. Thanks for the color. 

I will wait for more downloads before trying again on my end.  I am dealing with a corporate AV that tends to be very strict.
