### ISSUE TITLE
Code Inspector does not handle multiline statements

### ISSUE THREAD

**Issue by pchemguy** [rubberduck-vba/Rubberduck#5805]
Version 2.5.2.5871
OS: Microsoft Windows NT 6.2.9200.0, x64
Host Product: Microsoft Office XP x86
Host Version: 10.0.6501
Host Executable: EXCEL.EXE

**Description**
When Code Inspector detects an issue in a multiline statement:
```vba
          ConnectionString = ThisWorkbook.Name & "!" & _
                             ThisWorkbook.Worksheets(TableName).Name    '<- IndexedDefaultMemberAccess
```
it fails to add a single instance exception (at least when the problem is not in the first line). When such an exception is manually added, Code Inspector ignores it.

**Comment by MDoerner** [comment]
That no ignore annotation can be applied to any but the first line in a line-continued statement is a direct effect of the current scoping of our annotations. These always apply to the first physical line below them, i.e. the first line in the editor below them.
Since it is impossible to add comments on any but the last physical line of a line-continued logical line, it is currently impossible to apply an annotation to anything not in the first physical line of a logical line.

Changing this would require reworking the annotation scoping again, which is a bit more complicated to do in a performant way, if the annotations should apply to the following _logical_ line.
