### ISSUE TITLE
RubberDuck Integration into VSCode

### ISSUE THREAD

**Issue by abalhassans** [rubberduck-vba/Rubberduck#5833]
I am interested in a Rubberduck VSCode Extension to get many of the inspection features within  VSCode. I am looking for your assessment of how much effort would be involved to get these features in VSCode?

**Justification**
VSCode is primary IDE being used for vba code development. Would like many of the features to be available in VSCode

**Description**
Primarily interested in inspection features e.g unused variables 

**Additional context**

**Comment by Vogel612** [comment]
> "VSCode is primary IDE being used for vba code development" 

Citation needed.

There actually are some plans to move Rubberduck's capabilities to an external language server using the Language Server Protocol that is also employed by VSCode. (#5176)

This could help address problems with memory management, caching, invalidation and export behaviour, but an extension for Visual Studio would need some additional support.

You may also be interested in the [Twin Basic project](https://www.twinbasic.com/) that was created by Wayne Phillips, who contributed some very difficult VBE interaction components to the project.

Since the LSP prototype is already tracked and a VSCode extension would need a separate repository, I'm closing this issue as a duplicate :)

**Comment by serkonda7** [comment]
I'm maintaining a VS Code extension that brings improved VBA support: https://github.com/serkonda7/vscode-vba

Currently tho it only offers syntax highlighting, however I plan to extend the feature set.
Contributions are also appreciated.
