### ISSUE TITLE
Remove *.pdb files from release

### ISSUE THREAD

**Issue by A9G-Data-Droid** [rubberduck-vba/Rubberduck#5866]
**Justification**
Release versions should not contain debugging support files.

**Description**
These files add 13MB of junk to the installation that shouldn't be there for normal users. The purpose of these files is to debug release builds. They shouldn't be included in the final installation. 

The total install folder is 29.3MB so the PDB files make up %44 of the installation size.

![image](https://user-images.githubusercontent.com/26984068/135898568-97357205-e79e-4298-ba70-df88d4289e2f.png)

**Comment by Vogel612** [comment]
I am honestly surprised that those are visible. The releases (both prereleases and green releases) should be compiled with `RELEASE` enabled and `DEBUG` disabled (or more specifically, they are compiled using `RELEASE|Any CPU`.

It appears as though that does not automatically disable the generation of .pdb files. A fix would be to disable the generation of PDB information when we are in RELEASE mode in the RubberduckBaseProject.

**Comment by retailcoder** [comment]
We've been shipping these files since the beginning because they make exception stack traces point to specific code files and lines of code - without them release stack traces will still be readable, but only down to method names... which should be enough; I have no objection stopping the packaging of .pdb files.
