### ISSUE TITLE
Refactor > Rename: Provide Control of Scope of Operation

### ISSUE THREAD

**Issue by NDeLancie** [rubberduck-vba/Rubberduck#5870]
**Justification**
Refactor > Rename implements the renaming operation across the entire current project (all open projects?), but often renaming is desired only in the current module or even just the current procedure.

**Description**
Provide a radio button set in the Rename dialog box to control scope of renaming: all open projects, current project, current module, or current procedure.

**Comment by retailcoder** [comment]
Hi, thanks for the feedback!

Refactor/rename in Rubberduck is scoped by symbol resolution, not text search. The refactoring does what is necessary to keep the project consistent and compiling - if `Public Something As Long` is declared and used in `Module1` but also referenced in `Module2`, then "renaming" that variable "only in Module1" would amount to _breaking the code_, which isn't what a refactoring does (at least in theory ha!). And if there's a `Private Something As String` in `Module3`, then Rubberduck isn't going to rename _that_ one if you meant to rename the `Public Something` from `Module1`, because it knows and understands that `Something` means one thing inside `Module3`, and another in `Module1` and `Module2`. The "scope" of the refactoring is always as wide as that of the identifier you're renaming: renaming a local variable only affects the local scope; renaming a public variable affects that module _and everything that references it_.

What _could_ happen however, would be a regex-based text search/replace that could (and probably _should_) work within a certain scope - but that is a different functionality than refactor/rename.

**Comment by NDeLancie** [comment]
Ok, that’s good to know. I don’t know if it’s clear in the documentation, but a relief. I’ve been hesitant to use Refactor > Rename for this reason. I also hope that a RegEx search and replace feature (which exists on the menu but does nothing) will be provided, and yes, scope will clearly be needed there, but that is another matter.

 

Thanks for the quick reply.

 

                   Thanks,

                   

                   Nick
