### ISSUE TITLE
VariableDescription annotation not working for constants.

### ISSUE THREAD

**Issue by Rsge** [rubberduck-vba/Rubberduck#5926]
#### Rubberduck version information
* Rubberduck version: 2.5.2.5906
* Operating System: Microsoft Windows NT 10.0.19044.0 x64
* Host Product: Microsoft Office x64
* Host Version: 16.0.14701.20262
* Host Executable: EXCEL.EXE;

#### Description
When using the `@VariableDescription`-Annotation, it works fine with variables on module level, but shows an `InvalidAnnotation`-Warning when using it for constants on module level.

#### To Reproduce
Put this in a standard module (`.bas`) directly, not a sub or function:
```
'@VariableDescription "Test1"
Private Test1 As String

'@VariableDescription "Test2"
Private Const Test2 As String = "Test"
```
Rubberduck shows no `InvalidAnnotation`-Warning for `Test1`, but does so for `Test2`

#### Expected behavior
According to the website's documentation, `@VariableDescription` should work for constants, too.

**Comment by Vogel612** [comment]
From what I can tell (without an IDE and the exact inspection message) it seems that the `@VariableDescription` annotation is not correctly bound to `Const Test2` because the semantics between `AnnotationTarget` and `DeclarationType` are different. There is a dedicated `DeclarationType` for constants, and a separate one for Variables (which is necessary for proper resolution). But the `AnnotationTarget.Variables` encompasses both declaration types.

The fix is most likely going to be correctly binding the Variable-targetted annotation to the constant.

**Comment by MDoerner** [comment]
The problem is actually in the parser, more precisely in the `AttrubutesListener`. It does not save the attribute contexts for constants.
Since the `VarableDescriptionAnnotation` is an attribute annotation, it is considered invalid on objects without an attribute context.

**Comment by Rsge** [comment]
For completeness' sake, the log file with debug level logging enabled just before refresh:
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/7837446/RubberduckLog.txt)
