### ISSUE TITLE
wrong case of "member 'Range' implicitly references 'ActiveSheet'"

### ISSUE THREAD

**Issue by interservices** [rubberduck-vba/Rubberduck#5931]
The code inspector type "member 'Range' implicitly references 'ActiveSheet'" wrongly applies to 
`range(wks.cells(1,2), wks.cells(1,2))`
as in this case range implicitly reference wks, or atleast this is what it seems to me since it's working on wks even if activesheet is different than wks.

(also see your examples here: https://rubberduckvba.com/inspections/Details/ImplicitActiveSheetReference?example=1#examples)

**Comment by retailcoder** [comment]
As far as I can tell the `Range` property is indeed implicitly qualified in that instruction, which makes me expect error 1004 whenever the active sheet isn't `wks`, unless written in the code-behind of that specific worksheet.

Note that the example is *explicitly* qualifying the `Range` call while implicitly qualifying the inner `Cells` calls, which is the inverse situation, but both `Range` and `Cells` are properties of `Worksheet`, and the inspection is - correctly - flagging implicit references to _both_ (and a few others, too).

It's possible the code works fine as is in this particular instance; the problem is that by inconsistently qualifying `Worksheet` member calls, depending on where code is written and what sheet is active at run-time, you _will_ hit error 1004, and the cause will be implicit qualifiers flagged by this inspection.

If the code is written in the code-behind of the `wks` sheet, then the implicit qualifier is `Me` and the inspection is indeed wrong. Otherwise, it looks like it's trying to make you dodge a bullet to me!

**Comment by interservices** [comment]
The fact is that in range(sheet2.cells(1,2), sheet2.cells(1,2)), range implicitly reference to sheet2 instead than (the whatever) 'ActiveSheet' as Code Inspector wrongly says.

To see that, try these combinations in the immediate window or in a module while keeping sheet1 active:
activesheet.range(sheet2.cells(1,2), sheet2.cells(1,2)) = "abc"  '  -> error 1004
range(sheet2.cells(1,2), sheet2.cells(1,2)) = "abc"   ' -> writes "abc" in cell "B1" of sheet2
sheet2.range(sheet2.cells(1,2), sheet2.cells(1,2)) = "abc"   ' -> writes "abc" in cell "B1" of sheet2

As a frequent user of the short form range(wks.cells(1,2), wks.cells(1,2)) since I discovered that the implicit range reference just follows the (implicit or explicit) inner references, I was disappointed to see (many) warnings in Code Inspector (wrongly) telling me that these range calls implicitly references 'ActiveSheet', that is not true since I made explicit, and different than ActiveSheet, all the inner cells references.

Anyway, if you believe it's convenient to repeat the explicit reference in "range", you could just modify the last word of your warning message with the detected sheet: "member 'Range' implicitly references 'detectedSheet'".

**Comment by retailcoder** [comment]
A shorter form referring to a single cell would be `wks.Cells(1, 2)` though.

The problem with the implicit inferred-from-inner-calls form, is that it works until it doesn't. Lookup error 1004 on Stack Overflow, you'll see just how frequently it trips people over. Code that does one thing written here but does something else written identically over there, is exactly what Rubberduck is warning about. Agreed that the target should probably not be hard-coded, but "implicit Active sheet reference" is literally the name of the inspection class and there's little to no benefit making exceptions or duplicating the code to be make a similar one that only works in standard modules.

**Comment by interservices** [comment]
Ok I didn't know that if I put my range(wks.cells,wks.cells) expression in a document (sheet) module, the implicit reference to Me **prevails** on that inferred-from_inner_calls.
This is sufficient for me to give up on this.
