### ISSUE TITLE
Parse Error With Certain Files

### ISSUE THREAD

**Issue by ManuellMiranda** [rubberduck-vba/Rubberduck#5940]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

2022-01-24 15:41:24.2324;TRACE-2.5.2.5906;Rubberduck.Common.LogLevelHelper;
	Rubberduck version 2.5.2.5906 loading:
	Operating System: Microsoft Windows NT 10.0.19043.0 x64
	Host Product: Microsoft Office x64
	Host Version: 16.0.14729.20260
	Host Executable: EXCEL.EXE;

**Description**
When opening a specific file i get a parse error. The VBA code compiles without error. I am restrcited from posting the full file as it is company property.

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/7928739/RubberduckLog.txt)

**Comment by Vogel612** [comment]
That is very interesting. The parser seems to fail on `Option Explicit` when expecting an `<EOF>`. This suggests that you have declared the Option explicit later than the parser expects.

Since this is the latest green release it's impossible for the recent changes to the grammar to be responsible for this issue, which implies that this has been an issue for a bit longer than I'd like... Could you check whether (and how) moving the `Option Explicit` in the module `ThisWorkbook` affects this issue?

**Comment by ManuellMiranda** [comment]
Thank you for the help! I will test that today.

**Comment by ManuellMiranda** [comment]
I have found the issue. Removing option explicit made no difference and i got a parse error with and without it. However i noticed an issue in my code where i was declaring a variable outside a sub which was causing the issue.

This code causes a parse error.
`
Private Sub Workbook_SheetPivotTableUpdate(ByVal Sh As Object, ByVal Target As PivotTable)

With ActiveSheet.Range("A:BG")
.EntireColumn.AutoFit
End With

With ActiveSheet.Range("A:C")
.ColumnWidth = 1
End With

End Sub

Dim IsBookOpenStill As Boolean
`

This code does not cause a parse error
`
Private Sub Workbook_SheetPivotTableUpdate(ByVal Sh As Object, ByVal Target As PivotTable)

With ActiveSheet.Range("A:BG")
.EntireColumn.AutoFit
End With

With ActiveSheet.Range("A:C")
.ColumnWidth = 1
End With

End Sub
`

**Comment by retailcoder** [comment]
The VBE will not compile VBA code that isn't in a module that's not loaded in the execution path of a given entry point. For example if you had Module1 with invalid code, and a macro in Sheet1 and nothing in Sheet1 is referring to anything in Module1, the Sheet1 macro can still compile and run even though the project as a whole won't.

You can manually verify whether your project compiles using the "Compile (ProjectName)" command from the Debug menu... or, there's a setting in Rubberduck to require the project to compile before starting to parse it; when checked, that option will have Rubberduck essentially invoke that "compile project" command, which exposes compiler errors that might otherwise have gone unnoticed, and reduces the occurrence of parser errors 😉

**Comment by ManuellMiranda** [comment]
Thanks! I think the best option for me is to enable that setting. I have a few projects that cause parser errors so clearly my code needs some work :)

**Comment by Greedquest** [comment]
@ManuellMiranda 

<kbd>Alt</kbd> + <kbd>D</kbd> + <kbd>L</kbd> 

Sometimes you have to add and delete some empty lines/modify something in the VBE for this shortcut to be enabled.
