### ISSUE TITLE
Date of End-User License Agreement

### ISSUE THREAD

**Issue by INOPIAE** [rubberduck-vba/Rubberduck#5953]
Today I installed Rubberduck (2.5.2.5906) on a new pc and I was quite astonished to read in the End-User License Agreement:
Last updated: 1970-01-01

Is the date correct?
Is it the correct license or should it not be the GPL that should be displayed here?

**Comment by retailcoder** [comment]
Was it the only astonishing thing in the EULA? 😉

That's by design, since GPL isn't a EULA it makes little sense to make end users "agree" to terms that essentially govern the source code (we did keep the applicable "as-is in the hope it will be useful" part). It was changed last year if I recall correctly.

**Comment by INOPIAE** [comment]
I just read the first Loines of the EULA.
