### ISSUE TITLE
actualizing code automatically

### ISSUE THREAD

**Issue by DonBorste** [rubberduck-vba/Rubberduck#5967]
**Justification**
Actualize the code automatically in background and not over the manual way by clicking a button for that.

**Description**
Make it possible (maybe over personal settings) to actualize the vba code automatically in background 
- if the editor gets opened 
- after a time which can be given in rubberduck settings 
**without blocking work**.

**Additional context**

**Comment by Vogel612** [comment]
related #4862

**Comment by DonBorste** [comment]
Ok, now I'm not sure what you mean, therefor a screenshot is maybe better than ambiguous descriptions ;-)
I mean the "refresh" button / functionality which actualize the code linking...

![Rubberduck_Refresh](https://user-images.githubusercontent.com/103099800/161955323-5cdb307a-fbfe-411a-a133-b651525353ee.jpg)

**Comment by Greedquest** [comment]
@Vogel612  I think the request is to refresh RD/the parser automatically on a time interval (and on startup or other key moments).

@DonBorste At the moment, I think RD (RubberDuck) used to refresh on startup but this can lead to slow loading times especially if you only want to run/view VBA not analyse it with RD.
Refreshing on a time interval might be tricky as RD cannot parse broken code so it might not be very useful to have it refresh as you type. 
Other events like not pressing any keys for a while (indicating you aren't halfway through a line) could trigger a refresh that is more likely to succeed than on fixed time intervals, but RD isn't actually that deeply integrated into the VBA editor and some events are hard to capture. I think there is a plan to make RD its own editor rather than just an addin to the VBA default editor (VBE), that would give much more flexibility in this regard.

My method here is to use the keyboard shortcut <kbd>Ctrl</kbd>+<kbd>'</kbd> to refresh (all RD keyboard shortcuts are configurable, that's the default)*. This means I only trigger the refresh on demand when I know my code isn't broken. Also <kbd>Alt</kbd>+<kbd>d</kbd>+<kbd>l</kbd> recompiles your vba code so you can check for compilation errors before refreshing.

RD does automatically refresh when it knows it can - e.g. after a refactoring like Rename token the parser will automatically refresh.
---

<sub>*Note there is a bug in RD where it loses focus and sometimes the keyboard shortcuts don't work - in this case all you have to do is  click a rubberduck window to bring the focus back and they'll work again. Running <kbd>Ctrl</kbd>+<kbd>e</kbd> then <kbd>Esc</kbd> to flash open and shut the export project menu also works to bring focus back without your hands leaving the keyboard</sub>

**Comment by MDoerner** [comment]
I would like to add that we actually try to refresh on load of the VBE. However, the VBE's startup order is extremely unreliable. Since we must not query the VBE for the code before it has actually loaded the project, we listen for the project added event. Unfortunately, most of the time, but not always, the VBE finishes loading all projects before loading Rubberduck. In that case, the automatic refresh does not happen.

**Comment by Greedquest** [comment]
@MDoerner Oh that's interesting, I didn't know that. Weird the startup order changes in an unpredictable way like that!

**Comment by retailcoder** [comment]
This feature is happening in v3, but isn't going to work (not _nicely_ anyway) with the 2.x structure. Deferred to v3, since v3 is where Rubberduck gets to fully control the editor (by making our own!); automatic (using an idle timer reset on keypress) parsing proof-of-concept passed with flying colors - with parsing actually happening asynchronously and in a separate process in v3 (that part is WIP), consider it done 😉
