### ISSUE TITLE
The Implicitly Typed Const quick fixes don't do anything

### ISSUE THREAD

**Issue by DVT7125** [rubberduck-vba/Rubberduck#6102]
**Rubberduck version information**

    Rubberduck version [v2.5.2.6242) & 2.5.2.6260 & 2.5.2.6258
    Operating System: Windows Server 2022 x64 (Microsoft Windows NT 10.0.20348.1607) &
    Windows 11 pro x64 (10.22621.1413)
    Host Product: Microsoft Office x64
    Host Version: 16.0.16130.20332 & 16.0.16227.20212
    Host Executable: EXCEL.EXE

**Description**
If you have an implicitly Typed Const problem, like in this code:
Public Const DatePickerX_Title_Font = &H80FF80
You should be able to click on the quick fixes for it and fix it to this:
   Public Const DatePickerX_Title_Font as long = &H80FF80

**To Reproduce**
1. Go to and put in Public Const DatePickerX_Title_Font= &H80FF80 
2. Put more than 1 of these
3. Then go to code inspections and try the quick fix.
4. It just won't do anything. Sometimes it will apply the quick fix if you do it one at a time.

**Expected behavior**
it should always work, and all quick-fix buttons should do as the buttons say they will.

**Screenshots**
![Screenshot (11)](https://user-images.githubusercontent.com/99568947/227734176-baac7a2a-db78-4829-a658-a30ef769f091.png)

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/11069721/RubberduckLog.txt)

**Comment by DVT7125** [comment]
Just tested on the 2 newer versions and it still does not work,

**Comment by DVT7125** [comment]
Also if you select the "Selected occurrence" as the first thing after a refresh it will apply the fix. But then to apply the fix again you have to refresh.

**Comment by MDoerner** [comment]
Having to refresh after fixing one is expected since the module's state is not in line between Rubberduck and the VBE anymore; the first fix has changed the module. We have to reparse the module in this case.

Anyway, I cannot reproduce this on my machine with a debug build. However, my system specs are a bit differnent.
```
	Rubberduck version 2.5.2.0 loading:
	Operating System: Windows 10 Pro 2009 x64 (Microsoft Windows NT 10.0.19045.0)
	Host Product: Microsoft Office x64
	Host Version: 16.0.16130.20306
	Host Executable: EXCEL.EXE;
```

**Comment by BZngr** [comment]
I am unable to reproduce this scenario as well...

**My version info:**
```
Version 2.5.2.x (debug)
OS: Microsoft Windows NT 10.0.19044.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.16227.20280
Host Executable: EXCEL.EXE

```
Step 2 of the 'To Reproduce' steps:  "Put more than 1 of these" makes the VBA code un-compilable resulting in the pop-up message: 
>The following project(s) cannot be compiled, which will most likely result in parser errrors.  Continue anyway?

Clicking OK to this message results in Rubberduck completing its parse.  I did not expect the `QuickFix` to work since the targets in question _were_ the un-compilable code.  But, in my test, it still applied the `QuickFix` correctly - whether I selected one or _both_ of the flagged constants.
