### ISSUE TITLE
Rubberduck crashes at startup

### ISSUE THREAD

**Issue by philippetev** [rubberduck-vba/Rubberduck#6119]
Version infomation:

Version 2.5.2.6277/6279
OS: Microsoft Windows NT 10.0.22621.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.16529.20126
Host Executable: EXCEL.EXE

While starting, I get this error message:

![image](https://github.com/rubberduck-vba/Rubberduck/assets/5438221/3ef90c2d-3750-42e9-9a41-9ffa327ebf1b)
and the addon doesn't load in VBE at all.
Tried to clean the configuration, but I get the same screen.

This occurs only with builds 6277 and 6279. Version 6271 has no such issue.
Happens on both my desktop and laptop.

Logs:
[RubberduckLog.6271.zip](https://github.com/rubberduck-vba/Rubberduck/files/11837960/RubberduckLog.6271.zip)
[RubberduckLog.6277.zip](https://github.com/rubberduck-vba/Rubberduck/files/11837961/RubberduckLog.6277.zip)

**Comment by Vogel612** [comment]
It seems like you switched around the names of the affected versions in the uploaded zip files. Either way, this issue was introduced with #6093, where a large-scale refactoring towards using `DynamicResource` in our XAML definitions was performed. The error message suggests that `DynamicResource` is used within a binding converter, which is not allowed.

A quick grep invocation suggests that we have 110 instances of this. In opposition to that we have a total of 593 `DynamicResource` usages. Before the relevant MR we had 55 usages of DynamicResource in total and none where the DynamicResource was used as a Converter.

**Comment by Vogel612** [comment]
We're hoping that the change merged 15 minutes ago (the release should automatically publish in less than half an hour) fixes the issue. In the meanwhile I removed both affected releases (and their associated tags)
