### ISSUE TITLE
Autocompletion is not working very well

### ISSUE THREAD

**Issue by Starkard1** [rubberduck-vba/Rubberduck#6129]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

    Rubberduck version [2.5.9.6291]
    Operating System: [Win10 x64]
    Host Product: [MSOffice x64]
    Host Version: [16.0.16529.20154]
    Host Executable: [EXCEL.EXE]

**Description**
The autocompletion function is not completing functions such as If...For...etc.

**Comment by retailcoder** [comment]
Yeah that would be _block completion_; there was an initial implementation at one point, but it never shipped because I wanted it to work a bit like in VS/VSC with placeholders, but dealing with the char offsets while fighting the VBE's own auto-formatting made it a no-go.

The feature as shipped works as intended: it'll complete quotes and tremendously help with concatenating or breaking down large string literals.

Block completion will happen in RD3.x, when we have full control over the editor pane.

**Comment by Starkard1** [comment]
I understood. I made the report because I was looking for videos about the tool and even the RubberDuckVba page on YouTube mentioned this functionality, which on my PC does not work. Thank you very much for the brief reply.
