### ISSUE TITLE
Frequent Access 2021 crashes during code parsing

### ISSUE THREAD

**Issue by rkorne** [rubberduck-vba/Rubberduck#6144]
**Rubberduck version information**
Version 2.5.9.6289
OS: Microsoft Windows NT 10.0.19042.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.14332.20546
Host Executable: MSACCESS.EXE

**Description**
During code parsing Rubberduck crashes and takes Access down. Last status is "Inspecting".
Rubberduck log shows System.OutOfMemoryExceptions

With Access 2013 there have been frequent errors "Not enough System Resources" and / or "Not enough memory", but not crashes.
And yes, it's a big project.

**To Reproduce**
1. Open Access VBE
2. Click on Refresh
3. See error

**Expected behavior**
no crash, no error message

**Screenshots**
not available

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/12432431/RubberduckLog.txt)

**Additional context**
Apart from this issue I'm a happy user of Rubberduck. Wouldn't want to work without it.

**Comment by rkorne** [comment]
Please set this as critical, I can't work with my Access aplication at all in 2016.
Crashes with last stable as well.
Version 2.5.9.6291
OS: Microsoft Windows NT 10.0.19042.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.14332.20546
Host Executable: MSACCESS.EXE

**Comment by rkorne** [comment]
closed by mistake

**Comment by Vogel612** [comment]
The issue in the log file is an out of memory exception. This is an unfortunate problem we keep having, since we're memory-limited by the VBE context and keeping the parsing tree of code and all inspection results in memory is ... difficult.

There is an open issue around RAM consumption where some tips can be found at #3347.

With Rubberduck3 this should be greatly alleviated because we push the state management into a separate process, which allows us to be free from the VBE memory limit :)
