### ISSUE TITLE
Examples of legal single line if statements in VBE, rubberduck parsing failed:

### ISSUE THREAD

**Issue by neorobin** [rubberduck-vba/Rubberduck#6163]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

Version 2.5.9.6291
OS: Microsoft Windows NT 10.0.19045.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.16827.20130
Host Executable: EXCEL.EXE

**Description**
Examples of legal single line if statements in VBE, rubberduck parsing failed:
`         If True Then:`
or
```
         If True Then::::::::::::: _
             :::::::::::::::: _
             :::
```
The above two writing methods can be compiled in VBE, but rubberduck fails to parse.

**Comment by retailcoder** [comment]
Not sure that one is fixable, IIRC the grammar is ambiguous around the `:` token.
Note that while having a trailing `:` (nevermind 20 of them!) is indeed legal in the inline `If` syntax, its use is heavily discouraged because of how confusingly misleading it makes the condition. That said you are absolutely correct that Rubberduck should still be able to parse it.

**Comment by MDoerner** [comment]
Ok, I will fix this, but please note that this fails only in the really useless case that the Then part only consists of statement separators and white space, including line continuations, and there is no Else part. With an Else part, no matter whether it is empty or not, the statements parse just fine.

**Comment by retailcoder** [comment]
@MDoerner thanks! Parsing such redundant empty instructions allows us to warn about them!
