### ISSUE TITLE
Refactor>Rename is not available

### ISSUE THREAD

**Issue by Rovo1211** [rubberduck-vba/Rubberduck#6228]
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

    Rubberduck version 2.5.9.6316
    Operating System: Windows 11 Hom e23H2
    Host Product: MS Excel
    Host Version: Office365
    Host Executable: EXCEL.exe

**Description**
I've installed, uninstalled, and reinstalled Rubberduck several times. Occasionally, the Refactor > Rename feature becomes available, but most of the time, it does not work.

I’ve also tried other solutions, such as renaming the Rubberduck.config file to Backup_Rubberduck.config to force Rubberduck to create a new configuration file. However, the newly generated Rubberduck.config made the situation even worse.

Rubberduck has worked properly in the past, but I’ve noticed that whenever there’s an unexpected or strange error in my code, Rubberduck seems unable to handle it, and features like Refactor > Rename stop functioning.

Path %appData%Rubberduck. 

**To Reproduce**
1. Go to Rubberduck
2. Click on Refactor
3. Scroll right to Rename
4. See error: unavailable!!!

**Expected behavior**
That Refactor>Rename is available.
**Screenshots**
![Screenshot Rubberduck-Refactor unavailable](https://github.com/user-attachments/assets/4fbf8345-774c-4e6b-ac50-1d3722136b47)

**Logfile**
Rubberduck generates extensive logging in TRACE-Level. If no log was created at `%APPDATA%\Rubberduck\Logs`, check your settings. Include this log for bug reports about the behavior of Rubberduck.
[RubberduckLog.txt](https://github.com/user-attachments/files/18010295/RubberduckLog.txt)

**Additional context**

**Comment by Rovo1211** [comment]
Better image of the problem with Refactor>Rename:
![Screenshot Rubberduck-Refactor unavailable](https://github.com/user-attachments/assets/c9f9fd29-5fc4-4b48-a19f-9ae8bdd8e35b)

**Comment by retailcoder** [comment]
Hi, thanks for the feedback! This is entirely by design: Rubberduck assumes it's working with compilable VBA code that VBA can compile and run.
There's a plan to make v3.x able to handle syntax errors and report them with red squiggles, but in 2.x syntax errors must be fixed before Rubberduck can parse the code.
All the features that involve writing any code are intentionally disabled whenever Rubberduck's internal representation of the code doesn't match what's in the editor, because then doing something like renaming a variable would break everything and lose code changes, and we don't want that to happen.

**Comment by retailcoder** [comment]
The problem is that you are declaring constants outside of the module's _declarations_ section, which is the only place VBA allows such declarations. Once there's a procedure scope in a module, the only thing that can legally go underneath it is another procedure scope declaration.

Issuing meaningful parser error messages is something that demands a tremendous amount of effort, for extremely little gain (and the added possibility of introducing new bugs and even more confusing messages). As such, it was decided to let the VBE and compiler deal with reporting syntax errors.

**Comment by Greedquest** [comment]
@Rovo1211 my workflow is always to do `alt`+`d`+`l` to force VBA to check your code is compilable, then `ctrl`+`'` to make rubberduck refresh (or any other rubberduck command, most trigger the refresh as well)

<sub>Sometimes you need rubberduck to gain focus for the keyboard shortcuts to work, so I do `ctrl`+`E`,`Esc` to quickly bring the focus to rubberduck by opening and then closing the export dialog</sub>
