### ISSUE TITLE
Feature Request: Dockable Windows for Code Explorer, Test Explorer, Todo Explorer, and Code Inspections

### ISSUE THREAD

**Issue by Rovo1211** [rubberduck-vba/Rubberduck#6231]
**What**
Currently, these windows float as separate entities, which can make it challenging to manage screen real estate when working on larger projects or when switching between multiple tools. Additionally, the floating windows often cover the code, disrupting the workflow and making it harder to navigate between the explorers and the code editor.

While it is possible to dock the windows next to each other, this approach often consumes too much horizontal space. Allowing the windows to be docked under each other (stacked vertically) would provide a more efficient layout, especially on smaller screens or when working with a single monitor.

Dockable windows, similar to those in modern IDEs like Visual Studio or even the VBA editor's Properties and Project Explorer windows, would allow users to:

    Organize workspace more efficiently by attaching these explorers to specific areas of the VBA editor interface.
    Reduce clutter by grouping related tools together.
    Enhance focus by allowing seamless integration of Rubberduck’s powerful features into the VBA development workflow.

I believe this feature would align perfectly with Rubberduck’s mission to improve the VBA development experience.

**Why**
These mentioned windows are floating over the screen and covering code.
![Example Docked windows horizontally](https://github.com/user-attachments/assets/e8200552-6a9e-479d-98ba-3eca6e34c452)

Kind regards,
Ronald de Vos, The Netherlands.

**Comment by retailcoder** [comment]
Uhm, all the toolwindows are dockable already, and always have been (literally since before release 0.1).

The native toolwindows (Project Explorer, Properties, etc.) can be undocked by dragging them elsewhere; Rubberduck toolwindows are exactly the same kind of window and should behave identically, unless you specifically _made_ them undockable by right-clicking their title bar.

The problem is that native docking in the VBE sucks, ...but it's there, and it's entirely managed by the VBE and the Windows Registry.
