### ISSUE TITLE
Fix All

### ISSUE THREAD

**Issue by Hosch250** [rubberduck-vba/Rubberduck#651]
Right now, we have to fix each inspection result individually.  We should allow the user to fix all inspections of a given type that offer a quick fix with one click.

**Comment by retailcoder** [comment]
Right now, inspections work off parse results.. and that's not likely to change. Parse results include token positions, which is essentially how everything gets located in a code pane.

By applying a quickfix, we invalidate the parse results and token positions in a module. "Fix all" would require either re-parsing the module between every applied fix, or a very clever way of offsetting line numbers and/or column positions.

I'm tempted to close as "status-declined", but leaving it opened for discussion.

**Comment by Hosch250** [comment]
This actually wouldn't be an issue, I don't think.  All you have to do is use LINQ: `.Where(i => i.Name == SpecifiedName).OrderByDescending(LineNumber)`.  Apply the fix in order, and the ones at the bottom will be fixed first, not affecting the others.  Then reparse.

**Comment by retailcoder** [comment]
@Hosch250 how about the case where you have multiple issues of the same type on the same line? Say you have 10 variables implicitly declared as `Variant` on the same instruction?

**Comment by Hosch250** [comment]
Then you sort by StartColumn.

**Comment by retailcoder** [comment]
and go right-to-left huh?

    Dim a, b, c, _
           d, e, f, _
           g, h, i

^^ breaks

**Comment by retailcoder** [comment]
wait... this might work.

**Comment by daFreeMan** [comment]
Glad I noticed this, I was going to request it!  I thought about adding a checkbox column to the _Code Inspections_ window so the user could select multiple issues to be fixed with one click.

An initial implementation might allow it only for specific fix Inspection types:
- Member {x} is implicitly Public
 - Make all marked `Public`
 - Make all marked `Private`
- Parameter {x} can be passed by value
 - Change all to `ByVal`
- Variable {x} is never used|assigned
 - Delete declaration
 - Comment declaration (I'm fond of this one until things are working correctly, but then, my VBA isn't in Git quite yet)

Those should be simple since they should only effect one line of code, though if [this](https://github.com/rubberduck-vba/Rubberduck/issues/651#issuecomment-113538701) breaks things, that might need to be in phase 2 of the implementation.

**Comment by retailcoder** [comment]
The refactored inspection results /quickfix classes support this. It's only a matter of coming up with a nice xaml item template that hooks up the commands.

**Comment by retailcoder** [comment]
Linkbuttons in the bottom section don't look too bad:

![image](https://cloud.githubusercontent.com/assets/5751684/10127382/d805ae90-656e-11e5-8643-bc692a610d80.png)

And it works!
