### ISSUE TITLE
Code Inspection for "Procedure {x} is never used" doesn't check/find form events

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#707]
In my Access project, I have a form with a lot of buttons with events attached. Each one of the procedures called by an event is flagged as "never used" by the _Code Inspector_.

Also, `Form_Load` is flagged as "never used".

**Comment by daFreeMan** [comment]
You should be able to find a very simple Access database with a single form and a single button here:

https://drive.google.com/folder/d/0B3Ctki7FAhFlVkswWkJHWlQ0YU0/edit

When you open the DB, the form should open and a message box stating "Form loading" will appear. When you click the button you will see a message box stating "You clicked the button".

When you run code inspections, you'll see that both of the procedures to display the message boxen will be flagged as unused.

**Comment by retailcoder** [comment]
Access forms are not MSForms, that's why; in other Office hosts we find all the controls on a form and create a `Declaration` object for each one, so we know which procedures are handlers for these controls.

I don't have MS-Access so I'm not sure how to go about getting the same thing to work for Access forms. @ckuhn203 might have a clue?

**Comment by ckuhn203** [comment]
@Retailcoder do you know whereabouts the code is that you're referring to? If we have a way to handle this for MSForms & Excel, then surely I can make this happen for Access.

**Comment by retailcoder** [comment]
@ckuhn203  in the [DeclarationSymbolsListener](https://github.com/rubberduck-vba/Rubberduck/blob/a40594ce876e324393298067371cd87f1cab3573/Rubberduck.Parsing/Symbols/DeclarationSymbolsListener.cs#L53-L56) class, when the component type is `vbext_ComponentType.vbext_ct_MSForm`, we call a [DeclareControlsAsMembers](https://github.com/rubberduck-vba/Rubberduck/blob/a40594ce876e324393298067371cd87f1cab3573/Rubberduck.Parsing/Symbols/DeclarationSymbolsListener.cs#L65-L82) method, which iterates the designer controls:

    foreach (var control in ((dynamic)designer).Controls)
    {
        _declarations.Add(new Declaration(_qualifiedName.QualifyMemberName(control.Name), _parentDeclaration, _currentScope, "Control", true, true, Accessibility.Public, DeclarationType.Control, null, Selection.Home));
    }

The `DeclarationType.Control` declaration type tells the rest of Rubberduck that these declarations aren't in-code, while still allowing to resolve code-behind references, which makes the *rename* refactoring able to rename form controls - methods that start with the control's name and an underscore, are treated as event handlers and renamed along with the control by the *rename* refactoring.

**Comment by retailcoder** [comment]
@ckuhn203  As for `Form_Load`, it's not picked up as a form event because, well, [MSForms has no `Load` event](https://github.com/rubberduck-vba/Rubberduck/blob/32f350d6ef0cf072db126a5400227c589d983708/Rubberduck.Parsing/Symbols/VbaStandardLib.cs#L673-L696), and then there's the [FindFormEventHandlers](https://github.com/rubberduck-vba/Rubberduck/blob/6ab89507414f2dd4fb34892b902d54df05c917ea/Rubberduck.Parsing/Symbols/Declarations.cs#L157-L168) function that the inspection uses to determine which procedures to treat as "form event handlers":

        public IEnumerable<Declaration> FindFormEventHandlers(Declaration userForm)
        {
            var events = _declarations.Where(item => item.IsBuiltIn
                                                     && item.ParentScope == "MSForms.UserForm"
                                                     && item.DeclarationType == DeclarationType.Event).ToList();
            var handlerNames = events.Select(item => "UserForm_" + item.IdentifierName);
            var handlers = _declarations.Where(item => item.ParentScope == userForm.Scope
                                                       && item.DeclarationType == DeclarationType.Procedure
                                                       && handlerNames.Contains(item.IdentifierName));

            return handlers.ToList();
        }

Notice it's making the handler names `"UserForm_" & item.IdentifierName`, out of built-in declarations where the `DeclarationType` is `Event` and the `ParentScope` is `MSForms.UserForm`: the assumption here is obviously that the forms library is `MSForms`; I'm not sure modifying this procedure is the correcty way to go about it. Perhaps rename it to `FindMSFormEventHandlers`, and then make a similar one that fetches the events from whatever other forms library Access uses (well, `IsBuiltIn` declarations with a different `ParentScope` I mean), and makes the handler names `"Form_" & item.IdentifierName` instead.

The inspection itself is looking at the component type to determine whether there are any forms in the project:

            var forms = parseResult.Declarations.Items.Where(
                item => !item.IsBuiltIn && item.DeclarationType == DeclarationType.Class
                        && item.QualifiedName.QualifiedModuleName.Component.Type == vbext_ComponentType.vbext_ct_MSForm)
                .ToList();

            if (forms.Any())
            {
                handlers.AddRange(forms.SelectMany(form => parseResult.Declarations.FindFormEventHandlers(form)));
            }

If Access uses the `vbext_ct_Document` component type for its forms, this is going to get ugly.

**Comment by daFreeMan** [comment]
I just noticed this:

"in other Office hosts we find all the controls on a form and create a Declaration object for each one, so we know which procedures are handlers for these controls."

And I'm not sure I'd agree that this is working - I have an Excel worksheet with buttons, and the Subs that get called by those buttons are getting flagged as never used. (v1.4.3).

I can put together a simple demo if you'd like.

**Comment by retailcoder** [comment]
We find controls on **forms**, not in worksheet shapes (yet) :wink:

**Comment by daFreeMan** [comment]
Ah, gotcha. I do like the "yet"!  :)

**Comment by Hosch250** [comment]
This only flags the button event as not being used now.  I *think* that is because we don't have a declaration for the button because the form is created in Access rather than the VBE, but I will have to check.

**Comment by Hosch250** [comment]
Rubberduck does not have a declaration for the button.  The inspection works correctly.
