### ISSUE TITLE
Parser doesn't seem to like #const

### ISSUE THREAD

**Issue by zippy1981** [rubberduck-vba/Rubberduck#718]
This code runs, and contains #const instead of const. 

https://github.com/VBA-tools/VBA-Dictionary/blob/master/Dictionary.cls

Your Parser doesn't like that.

**Comment by retailcoder** [comment]
https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/Grammar/VBA.g4#L120

Turns out the grammar doesn't even define a token for it, that's why the parser doesn't like these instructions.

Should be an easy fix, definitely for next release.

Note that there's a known issue with the grammar, if precompiler directives are intertwined with other block statements, the parser won't be able to figure it out.
