### ISSUE TITLE
Logging of the main project

### ISSUE THREAD

**Issue by zippy1981** [rubberduck-vba/Rubberduck#737]
The parser uses NLog. There is no logging in the main addin solution. I propose (and will provide a patch for) the following:

* Nlog be configured for the main addin. It will write to a file for all severity and the event log for error severity
* A new event source be created in the application event log called RubberDuck.
* The installer will create this event source
* When one of the toolbox windows fails to initialize, the entire Exception details will be written to nlog at error level
* When the addin fails to initialize, the fill exception will be written to the event log
* I'll add some verbose messages (which won't be written anywhere by default) for all the tooltops being intiialized and long running actions starting and stopping for profiling purposes

**Comment by retailcoder** [comment]
:+1 I like that. I hadn't included NLog in the main dll because, to be honest, I had no idea *what* to log. I'm currently refactoring (heavily) the application's entry point to use Ninject - since Rubberduck.dll already has a dependency on Ninject, let's consider adding `Ninject.Extensions.Logging`; it automagically injects a class logger to whichever type declares an `ILogger` dependency in its constructor.

**Comment by zippy1981** [comment]
Well I've never actually done DI. Its about damn time I learned, ok I'll do that.

**Comment by retailcoder** [comment]
@zippy1981 IIRC nothing changes with the NLog configuration (has to be written in plain code with the config API, since we're a dll - the xml config won't work), it's just a matter of loading the NLog module into the Ninject kernel, and that's it.

Now, if you've peeked at my fork (haven't touched it in a week, been away), the way things are instantiated is drastically changing; I'm hoping to close #606 when I merge these changes, so the odds of merge conflict are just about 100%... a better alternative would be to set up NLog without Ninject in mind, and leave the logger dependencies tightly coupled with the classes consuming them, like..

    _logger = LogManager.GetCurrentClassLogger();

and then proceed with the logging code.

The real value here is with the logging configuration (wiring up NLog with the event log) and with the actual logging code - not so much with the DI plumbing.

**Comment by retailcoder** [comment]
#746 has been merged, I'm closing this issue - well done! :+1:  :beer:
