### ISSUE TITLE
Code Inspection Fix removes entire line when Issue is "Variable 'varname' is never assigned/used" and "Instruction contains multiple declarations"

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/Rubberduck#740]
I'm checking out the Code Inspections now and loving it. I did come across one issue that I wanted to bring to your attention, as you were so helpful already and I'm thankful to have the opportunity to give back in testing time.

Here is what the Code Inspections found:
    
![unnamed](https://cloud.githubusercontent.com/assets/2716800/9062470/9bc28650-3a90-11e5-858f-32a55bf6803d.png)

And here is line 174 of the module:

    Dim temp As String, MySpot As Integer, HoursLeft As Single

Clicking the Fix option for the current line removes line 174 entirely, even though the first two variables are assigned and used.

I wonder if it would be possible to add one more sort parameter to the table and force the "Instruction contains multiple declarations" issue to precede other issues of the same line.

**Comment by retailcoder** [comment]
I don't know about the sorting precedence of a specific inspection vs. another, it seems to open the door to inconsistencies.

The bug is really that the quick-fix doesn't seem to account for multiple declarations on the same line, and was implemented to simply remove the line of the unused declaration. The solution is to make it remove the specific involved tokens, not wipe out the entire line.

I bet there are more like this.

**Comment by Hosch250** [comment]
If this is not fixed yet, I have a tried and tested method for surgically removing variables from a list, as long as the parser is up-to-date.  Check out the Move Closer To Usage refactoring.

**Comment by retailcoder** [comment]
@Hosch250  yeah, it's not fixed yet.

**Comment by Hosch250** [comment]
Also, the Introduce Field, Introduce Parameter, and Encapsulate Field refactorings use this method and its callees.
