### ISSUE TITLE
Not recieving AppVeyor build notifications

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/Rubberduck#747]
I'm still getting build notifications emailed to me, but they're not showing up on GitHub or chat.

**Comment by retailcoder** [comment]
no idea how to fix this

**Comment by retailcoder** [comment]
the webhook's paylod url was mismatched... somehow.

**Comment by ckuhn203** [comment]
@retailcoder mind linking a commit so we know how to fix it should it break again?

**Comment by retailcoder** [comment]
@ckuhn203 the appveyor webhook payload url mismatched the url in the appveyor settings for some reason. there's no commit for this.. except, commit 10e4579 made sure the `RubberduckTests` project restored NuGet packages - appveyor build was failing because it couldn't resolve the `Moq.dll` dependency for some reason.

**Comment by ckuhn203** [comment]
Gotcha. My mistake.
