### ISSUE TITLE
feature request: link tests with sources

### ISSUE THREAD

**Issue by yadimon** [rubberduck-vba/Rubberduck#752]
would be nice to have a link between the generated tests with sources by annotation or name convention.

an method/module could have some annotation like `'@test %testModuleName%`
or a test could have `@testFor` annotation.

or the test module could have name like `%moduleToTest%_test`
methods in the module `%methodToTest%_somthing`

(in both cases problem with "rename" refactoring feature)

than maybe some hotkey for "navigate to test"/"navigate to source" from the source/test

**Comment by retailcoder** [comment]
I think we can implement this as a subset of the "Find all references" feature - i.e. make it a "Find all tests" and filter for references in test methods.

The main problem I see is that test discovery does not work off the parse results, mainly because comments aren't part of the parse tree; determining whether a method is a test method or not is going to be tricky without access to the `@TestMethod` hints.

OTOH, comments are parsed manually and, while not part of the parse tree, they *are* part of the `VBProjectParseResults`; we can determine if a method is a test method if:
 
 - It's defined in a standard module that contains a `@TestModule` hint
 - It's `Public` and parameterless
 - Its name starts with `Test`, or there's a `@TestMethod` hint immediately above the signature line

---

###Navigating from test to source

Not much work needed: the member under test is being called, so native "go to definition" on the call should just take you there. If coding against interfaces, "go to definition" would take you to the interface member which is useless, but the "find all implementations" feature can navigate you to the specific implementation you're looking for.

Hence I'm not sure I see a need for this.

---

###Navigating from source to test(s)

Selecting "find all references" from the code pane's context menu after right-clicking a procedure identifier, will already find all references to that method, regardless of whether they're in a test or not. This is where a "go to test" feature *can* be handy: by filtering the references to only those that are in test methods, and grouping by test - so as to avoid reporting two or more usages in the same test (which there *shouldn't* be, but we can't prevent that).

There isn't much need for `@TestFor` annotations in test modules, or to clutter-up user's code with `@Test` navigational hints; the parse tree already knows what methods are being called in the test, we can leverage that.

All in all it's an interesting feature, but I'd deem it of limited value since navigating from test to code-under-test is already available natively (and via "go to implementation"), and navigating from code to tests is already feasible via the "find all references" feature, although not in a test-specific way.

**Comment by retailcoder** [comment]
*find all references* should be used for this
