### ISSUE TITLE
Setup using bitbucket

### ISSUE THREAD

**Issue by jonwant** [rubberduck-vba/Rubberduck#770]
Hi, I'm trying to set this up using bitbucket.org rather than github.com as the remote location as I have a codebase there already.

I've got it to locate the local working directory OK, but if I try to commit it is coming up with an error that the Configuration value 'user.name' is missing or invalid.

Is there a way I can get this to work?

**Comment by retailcoder** [comment]
Source control is powered by LibGit2Sharp, a wrapper API for Git/GitHub. BitBucket unfortunately isn't a supported remote at the moment.

We have plans to eventually extend support to SVN; perhaps we could also consider supporting BitBucket then. @ckuhn203 thoughts?

**Comment by ckuhn203** [comment]
I haven't tested with BitBucket, but it should be supported via username/password credentials. I've seen this issue before (I'll find the duplicate later). 

Long story short, I never wired the username from Rubberduck's GUI into the 3rd Party Library (*oops!*). The version of LibGit2Sharp that we're using searches your machine for the username & email address in the `.gitconfig` file (and [several other places][1]). If it doesn't find one, this error is thrown. 

Until I get around to fixing this, you can work around this by installing a third party Git client, like Source Tree, GitHub for Windows, or MSysGit. Another potential workaround, **that I've not tried**, is creating a `.gitconfig` file in the proper location with the settings described in the doc I linked to. 

On a side note, the way the third party library handles this has changed in the latest release, so I'll need to fix this sooner rather than later anyway. 

[1]:https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup

**Comment by jonwant** [comment]
Thanks for your help.  I didn't have anything set in the .gitconfig file so I have now got past the username error but I have got another error saying that "The branch 'master' ("refs/heads/master") that you are trying to push does not track an upstream branch."

Any ideas?

**Comment by ckuhn203** [comment]
No. Not really... Can you walk me through how you created the repo and hooked it into RD?

**Comment by Vogel612** [comment]
that should not result in an actual error. This only results in problems if your behaviour for `push.default` in your `.gitconfig` is `"upstream"`. @ckuhn203 how do you push exactly? 

Git expects the branch(es) when pushing. That can be circumvented by the push behavior `"matching"` @jonwant you mind pasting your anonymized `.gitconfig`?

**Comment by Vogel612** [comment]
nevermind... most of this comment is useless.. it seems that LibGit2Sharp does not correctly match pushing behaviour wrt. upstream, as evidenced in the [relevant code](https://github.com/libgit2/libgit2sharp/blob/vNext/LibGit2Sharp/Network.cs#L402)

            foreach (var branch in enumeratedBranches)
            {
                if (string.IsNullOrEmpty(branch.UpstreamBranchCanonicalName))
                {
                    throw new LibGit2SharpException([...]

This should actually check some things depending on the `push.default`flag mentioned in the earlier comment. If necessary it may be appropriate to open an issue at libgit2sharp

until then the following command should fix the problem:

    git push origin master:master --set-upstream

**Comment by jonwant** [comment]
Thanks, I'll try this tomorrow and let you know.

**Comment by jonwant** [comment]
That seems to have worked, thanks.

Just a small point - if I want to add a new file to the branch, do I need to do that through a Git GUI or can I move a file from "untracked" within the Rubberduck add-on?

**Comment by retailcoder** [comment]
@jonwant you can drag files from the "untracked" box into the "included changes" box.

**Comment by jonwant** [comment]
Thanks guys - all seems to be working now

**Comment by ckuhn203** [comment]
@Hosch250 I think we should reopen this until we verify that we're using the credentials from the UI instead of the .gitconfig file. Will be closely related to the LibGit2 v0.22 upgrade. This method will no longer work after we do that. Thoughts?

**Comment by ckuhn203** [comment]
More info. I hotfixed the crash in f7166e1, but did so in a way that will no longer work after we update the library we're using.

**Comment by Hosch250** [comment]
@ckuhn203 We are using the credentials from the UI.  The only thing we actually use from the config is the repos and the default location.

**Comment by ckuhn203** [comment]
My man!

**Comment by Hosch250** [comment]
I actually need to remove the email/username from the config sometime.

**Comment by ckuhn203** [comment]
Our config, or the .gitconfig? We should probably hold onto the name/email for the signature in the sourcecontrol.rubberduck file. We'll need it in order to build the signature to attach to commits.

**Comment by Hosch250** [comment]
Oh, OK.  I won't remove it then.
