### ISSUE TITLE
Support @ignore markers for code inspections

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#810]
Procedures that are bound to ActiveX controls on a worksheet, will always fire up a `ProcedureNotUsedInspectionResult` - and there's nothing we can do to prevent this.

Unless...

    '@ignore ProcedureNotUsedInspection
    Private Sub cmdEnterToday_Click()
        presenter.EnterManualFigures
    End Sub

Let's implement `'@ignore [inspection-name]` meta-instructions.

 - At the top of a module, in the *declarations* section:

        '@ignore [inspection-name]

  Could be used to instruct Rubberduck to ignore a specific [set of] inspection(s) for an entire module.

 - Right on top of a procedure:

        '@ignore [inspection-name]

  Could be used to instruct Rubberduck to ignore a specific inspection for that procedure.

There are a number of challenges:

 - It needs to work with more than just one inspection specified:

        '@ignore ProcedureNotUsedInspection
        '@ignore ParameterNotUsedInspection
        Private Sub cmdEnterToday_Click(Byval unusedParam As Integer)
            presenter.EnterManualFigures
        End Sub

 - We need to change *all* inspections to support this. Perhaps the best way would be to *not* modify any inspection, and instead add some code in `InspectionResultBase` along with exposing some `IsIgnored` Boolean property getter - the main problem is that we don't have comments in the parse tree, so we need to think of something relatively clever here.

 - We need to add three commands in the code inspections UI:
  - "Ignore this instance" - adds an `'@ignore` annotation where relevant
  - "Ignore in this module" - adds an `'@ignore` annotation at the top of the module
  - "Ignore this inspection" - sets the inspection's severity to `DoNotShow`

Thoughts?

**Comment by retailcoder** [comment]
hmm.. the annotation would actually need to go on top of the *declaration* - for procedures and parameters, yeah, it's the line above the signature.

But for variables and constants? Needs to be atop the declaration:

    '@ignore VariableNotUsedInspection
    Dim unusedVariable As Integer

**Comment by Vogel612** [comment]
I find the `Inspection`-Suffix to be redundant...

Instead of requiring multiple `'@ignore` annotations for multiple inspections a comma-separated list may be more appropriate. For reference see Java's `@SuppressWarnings` which can be used like:

    @SuppressWarnings("unused", "rawtypes")

That translates to:

    '@ignore ProcedureNotUsed ParameterNotUsed

**Comment by retailcoder** [comment]
@Vogel612 I like that

**Comment by retailcoder** [comment]
#813 added support for `@annotations` directly into the `Declaration` type, so inspections can now verify a declaration's annotation comments.

**Comment by ckuhn203** [comment]
Nice work retail coder!

**Comment by retailcoder** [comment]
The `IdentifierReference` class should also have that `@annotations` support and expose the same `bool IsInspectionDisabled(string inspectionName)` method that returns `true` when the reference is annotated with an `Annotations.IgnoreInspection` comment. Here's the `Declaration` implementation:

        private readonly string _annotations;
        public string Annotations { get { return _annotations ?? string.Empty; } }

        public bool IsInspectionDisabled(string inspectionName)
        {
            return Annotations.Contains(Grammar.Annotations.IgnoreInspection) 
                && Annotations.Contains(inspectionName);
        }

The annotations are populated in the constructor, from `DeclarationSymbolsListener`, here:

        private Declaration CreateDeclaration(string identifierName, string asTypeName, Accessibility accessibility, DeclarationType declarationType, ParserRuleContext context, Selection selection, bool selfAssigned = false, bool withEvents = false)
        {
            var annotations = FindAnnotations(selection.StartLine);
            var result = new Declaration(new QualifiedMemberName(_qualifiedName, identifierName), _parentDeclaration, _currentScope, asTypeName, selfAssigned, withEvents, accessibility, declarationType, context, selection, false, annotations);

            OnNewDeclaration(result);
            return result;
        }

Similar logic will have to be implemented in the `CreateReference` method of the `IdentifierReferenceResolver` class.

**Comment by ckuhn203** [comment]
@retailcoder, any info on how this works? I'm terribly excited to see it get closer.

**Comment by ThunderFrame** [comment]
I can see `@Ignore` annotations, or something like them, being useful for code that:
 - Is Flat out Evil
 - Is subtly Evil for unknown reasons
 - Is causing problems under the current installation of Rubberduck
 - Needs to be explicitly unchanged due to weird 3rd-party API behaviors
 - Needs to be explicitly unchanged for licensing reasons
 - Needs to be explicitly unchanged to minimise risk in mission-critical projects
 - Needs to minimise/manage the quantity or scope of changes to a source control system.

The following list would also qualify for inspection annotations, but it might be helpful to add an extra annotation to describe *why* the procedure is excluded. That is, in addition to (or perhaps even instead of)  annotating with:
`'@ignore ProcedureNotUsed ParameterNotUsed Rubberduck<2.0`
You could further annotate with something like:
`'@IndirectUsage FormulaCallback, RibbonCallback, LibraryFunction`

 - A user-defined-function used in an Excel formula
 - A user defined function that has been added to the RegisteredFunctions in Excel
 - A user-defined-function used as a string-literal in an "INDIRECT" Excel formula
 - A user-defined function used in an Access query or expression
 - A procedure called by a string literal in a VBA `CallByName` function
 - A procedure called by a string literal in the host's `Application.Run` method
 - A procedure called by a string literal in an Excel `Evaluate` function
 - A procedure called by a string literal in an Access `Eval` function
 - An event handler for a control
 - A procedure assigned to a shape
 - A Ribbon callback
 - A callback for a COM Add-in
 - An event handler for a CommandBarControl
 - Called by an Access Macro
 - Used by other projects that refer to the current project. For example, you might be editing an add-in that gets used/called by other projects.

Does the inspector know about functions that are only used in conjunction with `Address Of`, where a function pointer is passed to a declared library function? If not, that should be a capability, and an annotation would be useful in the interim.

**Comment by ckuhn203** [comment]
The `@Ignore` annotation was originally meant to turn off inspections on the following line @Thunderframe. I was asking what syntax he settled on.
