### ISSUE TITLE
Keyboard hook

### ISSUE THREAD

**Issue by Hosch250** [rubberduck-vba/Rubberduck#842]
This [MSDN blog post](http://blogs.msdn.com/b/toub/archive/2006/05/03/589423.aspx) has a working key hook that reads the keys and prints them in a console application.  The core of the work should just be copy/paste into Rubberduck, but we will need to change how we handle the key input.  Do we create an interface, inject it into the classes that need it, and fire an event on every key press containing the key data?  How do we know when the VBE is actually active?  The key hook pulls data from every key press on the system.

**Comment by retailcoder** [comment]
Awesome! It *looks like* the hook is attached to the current process, which would be the host application process (e.g. `EXCEL.EXE`). Through the `VBE` interface we have access to the `ActiveWindow` - perhaps this might return a `null` reference if the VBE isn't active?

The strategy here would be to wrap it with an interface indeed, but abstract it quite a lot - we don't need to care for every single key press out there, but we could have events such as
 
 - `KeyShortcutPressed`, which would let RD know when Alt+Something or Ctrl+Something is pressed, and what that *something* is. I'd like some specific combinations to trigger some "wait" mode that "eats" the next key, so we could implement multi-step shortcuts such as Ctrl+R,R and Ctrl+R,M.
 - `CodeModuleEdited`, which would let RD know the `VBComponent` that was edited, and on which line - so we can look at our `Declaration` model and find the specific procedure to re-parse.
 - Anything else?

**Comment by Hosch250** [comment]
I have a working keyboard hook implemented that tells me both the active window title and the process name for each key press, so no need to check the active window for `null`, which I deeply suspect would not work anyway.  Essentially, we have to check that the active process is something like "WINWORD" or "EXCEL", and the window title starts with "Microsoft Visual Basic for Applications - ".

`KeyShortcutPressed` - should not be too hard.  Essentially, watch for certain key combos, and fire an event.

`CodeModuleEdited` - more complicated.  Do we fire an event every time a key is pressed?  Also, it reads keys typed into the Immediate Window, and such (although this is signified through the `ActiveWindow` field?).

Question - I can't get Rubberduck to work on my Windows 10 system.  Do keys typed into Rubberduck windows say they are part of the VBE process or the Rubberduck process?  Presumably (and hopefully) the Rubberduck process, but I do not know how add ins work.

**Comment by retailcoder** [comment]
Rubberduck is running in the VBE process, which is the same process as the host app - in Excel that would be EXCEL.EXE; there is no separate process for RD, the RD windows are essentially part of the VBE at runtime.

I'm running RD on Windows 10 / Office x64 with the build configuration we've always used, no need to switch to x64 target.

The immediate pane is its own [dockable] window, like our own dockable toolwindows; we need to be able to pick up keystrokes in *code pane* windows, whether they're maximized into the main window, floating or tiled: it's important to know which *code pane* is being edited, so we can know which `VBComponent` to mark as *dirty*.

We'll need to pick up every keystroke, yes; each keystroke will asynchronously cancel the task that's parsing the modified component if it's running (i.e. we force-cancel the parsing, or force-cancel the tree walking, or force-cancel the identifier resolution - whichever is running at that point), and enqueue a new parse cycle; this should be pretty seamless and low-impact on the typing since everything is async. If that slows things down in any way, we'll have to think of something else.

**Comment by Hosch250** [comment]
The base code for the key hook is available here: https://github.com/Hosch250/Key-Hook/blob/master/ConsoleApplication2/InterceptKeys.cs

**Comment by retailcoder** [comment]
All right, I'm tweaking this code to trigger background parsing.

**Comment by retailcoder** [comment]
Keyhook works to trigger parsing (/cancel previous parse of modified module), which is awesome. I tried capturing Ctrl and Alt flags to see if we can expand this to trigger keyboard shortcuts, but no luck for now.

**Comment by Vogel612** [comment]
Would it be useful to slip in a delay before the keypress to prevent starting and aborting Parsing unnecessarily? And if that's the case wouldn't that also allow capturing of key-presses / chords in VS-Style?

**Comment by retailcoder** [comment]
@Vogel612 there's a 50ms delay so that the pressed key is in the code pane when the hook handler notifies of a keypress. There would need to be some additional logic to avoid picking up say 5 keypresses and only notifying once.. otherwise a delay would only delay 5 notifications and make "real-time" parsing feel somewhat sluggish. Cancelling previous parse doesn't seem to incur any user-affecting hit, despite being indeed somewhat overkill.

**Comment by retailcoder** [comment]
ok. keyboard hook works in my environment. anyone has Office 2016 handy to test it out? there is a documented occurrence of the keyhook not working in an Office 2016 host, so more tests and perhaps some tweaks are needed - but it works in Office 2010 x64 on Win10.
