### ISSUE TITLE
Integrating features from AccUnit to Unit Testing

### ISSUE THREAD

**Issue by hapm** [rubberduck-vba/Rubberduck#856]
[AccUnit](http://wiki.access-codelib.net/AccUnit) is a rather old vba testing framework for access, that we currently use to test our databases. It has some handy [additional attributes](http://de.accunit.access-codelib.net/AccUnit-Attribute), that can be applied to test methods:
- **Tags (AccUnit:Tag)** - make organizing and filtering the tests very easy and comfortable
- **Parameterized Tests (AccUnit:Row)** - allow a single test to be run with different values and results defined in simple lines over the test method
- **Ignore (AccUnit:Ignore)** - sometimes you to disable a test for a while, so it is not run when you push the "run all tests" button. 

It would be cool to see this features in Rubberduck, because we can port our current test-suite over to it, when these features are implemented. Unfortunately the documentation of AccUnit is in german but I think you get the idea.

**Comment by ckuhn203** [comment]
These are really nice features to have. Thank you for recommending them!

Since we try to stay in line with MSTest, I recommend we use `'@Category = "SomeTestCategory"` instead of `'@Tag`.

**Comment by retailcoder** [comment]
@ckuhn203  how about we just parameterize the `@TestMethod` attribute?

    '@TestMethod("SomeTestCategory")
    Public Sub TestMethod1()
        Assert.Fail
    End Sub

**Comment by ckuhn203** [comment]
:+1:

**Comment by retailcoder** [comment]
I see the "ignore" feature implemented as a checkbox in the test explorer. Would that work?

**Comment by retailcoder** [comment]
The parameterized tests are somewhat of a problem though... they defy the very definition of a "test method", and require one to clutter up their test module with code-in-comments: I don't like that.

But, all is not lost: instead of writing code in comments/annotations, name each test accordingly with its parameter set, so that the tests that show up in the *Test Explorer* document what tests are actually being executed. Code-in-comments doesn't do that.

    Public Sub TestMethod1_ParameterSet1()
        Const expected As Integer = 32
        Dim actual As Integer
        actual = TestMethod1("foo", 23)
        Assert.AreEqual expected, actual
    End Sub

    Public Sub TestMethod1_ParameterSet2()
        Const expected As Integer = 42
        Dim actual As Integer
        actual = TestMethod1("bar", 24)
        Assert.AreEqual expected, actual
    End Sub

The parameterized test method can then be made `Private` (just for clarity's sake: test discovery ignores parameterized methods anyway), and you have several options to communicate the actual results to the actual unit tests: make it a `Function` and return a value, use `ByRef` parameters, use module-level state, ...whatever:

    Private Function TestMethod1(ByVal foo As String, ByVal bar As Integer) As Integer
        Dim testedClass As New SomeClass

        Dim result As Integer
        result = testedClass.TestedMethod(foo, bar)

        TestMethod1 = result
    End Sub

**Comment by ckuhn203** [comment]
@retailcoder Re:Ignore

That would certainly work. It's reminiscent of creating a playlist in VS. the problem I see is that sometimes you may want to ignore a certain category of tests *most* of the time. (I do this often for integration tests.) Placing an `Ignore` attribute on it would be more permanent than checkboxes in the UI. 

Re: Parameters 

I for one don't care for NUnit and this style of testing.  But just because I don't like it doesn't mean we shouldn't at least consider it. 

The real problem with it IMO is that, unlike .Net, our attributes aren't code. They're just text, so there's no easy way to verify they're syntacticly correct until runtime.

**Comment by retailcoder** [comment]
When the #1116 annotations API gets annotations syntax formalized into the grammar/parser itself, we'll be able to parameterize annotations. I'm pushing this one to v2.1.

**Comment by retailcoder** [comment]
About parameterized tests - how about a "migration tool" that takes the "magic comments" and automatically creates Rubberduck parameteless test methods out of the annotated AccUnit method? That seems entirely possible.
