### ISSUE TITLE
Line continuation breaks parser

### ISSUE THREAD

**Issue by kpstolk** [rubberduck-vba/Rubberduck#900]
I have this `Sub` for example:

    Sub Test()
    
    Dim myString As String: myString = "Some text " & _
    vbNewLine & vbNewLine
    
    End Sub

The code is valid (as far as I know) but gives an error:
> Extraneous input 'myString' expecting NEWLINE

See attached test xlsm (zipped) and screenshot. Is this a parser bug?

![expecting newline error](https://cloud.githubusercontent.com/assets/538170/11996955/b16b89c6-aa6f-11e5-99f1-eefa11241238.jpg)

[Test.zip](https://github.com/rubberduck-vba/Rubberduck/files/71869/Test.zip)

**Comment by retailcoder** [comment]
Indeed, it should be legal. See #861; the instruction separator is somehow not correctly picked up in the grammar, we'll definitely fix that for next release.

**Comment by retailcoder** [comment]
Closing as a duplicate of #861

**Comment by retailcoder** [comment]
Wait a sec... this doesn't parse either:

    Sub Test()
    
    Dim myString As String
    
    myString = "Some text " & _
    vbNewLine & vbNewLine
    
    End Sub

Looks like the line continuation is also a problem. Reopening.

**Comment by retailcoder** [comment]
Indentation *hides* the parser bug - adding even a single leading space on the continued line parses as expected:

    Sub Test()
    
    Dim myString As String: myString = "Some text " & _
     vbNewLine & vbNewLine
    
    End Sub

No issues. The problem is that the line continuation lexer token is defined as follows:

    LINE_CONTINUATION : ' ' '_' '\r'? '\n'

The whitespace being part of the token, and `LINE_CONTINUATION` tokens being ignored by the parser, results in this code ending up in the token stream:

    myString = "Some text " &vbNewLine & vbNewLine

Not sure how to fix this.

**Comment by retailcoder** [comment]
Removing [critical] label, since there's an easy work-around.

**Comment by retailcoder** [comment]
Idea: same kind of fix as for line numbers - replace instances of `WS '_'` with `WS WS '_'` in the source string *before* passing it to the lexer/parser.

**Comment by Vogel612** [comment]
shouldn't you be able to fix this by using `LINE_CONTINUATION: WS? '_' '\r'? '\n'` as rule?

**Comment by retailcoder** [comment]
@Vogel612 the problem is that the underscore is legal as part of an identifier, so it would break this:

    foo_ = 42 + foo_

Because the `foo_` would match the rule.

**Comment by Vogel612** [comment]
isn't the & before the _ required? Why is that not prerequisite for the LINE_CONTINUATION?

**Comment by retailcoder** [comment]
nope, the `&` is just the string concatenation operator. The code could just as well have been written like this:

    Sub Test()

    Dim myString As String: myString = "Some text " _
    & vbNewLine & vbNewLine

   End Sub

**Comment by retailcoder** [comment]
Ugh. The easy fix doesn't work for some reason - adding an additional space in front of the underscore actually makes matters worse. Indentation seems to be the only solution.

**Comment by retailcoder** [comment]
That one is totally infuriating - I can't find a way to get it to parse. At least the error message is clearer than it was:

    extraneous input 'vbNewLine' expecting WS

`WS` is the *whitespace* token - the only "fix" I can see is to avoid continued lines that start in column 1. The reason is purely grammatical, here are the lexer rules involved:

    LINE_CONTINUATION : ' ' '_' '\r'? '\n' -> skip;
    NEWLINE : WS? ('\r'? '\n') WS?; 

I tried a number of variations, including:

    LINE_CONTINUATION : WS? WS '_' NEWLINE -> skip;
    NEWLINE : WS? ('\r'? '\n') WS?; 

Combined with pre-processing the input string by inserting an extra whitespace before (tried after too) the underscore character, prior to passing the code to the parser - nothing did it. I'm out of ideas.

**Comment by Vogel612** [comment]
what about `LINE_CONTINUATION : WS? WS '_' NEWLINE -> ' ';`? wouldn't that fix the incorrect token stream passed on?

**Comment by ThunderFrame** [comment]
The VBA line continuation is actually an underscore **preceded** by a space, as per [MS](https://support.microsoft.com/en-us/kb/141513):
>To continue a statement from one line to the next, type a space followed by the line-continuation character [the underscore character on your keyboard (_)]

And:

>You can break a line at an operator, list separator, or period.

They fail to emphasize that you can break a line *before* **or** *after* an operator, list separator, period, and they fail to say that you can also break a line **after a comment ('), and within parentheses or statements**

So these 2 comments with trailing underscores behave differently
```
Sub Test1()

Dim x: x = 1 'Do not continue this comment_
x = 2

Dim y: y = 1 'Do continue this comment _
y = 2

'Results
' x = 2
' y = 1

End Sub
```
And these are valid line breaks
```
Option _
Base _
1 _

Function _
test _
( _
    Optional _
x _
    As _
String _
    = _
"abc" _
    ) _
As _
    Integer _
( _
    ) _
' _
Returns an array _
of integers _

  Open _
      "C:\test.csv" _
  For _
      Binary _
  Access _
      Read _
  As _
      #1 _
  ' _
      My Comment _
  My Final Comment _

End _
    Function _

```
So, the logic should be
WS? + [Space] + [underscore] + [end_of_line] + WS?

And the replacement should be
[Space]

I'm not familiar with ANTLR syntax :(

**Comment by ThunderFrame** [comment]
And you need to deal with multiple line continuations (Excel has limits, see link above), particularly where a continued line is nothing but another line continuation. Notice that it's not possible to have any white space (other than the necessary, single-preceding-space) in a continued-line that itself has a line continuation. Note all of the lines that are ` _` can only ever be ` _` regardless of whether you entered multiple spaces before the ` _`
```
'VBE will never persist the leading spaces on the 2nd line of the following statement
Option _
        _
    Explicit
``` 
```
Sub test()

  Option _
 _
 _
 _
  Base _
    1 _
 _
    'comment

End Sub
```

**Comment by retailcoder** [comment]
Good news! I asked on Stack Overflow, and got an answer that suggested merging the `LINE_CONTINUATION` and `WS` lexer tokens:

> *You basically want line continuation to be treated like whitespace. OK, then add the lexical definion of line continuation to the WS token.*

The latest changes to the grammar file:

    //LINE_CONTINUATION : ' ' '_' '\r'? '\n' -> skip;
    WS : ([ \t]+)|(' ' '_' '\r'? '\n');

This has implications that need further testing though: line continuations are treated as whitespace, and as such, the parser now "sees" them... which can't be bad actually.

@ThunderFrame thanks for the code samples, you've just highlighted a new lexer bug:

    OPTION_BASE : O P T I O N ' ' B A S E;
    OPTION_EXPLICIT : O P T I O N ' ' E X P L I C I T;
    OPTION_COMPARE : O P T I O N ' ' C O M P A R E;
    OPTION_PRIVATE_MODULE : O P T I O N ' ' P R I V A T E ' ' M O D U L E;

*Every single* multi-word token breaks whenever it's split with a line continuation, because the lexer token is defined with an explicit `' '` whitespace!

**Comment by retailcoder** [comment]
Crap, I'm not sure why the underscore needed to be unseen by the parser, but it seems like the only way to get the thing to parse this:

    Option _
    Base _
    1

**Comment by retailcoder** [comment]
*Almost* there:

    NEWLINE : '\r'? '\n'; 
    WS : ([ \t]+ ('_' NEWLINE)*)+ | NEWLINE+;

This picks up *most* of the horribly abusive line continuations @ThunderFrame supplied above; this parses:

    Option _
    Base _
    1
    
    
    Function _
    test _
    ( _
        Optional _
    x _
        As _
    String _
        = _
    "abc" _
        ) _
    As _
        Integer _
    ( _
        ) _
    ' _
    Returns an array _
    of integers
    
    Open _
          "C:\test.csv" _
      For _
          Binary _
      Access _
          Read _
      As _
          #1 _
      ' _
          My Comment _
      My Final Comment _

    End _
        Function _
    
The problem is that the underscore is no longer ignored by the parser, which causes all kinds of weirdness, e.g. code inspections suggesting to rename identifier `Option _\r\nBase _\r\n1`... 

I'm stumped.

**Comment by retailcoder** [comment]
Commit be3445a closes this issue - the insanely abusive line continuations in @ThunderFrame's sample above, parse *as-is* (i.e. not just "almost" - I *mean* "as-is"!)

**Comment by ThunderFrame** [comment]
\\o/

**Comment by kpstolk** [comment]
Looks like this was a nasty one, good to see it fixed! 😄
