### ISSUE TITLE
AreEqual to support Arrays

### ISSUE THREAD

**Issue by fraho** [rubberduck-vba/Rubberduck#908]
Hi - Is there a good way to assert the equality of 2 arrays? (i.e. same dimension, same bounds and same values)

`Assert.AreEqual Array(1, "hi"), Array(1, "hi")` does not currently work. I am getting: `AreEqual assertion failed. expected: System.Object[,]; actual: System.Object[,].`

Probably this could be restricted to arrays of max. 3 or 4 dimensions. Also ideally it would fail if the lbound/ubound of the arrays are not the same, even if all the values are identical.

What do you think? - Rgds

**Comment by Vogel612** [comment]
This seems to be currently handled by the [`AssertClass`](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.UnitTesting/AssertClass.cs#L121) where we can find following code:

            if (expected.Equals(actual))
            {
                AssertHandler.OnAssertSucceeded();
            }
            else
            {
                AssertHandler.OnAssertFailed("AreEqual", string.Concat("expected: ", expected.ToString(), "; actual: ", actual.ToString(), ". ", message));
            }

This doesn't seem to account for content equality over arrays instead of referential equality. I think PermissiveAssert would suffer the same problem.

Overall we should delegate this to a separate method dedicated to handling arrays. What's interesting is the dimension that gets marshalled over to the AssertClass. I'd have expected `Object[]` instead of `Object[,]` ...

I'd classify this as bug, nice find :+1: 

Sidenote: it shouldn't be too difficult to organize that method recursively to support near-arbitrary numbers of dimensions

**Comment by retailcoder** [comment]
I think this needs to be more like some `Enumerable.SequenceEquals`  assertion.. perhaps like `Assert.SequenceEquals(array1, array2)`
