### ISSUE TITLE
Move Closer To Usage Bugs

### ISSUE THREAD

**Issue by Hosch250** [rubberduck-vba/Rubberduck#943]
This refactoring works for a basic assignment for primitive types:
```
Private fizz As Boolean
Sub foo()
    fizz = True
End Sub
```
It does not work in any other use case, including:
```
Private fizz As Class1
Sub foo()
    Set fizz = New Class1
End Sub
```
```
Private fizz As Boolean
Sub foo()
    bar fizz
End Sub
Sub bar(ByVal b as Boolean)
End Sub
```

**Comment by ThunderFrame** [comment]
how about referenced object types?
```
Private fizz As Object
Sub foo()
  Set fizz = New Collection
End Sub
```
```
Private fizz as Collection
Sub foo()
  Set foo = New Collection
End Sub
```
```
Private fizz as VBA.Collection
Sub foo()
  Set foo = New VBA.Collection
End Sub
```

**Comment by Hosch250** [comment]
I believe those will all be dealt with when the first example is fixed because they are all in the `Set` statement context thingie.  It is the reference I need to deal with, not the declaration.

**Comment by retailcoder** [comment]
An `IdentifierReference` has a `Declaration` property pointing to the declaration being referenced; we definitely need to extend `Declaration` so that its `AsTypeName` becomes `AsType` and points to the resolved `Declaration` instance - the problem is that `Declaration` is immutable and it's the resolver that figures out what the type is; I'll change that and make the resolver make that assignment.

With that done, we'll be able to do this:

    var asType = reference.Declaration.AsType;
    if (asType != null && asType.DeclarationType == DeclarationType.Class)
    {
        // reference is pointing to an object
    }

...and this is where C#6 would make things prettier, since `AsType` would be `null` if the resolver couldn't find a declaration for it.

**Comment by retailcoder** [comment]
...with `Declaration` no longer immutable, there will be a massive opportunity to clean up that nasty constructor, too.. and perhaps introduce an inheritance hierarchy so we wouldn't constantly need to rely on `DeclarationType`... Picture this:

    var members = UserDeclarations.OfType<MemberDeclaration>();

Where `MemberDeclaration` would be used for procedures, functions and properties.

And...

    var modules = UserDeclarations.OfType<ModuleDeclaration>();

Where `ModuleDeclaration` would encompass standard modules, class modules, user forms and documents.

I need to think about this a bit more, there won't be 20 opportunities to get this right.
