### ISSUE TITLE
Create wiki page for PIA knowledge transfer, FAQ, examples

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#957]
There seems to be considerable confusion about how PIAs work with multiple versions of an application, which ones should be referenced and how to properly reference them in a project.

That's largely because there seems to be very little documentation, other than these articles:

**[MZTOOLS](http://www.mztools.com/articles/2012/MZ2012011.aspx) HOWTO: Generate Interop assemblies to create an add-in for the VBA editor (32-bit or 64-bit) of Office with Visual Studio .NET.**
This article focuses on pre .NET 4.0, but is still informative, and particularly useful as MZTOOLS was/is VBA centric.

**[MS](https://msdn.microsoft.com/en-us/library/dd409610.aspx) Walkthrough: Embedding Types from Managed Assemblies (C# and Visual Basic)**
Technical discussion

**[MS](https://msdn.microsoft.com/en-us/library/ee317478.aspx) Walkthrough: Embedding Type Information from Microsoft Office Assemblies (C# and Visual Basic)**
Example of embedding type info and having the addin work under multiple versions of that host.

We should be able to get RubberDuck working in most applications that support VBA, which will include most Office applications, some AutoCAD applications and some Corel applications, and possibly others.

I guess we need a second wiki page that details the O/S, 32/64 bit host, host application name and version, and the Application.Run method that is available. And whether RD has been successfully launched, and parsed, and used for TDD.

**Comment by ckuhn203** [comment]
A wiki page isn't a bad idea, but in general, we already support the Office Applications that *can be* supported. And their calls to `Application.Run` are documented in the code itself. I'm unsure of what confusion it is that we're talking about/experiencing.

@retailcoder can we open our wiki up so that the community can contribute to it? Most of our users don't know C#, so can't really contribute to the code, but everyone is capable of contributing documentation. As another thought, we may be able to open the wiki up to the Contributors group if you don't want to make it public.

**Comment by ckuhn203** [comment]
@ThunderFrame @retailcoder has changed the wiki settings to allow anyone to contribute to our wiki.

**Comment by ThunderFrame** [comment]
Great, thanks. Can anybody kick-off by describing/clarifying why the Office PIAs need to be 2007, when the MS documents suggest any version will do? And why 2007 in particular? Why not 2003? Can't we just use whatever is at hand? Would it be worthwhile including the types from PIAs from multiple versuons, in the build? Members tend to get added across versions, and deprecated members are usually moved to hidden before (if ever) being removed.

**Comment by retailcoder** [comment]
For now we're really only ever using the PIA's for the unit testing feature - i.e. the only "Office Interop" thing we do is *programmatically execute VBA code* in specifically-identified standard modules. In other words, we only need the PIA's to call the `Application.Run` method. I don't know why 2007 PIA's would be a *requirement*, but PIA's being a bit of a ...PIA, we ended up settling with whatever worked, and that turned out being the solution we have now.

I really don't think multiple versions of the same types could be embedded though (we're embedding the interop types) - that would mean `Microsoft.Office.Interop.Excel.Application` would be pointing to two or more types, which wouldn't compile.

**Comment by retailcoder** [comment]
At one point we'll probably be using more Office interop, as we expand into more and more host-specific functionalities. For example, we'll probably eventually want to inspect the `Shapes` collection of a document, and create `Declaration` objects for them, so they can be refactored/renamed without breaking the bond between a worksheet shape and its associated macro. Things like that.

**Comment by ckuhn203** [comment]
> Can anybody kick-off by describing/clarifying why the Office PIAs need to be 2007, when the MS documents suggest any version will do? And why 2007 in particular? Why not 2003? Can't we just use whatever is at hand? 

No. We can't just use whatever is at hand. We have to use the PIAs for the oldest version that we support. We had issues when Retailcoder was using the 2010 PIAs an I was using the 2007 PIAs. We accidentally put out a release that used the 2010 PIAs and broke all of our 2007 users in the process.

I'll try to dig up the documentation that explains this behavior later.

**Comment by ThunderFrame** [comment]
So there's a disconnect between the advertised feature in the MS document, and the actual MS implementation? Who'd of think?

Presumably a 2007 PIA would cause problems for 2003 and prior?

If it's just testing that breaks, then not having tests in 2003 and prior is the least of your concerns. Or does RD just fail to work in 2003, when compliled with 2007 PIAs, even without tests?

**Comment by ckuhn203** [comment]
I honestly don't know. We don't test or support 2003. [Please see our minimum system requirements](https://github.com/rubberduck-vba/Rubberduck/wiki/Building-&-Installation#system-requirements).

**Comment by retailcoder** [comment]
IMO it shouldn't impact anything other than the unit testing feature. See #197, RD has been seen working on Access 97.

**Comment by ThunderFrame** [comment]
So I'm trying to get CorelDraw PIA into my RD branch. Can somebody please clarify the steps?

Is it something like:

 1. Create PIA using MZTools approach.
 2. Copy the PIA dll into RD libs folder
 3. Reference the dll in RD
 4. Add code to specify "RunMacro" as the method used for executing RD tests in CorelDraw?

Maybe check the IsBuiltIn property works?

**Comment by Vogel612** [comment]
The Wiki page about that has been created [here](https://github.com/rubberduck-vba/Rubberduck/wiki/Adding-a-new-Host-Application-to-Rubberduck) quite a while ago already
