### ISSUE TITLE
copy/export project/module/procedure/selection as HTML

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#958]
Would be nice to copy/export VBA and retain syntax highlighting. Could then email code, or place in documents without a loss of syntax highlighting.

Need to consider options for color/font etc. And options for stylesheets vs inline style (eg. Pasting markup into gmail requires markup that has inline style, otherwise the formatting is lost)

**Comment by Vogel612** [comment]
This is complicated due to multiple reasons:

Email, Documents and In general every other application have their own way of syntax-highlighting. This would mean you'd have to go through lenghts to build syntax highlighting **into Rubberduck** (because AFAIK it currently doesn't do that or care about it), export that syntax highlighting correctly for multiple formats (which is a hassle) and generally seems to be a lot of effort.

If you just want to embed code into documents or Email, Microsoft already has great support to copy rich text into documents (Insert > Object > Rich Text) or Email (which works the same in Outlook). 

Exporting syntax highlight into HTML (EMail sending) is a whole different problem, which also has the same problems as exporting to RichText when Rubberduck would have to build the syntax highlight in the first place.

**Comment by retailcoder** [comment]
Nice idea, but I'd deem this one out of scope.

**Comment by ThunderFrame** [comment]
I wasn't suggesting multiple formats, just one format, valid XHTML with inline style attributes. Making preferences for the HTML design pattern would <s>be 4.0</s> not be necessary.

Just about all email clients, web browsers and word processors and Office applications support HTML. I know HTML compatibility is hard across email clients/platforms (I use Notes at work (and some colleagues have Outlook), and gmail at home), but worst case, you can attach a HTM file to the email.

While inline style tags add bloat, and disregard the principles of CSS and separation, it does allow each element to be self-sufficient with regard to it's own styling, and it makes itself work in more/most clients.

HTML can be saved in a stand-alone file, placed on the clipboard, and web hosted. So it's the ideal format?

I had thought it might be possible to have something like a ToHTML method on each token?

If the HTML is valid, then you should/would get round-tripping for free. That is, when the client puts the HTML selection on the clipboard, it would *typically* put an HTML format and a cfText format on the clipboard, so the text would paste into a module nicely.

**Comment by retailcoder** [comment]
@ThunderFrame that still entails writing a code prettifier, which is a whole project on its own...

Also not all tokens end up in the parse tree: line continuations and comments are ignored by the parser, notably. This could get very complicated, very fast!

**Comment by Vogel612** [comment]
@retailcoder Should we reconsider this, given that we do have AvalonEdit providing pretty-printing now?
