### ISSUE TITLE
Parser errors

### ISSUE THREAD

**Issue by Thinqer77** [rubberduck-vba/Rubberduck#961]
Hi there,

I'm new to RubberDuck but have been developing in VBA for a while. I've just tried to run the Code Explorer and it starts to parse my VB Project (this is in Excel, btw) and throws up lots of Parser errors, none of which seem to be valid. Here are some examples (Parser error followed by VBA code block that threw the error):

extraneous input '1' expecting NEWLINE (this is raised at the line 1:)
```VBA
Sub GotoSpecial()

On Error GoTo 1
Selection.SpecialCells(xlCellTypeFormulas, 23).Select
Exit Sub

1:
MsgBox Err.Description

End Sub
```
no viable alternative at input 'On Local Error'
```VBA
Private Function IsInitialized(ByRef vArray As Variant) As Boolean

On Local Error Resume Next
IsInitialized = IsNumeric(UBound(vArray))
    
End Function
```
extraneous input "(" expecting { long list of items not reproduced here for the sake of brevity } - this was raised on the ( after OpenTextFile

```VBA
Dim fsoF As New Scripting.FileSystemObject
Dim stmS As TextStream
Set stmS = fsoF.OpenTextFile(strLogFile)
```
extraneous input '"kernel32"' expecting WS

```VBA
Private Declare Sub GlobalMemoryStatus Lib _
"kernel32" (lpBuffer As MEMORYSTATUS)
```
There are plenty more but so far as I can see there's nothing wrong with the code in the items above and they all compile just fine.

Also, the parser seems to hang while processing - it raises about 20 or 30 errors and then just shows all my VBProjects with (parsing...) after them in the Code Explorer window, but no more errors raised and no progress seems to be made.

Any help greatly appreciated - am more than happy to give more details if need be and help wherever I can as RD seems to be a great tool and would love to get it working for us.

Many thanks,

Ben.

**Comment by retailcoder** [comment]
Thanks for the feedback!

Rubberduck uses an ANTLR grammar to generate its parser; that grammar is a modified VB6 grammar that had a number bugs, oversights and limitations, a lot of which have been fixed - the 2.0 parser will be much closer to be able to take everything the VBA compiler handles.

`On Local Error` was one such oversight - it's simply not defined; turns out it's an obsolete construct that VBA supports for backward compatibility, you can use `On Error` instead, and it will parse fine. I added `On Local Error` fairly recently to the grammar, so next release it will parse fine too.

Line continuations have also proven to be a problem when they're in the middle of a parser rule, like this:

    Private Declare Sub GlobalMemoryStatus Lib _
    "kernel32" (lpBuffer As MEMORYSTATUS)

The parser expects a `WS` (whitespace) token, and bumps on the line continuation (which gets ignored, so the parser sees `Private Declare Sub GlobalMemoryStatus Lib"kernel32" (lpBuffer As MEMORYSTATUS)` and can't match the parser rule for a `declareStmt`.

I've fixed this bug recently, by redefining the `WS` lexer token and basically treating line continuations as whitespace - so next release that code will parse just fine.. in the mean time this should parse:

    Private Declare Sub GlobalMemoryStatus Lib "kernel32" (lpBuffer As MEMORYSTATUS)

Line numbers are a bigger problem. Despite multiple attempts and loss of hair and sanity, I have not been able to get the parser to understand what a line number is - line numbers blow up the parser everytime. I have <s>fixed</s> *worked around* this for next release, by stripping them from the string I'm giving the parser to process, so line numbers no longer blow up anything.

The `onErrorStmt` parser rule will happily take a line number though, because an integer literal is a valid `valueStmt`:

    onErrorStmt : ON_ERROR | ON_LOCAL_ERROR WS (GOTO WS valueStmt | RESUME WS NEXT);

However the line number itself will go boom.

You can get that first snippet to parse fine, by using a *line label* instead:

    Sub GotoSpecial()

    On Error GoTo ErrHandler
    Selection.SpecialCells(xlCellTypeFormulas, 23).Select
    Exit Sub

    ErrHandler:
    MsgBox Err.Description

    End Sub

I really wish I could figure out a way to treat line numbers as line labels, but really, nothing worked and I'm done trying :unamused:

Besides, Rubberduck picks up line labels as *declarations*, which means they become searchable, navigatable, and refactorable - you can refactor/rename a line label, but not a line number.

---

So, all the mentioned parser problems have been fixed and will work fine in the next release, and have a work-around to work in the current latest release. There's another common one that was fixed, that you might encounter though.

The parser rule for a function/array/member call doesn't allow subscripts, so you can't do this:

    Dim foo As String
    foo = Range("A1:A10")(2)

It will parse correctly next release, but here's the (perhaps slightly annoying) work-around:

    Dim foo As String
    Dim bar As Range
    Set bar = Range("A1:A10")
    foo = bar(2)

**Comment by retailcoder** [comment]
Other limitations include the absence of a parser rule for `#Const`, which is very unfortunate, but fixed next release.

**Comment by retailcoder** [comment]
@Thinqer77 reading this issue again, I see I missed one - could there be surrounding code that's interfering with the member call on the `fsoF` object here? This code parses fine on build 1.4.3.2343 (last release):

    Sub Test()
    Dim fsoF As New Scripting.FileSystemObject
    Dim stmS As TextStream
    Set stmS = fsoF.OpenTextFile(strLogFile)
    End Sub

**Comment by retailcoder** [comment]
I'm going to close this issue now, since everything is working as expected in the [next] branch.
