### ISSUE TITLE
Rubberduck should act as a Rubber Duck

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#967]
Despite the name, and the nature of the add-in, RD is missing the feature it was named after....

Namely, it's missing a *Virtual Rubber Duck".

![virtualrdzoom](https://cloud.githubusercontent.com/assets/16574009/12534470/a16ed1ca-c2ae-11e5-80f4-aa2cf86379f8.png)

![virtualrd](https://cloud.githubusercontent.com/assets/16574009/12534472/aaf6987c-c2ae-11e5-823a-71d3e9d47bfa.png)

And finally, the Clippy + Rubber Ducky Mashup....

![rubberduckyclippy](https://cloud.githubusercontent.com/assets/16574009/12534474/c50ab48c-c2ae-11e5-9932-083c328166df.png)

**Comment by Hosch250** [comment]
This would likely be incredibly tricky to implement in any reasonable format.  If you want to compile a comprehensive set of triggers and what this duck should say, I can handle the rest.  *Tip: I gave you the hard part*

**Comment by PeterMTaylor** [comment]
I like it! Looks good to match the similar Clippy paperclip I remembered. Needs emotions or as they say "with feeling!" I imagine it needs an artificial intelligence as well :smile:

**Comment by ThunderFrame** [comment]
I don't expect it to actually give advice or suggestions. It's just a virtual rubber duck. It does nothing more than a physical rubber duck does. It sits. It listens. It doesn't judge, and it doesn't answer back.

Maybe, as an easter egg, it acts as a Magic-8-ball.... 
 Q. "Should I write my own collection class?"
 A. "Yeah, it can't hurt" || "No way, are you crazy?"

The clippy mashup was for shiggles.

**Comment by retailcoder** [comment]
*wipes tears*

Believe it or not, I actually thought of implementing *something like it* at one point...

Here's how I see it: we keep implementing inspections and refactorings, refine them, make them rock-solid and resistant to every single edge case we can come up with.

Then (and *only then*), we add a "Rubberduck this" button on the commandbar that analyzes the current selection or current code pane and/or current project, and makes recommendations / applies quick-fixes and refactorings as it sees fit. One click, and `If foo = False Then` disappears and becomes `If Not foo Then`, and `GoSub` subroutines are replaced with method calls, indentation becomes standard, and whatever else makes sense to apply.

But there's a long way to go before it gets there still... and I'm not sure it's a good idea to automate everything. Perhaps just having a rubber ducky to talk to (*"walk me through your code, tell me like I'm 5"*) when the user is stuck on a bug would be a nice feature... perhaps.

**Comment by ThunderFrame** [comment]
Making it *too* integrated with the inspections might be a little intrusive. Some user's won't want a duck on the screen, *ever*.
But adding a *rubber ducky to talk to" is entirely opt-in, makes a reinforcing association between the add-in and code-review, and adds a touch of humor.

**Comment by retailcoder** [comment]
@ThunderFrame one of the features that went into the roadmap early on, was the ability to leverage the Stack Exchange API to put the working code up for review on Code Review. I can see a ducky be useful for 2 things:

 - "Stuck? Walk me through your code"
  - "Still not working? Would you like to *search* Stack Overflow?"
    - "Still stuck? Would you like to *ask* on Stack Overflow?"
 - "Works as intended? Want to get it peer reviewed on Code Review?"

**Comment by PeterMTaylor** [comment]
@retailcoder I agree myself with your reasoning regarding the roadmap and Integration by way of API towards Stack Exchange.

Is it intrusive as ThunderFrame highlighted for "Ducky" to provide a few data driven suggestions that is already known in Rubberducky's cache as the user (for UX user experience aspect) is focusing on otherwise the output response end up by default a simple straight forward response as there is nothing else to give back to the user.

To give a different context for discussion. If the user is currently attempting to resolve a number of bugs (just making one up on the fly for this topic) object missing 434 and still cannot work out a better way to resolve it. 

I could see the possible outcomes if given by a mini-wizard (the structured questionnaire format) the user can ask.

- stuck? Walk me through with me?
The user can type in the wizard a few key words that the parser is aware of (taking a common direct route out of the multi-path option offered)

- still not working? Would you like to *search* Stack Overflow?
  (If user replies yes, we can add to the user's search as a suggestion with additional tags  -VBA -object -error -434 given the key words given that will help to find it successfully)

- still stuck? Would you like to ask on Stack Overlow?
 (Just to offer to the user a list however show that there are few duplicate questions on -VBA -object -error -434 already solved perhaps sorted in reverse chonological order the latest first)

- Works as intended? Want it peer reviewed? 
(Indicate if common tags are found in the search so the user review these before providing their code as a new peer review question)

**Comment by ckuhn203** [comment]
I really think that this "feature" should be nothing more than a rubberduck to listen to your problems. Is that strange?

**Comment by ThunderFrame** [comment]
Not strange at all. A duck that listens to your problems makes for a nice easter-egg.

The problem, IMO, with actual suggestions or questions coming from the duck, is that it takes you into *Clippy" territory very, very quickly. It didn't take me long to realize the potential for a comparison to Clippy. MS still hasn't lived that one down.

**Comment by ckuhn203** [comment]
Yeah. I wasn't a fan of clippy. We've made fun of that in our chatroom a good bit. I'd be wary of walking that road too.

**Comment by retailcoder** [comment]
All agreed.

**Comment by ThunderFrame** [comment]
![rubbermerlin](https://cloud.githubusercontent.com/assets/16574009/12701644/967a0a72-c863-11e5-9724-7ccf802df5c1.png)

**Comment by ckuhn203** [comment]
Bahahahaha hajahahahagssafhahahaha

**Comment by ThunderFrame** [comment]
[Clippy.js](https://www.smore.com/clippy-js) says:
> Our research shows that people love two things: failed Microsoft technologies and obscure Javascript libraries.

**Comment by Hosch250** [comment]
![](https://tse1.mm.bing.net/th?&id=OIP.M4014c32be7b8dbeed0b06cae3f78185fH0&w=225&h=300&c=0&pid=1.9&rs=0&p=0)

**Comment by ThunderFrame** [comment]
^ Celluloid Duck

**Comment by Hosch250** [comment]
@ThunderFrame Nope, Daffy Duck.

**Comment by ThunderFrame** [comment]
@hosch250 yes, but Daffy was originally produced on film, and at the time, the film was made from Celluloid. Hence Celluloid duck. :-)

**Comment by Hosch250** [comment]
@ThunderFrame Thanks.  I didn't know the history behind it.

**Comment by Hosch250** [comment]
This seems kind of corny to me, and we already have so many windows I can't have all the ones open I want all the time.  Do we really need this?

**Comment by PeterMTaylor** [comment]
Perhaps soon allow machine learning and it would like Cortana the AI lady

**Comment by ckuhn203** [comment]
I vote [status-declined].
