### ISSUE TITLE
Assignment operator issue in VBA grammer

### ISSUE THREAD

**Issue by u-riaz** [rubberduck-vba/Rubberduck#974]
Hi Mathieu,
Sorry if i'm opening this ticket at wrong place.
Got your VBA written grammer from Github (retailcoder/grammars-v4). 
I'm using ANTLR-v4 parser to parse VBA codes to generate tokens, but the following like statements are being bypassed/ignored. 
myvar = 5;
sum = 3+2
and so on.. all assignment like statements generating no token. I want to generate a token of "assignment" here.
In blockStmt's productions, i think, there is no production which can handle assign-like statements. I'had also checked by adding 
| valueStmt
in blockStmt, as valueStmt's production
| valueStmt WS? EQ WS? valueStmt 			# vsEq
can handle these.  But no success. 
PS.: EQ (=), getting hit if used in if-else conditions, but not in assign-like operations.
Can you  please have a look.
Thanks

**Comment by retailcoder** [comment]
Rubberduck uses that grammar and correctly determines what variables are assigned or not (well, with the 2.0 resolver at least), so it works for us :wink: 

*Value* assignments would be picked up with the [letStmt](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/Grammar/VBA.g4#L347) rule:

    letStmt : (LET WS)? implicitCallStmt_InStmt WS? (EQ | PLUS_EQ | MINUS_EQ) WS? valueStmt;

VBA value assignments were historically done using the `Let` keyword. The grammar allows that `Let` keyword to be present, while still matching the rule when it isn't. The left side of the assignment (the assignment target) is an *in-statement implicit call statement* which in the simplest form is referring to a local variable, but it could also be a member call, an array subscript, or whatever.

Similarly, *reference* assignments would be picked up with the [setStmt](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/Grammar/VBA.g4#L479) rule:

    setStmt : SET WS implicitCallStmt_InStmt WS? EQ WS? valueStmt;

The `Set` keyword is mandatory in VBA for reference assignments, but aside from that, the two rules are pretty much identical.

---

The grammar merely tokenizes the VBA code; you'll notice it doesn't *resolve* identifier references, and doesn't know what variables are being declared: Rubberduck achieves this by walking the parse tree and using a *listener* to create objects when specific parser rules are encountered - see [DeclarationSymbolListener](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/Symbols/DeclarationSymbolsListener.cs) and [IdentifierReferenceListener](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/Symbols/IdentifierReferenceListener.cs) classes if you want ideas, but if you're on a new project you might prefer tweaking the grammar into a context-sensitive one, so that you don't need to implement your own [IdentifierReferenceResolver](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/Symbols/IdentifierReferenceResolver.cs), which to be honest is a total nightmare :smile:

**Comment by u-riaz** [comment]
Thanks you Mathieu. Your help solved my problem. 
Actually, i was trying to pick assignments by Listener on EQ, which was wrong. Now, i'had a listener on letStmt and got assignments triggered. 
I'm only in need to tokenize the code, so, No nightmares :smile:
Thanks again.
Regards:
Usman Riaz

**Comment by ckuhn203** [comment]
Man, I love Open Source. =)
